src/utils/resolvePath.js

Fixed endless cycle on Windows

---

src/Bundle.js
src/ExternalModule.js
src/Module.js
src/finalisers/amd.js
src/finalisers/es6.js
src/finalisers/iife.js
src/finalisers/shared/getInteropBlock.js
src/finalisers/umd.js
test/form/external-imports/_config.js
test/form/external-imports/_expected/amd.js
test/form/external-imports/_expected/cjs.js
test/form/external-imports/_expected/es6.js
test/form/external-imports/_expected/iife.js
test/form/external-imports/_expected/umd.js
test/form/external-imports/main.js

This addresses a couple of issues in #59

Handle external dependencies correctly

---

README.md

* Made the Wiz Khalifa quote a quote proper
* Added README info on the CLI
* Plus a deprecation notice on Esperanto
Fixes #69

Added some README info on the CLI

---

bin/help.md
bin/rollup

Add `--strict/--no-strict` CLI option.

---

src/utils/path.js
src/utils/resolveId.js
test/cli/external-modules/main.js
test/function/allows-external-modules-from-nested-module/main.js
test/function/custom-path-resolver-async/_config.js
test/function/custom-path-resolver-sync/_config.js
test/function/duplicate-import-fails/_config.js
test/function/duplicate-import-specifier-fails/_config.js
test/function/export-not-at-top-level-fails/_config.js
test/function/import-default-from-external/main.js
test/function/import-named-from-external/main.js
test/function/import-namespace-from-external-module-renamed/main.js
test/function/import-namespace-from-external-module/main.js
test/function/import-not-at-top-level-fails/_config.js
test/function/imports-are-deconflicted-b/main.js
test/function/imports-are-deconflicted/main.js
test/function/namespace-reassign-import-fails/_config.js
test/function/namespace-update-import-fails/_config.js
test/function/reassign-import-fails/_config.js
test/function/reassign-import-not-at-top-level-fails/_config.js
test/function/shadowed-external-export/main.js
test/function/update-expression-of-import-fails/_config.js
test/test.js

Builds on #117, fixing another windows issue and the tests.
I did not include appveyor config. I believe you should set that up once this is merged and released.

Fix windows

---

src/Bundle.js
src/Module.js
src/Statement.js
test/form/unused-side-effect/_config.js
test/form/unused-side-effect/_expected/amd.js
test/form/unused-side-effect/_expected/cjs.js
test/form/unused-side-effect/_expected/es6.js
test/form/unused-side-effect/_expected/iife.js
test/form/unused-side-effect/_expected/umd.js
test/form/unused-side-effect/foo.js
test/form/unused-side-effect/main.js
test/function/globally-called-modifying-function/_config.js
test/function/globally-called-modifying-function/main.js
test/function/globally-called-modifying-function/module.js
test/function/modify-assumed-global/_config.js
test/function/modify-assumed-global/main.js
test/function/modify-assumed-global/math.js

Include statements with side-effects

---

src/utils/path.js

Fix directories having '.'

---

src/Module.js
test/form/export-all-from-internal/_expected/amd.js
test/form/export-all-from-internal/_expected/cjs.js
test/form/export-all-from-internal/_expected/es6.js
test/form/export-all-from-internal/_expected/iife.js
test/form/export-all-from-internal/_expected/umd.js

Don't include 'default' export from 'export * from ...'

---

src/Statement.js

* Explain better how optimization of namespace lookups are done in comments.
* Consider `hasReplacements` to be true if there exists any namespace replacements.
* Improve error messages slightly
I have added a test-case based on #139, but I'm not sure what to call it.
Fixes #139

Polish optimization of namespace lookups

---

package.json
src/Module.js
src/Statement.js
test/function/cannot-import-self/_config.js
test/function/cannot-import-self/main.js
test/function/export-type-mismatch-b/_config.js
test/function/export-type-mismatch-b/main.js
test/function/export-type-mismatch-c/_config.js
test/function/export-type-mismatch-c/main.js
test/function/export-type-mismatch/_config.js
test/function/export-type-mismatch/main.js
test/function/property-keys-not-renamed/_config.js
test/function/property-keys-not-renamed/main.js
test/function/property-keys-not-renamed/one.js
test/function/property-keys-not-renamed/three.js
test/function/property-keys-not-renamed/two.js
test/test.js

Following #130, this is a place to collect additional tests, and to remove code that is no longer necessary. 
I recommend the [Codecov Chrome extension](https://chrome.google.com/webstore/detail/codecov-extension/keefkhehidemnokodkdkejapdgfjmijf?hl=en-US) – it makes it easy to see which lines are untested within GitHub:

remove some unused code, add some additional tests

---

src/Bundle.js
src/Statement.js
src/optimise/namespace-lookup.js
test/function/namespace-optimisation-before-exports/_config.js
test/function/namespace-optimisation-before-exports/bar.js
test/function/namespace-optimisation-before-exports/foo.js
test/function/namespace-optimisation-before-exports/main.js
test/function/namespace-optimisation-before-exports/zoo.js

Extract namespace lookup optimisation into separate pass

---

test/function/export-from-no-local-binding/_config.js

Enable test/function/export-from-no-local-binding

---

appveyor.yml

Only build latest node on windows

---

test/function/shadowed-namespace/_config.js
test/function/shadowed-namespace/bar.js
test/function/shadowed-namespace/main.js

test for #154 (shadowed namespaces)

---

src/Module.js
test/form/export-multiple-vars/_config.js
test/form/export-multiple-vars/_expected/amd.js
test/form/export-multiple-vars/_expected/cjs.js
test/form/export-multiple-vars/_expected/es6.js
test/form/export-multiple-vars/_expected/iife.js
test/form/export-multiple-vars/_expected/umd.js
test/form/export-multiple-vars/bar.js
test/form/export-multiple-vars/baz.js
test/form/export-multiple-vars/foo.js
test/form/export-multiple-vars/main.js

split up export var a, b, c

---

src/utils/first.js

Added missing import

---

CHANGELOG.md

* `rollup.VERSION`
* `options.resolveExternal`

Added missing CHANGELOG info

---

src/Bundle.js
src/Module.js
test/function/namespaces-are-frozen/_config.js
test/function/namespaces-are-frozen/main.js
test/function/namespaces-are-frozen/mod.js

Use all export declarations

---

src/Bundle.js

I've created an experimental Babel plugin for testing (not yet released to npm): https://github.com/rollup/rollup-plugin-babel
The basic idea:
```js
rollup.rollup({
entry: 'main.js',
plugins: [ require( 'rollup-babel-plugin' )() ]
}).then(...);
// this is basically equivalent to
rollup.rollup({
entry: 'main.js',
plugins: [{
transform: function ( code, id ) {
// babelify code
},
intro: function () {
// generate helpers to insert at top of bundle
}
}]
}).then(...);
```
So as far as Rollup is concerned, a plugin is just an object with various properties. As of this PR, the `transform` and `intro` properties are supported, because that's the bare minimum we need to support the Babel plugin. My feeling is that if we go down this road, we should add new hooks only as and when they become …

[RFC] support plugins that return transform and intro functions

---

CHANGELOG.md
package.json

* `--config` support for plugins via CLI
* Fix #215
* update deps

Release 0.20.1

---

src/Bundle.js
src/ExternalModule.js
src/Module.js
src/Statement.js
src/ast/Scope.js
src/ast/attachScopes.js
src/finalisers/amd.js
src/finalisers/cjs.js
src/finalisers/es6.js
src/finalisers/iife.js
src/finalisers/index.js
src/finalisers/umd.js
src/rollup.js
src/utils/defaults.js
src/utils/first.js
src/utils/fs.js
src/utils/getExportMode.js
src/utils/makeLegalIdentifier.js

Via #236 – this PR adds .js extensions to all local module imports

add js extensions

---

src/Bundle.js
src/utils/callIfFunction.js
test/form/banner-and-footer-plugin/_config.js
test/form/banner-and-footer-plugin/_expected/amd.js
test/form/banner-and-footer-plugin/_expected/cjs.js
test/form/banner-and-footer-plugin/_expected/es6.js
test/form/banner-and-footer-plugin/_expected/iife.js
test/form/banner-and-footer-plugin/_expected/umd.js
test/form/banner-and-footer-plugin/main.js

support banner and footer options in plugins

---

src/utils/transform.js
test/function/transformer-async/_config.js
test/function/transformer-async/main.js

support async transformers

---

src/Module.js
src/ast/attachScopes.js
test/function/assignment-to-re-exports-conflict/_config.js
test/function/assignment-to-re-exports-conflict/count.js
test/function/assignment-to-re-exports-conflict/main.js
test/function/assignment-to-re-exports/_config.js
test/function/assignment-to-re-exports/count.js
test/function/assignment-to-re-exports/main.js

Fix assignment to re-exported bindings.

---

src/Module.js
src/ast/Scope.js

I don't have any tests for it, but it fixes the issue I had.
Fix #291

Check isUsed to prevent potentially infinite recursion

---

src/rollup.js
test/test.js

Promise reject instead of throwing Error

---

src/Module.js
test/function/reexport-missing-error/_config.js
test/function/reexport-missing-error/empty.js
test/function/reexport-missing-error/main.js

Add error message when reexporting missing identifier

---

src/Declaration.js
test/function/resolves-namespace-default/_config.js
test/function/resolves-namespace-default/main.js
test/function/resolves-namespace-default/mod.js

Move declaration assignment before the if statement

---

test/test.js

more informative error when test config fails to load (#325)

---

src/Statement.js
src/ast/modifierNodes.js
src/utils/run.js
test/function/delete/_config.js
test/function/delete/main.js

Ensure `delete` operations at the top level are preserved.

---

src/Statement.js
test/form/object-destructuring-default-values/_config.js
test/form/object-destructuring-default-values/_expected/amd.js
test/form/object-destructuring-default-values/_expected/cjs.js
test/form/object-destructuring-default-values/_expected/es6.js
test/form/object-destructuring-default-values/_expected/iife.js
test/form/object-destructuring-default-values/_expected/umd.js
test/form/object-destructuring-default-values/main.js

Ensure references inside default destructuring values count.

---

src/utils/transform.js
test/function/handles-stringified-sourcemaps/_config.js
test/function/handles-stringified-sourcemaps/main.js

Handle stringified sourcemaps

---

package.json
src/Bundle.js
src/utils/transformBundle.js
test/form/transform-bundle-plugin/_config.js
test/form/transform-bundle-plugin/_expected/amd.js
test/form/transform-bundle-plugin/_expected/cjs.js
test/form/transform-bundle-plugin/_expected/es6.js
test/form/transform-bundle-plugin/_expected/iife.js
test/form/transform-bundle-plugin/_expected/umd.js
test/form/transform-bundle-plugin/main.js
test/sourcemaps/transform-bundle/_config.js
test/sourcemaps/transform-bundle/main.js

Need to decide what to do with promises. This does not seem like a good idea.
```js
.then(bundle => {
return bundle.generate({...});
}).then(({ code, map }) => {})
```

Add transformBundle plugin hook

---

bin/help.md
bin/runRollup.js
test/cli/banner-intro-outro-footer/_config.js
test/cli/banner-intro-outro-footer/_expected.js
test/cli/banner-intro-outro-footer/main.js

support banner/footer/intro/outro options via CLI

---

src/ast/isReference.js
test/function/top-level-arrow-function/_config.js
test/function/top-level-arrow-function/main.js

handle a => a at top level

---

src/Bundle.js
test/sourcemaps/relative-paths/_config.js
test/sourcemaps/relative-paths/main.js
test/test.js

Fixes the issue described in #344

ensure dest is resolved against cwd, to make sourcemap paths relative when using CLI

---

src/Declaration.js
src/Module.js
test/form/side-effect-m/_config.js
test/form/side-effect-m/_expected/amd.js
test/form/side-effect-m/_expected/cjs.js
test/form/side-effect-m/_expected/es6.js
test/form/side-effect-m/_expected/iife.js
test/form/side-effect-m/_expected/umd.js
test/form/side-effect-m/even.js
test/form/side-effect-m/main.js
test/form/side-effect-m/odd.js

Fixes #397. It's not *totally* perfect, because if it encounters an infinite loop it's forced to assume that all functions in the cycle have side-effects, but it's a rare case and we're erring on the side of caution, so it's probably good enough.

Side-effect detection in cyclical function calls

---

src/utils/collapseSourcemaps.js
test/sourcemaps/untransformed-modules/_config.js
test/sourcemaps/untransformed-modules/foo.js
test/sourcemaps/untransformed-modules/main.js

Fixes #404. Will merge and release immediately as it's broken a couple of other modules.

fix sourcemap resolution in cases where some moudles are untransformed

---

bin/runRollup.js

```js
export default {
entry: ...,
external: [ 'yo', 'foo' ] // these have been ignored so far
};
```

Pass external config option through to `rollup.rollup`

---

src/Bundle.js
test/cli/config-external/_config.js
test/cli/config-external/_expected.js
test/cli/config-external/main.js
test/cli/config-external/rollup.config.js
test/test.js

#418, but with (hopefully) Windows support. Separate PR because I didn't want to mess up the commit history if this turns out to be wrong.
Damn you, Windows. Damn you forever

Force external (windows)

---

src/ast/isReference.js
test/form/computed-properties/_config.js
test/form/computed-properties/_expected/amd.js
test/form/computed-properties/_expected/cjs.js
test/form/computed-properties/_expected/es6.js
test/form/computed-properties/_expected/iife.js
test/form/computed-properties/_expected/umd.js
test/form/computed-properties/main.js

Ensure computed property keys are considered references.

---

src/Declaration.js
test/function/call-non-function-default-exports/_config.js
test/function/call-non-function-default-exports/foo.js
test/function/call-non-function-default-exports/main.js
test/function/default-exports-in-parens/_config.js
test/function/default-exports-in-parens/foo.js
test/function/default-exports-in-parens/main.js

handle calls to default exports other than function expressions

---

src/Bundle.js
src/Declaration.js
test/form/external-import-alias-shadow/_config.js
test/form/external-import-alias-shadow/_expected/amd.js
test/form/external-import-alias-shadow/_expected/cjs.js
test/form/external-import-alias-shadow/_expected/es6.js
test/form/external-import-alias-shadow/_expected/iife.js
test/form/external-import-alias-shadow/_expected/umd.js
test/form/external-import-alias-shadow/main.js
test/form/external-import-alias-shadow/parse.js

I haven't bothered looking into fixing this yet, but I can if it's not obvious to anyone else.

Add a failing test illustrating a renaming bug in ES6 output.

---

src/utils/defaults.js

provide informative error if rollup is used in browser without custom resolveId/load functions

---

src/Module.js
test/function/disappearing-exported-value/_config.js
test/function/disappearing-exported-value/answer.js
test/function/disappearing-exported-value/main.js

correctly rewrite exported var declarations

---

src/finalisers/cjs.js
test/form/external-imports-custom-names/_expected/cjs.js
test/form/external-imports/_expected/cjs.js

check that _interopDefault's input is a non-null object

---

src/utils/run.js
test/function/member-expression-assignment-in-function/_config.js
test/function/member-expression-assignment-in-function/main.js

Detect side effect in member expression assignment when not top level

---

bin/handleError.js
bin/runRollup.js
test/cli/config-missing-export/_config.js
test/test.js

via https://github.com/rollup/rollup-plugin-babel/issues/43#issuecomment-183884261

warn on missing options in config file

---

src/finalisers/es6.js
test/form/export-default-import/_config.js
test/form/export-default-import/_expected/amd.js
test/form/export-default-import/_expected/cjs.js
test/form/export-default-import/_expected/es6.js
test/form/export-default-import/_expected/iife.js
test/form/export-default-import/_expected/umd.js
test/form/export-default-import/main.js

fix misnamed exports of default imports in ES bundles

---

src/Statement.js
test/function/object-destructuring-renaming/_config.js
test/function/object-destructuring-renaming/main.js
test/function/object-destructuring-renaming/module.js

Make sure shorthand destructuring assignments don't break

---

src/Declaration.js
test/form/whitespace-around-namespace-member-expression/_config.js
test/form/whitespace-around-namespace-member-expression/_expected/amd.js
test/form/whitespace-around-namespace-member-expression/_expected/cjs.js
test/form/whitespace-around-namespace-member-expression/_expected/es6.js
test/form/whitespace-around-namespace-member-expression/_expected/iife.js
test/form/whitespace-around-namespace-member-expression/_expected/umd.js
test/form/whitespace-around-namespace-member-expression/foo.js
test/form/whitespace-around-namespace-member-expression/main.js

Rewrite an entire member expression for namespace imports.

---

src/Module.js
test/form/import-named-exported-global-with-alias/_config.js
test/form/import-named-exported-global-with-alias/_expected/amd.js
test/form/import-named-exported-global-with-alias/_expected/cjs.js
test/form/import-named-exported-global-with-alias/_expected/iife.js
test/form/import-named-exported-global-with-alias/_expected/umd.js
test/form/import-named-exported-global-with-alias/browser.js
test/form/import-named-exported-global-with-alias/main.js

Fix edge case for non-exported variable declaration aliases for exported globals.

---

src/Declaration.js
src/Reference.js
test/form/erroneous-nested-member-expression/_config.js
test/form/erroneous-nested-member-expression/_expected/amd.js
test/form/erroneous-nested-member-expression/_expected/cjs.js
test/form/erroneous-nested-member-expression/_expected/es6.js
test/form/erroneous-nested-member-expression/_expected/iife.js
test/form/erroneous-nested-member-expression/_expected/umd.js
test/form/erroneous-nested-member-expression/foo.js
test/form/erroneous-nested-member-expression/main.js

Handle erroneous nested member expressions

---

src/Module.js
test/function/trim-conditional-branches-in-exports/_config.js
test/function/trim-conditional-branches-in-exports/foo.js
test/function/trim-conditional-branches-in-exports/main.js

Prune dead conditional expressions more carefully.

---

src/Module.js
test/function/deshadowed-shorthand-property/_config.js
test/function/deshadowed-shorthand-property/foo.js
test/function/deshadowed-shorthand-property/main.js

Expand deshadowed shorthand properties

---

src/utils/collapseSourcemaps.js
test/sourcemaps/single-length-segments/_config.js
test/sourcemaps/single-length-segments/main.js
test/sourcemaps/single-length-segments/output.js
test/sourcemaps/single-length-segments/output.js.map

Don't throw on single-length sourcemap segment

---

bin/runRollup.js
src/Bundle.js
src/Module.js
src/rollup.js
test/cli/no-treeshake/_config.js
test/cli/no-treeshake/_expected.js
test/cli/no-treeshake/main.js
test/form/no-treeshake/_config.js
test/form/no-treeshake/_expected/amd.js
test/form/no-treeshake/_expected/cjs.js
test/form/no-treeshake/_expected/es6.js
test/form/no-treeshake/_expected/iife.js
test/form/no-treeshake/_expected/umd.js
test/form/no-treeshake/foo.js
test/form/no-treeshake/main.js
test/form/no-treeshake/quux.js
test/test.js

Add option to disable treeshaking

---

src/Bundle.js
test/function/load-returns-string-or-null/_config.js

sanity check output of load hook

---

src/Module.js
test/function/assignment-to-exports-b/_config.js
test/function/assignment-to-exports-b/main.js

allow rewrites of variable declarator inits

---

src/Bundle.js
test/function/external-alias/_config.js
test/function/external-alias/first/main.js
test/function/external-alias/first/module.js

Should close #660 (and maybe #633).

ensure that external alias are not treated as relative path

---

src/utils/run.js
test/form/preserve-debugger/_config.js
test/form/preserve-debugger/_expected/amd.js
test/form/preserve-debugger/_expected/cjs.js
test/form/preserve-debugger/_expected/es6.js
test/form/preserve-debugger/_expected/iife.js
test/form/preserve-debugger/_expected/umd.js
test/form/preserve-debugger/main.js

preserve debugger statements

---

src/Bundle.js
test/function/external-function/_config.js
test/function/external-function/main.js

allow options.external to be a function

---

src/finalisers/es6.js
test/form/conflicting-imports/_config.js
test/form/conflicting-imports/_expected/amd.js
test/form/conflicting-imports/_expected/cjs.js
test/form/conflicting-imports/_expected/es6.js
test/form/conflicting-imports/_expected/iife.js
test/form/conflicting-imports/_expected/umd.js
test/form/conflicting-imports/main.js
test/form/conflicting-imports/other.js

deconflict ES bundle imports

---

src/Bundle.js
src/Declaration.js
src/Module.js
src/finalisers/cjs.js
src/finalisers/iife.js
src/finalisers/shared/getInteropBlock.js
src/rollup.js
test/form/prefer-const/_config.js
test/form/prefer-const/_expected/amd.js
test/form/prefer-const/_expected/cjs.js
test/form/prefer-const/_expected/es6.js
test/form/prefer-const/_expected/iife.js
test/form/prefer-const/_expected/umd.js
test/form/prefer-const/main.js
test/form/prefer-const/namespace.js
test/test.js

options.preferConst to use const instead of var when creating statements

---

src/Declaration.js
src/ExternalModule.js
src/finalisers/cjs.js
src/finalisers/es6.js
src/finalisers/shared/getInteropBlock.js
test/form/import-external-namespace-and-default/_config.js
test/form/import-external-namespace-and-default/_expected/amd.js
test/form/import-external-namespace-and-default/_expected/cjs.js
test/form/import-external-namespace-and-default/_expected/es6.js
test/form/import-external-namespace-and-default/_expected/iife.js
test/form/import-external-namespace-and-default/_expected/umd.js
test/form/import-external-namespace-and-default/main.js
test/form/import-external-namespace-and-default/other.js

distinguish between default and namespace imports from external module

---

bin/runRollup.js
src/rollup.js
test/cli/multiple-targets/_config.js
test/cli/multiple-targets/_expected/cjs.js
test/cli/multiple-targets/_expected/es6.js
test/cli/multiple-targets/main.js
test/cli/multiple-targets/rollup.config.js
test/test.js

Allow specifying multiple output targets.

---

package.json
src/rollup.js
src/utils/first.js
src/utils/fs.js
src/utils/promise.js
src/utils/transform.js
test/function/transformer-async/_config.js

remove es6-promise

---

bin/runRollup.js
test/cli/multiple-targets-shared-config/_config.js
test/cli/multiple-targets-shared-config/_expected/cjs.js
test/cli/multiple-targets-shared-config/_expected/cjs.js.map
test/cli/multiple-targets-shared-config/_expected/es6.js
test/cli/multiple-targets-shared-config/_expected/es6.js.map
test/cli/multiple-targets-shared-config/main.js
test/cli/multiple-targets-shared-config/rollup.config.js

Merge target options with main options.

---

src/utils/defaults.js
test/form/absolute-path-resolver/_config.js
test/form/absolute-path-resolver/_expected/amd.js
test/form/absolute-path-resolver/_expected/cjs.js
test/form/absolute-path-resolver/_expected/es6.js
test/form/absolute-path-resolver/_expected/iife.js
test/form/absolute-path-resolver/_expected/umd.js
test/form/absolute-path-resolver/a.js
test/form/absolute-path-resolver/main.js

Add normalize-absolute test

---

src/rollup.js
test/test.js

Fixes #717.
I didn't add a test for this because I wasn't really sure where it should go.

Allow `sourceMapFile` as an option.

---

bin/src/runRollup.js
test/cli/external-modules-auto-global/_config.js
test/cli/external-modules-auto-global/main.js

allow --globals to work with --external and options.external in whatever configuration

---

src/Module.js
test/form/assignment-to-exports-class-declaration/_expected/es.js
test/form/assignment-to-exports/_config.js
test/form/assignment-to-exports/_expected/amd.js
test/form/assignment-to-exports/_expected/cjs.js
test/form/assignment-to-exports/_expected/es.js
test/form/assignment-to-exports/_expected/iife.js
test/form/assignment-to-exports/_expected/umd.js
test/form/assignment-to-exports/main.js

ensure reassigned exports are declared in an ES bundle

---

bin/src/runRollup.js
src/rollup.js
test/cli/sourcemap-newline/_config.js
test/cli/sourcemap-newline/main.js
test/test.js

add newline after sourcemap comment

---

rollup.config.js
src/Bundle.js
src/Module.js
test/function/has-resolved-ids/_config.js
test/function/has-resolved-ids/foo.js
test/function/has-resolved-ids/main.js
test/test.js

Cache resolve

---

src/Module.js

Ref https://github.com/rollup/rollup/issues/723

Module render performance tweak

---

src/Bundle.js
src/utils/collapseSourcemaps.js
src/utils/transform.js
src/utils/transformBundle.js

Cache decoded mappings

---

src/utils/getIndentString.js
test/cli/banner-intro-outro-footer/_config.js
test/cli/module-name/_config.js
test/cli/no-strict/_config.js
test/cli/no-treeshake/_config.js
test/test.js

Change indent default to false

---

src/Bundle.js
test/function/check-resolve-for-entry/_config.js
test/function/load-returns-string-or-null/main.js

Add explicit entry resolve error message

---

bin/src/runRollup.js
test/cli/no-conflict/_config.js
test/cli/no-conflict/_expected.js
test/cli/no-conflict/main.js
test/cli/no-conflict/rollup.config.js

fix noConflict when used via config file

---

src/Bundle.js
src/finalisers/amd.js
src/finalisers/cjs.js
src/finalisers/es.js
src/finalisers/iife.js
src/finalisers/umd.js
test/form/intro-and-outro/_config.js
test/form/intro-and-outro/_expected/amd.js
test/form/intro-and-outro/_expected/cjs.js
test/form/intro-and-outro/_expected/es.js
test/form/intro-and-outro/_expected/iife.js
test/form/intro-and-outro/_expected/umd.js
test/form/intro-and-outro/main.js

put outro after export block, not before

---

README.md

fixes https://github.com/rollup/rollup/issues/878

Update link to Codecov image. 

---

bin/src/runRollup.js
rollup.config.cli.js

See https://github.com/rollup/rollup/pull/706#issuecomment-243290485

replace require kludge in runRollup.js

---

src/Bundle.js
src/finalisers/amd.js
src/finalisers/cjs.js
src/finalisers/es.js
src/finalisers/iife.js
src/finalisers/umd.js
test/form/intro-and-outro/_config.js
test/form/intro-and-outro/_expected/amd.js
test/form/intro-and-outro/_expected/cjs.js
test/form/intro-and-outro/_expected/es.js
test/form/intro-and-outro/_expected/iife.js
test/form/intro-and-outro/_expected/umd.js
test/form/intro-and-outro/main.js

ensure intro appears before interop block

---

src/Module.js
test/function/module-tree/_config.js
test/function/module-tree/bar.js
test/function/module-tree/foo.js
test/function/module-tree/main.js
test/function/module-tree/nested/baz.js
test/function/module-tree/nested/qux.js

include dependencies in bundle.modules

---

src/Bundle.js
src/Module.js
src/rollup.js
src/utils/flushTime.js

Ref https://github.com/rollup/rollup/pull/902#issuecomment-246112330

Add performance labels

---

src/ast/nodes/ExpressionStatement.js
src/ast/nodes/ForInStatement.js
src/ast/nodes/ForOfStatement.js
src/ast/nodes/IfStatement.js
src/ast/nodes/ThrowStatement.js
src/ast/nodes/index.js
src/ast/nodes/shared/Statement.js
src/ast/nodes/shared/assignTo.js
test/form/effect-in-for-of-loop-in-functions/_config.js
test/form/effect-in-for-of-loop-in-functions/_expected/amd.js
test/form/effect-in-for-of-loop-in-functions/_expected/cjs.js
test/form/effect-in-for-of-loop-in-functions/_expected/es.js
test/form/effect-in-for-of-loop-in-functions/_expected/iife.js
test/form/effect-in-for-of-loop-in-functions/_expected/umd.js
test/form/effect-in-for-of-loop-in-functions/main.js
test/form/effect-in-for-of-loop/_config.js
test/form/effect-in-for-of-loop/_expected/amd.js
test/form/effect-in-for-of-loop/_expected/cjs.js
test/form/effect-in-for-of-loop/_expected/es.js
test/form/effect-in-for-of-loop/_expected/iife.js
test/form/effect-in-for-of-loop/_expected/umd.js
test/form/effect-in-for-of-loop/main.js

Preserve effects in for-of and for-in statements

---

package.json
src/ast/Node.js
src/ast/nodes/ArrowFunctionExpression.js
src/ast/nodes/ForInStatement.js
src/ast/nodes/ForOfStatement.js
src/ast/nodes/ForStatement.js
test/form/body-less-for-loops/_config.js
test/form/body-less-for-loops/_expected/amd.js
test/form/body-less-for-loops/_expected/cjs.js
test/form/body-less-for-loops/_expected/es.js
test/form/body-less-for-loops/_expected/iife.js
test/form/body-less-for-loops/_expected/umd.js
test/form/body-less-for-loops/main.js
test/form/for-loop-with-empty-head/_config.js
test/form/for-loop-with-empty-head/_expected/amd.js
test/form/for-loop-with-empty-head/_expected/cjs.js
test/form/for-loop-with-empty-head/_expected/es.js
test/form/for-loop-with-empty-head/_expected/iife.js
test/form/for-loop-with-empty-head/_expected/umd.js
test/form/for-loop-with-empty-head/main.js

allow empty for loop heads

---

src/ast/nodes/ClassDeclaration.js
test/function/includes-superclass/_config.js
test/function/includes-superclass/base.js
test/function/includes-superclass/main.js
test/function/includes-superclass/thing.js

include superclass when including a class declaration

---

src/ast/scopes/ModuleScope.js
test/function/warn-on-unused-missing-imports/_config.js
test/function/warn-on-unused-missing-imports/foo.js
test/function/warn-on-unused-missing-imports/main.js

warn on missing unused imports in deshadowing phase, rather than throwing

---

src/Bundle.js
src/rollup.js
test/test.js

ensure bundle ends with newline

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Goal here is to waste less time reproducing bugs from scraps of evidence. Would welcome feedback on any of the wording

add issue and pull request templates

---

src/ast/nodes/ExportDefaultDeclaration.js
test/function/includes-internally-used-default-export/_config.js
test/function/includes-internally-used-default-export/main.js
test/function/includes-internally-used-default-export/module.js

[They're currently omitted.](http://rollupjs.org/?shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybW9kdWxlTmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMm1vZHVsZXMlMjIlM0ElNUIlN0IlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0IlMjBiJTIwJTdEJTIwZnJvbSUyMCcuJTJGbW9kdWxlLmpzJyUzQiU1Q24lNUNuY29uc29sZS5sb2coYigpKSUzQiU1Q24lMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybW9kdWxlLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGRlZmF1bHQlMjBmdW5jdGlvbiUyMGEoKSUyMCU3QiU1Q24lMjAlMjBjb25zb2xlLmxvZygneCcpJTNCJTVDbiUyMCUyMHJldHVybiUyMDUlM0IlNUNuJTdEJTVDbiU1Q25hKCklM0IlNUNuJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwYigpJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMGEoKSUyMCUyQiUyMDEwJTNCJTVDbiU3RCU1Q24lMjIlN0QlNUQlN0Q=)

Include default exports used within the module but not by importers.

---

src/Bundle.js
src/utils/getExportMode.js

This improves on https://github.com/rollup/rollup/issues/587#issuecomment-216528129

Avoid exports:auto warning on format:es

---

src/ast/nodes/IfStatement.js
test/function/if-statement-with-false-condition/_config.js
test/function/if-statement-with-false-condition/main.js

Make optimization for if statements with false conditions not break generated code

---

src/ast/nodes/BlockStatement.js
test/form/non-empty-block-statement/_config.js
test/form/non-empty-block-statement/_expected/amd.js
test/form/non-empty-block-statement/_expected/cjs.js
test/form/non-empty-block-statement/_expected/es.js
test/form/non-empty-block-statement/_expected/iife.js
test/form/non-empty-block-statement/_expected/umd.js
test/form/non-empty-block-statement/main.js

Do not skip non empty block statements

---

src/ast/scopes/Scope.js

i couldn't think of a reason you'd opt out of destructuring here; apologies if i'm mistaken somehow

destructure options in Scope constructor

---

test/form/unused-called-import/_config.js
test/form/unused-called-import/_expected/amd.js
test/form/unused-called-import/_expected/cjs.js
test/form/unused-called-import/_expected/es.js
test/form/unused-called-import/_expected/iife.js
test/form/unused-called-import/_expected/umd.js
test/form/unused-called-import/dead.js
test/form/unused-called-import/foo.js
test/form/unused-called-import/main.js
test/form/unused-called-with-side-effects/_config.js
test/form/unused-called-with-side-effects/_expected/amd.js
test/form/unused-called-with-side-effects/_expected/cjs.js
test/form/unused-called-with-side-effects/_expected/es.js
test/form/unused-called-with-side-effects/_expected/iife.js
test/form/unused-called-with-side-effects/_expected/umd.js
test/form/unused-called-with-side-effects/main.js

Add failing test case for #977.

---

src/ast/nodes/shared/callHasEffects.js
test/function/braceless-arrow-function-returning-function/_config.js
test/function/braceless-arrow-function-returning-function/main.js

fix TypeError in arrow function without braces returning a function

---

src/ast/nodes/MemberExpression.js
test/function/namespace-missing-export/_config.js

fix missing namespace member warnings

---

src/Module.js
test/function/default-not-reexported/_config.js
test/function/default-not-reexported/bar.js
test/function/default-not-reexported/foo.js
test/function/default-not-reexported/main.js

Fixes #1028. Will need to be a 0.37 release as it could potentially break some people's code.

[BREAKING] fix behaviour of export * in relation to defaults

---

src/Declaration.js
test/function/call-external-function/_config.js
test/function/call-external-function/foo.js
test/function/call-external-function/main.js

implement gatherPossibleValues on ExternalDeclaration

---

src/Bundle.js
src/finalisers/amd.js
src/finalisers/cjs.js
src/finalisers/es.js
src/finalisers/iife.js
src/finalisers/umd.js
test/cli/banner-intro-outro-footer/_expected.js
test/form/intro-and-outro/_config.js
test/form/intro-and-outro/_expected/amd.js
test/form/intro-and-outro/_expected/cjs.js
test/form/intro-and-outro/_expected/es.js
test/form/intro-and-outro/_expected/iife.js
test/form/intro-and-outro/_expected/umd.js

Somehow this got overlooked – plugin outros were never accounted for. Fixes #1116

support plugin outros

---

src/Bundle.js
src/Module.js
test/function/sourcemapping-url-comment/_config.js
test/function/sourcemapping-url-comment/main.js

only remove valid sourcemapping URL comments

---

src/ast/nodes/VariableDeclarator.js
test/function/vars-not-removed-in-if-block/_config.js
test/function/vars-not-removed-in-if-block/main.js

include blocks containing activated var declarations

---

src/ast/nodes/FunctionExpression.js
test/function/preserves-function-expression-names/_config.js
test/function/preserves-function-expression-names/main.js

bind function expression ids to the child scope

---

test/form/removes-existing-sourcemap-comments/_expected/amd.js
test/form/removes-existing-sourcemap-comments/_expected/cjs.js
test/form/removes-existing-sourcemap-comments/_expected/es.js
test/form/removes-existing-sourcemap-comments/_expected/iife.js
test/form/removes-existing-sourcemap-comments/_expected/umd.js
test/form/removes-existing-sourcemap-comments/main.js

@Rich-Harris i am really sorry for being that noisy.

Failling test for #1104

---

src/Bundle.js
test/function/consistent-renaming/main.js
test/function/cycles-pathological-3/_config.js
test/function/cycles-pathological-3/a.js
test/function/cycles-pathological-3/b.js
test/function/cycles-pathological-3/c.js
test/function/cycles-pathological-3/main.js
test/function/cycles-pathological-3/x.a.js
test/function/cycles-pathological-3/x.b.js
test/function/cycles-pathological-3/x.c.js
test/function/empty-exports/_config.js
test/function/handles-multiple-declarations/_config.js
test/function/handles-multiple-declarations/main.js
test/function/module-tree/_config.js
test/function/warn-on-empty-bundle/_config.js
test/function/warn-on-empty-bundle/main.js

warn on empty bundle, and remove some tests that are no longer testing anything

---

src/Bundle.js
src/Declaration.js
src/finalisers/cjs.js
src/finalisers/es.js
test/form/prefer-const/_expected/amd.js
test/form/prefer-const/_expected/cjs.js
test/form/prefer-const/_expected/es.js
test/form/prefer-const/_expected/iife.js
test/form/prefer-const/_expected/umd.js
test/form/prefer-const/main.js
test/form/unused-import/_config.js
test/form/unused-import/_expected/amd.js
test/form/unused-import/_expected/cjs.js
test/form/unused-import/_expected/es.js
test/form/unused-import/_expected/iife.js
test/form/unused-import/_expected/umd.js
test/form/unused-import/main.js
test/function/class-methods-not-renamed/foo.js
test/function/preserves-function-expression-names/_config.js
test/function/preserves-function-expression-names/main.js
test/function/unused-import/_config.js
test/function/unused-import/main.js

remove, and warn about, unused imports from external modules

---

package.json

Since we're using GitHub we can use [the shorthand syntax](https://docs.npmjs.com/files/package.json#repository).

Simplify repository value

---

src/ast/nodes/ClassDeclaration.js
src/ast/nodes/FunctionDeclaration.js
test/form/unused-inner-functions-and-classes/_config.js
test/form/unused-inner-functions-and-classes/_expected/amd.js
test/form/unused-inner-functions-and-classes/_expected/cjs.js
test/form/unused-inner-functions-and-classes/_expected/es.js
test/form/unused-inner-functions-and-classes/_expected/iife.js
test/form/unused-inner-functions-and-classes/_expected/umd.js
test/form/unused-inner-functions-and-classes/main.js
test/form/unused-inner-functions-and-classes/stuff.js

drop unused function and class declarations within functions

---

src/ast/nodes/FunctionExpression.js
test/function/deshadows-function-expression-id/_config.js
test/function/deshadows-function-expression-id/foo.js
test/function/deshadows-function-expression-id/main.js
test/function/preserves-function-expression-names/_config.js

deconflict function expression IDs

---

package.json
src/ast/nodes/IfStatement.js
test/function/preserves-var-declarations-in-dead-branches/_config.js
test/function/preserves-var-declarations-in-dead-branches/main.js

preserve var declarations in dead branches

---

src/ast/nodes/LogicalExpression.js
src/ast/nodes/index.js
test/form/skips-dead-branches-i/_config.js
test/form/skips-dead-branches-j/_config.js
test/form/skips-dead-branches-j/_expected/amd.js
test/form/skips-dead-branches-j/_expected/cjs.js
test/form/skips-dead-branches-j/_expected/es.js
test/form/skips-dead-branches-j/_expected/iife.js
test/form/skips-dead-branches-j/_expected/umd.js
test/form/skips-dead-branches-j/main.js

Half of #1061 (the other half is https://github.com/rollup/rollup-plugin-commonjs/issues/151)

statically analyse LogicalExpression nodes

---

src/Bundle.js
src/rollup.js
test/cli/sourcemap-newline/_config.js
test/test.js

warn on missing format

---

bin/src/handleError.js
bin/src/runRollup.js

change recommendation to local installation of rollup-watch

---

src/ast/nodes/IfStatement.js
test/function/vars-with-init-in-dead-branch/_config.js
test/function/vars-with-init-in-dead-branch/main.js

ignore var inits in dead branches

---

package.json

chmod a+x bin/rollup

---

src/ast/nodes/ExportDefaultDeclaration.js
test/function/export-default-no-space/_config.js
test/function/export-default-no-space/main.js

Via [Gitter](https://gitter.im/rollup/rollup?at=586d12677a3f79ef5dd61d15)

handle export default{}

---

src/Module.js
src/finalisers/amd.js
src/finalisers/cjs.js
src/finalisers/es.js
src/finalisers/iife.js
src/finalisers/shared/getExportBlock.js
src/finalisers/umd.js
test/form/reexports-from-external/_config.js
test/form/reexports-from-external/_expected/amd.js
test/form/reexports-from-external/_expected/cjs.js
test/form/reexports-from-external/_expected/es.js
test/form/reexports-from-external/_expected/iife.js
test/form/reexports-from-external/_expected/umd.js
test/form/reexports-from-external/main.js
test/function/reexports-from-external/_config.js
test/function/reexports-from-external/main.js

fixes #791. maybe not the nicest code in the world but it works

implement export * from external

---

src/ast/nodes/ThrowStatement.js
test/form/side-effect-h/_expected/amd.js
test/form/side-effect-h/_expected/cjs.js
test/form/side-effect-h/_expected/es.js
test/form/side-effect-h/_expected/iife.js
test/form/side-effect-h/_expected/umd.js
test/form/side-effect-t/_config.js
test/form/side-effect-t/_expected/amd.js
test/form/side-effect-t/_expected/cjs.js
test/form/side-effect-t/_expected/es.js
test/form/side-effect-t/_expected/iife.js
test/form/side-effect-t/_expected/umd.js
test/form/side-effect-t/main.js

Fixes one of the bugs listed in #305

`throw` always considered to be a side effect

---

src/ast/nodes/shared/callHasEffects.js
test/form/class-constructor-side-effect/_config.js
test/form/class-constructor-side-effect/_expected/amd.js
test/form/class-constructor-side-effect/_expected/cjs.js
test/form/class-constructor-side-effect/_expected/es.js
test/form/class-constructor-side-effect/_expected/iife.js
test/form/class-constructor-side-effect/_expected/umd.js
test/form/class-constructor-side-effect/main.js

include new expressions where callee is a class

---

src/finalisers/umd.js
test/form/indent-false/_expected/amd.js
test/form/indent-false/_expected/iife.js
test/form/indent-false/_expected/umd.js
test/form/indent-false/main.js
test/form/indent-spaces/_config.js
test/form/indent-spaces/_expected/amd.js
test/form/indent-spaces/_expected/cjs.js
test/form/indent-spaces/_expected/es.js
test/form/indent-spaces/_expected/iife.js
test/form/indent-spaces/_expected/umd.js
test/form/indent-spaces/main.js

use options.indent for UMD block

---

bin/src/help.md
bin/src/runRollup.js
test/cli/silent/_config.js
test/cli/silent/_expected.js
test/cli/silent/foo.js
test/cli/silent/main.js
test/test.js

suppress warnings with --silent

---

CHANGELOG.md

mention `throw` always considered to be a side effect

change log addition for 0.41.0

---

src/Module.js
test/form/export-all-multiple/_config.js
test/form/export-all-multiple/_expected/amd.js
test/form/export-all-multiple/_expected/cjs.js
test/form/export-all-multiple/_expected/es.js
test/form/export-all-multiple/_expected/iife.js
test/form/export-all-multiple/_expected/umd.js
test/form/export-all-multiple/main.js

handle multiple export * from external declarations

---

src/ast/nodes/shared/callHasEffects.js
test/function/handle-calling-uncallable/_config.js
test/function/handle-calling-uncallable/foo.js
test/function/handle-calling-uncallable/main.js

handle call expressions of uncallable things more gracefully

---

package.json
src/ast/nodes/ConditionalExpression.js
test/form/conditional-put-parens-around-sequence/_config.js
test/form/conditional-put-parens-around-sequence/_expected/amd.js
test/form/conditional-put-parens-around-sequence/_expected/cjs.js
test/form/conditional-put-parens-around-sequence/_expected/es.js
test/form/conditional-put-parens-around-sequence/_expected/iife.js
test/form/conditional-put-parens-around-sequence/_expected/umd.js
test/form/conditional-put-parens-around-sequence/main.js

put parens around sequences if conditional simplified

---

src/Module.js
test/test.js

Fix cache losing originalSourceMap for loaders with sourcemaps

---

README.md

There was a very tiny typo in the readme. :-)

fix a tiny typo in the readme

---

src/ast/nodes/BinaryExpression.js
test/form/exponentiation-operator/_config.js
test/form/exponentiation-operator/_expected/amd.js
test/form/exponentiation-operator/_expected/cjs.js
test/form/exponentiation-operator/_expected/es.js
test/form/exponentiation-operator/_expected/iife.js
test/form/exponentiation-operator/_expected/umd.js
test/form/exponentiation-operator/main.js

This builds on #1419 by explicitly supporting the exponentiation operator. Closes #1416

support exponentiation operator

---

src/Bundle.js

Hi, this PR is to tackle issue #1274 brought up by @coni2k. 
Using a couple of null checks the verification produces its intended result.
Feel free to point out any issue about this, as I'm not aware of any underlying implications it would have (and it's my first PR here).
Hopefully this makes sense!
Best regards.

Fix for cannot-import-self check, adding sanity check

---

bin/src/runRollup.js

add ROLLUP_WATCH environment variable

---

src/ast/Node.js
src/ast/nodes/ConditionalExpression.js
src/ast/nodes/Identifier.js
src/ast/nodes/IfStatement.js
src/ast/nodes/MemberExpression.js
src/ast/nodes/ThisExpression.js
test/sourcemaps/names-transformed/_config.js

Prevent some warnings related to magic-string deprecations.

Fix magic-string deprecations

---

bin/src/runRollup.js
src/Bundle.js
src/rollup.js
test/cli/config-plugin-entry/_config.js
test/cli/config-plugin-entry/_expected.js
test/cli/config-plugin-entry/main.js
test/cli/config-plugin-entry/rollup.config.js
test/test.js

apply plugins before checking for options.entry

---

src/ast/nodes/IfStatement.js

Fix magic-string insertRight deprecation warning.

use prependRight in IfStatement

---

src/utils/transform.js
test/function/plugin-error-loc-instead-pos/_config.js
test/function/plugin-error-loc-instead-pos/main.js
test/function/plugin-warn-loc-instead-pos/_config.js
test/function/plugin-warn-loc-instead-pos/main.js

Let this.error and this.warn accept loc-object

---

src/ast/nodes/CatchClause.js
src/ast/nodes/index.js
test/function/preserves-catch-argument/_config.js
test/function/preserves-catch-argument/main.js

fix catch clause scopes

---

package-lock.json
package.json
test/leak/test.js

remove weak from optionalDependencies

---

src/Bundle.js
src/Module.js
test/mocha.opts
test/test.js

This fixes https://github.com/rollup/rollup-watch/issues/54

separate resolvedIds from resolvedExternalIds

---

bin/src/runRollup.js

Aint sure how to add test for this, although I still feel that this should be released asap as patch version and the test can be added in another PR - if you guide me a little I can provide that ;)
cc @Rich-Harris @bfred-it

Fixed --extend flag not being passed correctly from the CLI arguments

---

src/ast/nodes/VariableDeclaration.js
test/form/line-wrap/_config.js
test/form/line-wrap/_expected/amd.js
test/form/line-wrap/_expected/cjs.js
test/form/line-wrap/_expected/es.js
test/form/line-wrap/_expected/iife.js
test/form/line-wrap/_expected/umd.js
test/form/line-wrap/main.js

I'm not sure if I went about writing the tests the correct way. I'm interested in helping out with rollup and thought this would be a good, small way to get started. I used the tests linked in the issue as a reference. Please let me know if I should rename anything or if the tests aren't sufficient. Also, I wasn't sure where to find a reference of unconditionally adding parens (as per Buble) to give that a try instead of the newline, but I'm open to trying that instead.
Cheers
Fixes #1275

Semicolon Removal Fix

---

bin/src/runRollup.js
test/cli/multiple-configs/_config.js
test/cli/multiple-configs/_expected/bundle1.js
test/cli/multiple-configs/main.js
test/cli/multiple-configs/rollup.config.js

This modifications fix the issue but need improvement to log the success of bundle generation and fix the UnhandledPromiseRejectionWarning.
Your help would be appreciated.

Fix issue : In multiple configurations context, no bundle is created

---

bin/src/run/index.js
package.json
rollup.config.cli.js

Can't remember why this was in here at all. Let's remove it and see what happens

remove source-map-support

---

src/watch/index.js
test/watch/index.js
test/watch/samples/globals/main.js

pass through all necessary options to bundle.write in rollup.watch

---

src/ast/nodes/ForInStatement.js
test/function/samples/for-loop-head-dependencies/_config.js
test/function/samples/for-loop-head-dependencies/main.js

init right hand side of for-in loop head with correct scope

---

src/Bundle.js
src/Declaration.js
src/Module.js
src/finalisers/cjs.js
src/finalisers/es.js
src/finalisers/shared/getExportBlock.js
test/form/samples/external-imports/_expected/es.js
test/form/samples/import-external-namespace-and-default/_expected/es.js
test/form/samples/import-namespace/_config.js
test/form/samples/import-namespace/_expected/amd.js
test/form/samples/import-namespace/_expected/cjs.js
test/form/samples/import-namespace/_expected/es.js
test/form/samples/import-namespace/_expected/iife.js
test/form/samples/import-namespace/_expected/umd.js
test/form/samples/import-namespace/main.js
test/form/samples/no-treeshake/_expected/es.js

#1511 led down a bit of a rabbit hole. We need to treat exports and re-exports differently — this PR implements that.

Treat exports and re-exports differently

---

src/ast/scopes/ModuleScope.js
test/function/samples/deshadowed-namespaced-import/_config.js
test/function/samples/deshadowed-namespaced-import/foo.js
test/function/samples/deshadowed-namespaced-import/main.js
test/function/samples/deshadowed-namespaced-import/ns.js

fixes #1488 and #1505 (hopefully)

deshadow indirectly-imported namespaces

---

src/ast/nodes/ForOfStatement.js
src/ast/nodes/ForStatement.js
test/function/samples/for-in-loop-head-dependencies/_config.js
test/function/samples/for-in-loop-head-dependencies/main.js
test/function/samples/for-loop-head-dependencies/_config.js
test/function/samples/for-of-loop-head-dependencies/_config.js
test/function/samples/for-of-loop-head-dependencies/main.js

init for loop scopes correctly

---

bin/src/run/batchWarnings.js
bin/src/run/index.js
bin/src/run/loadConfigFile.js
bin/src/run/watch.js
package-lock.json
package.json
src/watch/index.js

watch config file, restart on changes

---

src/ast/scopes/ModuleScope.js
test/function/samples/deshadowed-namespaced-external-import-ignored/_config.js
test/function/samples/deshadowed-namespaced-external-import-ignored/foo.js
test/function/samples/deshadowed-namespaced-external-import-ignored/main.js
test/function/samples/deshadowed-namespaced-external-import-ignored/ns.js

ignore external namespace imports when deshadowing

---

.travis.yml
appveyor.yml

Add NodeJS 8 travis&appveyor builds

---

src/ast/scopes/ModuleScope.js
test/function/samples/deshadowed-namespaced-import-renamed/_config.js
test/function/samples/deshadowed-namespaced-import-renamed/foo.js
test/function/samples/deshadowed-namespaced-import-renamed/main.js
test/function/samples/deshadowed-namespaced-import-renamed/ns.js

I *think* this is the right fix for #1550

deshadow aliased imports

---

package-lock.json
src/utils/promise.js

use Promise.resolve in mapSequence, to ensure each item is thenable

---

bin/src/run/watch.js
src/watch/index.js

update configs when watcher is restarted, and print deprecation warnings in watch mode

---

README.md

Fix JavaScript API link in README.md

---

README.md

Per https://gist.github.com/Rich-Harris/d472c50732dab03efeb37472b08a3f32 the options have been changed, but these changes were not reflected in the README.

Update output options in README

---

src/ast/nodes/ReturnStatement.js
test/function/samples/associate-function-return-values-4/_config.js
test/function/samples/associate-function-return-values-4/main.js

Handle empty return statements

---

src/finalisers/iife.js
src/finalisers/shared/setupNamespace.js
src/finalisers/umd.js
test/form/samples/use-global-map-for-export-name/_config.js
test/form/samples/use-global-map-for-export-name/_expected/amd.js
test/form/samples/use-global-map-for-export-name/_expected/cjs.js
test/form/samples/use-global-map-for-export-name/_expected/es.js
test/form/samples/use-global-map-for-export-name/_expected/iife.js
test/form/samples/use-global-map-for-export-name/_expected/umd.js
test/form/samples/use-global-map-for-export-name/main.js

Closes #1746. There should be a test for this.

Use globals map for export name

---

src/ast/nodes/shared/pureFunctions.js
test/form/samples/json-parse-is-not-pure/_config.js
test/form/samples/json-parse-is-not-pure/_expected/amd.js
test/form/samples/json-parse-is-not-pure/_expected/cjs.js
test/form/samples/json-parse-is-not-pure/_expected/es.js
test/form/samples/json-parse-is-not-pure/_expected/iife.js
test/form/samples/json-parse-is-not-pure/_expected/umd.js
test/form/samples/json-parse-is-not-pure/main.js
test/form/samples/json-stringify-is-not-pure/_config.js
test/form/samples/json-stringify-is-not-pure/_expected/amd.js
test/form/samples/json-stringify-is-not-pure/_expected/cjs.js
test/form/samples/json-stringify-is-not-pure/_expected/es.js
test/form/samples/json-stringify-is-not-pure/_expected/iife.js
test/form/samples/json-stringify-is-not-pure/_expected/umd.js
test/form/samples/json-stringify-is-not-pure/main.js

Should close https://github.com/rollup/rollup/issues/1775

Do not mark JSON.parse and JSON.stringify as pure functions

---

src/ast/nodes/ExportDefaultDeclaration.js
test/form/samples/removes-existing-sourcemap-comments/_expected/amd.js
test/form/samples/removes-existing-sourcemap-comments/_expected/cjs.js
test/form/samples/removes-existing-sourcemap-comments/_expected/es.js
test/form/samples/removes-existing-sourcemap-comments/_expected/iife.js
test/form/samples/removes-existing-sourcemap-comments/_expected/umd.js
test/form/samples/this-in-imports/_expected/amd.js
test/form/samples/this-in-imports/_expected/cjs.js
test/form/samples/this-in-imports/_expected/es.js
test/form/samples/this-in-imports/_expected/iife.js
test/form/samples/this-in-imports/_expected/umd.js
test/form/samples/unused-called-import/_expected/amd.js
test/form/samples/unused-called-import/_expected/cjs.js
test/form/samples/unused-called-import/_expected/es.js
test/form/samples/unused-called-import/_expected/iife.js
test/form/samples/unused-called-import/_expected/umd.js
test/function/samples/cycles-default-anonymous-function-hoisted/_config.js
test/function/samples/cycles-default-anonymous-function-hoisted/f.js
test/function/samples/cycles-default-anonymous-function-hoisted/g.js
test/function/samples/cycles-default-anonymous-function-hoisted/main.js

Fixes #1784
I didn't add any test because I already modified the expected output of some existing tests. If you want a new test, let me know.

Hoist default exported anonymous function declarations

---

src/finalisers/es.ts
test/form/samples/re-export-aliasing/_config.js
test/form/samples/re-export-aliasing/_expected/amd.js
test/form/samples/re-export-aliasing/_expected/cjs.js
test/form/samples/re-export-aliasing/_expected/es.js
test/form/samples/re-export-aliasing/_expected/iife.js
test/form/samples/re-export-aliasing/_expected/umd.js
test/form/samples/re-export-aliasing/first.js
test/form/samples/re-export-aliasing/main.js

This tests the remaining bug from https://github.com/rollup/rollup/issues/1794#issuecomment-351728892, not already solved by https://github.com/rollup/rollup/pull/1795.
~~Fix still pending though....~~

Reexport aliasing bug

---

package.json
src/Module.ts
src/ast/CallOptions.ts
src/ast/ExecutionPathOptions.ts
src/ast/nodes/ArrayPattern.ts
src/ast/nodes/AssignmentPattern.ts
src/ast/nodes/BinaryExpression.ts
src/ast/nodes/BlockStatement.ts
src/ast/nodes/LogicalExpression.ts
src/ast/scopes/BlockScope.ts
src/ast/scopes/CatchScope.ts
src/ast/scopes/GlobalScope.ts
src/ast/variables/VariableReassignmentTracker.ts
src/node-entry.ts
src/utils/flushTime.ts
src/utils/transform.ts
src/watch/index.ts
tsconfig.json

Closes: #1836
Some code changes needed to be done as some interface needs to be exported.

feat: ship TypeScript declaration files

---

CHANGELOG.md

docs: typescripts is always written as a single word

---

src/Module.ts
src/utils/defaults.ts

This is a precursor piece of #1845 that has no functionality change.

extract missing export error for reuse

---

src/Chunk.ts
src/Module.ts
src/ast/nodes/BlockStatement.ts
src/ast/nodes/ClassDeclaration.ts
src/ast/nodes/ConditionalExpression.ts
src/ast/nodes/EmptyStatement.ts
src/ast/nodes/ExportAllDeclaration.ts
src/ast/nodes/ExportDefaultDeclaration.ts
src/ast/nodes/ExportNamedDeclaration.ts
src/ast/nodes/ExpressionStatement.ts
src/ast/nodes/FunctionDeclaration.ts
src/ast/nodes/Identifier.ts
src/ast/nodes/IfStatement.ts
src/ast/nodes/Import.ts
src/ast/nodes/ImportDeclaration.ts
src/ast/nodes/Literal.ts
src/ast/nodes/MemberExpression.ts
src/ast/nodes/Property.ts
src/ast/nodes/SequenceExpression.ts
src/ast/nodes/TemplateLiteral.ts
src/ast/nodes/ThisExpression.ts
src/ast/nodes/VariableDeclaration.ts
src/ast/nodes/shared/Node.ts
src/ast/nodes/shared/Statement.ts

This reworks #1882 to the release branch. I'll update the system format PR to rebase on top of this now.
//cc @kellyselden hope this helps you there, and sorry we've had to deal with these diffing problems - helps to coordinate this stuff though.

Render options - rework of #1882

---

src/Bundle.ts

This small change will help make #1878 smaller.

extract createGetPath

---

src/rollup/index.ts

This small change will help make #1878 smaller.

extract normalizeOptions

---

src/Module.ts

seems like a good type to join the other descriptions.

extract ImportDescription

---

src/Graph.ts
src/rollup/index.ts

declare preserveSymlinks option as optional

---

src/ast/nodes/MemberExpression.ts
test/form/samples/export-globals/Number.js
test/form/samples/export-globals/_config.js
test/form/samples/export-globals/_expected/amd.js
test/form/samples/export-globals/_expected/cjs.js
test/form/samples/export-globals/_expected/es.js
test/form/samples/export-globals/_expected/iife.js
test/form/samples/export-globals/_expected/umd.js
test/form/samples/export-globals/main.js

If only all bugs were this easy to fix...

Fix for #1735

---

src/ast/nodes/SwitchCase.ts
test/function/samples/switch-cases-are-deconflicted/_config.js
test/function/samples/switch-cases-are-deconflicted/main.js
test/function/samples/switch-cases-are-deconflicted/mod1.js
test/function/samples/switch-cases-are-deconflicted/mod2.js

Deconflict variables in switch cases

---

package-lock.json
package.json

fix(typescript): Upgrade to TypeScript 2.7.2+

---

src/Module.ts

See #1817. Apparently this is a common problem.

Catch errors when following source maps in error reporting

---

src/ast/nodes/MemberExpression.ts
test/form/samples/circular-member-expression/_config.js
test/form/samples/circular-member-expression/_expected/amd.js
test/form/samples/circular-member-expression/_expected/cjs.js
test/form/samples/circular-member-expression/_expected/es.js
test/form/samples/circular-member-expression/_expected/iife.js
test/form/samples/circular-member-expression/_expected/system.js
test/form/samples/circular-member-expression/_expected/umd.js
test/form/samples/circular-member-expression/main.js

discovered from this source https://github.com/emberjs/data

fix circular member expression bug

---

README.md

There were nested `<a>`s for some reason?

Fixed npm link.

---

package-lock.json
package.json
src/ast/nodes/shared/Node.ts

A few minor optimizations:
- Upgraded `sourcemap-codec` to an optimized version (see https://github.com/Rich-Harris/sourcemap-codec/pull/71)
- Improved some hot loops in the Node class.
With this PR, Mapbox GL JS bundle is about 10-12% faster (from 9.5s to 8.5s).

A few performance improvements

---

src/Graph.ts
src/Module.ts

I attempted to see how far these perf gains could get us in the dependency analysis, and it's not very significant, but seems to be about a 20% improvement (90ms to 70ms in my example). It's amazing how variable these numbers can be between runs though - difficult to know how much is just unconscious selection bias :P

Use for loops in analysis

---

src/Graph.ts

While working on a plugin that has workers implemented within the `transform` hook, I noticed there was a consistent drastic slowdown when implementing this parallelization, instead of a speedup.
It turns out, the issue is that the implementation of fetchAllDependencies is a blocking one. With this change, workers in the transform hook now result in faster builds. It will likely also speed up builds in general.

Support parallel dependency fetching

---

src/ExternalModule.ts
src/ast/variables/ExternalVariable.ts
test/function/samples/unused-import/_config.js

Remove warning for tree-shaken external imports being unused (#2112)

---

src/utils/collapseSourcemaps.ts

This fixes the bug posted in #1932

Fix collapseSourceMaps error message

---

src/ast/nodes/ExportDefaultDeclaration.ts
test/form/samples/system-semicolon/_config.js
test/form/samples/system-semicolon/_expected.js
test/form/samples/system-semicolon/main.js

This fixes #2173. The issue was exactly the need to use `appendLeft`.

Fix system default semicolon case

---

src/Chunk.ts
src/ast/scopes/Scope.ts
src/utils/base64.ts
test/form/samples/base64-deshadow/_config.js
test/form/samples/base64-deshadow/_expected.js
test/form/samples/base64-deshadow/dep1.js
test/form/samples/base64-deshadow/dep10.js
test/form/samples/base64-deshadow/dep11.js
test/form/samples/base64-deshadow/dep2.js
test/form/samples/base64-deshadow/dep3.js
test/form/samples/base64-deshadow/dep4.js
test/form/samples/base64-deshadow/dep5.js
test/form/samples/base64-deshadow/dep6.js
test/form/samples/base64-deshadow/dep7.js
test/form/samples/base64-deshadow/dep8.js
test/form/samples/base64-deshadow/dep9.js
test/form/samples/base64-deshadow/main.js

This implements base64 deshadowing indices on names, as discussed in https://github.com/rollup/rollup/issues/2144.

base64 deshadowing indices

---

test/function/samples/adds-semicolons-if-necessary-d/_config.js
test/function/samples/adds-semicolons-if-necessary-d/foo.js
test/function/samples/adds-semicolons-if-necessary-d/main.js
test/function/samples/compact/main.js
test/function/samples/function-use-strict-directive-removed/_config.js

This just adds a functional test for #2110 which has been resolved via #2151 (which is merged to master but unreleased).
It also fixes another test that caused an unhandled promise rejection.

Add test for #2110

---

README.md
package.json

Note directly mentioning "ES6" makes projects look a little more future-relevant at this point.

ES6 Module -> ES module

---

src/rollup/types.d.ts

fix(types): inlineDynamicImports is optional

---

bin/src/run/timings.ts
package-lock.json
package.json
src/rollup/types.d.ts
src/utils/timers.ts
test/function/samples/adds-timings-to-bundle-when-codesplitting/_config.js
test/function/samples/adds-timings-to-bundle/_config.js
typings/declarations.d.ts

Values looks a bit weird, but I think it's something like GC diagram

Add memory perf metric along with time metrics

---

bin/src/run/watch.ts

If yes, please describe the breakage.
Solving the following problem: #1919

feat: skip stdin resuming in watch mode

---

src/Graph.ts
src/watch/index.ts

See https://github.com/rollup/rollup/pull/2441#issuecomment-418723522

preserve change listeners

---

package-lock.json
package.json
test/function/samples/export-default-exported-id/_config.js
test/function/samples/export-default-exported-id/main.js

Update dependencies, resolves #2722

---

docs/05-plugins.md

Docs: Fix return type

---

package-lock.json
package.json

Update all dependencies to fix security issues

---

docs/999-big-list-of-options.md

Docs: Fix syntax error

---

docs/05-plugins.md

The generateBundle hook also receives code and map of each chunk, which should probably be mentioned...

Also mention code and map in the generateBundle hook documentation

---

bin/src/help.md
docs/01-command-line-reference.md
docs/02-javascript-api.md

Just some missing documentation for strictDeprecations

Add missing docs for strictDeprecations

---

src/finalisers/shared/getExportBlock.ts
test/function/samples/avoid-exports-dot-asterisk/_config.js
test/function/samples/avoid-exports-dot-asterisk/main.js

List any relevant issue numbers: #3023 
```js
import * as x from 'x';
export { x as default };
```
Avoid source above generate below thing:
```js
var x = require('x');
module.exports = x.*;
```

Avoid generate .* thing

---

README.md

Update link to JavaScript API documentation

Update link to JavaScript API documentation

---

docs/05-plugin-development.md

fix typo: this.addWatchfile

---

docs/05-plugin-development.md

List any relevant issue numbers: #3404
Removed references to old APIs.

Update resolveFileUrl docs

---

package-lock.json
package.json

The previous fix apparently broke the ESM import due to an ordering issue, so here we go again...

Fix conditional exports again for ESM

---

docs/999-big-list-of-options.md

Fixes some errors in the docs.

Improve manualChunks docs

---

src/ast/ExecutionContext.ts
src/ast/variables/LocalVariable.ts
test/form/samples/include-recursive-call-arguments/_config.js
test/form/samples/include-recursive-call-arguments/_expected.js
test/form/samples/include-recursive-call-arguments/main.js

Resolves #3579 
This will prevent infinite recursions when including call arguments

Do not fail when including call arguments of recursively defined variables

---

docs/999-big-list-of-options.md

Closes #3571
As discussed in #3571, this PR provides more thorough documentation for `output.paths`.

Clarify documentation for `output.paths`

---

docs/01-command-line-reference.md

Convert tab to spaces

---

docs/08-troubleshooting.md

Fixes #3662
List any relevant issue numbers: #3666
This PR adds an additional section in the troubleshooting section of the Rollup documentation for how to work around EMFILE errors on macOS when building large projects with Rollup.

Add troubleshooting section about handling EMFILE errors on macOS

---

src/rollup/types.d.ts

I'm sure this is supposed to be optional.

Make `options` of `PluginContext#parse` optional

---

docs/999-big-list-of-options.md

Document that the default value of --format is 'es'

---

docs/02-javascript-api.md

Fix minor typo on docs/02-javascript-api.md

Fix typo on docs

---

package.json
src/Module.ts

Apparently people are using the REPL to actually debug Rollup issues. Which is a good thing, therefore this is including specifically the source map of the browser bundle in the package.
Also it removes a left-over log statement.

Add browser sourcemap

---

.github/workflows/repl-artefacts.yml

Unfortunately due to the use of the `pull_request_target`, the REPL artefact for pull requests was built from the target branch and not from the PR branch. Hopefully this fixes it.

Fix REPL artefact branch reference

---

src/utils/collapseSourcemaps.ts

Use Map to optimize performance of traceMappings.
Before: 
After:

perf: User Map to optimize performance

---

.github/PULL_REQUEST_TEMPLATE.md

This will add a comment to the PR template prompting collaborators to list resolved issues as `resolves #<issue number>` so that Github can auto-close the issues when the PR is merged.

Add clarifying note to PR template

---

src/utils/renderHelpers.ts

Fix typo in renderHelpers.ts

---

docs/999-big-list-of-options.md

Fix typo in docs

---

test/watch/index.js

This is a follow-up to the previous PR that was merged to find solutions for the remaining issues. This time I repeat flaky tests in loops.

Further stabilize watch tests

---

src/utils/pureComments.ts

fix: remove acorn-walk patch

---

docs/05-plugin-development.md

Fix a typo in 'Direct plugin communication' documentation code example

---

.github/workflows/repl-artefacts.yml
.github/workflows/tests.yml

ci: bump github actions

---

package-lock.json

chore: bump resolve from 1.22.0 to 1.22.1

---

src/Chunk.ts
test/chunking-form/samples/preserve-modules-root/_config.js

resolve currentPath

---

package-lock.json

sync package-lock version with package verision
package version 3.2.3

sync package-lock version with package verision

---

docs/configuration-options/index.md

docs: Fix typo

---

README.md

Fixed the logo link of the README.md file.

fixed the logo link

---

docs/configuration-options/index.md
docs/plugin-development/index.md

docs: fix style

---

src/Graph.ts

no
Avoid duplication of getting all entry modules, It feels more efficient than before.

simplify code in includeStatements

---

docs/configuration-options/index.md

I found that this table's formatting is not the same as others'.

docs: fix table at `output.sanitizeFileName` section

---

docs/repl/components/BundleOptions.vue
docs/repl/components/InputHeader.vue
docs/repl/components/OutputStatus.vue
docs/repl/components/ReplInput.vue
docs/repl/components/ReplMain.vue
docs/repl/components/ReplModule.vue
docs/repl/components/SelectOption.vue
docs/repl/components/StatusMessage.vue

In a previous PR, we made all REPL styles scope. The styles in question, however, were global on purpose, which I completely overlooked. This fixes it but makes them more specific to avoid conflicts.

Reinstate global styles

---

docs/repl/stores/options.ts
docs/repl/stores/rollupOutput.ts

This will log the JSON output of Rollup to the browser console in the REPL for convenience and debugging purposes.

Log REPL output to console

---

.github/workflows/clean-cache.yml
.github/workflows/repl-artefacts.yml
.github/workflows/tests.yml

Add node_modules caching to workflows

Better workflow caching

---

docs/plugin-development/index.md

Fix typo in index.md

---

src/utils/transform.ts
test/cli/samples/watch/bundle-error/main.js
test/function/samples/plugin-error-transform-pos/_config.js
test/function/samples/plugin-error-transform-pos/main.js

resolves #5044
resolves https://github.com/vitejs/vite/issues/13571
The original source was passed to `augmentCodeLocation` instead of the current source.

Fix `this.error` with `pos` in `transform` hook

---

docs/repl/stores/rollup.ts

Docs: load full path of rollup.browser.js for Rollup V4

---

.github/workflows/repl-artefacts.yml

re-enbale repl-artefacts workflow for rollup-swc branch

---

src/utils/convert-ast.ts
tsconfig.json

[v4.0] Imporve the performance of generating ast and rollup ast nodes

---

docs/repl/components/ReplModule.vue
docs/repl/helpers/editor.ts

After changes
But these changes also slightly affected the dark mode.

docs: improve the docs repl appearance in the light mode

---

src/ModuleLoader.ts
test/browser/samples/missing-dependency-resolution/_config.js
test/function/samples/external-conflict/_config.js
test/function/samples/load-module-error/load/_config.js
test/function/samples/load-returns-string-or-null/_config.js
test/function/samples/max-parallel-file-operations/error/_config.js
test/function/samples/plugin-error/load/_config.js

[v4.0] feat: Do not watch files anymore if their content is returned by the load hook

---

src/Module.ts
test/function/samples/strip-bom/_config.js
test/function/samples/strip-bom/main.js

[v4.0] fix: also strip BOM from code strings in JS

---

rust/bindings_napi/src/lib.rs
rust/bindings_wasm/src/lib.rs

Removed unnecessary `to_vec` & `single_component_path_imports`

Resolve clippy errors

---

docs/migration/index.md

Improve wording for native artifacts in migration guide

---

test/types.d.ts

test: add verifyAst type

---

docs/.vitepress/config.ts
docs/repl/components/ReplEditor.vue

Also fix a type issue
The syntax error highlighting in the REPL has been broken for some time due to a path issue, which is fixed here.

Fix error highlight in REPL

---

package-lock.json
package.json

As the license plugin now allows rollup@4 as peer dependency, we can switch back to the npm version.

Update license plugin

---

.github/workflows/build-and-tests.yml
rust/rust-toolchain.toml

build: ensure rust toolchain components for linting are installed

---

.github/workflows/build-and-tests.yml
.github/workflows/repl-artefacts.yml
rust/rust-toolchain.toml

There was an issue in a recent pipeline run that is hopefully fixed by this

Revert specifying rustfmt and clippy in toolchain file as it breaks REPL build

---

package-lock.json
package.json
tsconfig.json
typings/hash.js.d.ts
wasm.d.ts

chore: remove unused files and deps

---

.github/workflows/build-and-tests.yml
.github/workflows/repl-artefacts.yml
native.js

- See also #5254 
This will ensure we show a proper error when running on an armv7 Linux system that needs musl instead of a technical error. This will also point users to using the WASM build.

Error for armv7 musl build

---

.github/workflows/build-and-tests.yml
native.js
npm/linux-riscv64-gnu/README.md
npm/linux-riscv64-gnu/package.json
package-lock.json
package.json

Bump napi-rs/cli to 2.17, which is necessary for riscv64 support.
Add support for riscv64 linux gnu target.
I would very much appreciate it if a new release with riscv64 support could be published after we get this PR merged :)

Add support for linux riscv64 gnu

---

README.md

chode: add node badge

---

docs/configuration-options/index.md

docs: fix grammar

---

test/types.d.ts
tsconfig.json

Resolve all rollup imports to node_modules to avoid type conflict

---

src/ast/nodes/AssignmentExpression.ts
src/utils/logs.ts
test/function/samples/error-const-reassign/_config.js
test/function/samples/error-const-reassign/main.js

The related REPL: https://rollupjs.org/repl/?version=4.10.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwZm9vJTIwJTNEMSUzQiU1Q25mb28lMjAlM0QlMjAyJTNCJTVDbmNvbnNvbGUubG9nKGZvbyklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSUyQyUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMm91dHB1dCUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTdEJTJDJTIydHJlZXNoYWtlJTIyJTNBdHJ1ZSU3RCU3RA==

Add const reassign rule

---

scripts/generate-buffer-to-ast.js
src/ast/nodes/PanicError.ts
src/ast/nodes/ParseError.ts
src/utils/bufferToAst.ts
src/utils/logs.ts

Rename `getRollupEror` to `getRollupError`

---

build-plugins/replace-browser-modules.ts
src/ast/nodes/ArrayPattern.ts

chore: fix typo

---

.github/workflows/build-and-tests.yml
native.js
npm/linux-s390x-gnu/README.md
npm/linux-s390x-gnu/package.json
package.json

Add support for s390x linux gnu target.
I would very much appreciate it if a new release with s390x support could be published after we get this PR merged :)

Add support for linux s390x gnu

---

native.js

When a user is running an unsupported MUSL Linux machine, the error message can be misleading as it states that the platform is unsupported while only the MUSL flavor may be unsupported.
This improves the error message by adding ` (musl)` next to the platform in those situations in the error message, so that it matches the format of supported architectures in the list below, e.g.
```
Error: Your current platform "linux (musl)" and architecture "arm" combination is not yet supported by the native Rollup build. Please use the WASM build "@rollup/wasm-node" instead.
The following platform-architecture combinations are supported:
android-arm
android-arm64
darwin-arm64
darwin-x64
linux-arm
linux-arm64 …
```

Improve error message when running on unsupported MUSL Linux

---

npm/linux-arm-gnueabihf/package.json
npm/linux-arm-musleabihf/package.json

Without `libc` field, both packages will be downloaded by the package manager.

Add libc field to armv7 packages

---

src/ast/nodes/shared/FunctionBase.ts
test/function/samples/rest-element-argument/_config.js
test/function/samples/rest-element-argument/main.js

- resolves #5502
Deoptimize function parameters values when there is a `RestElement` in function arguments.

fix: rest element should deoptimize parameter values

---

ARCHITECTURE.md

Fix typos in ARCHITECTURE.md

---

src/ast/nodes/shared/ObjectEntity.ts

refactor(ast): conditional branch

---

docs/configuration-options/index.md
docs/plugin-development/index.md

This resolves some inconsistencies in the type information in the docs and specifies the intermediate stages for chunks and assets more explicitly. It also makes sure to align the type names with the type names in the actual TypeScript types.

Improve chunk and asset type information in docs

---

docs/repl/stores/rollup.ts

preload the WASM file even though the version is undefined.

---

src/ast/nodes/shared/knownGlobals.ts

List any relevant issue numbers: 
- resolves #5387 
Add `AggregateError`, `FinalizationRegistry`, `WeakRef` to knownGlobals.

feat: add `AggregateError`, `FinalizationRegistry`, `WeakRef` to knownGlobals

---

.github/workflows/performance-report.yml

This PR fixes a typo in the CI configuration file.
Fixing the typo ensures that the CI pipeline runs correctly without errors.

fix: type in CI file

---

src/Graph.ts
src/Module.ts
src/ast/nodes/Identifier.ts
src/utils/renderChunks.ts
test/function/samples/tree-shake-module-side-effects-update/_config.js
test/misc/misc.js

It appears that this might cause some build failures that need further investigation.
- reopens #5408 
- reopens #5650 
Apparently, the previous change caused bigger issues that need investigation.

Partially revert #5658 and re-apply #5644

---

browser/package.json
package-lock.json
package.json
src/Bundle.ts
src/Chunk.ts
src/Graph.ts
src/Module.ts
src/ast/nodes/Identifier.ts
test/function/samples/tree-shake-module-side-effects-dependencies/_config.js
test/function/samples/tree-shake-module-side-effects-dependencies/dep.js
test/function/samples/tree-shake-module-side-effects-dependencies/effect.js
test/function/samples/tree-shake-module-side-effects-dependencies/main.js
test/function/samples/tree-shake-module-side-effects-dependencies/shared.js
test/function/samples/tree-shake-module-side-effects-update/_config.js

I think this is the bug of the original implementation, I missed impure dependencies of pure modules...

Ensure impure dependencies of pure modules are added

---

rust/Cargo.lock
rust/parse_ast/Cargo.toml
test/function/samples/unicode-string/_config.js
test/function/samples/unicode-string/main.js

- resolves #5672
- resolves https://github.com/vitejs/vite/issues/18179
This PR reverts updates of unicode related rust packages.
It seems after updating them, swc panics at this line with `width 3 given for non-narrow character`.
https://github.com/swc-project/swc/blob/14cfd70ee00938497ce6b59f68332f9daa17378b/crates/swc_common/src/syntax_pos.rs#L702

Fix panic with unicode characters

---

src/ast/nodes/shared/knownGlobals.ts
src/ast/utils/identifyNode.ts
test/function/samples/tree-shaking-proxy-2/_config.js
test/function/samples/tree-shaking-proxy-2/main.js
test/function/samples/tree-shaking-proxy/_config.js
test/function/samples/tree-shaking-proxy/main.js

resolved #5709 
For fixing the circular dependency issues, I added `src/ast/utils/identifyNode.ts` file. I think we need to sort out the dependencies of some of the current ast files later, especially where `instanceof` is called.

fix: Deoptimize the proxied object if its property is reassigned in the handler functions

---

browser/package.json
package-lock.json
package.json
src/ast/nodes/MemberExpression.ts
src/ast/nodes/SpreadElement.ts
src/ast/nodes/shared/ObjectEntity.ts
src/ast/utils/limitPathLength.ts
src/ast/variables/LocalVariable.ts
src/ast/variables/ParameterVariable.ts
test/form/samples/deep-properties-access/_expected.js
test/form/samples/deep-properties/_expected.js
test/form/samples/recursive-destructuring/_config.js
test/form/samples/recursive-destructuring/_expected.js
test/form/samples/recursive-destructuring/main.js
test/form/samples/recursive-property-access/_config.js
test/form/samples/recursive-property-access/_expected.js
test/form/samples/recursive-property-access/main.js

Some attempts to debug an issue reported here https://github.com/rollup/rollup/pull/5420#issuecomment-2478690184

Debug out-of-memory issues with Rollup v4.27.0

---

.github/workflows/build-and-tests.yml
native.js
npm/linux-loongarch64-gnu/README.md
npm/linux-loongarch64-gnu/package.json
package.json
rust/bindings_napi/Cargo.toml
rust/bindings_napi/src/lib.rs

This PR adds support for LoongArch, a RISC-style ISA developed by Loongson.
Note: I am using build image from https://github.com/darkyzhou/napi-rs-nodejs-rust, which is based on unreleased Debian Trixie because the ecosystem of LoongArch is quite immature now.

feat: add support for LoongArch

---

docs/command-line-interface/index.md

docs: add utf-8 encoding to JSON file reading

---

src/ast/nodes/LogicalExpression.ts
src/ast/nodes/shared/BitFlags.ts
test/function/samples/treeshake-logical-expression/_config.js
test/function/samples/treeshake-logical-expression/main.js

resloves #5770 
Thanks, @lukastaegert, for providing a valid test case 😊. I’ve been struggling to find one for such a long time.

fix: do not optimize the literal value if the cache is deoptimized

---

.github/workflows/build-and-tests.yml
.github/workflows/performance-report.yml
.github/workflows/repl-artefacts.yml

As we are constantly running over the limits of our available cache storage, the goal is to only save caches from master and read them on branches/tags, and also to align cache keys between different jobs.

Improve caching on CI

---

docs/configuration-options/index.md
src/Chunk.ts
src/ExternalChunk.ts
test/form/samples/import-attributes/keep-dynamic-assertions/_expected/cjs.js
test/form/samples/import-attributes/keep-dynamic-attributes/_expected/cjs.js

fix: keep import attributes for cjs format

---

src/ast/nodes/SwitchCase.ts
src/ast/nodes/UnaryExpression.ts
test/form/samples/switch-cases/missing-space/_config.js
test/form/samples/switch-cases/missing-space/_expected.js
test/form/samples/switch-cases/missing-space/main.js
test/form/samples/treeshake-unary/_expected.js
test/form/samples/treeshake-unary/main.js

- resolves #5784 
- resolves #5785 
related #5775

fix: consider that literals cannot following switch case.

---

src/ModuleLoader.ts
src/utils/stripBom.ts
test/function/samples/strip-bom-2/_config.js
test/function/samples/strip-bom-2/main.js

fix: strip all BOMs

---

src/ast/nodes/LogicalExpression.ts
test/function/samples/logical-expressions-literal-value/_config.js
test/function/samples/logical-expressions-literal-value/main.js

Return UnknownValue if getLiteralValueAtPath is called recursively within logical expressions

---

docs/configuration-options/index.md

Required to add default chunking

return null

---

src/ast/nodes/ObjectPattern.ts
test/form/samples/object-expression-treeshaking/remove-props-via-destructuring/main.js
test/function/samples/object-tree-shaking-with-rest-element-destructed/_config.js
test/function/samples/object-tree-shaking-with-rest-element-destructed/main.js

include all properties if a rest element is destructed

---

src/ast/nodes/UnaryExpression.ts
test/chunking-form/samples/missing-export-reused-deconflicting/_expected/amd/dep2.js
test/chunking-form/samples/missing-export-reused-deconflicting/_expected/cjs/dep2.js
test/chunking-form/samples/missing-export-reused-deconflicting/_expected/es/dep2.js
test/chunking-form/samples/missing-export-reused-deconflicting/_expected/system/dep2.js
test/form/samples/nested-member-access/_expected.js
test/form/samples/supports-es5-shim/_expected.js
test/form/samples/supports-es6-shim/_expected.js
test/form/samples/treeshake-unary/_expected.js

related #5775
Replace `undefined` with `void 0` in unary expressions using the void operator. This way, we can preserve the original shape of the source code, because some people prefer using `void 0` instead of `undefined` in their code.

replace undefined with void 0 for operator void

---

src/ast/nodes/LogicalExpression.ts
test/form/samples/logical-expression-with-property-access/_config.js
test/form/samples/logical-expression-with-property-access/_expected.js
test/form/samples/logical-expression-with-property-access/main.js

return UnknownValue if the usedbranch is unkown and the path is not empty

---

native.wasm.js

resolves #5865 
That’s an oversight; we forgot to modify the `native.wasm.js` file while supporting the JSX.

Add jsx parameter to parseAsync in native.wasm.js

---

src/rollup/types.d.ts

Export types that used from [Vite](https://cdn.jsdelivr.net/npm/vite/dist/node/index.d.ts)
```ts
import { PluginHooks, RollupError, SourceMap, ModuleInfo, PartialResolvedId, RollupOptions, InputOption, ModuleFormat, WatcherOptions, RollupOutput, RollupWatcher, InputOptions, CustomPluginOptions, LoadResult, SourceDescription, PluginContextMeta, RollupLog, OutputBundle, OutputChunk, ObjectHook, ResolveIdResult, ExistingRawSourceMap, SourceMapInput, GetManualChunk } from 'rollup';
```

fix: export types

---

.github/workflows/build-and-tests.yml
.github/workflows/clean-cache.yml
.github/workflows/performance-report.yml
.github/workflows/repl-artefacts.yml
renovate.json

Specified commit hash for GHA third-party action  
The version specification may cause vulnerable code to be included at unintended times.

Pin digest of 3rd party actions

---

.github/workflows/build-and-tests.yml
native.js
npm/linux-riscv64-musl/README.md
npm/linux-riscv64-musl/package.json
package-lock.json
package.json

Supports linux riscv on musl systems like Alpine Linux.

Add support for linux riscv64 musl

---

src/rollup/types.d.ts

This should be optional for consistency with other hook filters.

fix: resolveId id filter is optional

---

src/watch/watch-proxy.ts
test/cli/samples/watch/watch-output-contain-input/_config.js
test/cli/samples/watch/watch-output-contain-input/main.js
test/cli/samples/watch/watch-output-contain-input/rollup.config.mjs
test/watch/index.js

fix: watch mode input should not be an output subpath

---

package-lock.json
package.json
renovate.json
rust/Cargo.lock
rust/bindings_wasm/Cargo.toml
src/ast/nodes/ImportExpression.ts
src/ast/nodes/MemberExpression.ts
src/ast/nodes/shared/Expression.ts
src/ast/utils/identifyNode.ts
src/ast/variables/LocalVariable.ts
test/form/samples/treeshake-deterministic-dynamic-import/_expected.js
test/form/samples/treeshake-deterministic-dynamic-import/main.js

This PR slightly improves tree-shaking for dynamic imports. For direct calls like `module.foo()`, it's no longer necessary to consider including all properties of `this`. It also improves the object tree-shaking for parameters in `then` callbacks.

enhance tree-shaking for dynamic imports

---

package-lock.json

This updates mermaid in the lock file to fix a transitive dev dependency vulnerability.

Update transitive dependency to fix audit

---

cli/run/loadConfigFile.ts
test/cli/samples/config-file-bundle-with-extensionless-importee/_config.js
test/cli/samples/config-file-bundle-with-extensionless-importee/_expected.js
test/cli/samples/config-file-bundle-with-extensionless-importee/input.js
test/cli/samples/config-file-bundle-with-extensionless-importee/rollup.base.config.mjs
test/cli/samples/config-file-bundle-with-extensionless-importee/rollup.config.mjs

Return null to defer to the default resolution behavior

---

src/ast/nodes/ArrayPattern.ts
test/form/samples/tree-shake-un-included-elements-in-array-pattern/_config.js
test/form/samples/tree-shake-un-included-elements-in-array-pattern/_expected.js
test/form/samples/tree-shake-un-included-elements-in-array-pattern/main.js
test/form/samples/tree-shake-un-included-elements-in-array-pattern/module1.js
test/form/samples/tree-shake-un-included-elements-in-array-pattern/module2.js
test/form/samples/tree-shake-un-included-elements-in-array-pattern/module3.js

Tree-shake un-included elements in array pattern

---

src/ast/nodes/LogicalExpression.ts
test/function/samples/nullish-coalescing-operator-tree-shaking/_config.js
test/function/samples/nullish-coalescing-operator-tree-shaking/main.js

Correct nullish coalescing branch resolution for symbol left value
