.github/ISSUE_TEMPLATE/BUG.md
This will adjust the BUG issue template in two ways:
- It mentions the REPL.it template used by the plugins repo as it is also valuable for Rollup core as it allows all options to be used
- It requires a "reproduction link" as I believe ALL reproductions should be possible to be provided as some link. Would like to experiment how users react to that and if it improves provided reproductions.
Opinions?
=> Adjust bug template to mention REPL.it

src/watch/index.ts, test/watch/index.js
Resolves #3386 
Resolves rollup/plugins#186
This is a very simple fix that will make sure that after changing an errored file back to its previous state in watch mode, transform hooks will run again on this file. The diagnostics of @rollup/plugin-typescript depends on this and it is really a sensible approach IMO. This fix is solely in `rollup.watch` and works by checking if a thrown error has an id property. This id is then removed from the cache before the next run.
=> Run transform hooks again in watch mode on files that errored

LICENSE.md, cli/run/build.ts, docs/02-javascript-api.md, docs/05-plugin-development.md, package-lock.json, package.json, scripts/test-package.js, src/Graph.ts, src/Module.ts, src/ModuleLoader.ts, src/rollup/rollup.ts, src/rollup/types.d.ts, src/utils/PluginContext.ts, src/utils/fs.ts, src/utils/pureComments.ts, src/utils/transform.ts, test/typescript/tsconfig.json
Resolves #3108, #2142
I hope this is the last change that is going into 2.0.0.
One problem that was reported repeatedly is that Rollup's dependency on `@types/node` was causing issues for users that were not targeting Node but had conflicting types such as AMD or browser types. Moreover it was not clear why non-TypeScript-users would need to have external type dependencies.
One suggestion was to make the types a peerDependency but in our opinion this would have caused unnecessary friction for TypeScript users. This PR finally fixes this by getting rid of the @types dependencies the following way:
- The only Node type we needed for our external interface was `Buffer`. A Node `Buffer` however is a …
=> [v2.0.0] Remove @types dependencies

docs/05-plugin-development.md
Resolves #3409
This will
- split up the hooks in the documentation into build phase and output generation phase hooks
- mention in the beginnings of these sections which are the first and last hooks of each phase
- add to each hook which hooks precede and follow it
This is still WIP. The build phase is already done, I hope to finish the output generation phase until tomorrow. Feedback already welcome.
=> Structure lifecycle hooks, add links to build time hooks

src/Module.ts, test/function/samples/circular-missed-reexports-2/_config.js, test/function/samples/default-not-reexported/_config.js, test/function/samples/error-after-transform-should-throw-correct-location/_config.js, test/function/samples/import-of-unexported-fails/_config.js, test/function/samples/reexport-missing-error/_config.js
Resolves #3400
This PR refactors the error message printed by `Module.handleMissingExport`, so it now contains the importing module.
Prior to this change, we only printed the imported module that failed, with no context on which module was attempting the import. In some cases, the error could occur due to an invalid import within the importing module, so this info may needed to remedy the problem. This could be difficult to debug in large codebases, especially when importing commonly-used modules.
=> Missing exports errors now print the importing module

src/ast/nodes/IfStatement.ts, test/function/samples/if-statement-insert-whitespace/_config.js, test/function/samples/if-statement-insert-whitespace/main.js
Resolves #3419
This ensures that in a situation such as #3419, there is always whitespace or a similar separator between the "else" keyword and the following branch so that the expression can be transformed freely. This is a similar fix as was previously implemented for for..in and for..of statements.
=> Avoid invalid code when "else" branch is simplified

LICENSE.md, scripts/post-comment.js, src/finalisers/umd.ts, test/function/samples/error-missing-umd-name/_config.js
refs #3372 
In above PR, I was suggested to tweak error code for UMD bundle.
Because this patch will be breaking change for people already using this code in plugins, I create PR based on `release-2.0.0` .
=> more explained error code for name-less umd bundle 

docs/05-plugin-development.md
From reading the docs, it wasn't clear to me how the value returned from `augmentChunkHash` would be used. I added a link to `hash.update` so plugin authors could refer to the node docs for valid types. I also modified the example so it was returning a valid type.
=> Detail how return values from `augmentChunkHash` are used

docs/05-plugin-development.md, src/rollup/types.d.ts, src/utils/transform.ts
=> Add missing type declaration for getCombinedSourcemap

src/ast/nodes/MetaProperty.ts, src/rollup/rollup.ts, src/rollup/types.d.ts, src/utils/PluginDriver.ts, src/utils/renderChunk.ts, src/utils/transform.ts
Adds strict typing for the PluginDriver class.
=> Use strict types with PluginDriver

src/ast/nodes/LogicalExpression.ts, test/function/samples/reassigned-return-expression/_config.js, test/function/samples/reassigned-return-expression/main.js
Resolves #3382 
There is a bug in logical expressions in that it would only check one of the arguments for side-effects if the value can be resolved at some point. However, checking for side-effects has the "side-effect" of binding new assignments, which in the linked issue was necessary to trigger some deoptimizations. The fix here is rather small even though tracking it was quite intricate.
=> Make sure logical expressions always check the left argument for side effects

src/Chunk.ts, src/utils/collapseSourcemaps.ts, test/cli/samples/config-multiple-source-maps/_config.js, test/cli/samples/config-multiple-source-maps/_expected/main-cjs.js, test/cli/samples/config-multiple-source-maps/_expected/main-cjs.js.map, test/cli/samples/config-multiple-source-maps/_expected/main-es.js, test/cli/samples/config-multiple-source-maps/_expected/main-es.js.map, test/cli/samples/config-multiple-source-maps/main.js, test/cli/samples/config-multiple-source-maps/rollup.config.js
Resolves #3439
The issue was that Rollup mutates the generated chunk objects when writing multiple outputs, overwriting the chunk ids in the process. When using a config file, writing multiple outputs is interleaved. As the sourcemapfile is using the chunk id and is generated at the end, an overwritten chunk id is used. This is fixed for now by storing the chunk id in a local variable.
=> Use correct file names when writing sourcemaps for multiple outputs using the "dir" option

docs/05-plugin-development.md
None
In contrary to the documentation, the `writeBundle` hook for plugins is apparently called with two arguments, the first being the `OutputOptions` and the second the bundle.
=> Correctly specify type of writeBundle hook in docs

src/rollup/types.d.ts
The `rollup.watch` API accepts a single config object or an array of config objects. This is correct everywhere else ([one](https://github.com/rollup/rollup/blob/master/src/watch/watch-proxy.ts#L17), [two](https://github.com/rollup/rollup/blob/master/src/watch/watch.ts#L27), and [three](https://rollupjs.org/guide/en/#watchoptions)) except the shipped types.
=> fix(types): watch accepts single or array config

docs/04-tutorial.md
Fixes the SystemJS URL in the tutorial which is currently incorrect.
=> fixup SystemJS url

docs/04-tutorial.md, docs/05-plugin-development.md
Part of the edits expected in #3381
=> Don't Use esm Output Format (Alias)

cli/run/loadConfigFile.ts, test/cli/index.js, test/cli/samples/config-async-function/_config.js, test/cli/samples/config-async-function/_expected.js, test/cli/samples/config-async-function/main.js, test/cli/samples/config-async-function/rollup.config.js
Resolves #3470 
Don't know how this could slip past the radar. We had tests for configs as Promises and configs as functions, but functions that return promises...
Now async functions are supported again.
=> Fix support for async functions as config

.prettierrc, src/ast/nodes/CallExpression.ts, src/ast/nodes/TaggedTemplateExpression.ts, test/function/samples/cannot-call-external-namespace/_config.js, test/function/samples/cannot-call-external-namespace/main.js, test/function/samples/cannot-call-internal-namespace/_config.js, test/function/samples/cannot-call-internal-namespace/main.js
This converts the error when a namespace is called into a warning.
The reason being that there may exist valid runtime paths through the code that do not trigger the error, despite it being invalid. So allowing the build to proceed can allow valid runtime code to work despite the underlying "typing issue".
Alternatively it might be worth considering a strict / loose mode for Rollup "typing errors" so far as it cares about module semantics, but I actually think it would be better to treat Rollup as allowing anything to execute which would execute in a JS engine, since it is not a type system.
Landing as-is seems sensible to me, but I would be open to suggestions too.
=> feat: Call namespace error as a warning

.prettierrc, src/Module.ts, src/rollup/types.d.ts, src/utils/transform.ts, test/misc/misc.js, test/sourcemaps/samples/existing-external-sourcemaps-combined/_config.js, test/sourcemaps/samples/existing-external-sourcemaps-combined/main.js, test/sourcemaps/samples/existing-external-sourcemaps-combined/main.js.map, test/sourcemaps/samples/existing-external-sourcemaps-combined/other.js, test/sourcemaps/samples/existing-external-sourcemaps-combined/other.js.map, test/sourcemaps/samples/existing-inline-sourcemaps-combined/_config.js, test/sourcemaps/samples/existing-inline-sourcemaps-combined/main.js, test/sourcemaps/samples/existing-inline-sourcemaps-combined/other.js
Resolves #3465 
Comments are not part of the cache, which had the effect that sourcemap comments were no longer removed when rebuilding using cached modules. This fixes this by adding the location of sourcemap comments to the cache (I decided against adding all comments to avoid blowing up the cache unnecessarily).
=> Store locations for removed comments in cache

src/Chunk.ts, src/Module.ts, src/ast/nodes/BreakStatement.ts, src/ast/nodes/ContinueStatement.ts, src/ast/nodes/ExportDefaultDeclaration.ts, src/ast/nodes/Identifier.ts, src/ast/nodes/LabeledStatement.ts, src/ast/nodes/MemberExpression.ts, src/ast/nodes/shared/FunctionNode.ts, src/ast/variables/LocalVariable.ts, src/ast/variables/NamespaceVariable.ts, src/ast/variables/SyntheticNamedExportVariable.ts, src/ast/variables/Variable.ts, test/form/samples/no-treeshake-include-labels/_config.js, test/form/samples/no-treeshake-include-labels/_expected.js, test/form/samples/no-treeshake-include-labels/dep1.js, test/form/samples/no-treeshake-include-labels/dep2.js, test/form/samples/no-treeshake-include-labels/main.js
Resolves #3473
This PR makes sure
- labels are always included when not tree-shaking
- Rollup uses a fresh inclusion context when including the declaration of a variable. This alone was the culprit of #3473 and fixes it, but I thought I add the first point for completeness.
=> Make sure labels are always included when not tree-shaking

cli/run/watch.ts, test/cli/samples/watch/close-stdin/_config.js, test/cli/samples/watch/close-stdin/_expected/out.js, test/cli/samples/watch/close-stdin/main.js, test/cli/samples/watch/close-stdin/wrapper.js
This PR ensures that the `rollup --watch` process exits correctly when stdin is closed by the parent process.
This is necessary when rollup is used as the front end for an Elixir Phoenix application. In dev mode, the phoenix watchers run the rollup command as a child process and the underlying erlang port mechanism assumes that the child process closes when the parent stdin is closed. Without this fix the old zombie processes never close and accumulate as you stop and start in development mode.
This was discussed and fixed in 2017 in the original rollup-watcher repository:
* https://github.com/rollup/rollup-watch/issues/30#issuecomment-316468552
* https://github.com/rollup/rollup-watch/pull/57/files …
=> Ensure --watch mode exits correctly when stdin is closed.

src/Chunk.ts, test/form/samples/paths-function/_expected/amd.js, test/form/samples/paths-function/_expected/cjs.js, test/form/samples/paths-function/_expected/es.js, test/form/samples/paths-function/_expected/iife.js, test/form/samples/paths-function/_expected/system.js, test/form/samples/paths-function/_expected/umd.js, test/form/samples/paths-function/main.js
Resolves #3464 
This will make sure that both static and dynamic imports will respect the `paths` option.
=> Respect output.paths in dynamic imports

src/Chunk.ts, test/chunking-form/samples/circular-manual-chunks/_config.js, test/chunking-form/samples/circular-manual-chunks/_expected/amd/generated-lib1.js, test/chunking-form/samples/circular-manual-chunks/_expected/amd/generated-lib2.js, test/chunking-form/samples/circular-manual-chunks/_expected/amd/main.js, test/chunking-form/samples/circular-manual-chunks/_expected/cjs/generated-lib1.js, test/chunking-form/samples/circular-manual-chunks/_expected/cjs/generated-lib2.js, test/chunking-form/samples/circular-manual-chunks/_expected/cjs/main.js, test/chunking-form/samples/circular-manual-chunks/_expected/es/generated-lib1.js, test/chunking-form/samples/circular-manual-chunks/_expected/es/generated-lib2.js, test/chunking-form/samples/circular-manual-chunks/_expected/es/main.js, test/chunking-form/samples/circular-manual-chunks/_expected/system/generated-lib1.js, test/chunking-form/samples/circular-manual-chunks/_expected/system/generated-lib2.js, test/chunking-form/samples/circular-manual-chunks/_expected/system/main.js, test/chunking-form/samples/circular-manual-chunks/lib1.js, test/chunking-form/samples/circular-manual-chunks/lib2.js, test/chunking-form/samples/circular-manual-chunks/main.js
Resolves #3499 
There was a missing break-off condition that lead to an infinite recursion when there was a circular dependency between manual chunks.
=> Do not fail for circular imports between manual chunks

src/ast/ExecutionContext.ts, src/ast/nodes/CallExpression.ts, src/ast/nodes/Property.ts, src/ast/utils/PathTracker.ts, src/ast/variables/LocalVariable.ts, test/cli/samples/watch/watch-config-error/_config.js, test/function/samples/nested-foreach/_config.js, test/function/samples/nested-foreach/main.js
…tracked side-effects in nested calls
Resolves #3533
See #3533. In this situation, the tracking logic that is meant to prevent infinite recursions in Rollup's side-effect detection would fire for the inner `.forEach` call expression because it thought this call had already been tracked as it was the same variable and path of the outer `.forEach` call. Of course this is not the case, so for call expressions, the recursion prevention logic will now also discriminate based on original call expression and not only variable.
=> Improve side-effect tracking for call arguments

cli/run/commandPlugins.ts, test/cli/samples/plugin/default-export/_config.js, test/cli/samples/plugin/default-export/_expected.js, test/cli/samples/plugin/default-export/my-plugin.js
List any relevant issue numbers: https://github.com/rollup/plugins/issues/360
Adds support for `exports.default` when including a plugin on the CLI
=> Use default named export with plugins

src/ast/nodes/ObjectExpression.ts, test/function/samples/simplify-arrow-expression-with-object/_config.js, test/function/samples/simplify-arrow-expression-with-object/main.js
Resolves #3530 
This makes sure that object expressions are not mis-interpreted as block statements when the body of an arrow function expression is simplified
=> Wrap object expressions in parentheses if they become children of an arrow function expression

src/ast/variables/ExportDefaultVariable.ts, test/form/samples/undefined-default-export/_config.js, test/form/samples/undefined-default-export/_expected.js, test/form/samples/undefined-default-export/dep.js, test/form/samples/undefined-default-export/main.js
Resolves #3557 
This will make sure that the default export simplification logic does not kick in when `undefined` is exported, leading to a crash.
=> Properly handle default exporting "undefined"

src/ast/nodes/shared/MultiExpression.ts, test/function/samples/chained-mutable-array-methods/_config.js, test/function/samples/chained-mutable-array-methods/main.js
Resolves #3555
Apparently when using a return value of a function that contained conditional expressions and builtin methods, later mutations of that return value would not be tracked properly. This is fixed here. See the examples at #3555.
=> Make sure UnknownFooExpressions are included when referenced as return values in a MultiExpression

src/Chunk.ts, test/function/samples/invalid-transform-source-function/_config.js, test/function/samples/invalid-transform-source-function/main.js
I tried writing a test for this but couldn't manage to find test cases which overs actual errors (and I also couldn't find any documentation of how tests are set up in this project, sorry If I missed something).
What I tried:
```js
module.exports = {
description: 'throw descriptive error if sourcemapPathTransform-function does not return a string (#3484)',
options: {
output: {
name: 'myModule',
file: path.resolve(__dirname, '_actual/bundle.js'),
sourcemapPathTransform: () => {}
}
},
error: () => true,
stderr: (stderr) =>
assertStderrIncludes(
stderr,
'[!] Error: sourcemapPathTransform function must return a string.'
),
}
```
but `error` does not seem to be part of the sourcemaps test suites 😕
#3484 …
=> Throw error if sourcemapPathTransform-option does not return a string (#3484)

src/Chunk.ts, src/Module.ts, src/ast/variables/ExportDefaultVariable.ts, test/cli/samples/watch/watch-config-early-update/_config.js, test/form/samples/side-effect-default-reexport/_config.js, test/form/samples/side-effect-default-reexport/_expected.js, test/form/samples/side-effect-default-reexport/default-export/index.js, test/form/samples/side-effect-default-reexport/default-export/index2.js, test/form/samples/side-effect-default-reexport/default-export/item.js, test/form/samples/side-effect-default-reexport/default-export/menu.js, test/form/samples/side-effect-default-reexport/default-export2/index.js, test/form/samples/side-effect-default-reexport/default-export2/index2.js, test/form/samples/side-effect-default-reexport/default-export2/item.js, test/form/samples/side-effect-default-reexport/default-export2/menu.js, test/form/samples/side-effect-default-reexport/main.js, test/form/samples/side-effect-default-reexport/named-export/index.js, test/form/samples/side-effect-default-reexport/named-export/index2.js, test/form/samples/side-effect-default-reexport/named-export/item.js, test/form/samples/side-effect-default-reexport/named-export/menu.js
Resolves #3565 
This improves side-effect handling to make sure that when a module contains a default export declaration that is used, then side-effects in that module are included even if it is declared as having no side-effects and the default export just references a variable from another module. See #3565 for more reasoning.
=> Observe side-effects in files containing a default export declaration that reexports a variable

.github/workflows/node-windows.yml
This is my first contribution. I'm adding GitHub actions at my job, and I figured I would investigate how Rollup does it; in turn, I noticed this potential oversight.
Because Node.js v13 has been superseded by v14 with the intention to make the latter an LTS version, builds should target the eventual LTS version.
=> Target Node.js v14 instead of v13

src/utils/pureComments.ts, test/form/samples/pure-class-field/_config.js, test/form/samples/pure-class-field/_expected.js, test/form/samples/pure-class-field/main.js
Resolves #3591 
Unfortunately, `acorn-walk` is not yet properly updated for the new nodes added for class fields. This adds a temporary patch until this is hopefully resolved once the feature is merged to acorn.
=> Retain pure annotations in class fields

src/Module.ts, test/form/samples/side-effect-default-reexport/default-export/reexport.js, test/form/samples/side-effect-default-reexport/main.js
Resolves #3565
Apparently side-effects next to a default export statement were still not included when there were side-effect-free modules in between through which the default is reexported as a named export.
=> Handle side-effects next to side-effect-free default exports in case the default export is reexported

src/Chunk.ts, src/Module.ts, src/ModuleLoader.ts, src/ast/nodes/shared/knownGlobals.ts, test/function/samples/array-from-side-effect/_config.js, test/function/samples/array-from-side-effect/main.js
resolves #3603
Apparently `Array.from` can have a second argument with side-effects. Unfortunately, this will now mark any call to `Array.from` as having side-effects as the global local does not support anything better yet, but at least it should fix the provided issue. In the future, we might be able to do better.
=> Observe side-effects in second argument of `Array.from`

src/Chunk.ts, test/hooks/index.js, test/misc/misc.js
This allows RollupJS to support builds where you have a directory module that is built as a module, while containing subpaths itself.
For example:
```js
input: {
'pkg': 'main.js',
'pkg/feature': 'feature.js'
}
```
Without this patch, the relative path for the `pkg/feature` chunk reference to `pkg` will look like `./..` which doesn't resolve as a URL properly.
I haven't fleshed out tests here as I wanted to see if there is interest first. @lukastaegert let me know your thoughts and I can do the work to finish it up as necessary.
=> Handle imports from chunks with names that correspond to parent directory names of other chunks

src/Chunk.ts, test/form/samples/protect-cjs-globals/_expected/system.js, test/form/samples/sequence-expression/_expected/system.js, test/form/samples/system-module-reserved/_config.js, test/form/samples/system-module-reserved/_expected/amd.js, test/form/samples/system-module-reserved/_expected/cjs.js, test/form/samples/system-module-reserved/_expected/es.js, test/form/samples/system-module-reserved/_expected/iife.js, test/form/samples/system-module-reserved/_expected/system.js, test/form/samples/system-module-reserved/_expected/umd.js, test/form/samples/system-module-reserved/main.js
Fixes https://github.com/rollup/rollup/issues/3613
=> Ensure system-reserved identifiers are deduped

docs/04-tutorial.md
Wasted quite some time to learn that `manualChunks` exists. This change is what I think would help me find it earlier.
=> Docs > Tutorial > Improve discoverability of `manualChunks` for code splitting

LICENSE.md, package-lock.json, package.json, src/utils/options/normalizeInputOptions.ts, test/form/samples/numeric_separators/_config.js, test/form/samples/numeric_separators/_expected.js, test/form/samples/numeric_separators/main.js, test/function/samples/options-hook/_config.js, typings/declarations.d.ts
List any relevant issue numbers: https://github.com/rollup/rollup/issues/3605
Node already supports numeric separators and using babel target "node: current" breaks rollup.
=> Support numeric separator

src/ast/nodes/MemberExpression.ts, test/function/samples/namespace-reassign-import-fails/_config.js, test/function/samples/namespace-update-import-fails/_config.js
Similarly to https://github.com/rollup/rollup/pull/3475 this turns the static error into a warning that will become a runtime error only on the execution paths that actually attempt it.
=> Turn namespace assignment error into a warning

src/utils/escapeId.ts, test/form/samples/quote-id/_config.js, test/form/samples/quote-id/_expected/amd.js, test/form/samples/quote-id/_expected/cjs.js, test/form/samples/quote-id/_expected/es.js, test/form/samples/quote-id/_expected/iife.js, test/form/samples/quote-id/_expected/system.js, test/form/samples/quote-id/_expected/umd.js, test/form/samples/quote-id/main.js
This adds backslash escaping as well to the recent escaping work.
I've also reverted to the direct newline escaping over the table approach here, but we can add back the table too if you prefer.
I've also added an extra check in the escaping function to avoid any replacement if escaping is unnecessary. This is a super minor mostly theoretical pref improvement to avoid copying strings.
=> Support backslash escaping, retain exact newline escaping

src/Graph.ts, src/ModuleLoader.ts
Resolves #3640
In Rollup 2.9.0, new properties `importers` and `dynamicImporters` were added to `this.getModuleInfo`. While the graph was built, these properties were extended ver often for some files (in the example in #3640, `react` and another file were imported both by more than 5000 files).
These properties were also sorted and the logic was built in a way so that the properties were sorted after any new importer was added. Now if you add 5000 properties to an array and sort the array after each added property, this does not scale well.
This PR fixes this regression by only sorting when the `this.getModuleInfo` is actually called.
=> Fix performance regression when a file is imported by many importers

package.json
This sets the exports `"browser"` condition to point to the correct ES browser build to use for RollupJS.
@lukastaegert we had quite a bit of discussion about this stuff previously, but I don't think we had any disagreements about this support mode specifically. If there are any concerns and you want to discuss anything in more detail, I'm happy to leave this till you are back from your holiday and we can arrange a time to chat?
=> set browser build in exports

CHANGELOG.md, src/ast/nodes/MemberExpression.ts, test/cli/samples/watch/bundle-error/_config.js, test/function/samples/nested-namespace-member-expression/_config.js, test/function/samples/nested-namespace-member-expression/helpers.js, test/function/samples/nested-namespace-member-expression/main.js
Resolves #3642 
As part of a refactoring in #3637, accessing properties of namespace members was no longer working correctly, which is fixed here.
=> Fix accessing nested properties of namespaces

src/ast/scopes/ParameterScope.ts, test/function/samples/spread-arguments-unused/_config.js, test/function/samples/spread-arguments-unused/main.js
Resolves #3652 
Disabling argument tree-shaking if a spread element is passed seems prudent as it is hard to associate arguments with variables in such a case, otherwise the logic would grow really convoluted.
=> Do not tree-shake arguments that contain a spread element

docs/02-javascript-api.md, docs/05-plugin-development.md, src/Bundle.ts, src/Chunk.ts, src/ast/nodes/MetaProperty.ts, src/rollup/types.d.ts, test/function/samples/emit-file/emit-from-output-options/buildStart1.js, test/function/samples/emit-file/emit-from-output-options/buildStart2.js, test/function/samples/emit-file/file-references-in-bundle/_config.js, test/function/samples/emit-file/file-references-in-bundle/main.js, test/function/samples/emit-file/file-references-in-bundle/ref.js, test/watch/index.js
Resolves #3644 
This will add a `referencedFiles` property to chunks in generateBundle and to the bundle in the JavaScript API. It contains a list of all chunks and assets that are referenced in the given chunk via `import.meta.ROLLUP_FILE_URL_<id>`.
=> Add referenced files to bundle

src/ast/nodes/ConditionalExpression.ts, test/form/samples/tree-shake-arguments-conditional/_config.js, test/form/samples/tree-shake-arguments-conditional/_expected.js, test/form/samples/tree-shake-arguments-conditional/main.js
Resolves #3674 
This will track function identity through conditional expressions with regard to tree-shaking function arguments as in this example: https://rollupjs.org/repl/?circleci=12359&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwaWdub3JpbmdBcmdzJTIwKCklMjAlN0IlMjAlNUNuJTIwJTIwcmV0dXJuJTIwJ25vJTIwYXJncyclM0IlNUNuJTdEJTVDbiU1Q25mdW5jdGlvbiUyMHRha2luZ0FyZ3MoYXJnKSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjBhcmclM0IlNUNuJTdEJTVDbiU1Q25jb25zdCUyMGhhbmRsZXIlMjAlM0QlMjBmYWxzZSUyMCUzRiUyMHRha2luZ0FyZ3MlMjAlM0ElMjBpZ25vcmluZ0FyZ3MlM0IlNUNuJTVDbmNvbnNvbGUubG9nKGhhbmRsZXIoJ3Nob3VsZCUyMGJlJTIwcmVtb3ZlZCcpKSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJT …
=> Allow treeshaking of arguments of functions that are returned by conditional expressions

docs/01-command-line-reference.md, docs/02-javascript-api.md, docs/999-big-list-of-options.md
List any relevant issue numbers: #3664
The `input` option is not required if some plugin emits a chunk by the end of the `buildStart` hook, but this is not well documented. This PR adds documentation for this.
=> Acknowledge that the `input` option is conditionally required

src/Chunk.ts, test/function/samples/dynamic-import-default-mode-facade/_config.js, test/function/samples/dynamic-import-default-mode-facade/bar.js, test/function/samples/dynamic-import-default-mode-facade/foo.js, test/function/samples/dynamic-import-default-mode-facade/main.js, test/function/samples/dynamic-import-default-mode-facade/square.js
Resolves #3708 
When a module was dynamically imported that formed the entry point of a chunk and that chunk had a facade chunk and this happened in AMD or CJS format where the chunk was in default export mode, THEN Rollup would not properly form a namespace to wrap the import as the `default` of an object. Kindof hard to explain, but here is the fix.
=> Properly construct namespace when dynamically importing chunks with facades in default export mode

src/Chunk.ts, test/form/samples/handles-empty-imports-iife/_config.js, test/form/samples/handles-empty-imports-iife/_expected.js, test/form/samples/handles-empty-imports-iife/main.js, test/form/samples/handles-empty-imports-umd/_config.js, test/form/samples/handles-empty-imports-umd/_expected.js, test/form/samples/handles-empty-imports-umd/main.js
Resolves #3723
There was a rendering issue that was not popping up in tests due to an interaction between different builds, which is fixed here.
=> Fix missing variables for UMD and IIFE builds

src/ast/nodes/IfStatement.ts, test/function/samples/simplified-nested-if/_config.js, test/function/samples/simplified-nested-if/main.js
Resolves #3716
In case an if statement is nested within another if statement with no block statement in between and the outer if statement has an `else` branch, then any else branch of the inner if statement will not be entirely removed to avoid accidentally catching the `else` branch of the outer if statement.
=> Do not entirely move else branch if another else branch might accidentally be referenced.

docs/02-javascript-api.md, docs/05-plugin-development.md, src/Chunk.ts, src/rollup/types.d.ts, test/incremental/index.js, test/misc/bundle-information.js
Resolves #3374
This will add a list of imported symbols per chunk to the bundle information
=> Add import specifiers to bundle information

src/ast/nodes/ConditionalExpression.ts, src/ast/nodes/LogicalExpression.ts, src/ast/nodes/YieldExpression.ts, test/function/samples/prevent-tree-shaking-asi/main.js
Resolves #3729 
Apparently, the flag to prevent ASI-related issues was not correctly passed to nested expressions. This is fixed now, and also fixes this issue for yield expressions.
=> Prevent unintended ASI for nested conditionals

src/ast/nodes/LogicalExpression.ts, test/function/samples/prevent-tree-shaking-asi/main.js
Resolves #3729
There was one situation left in #3279 where a logical expression was simplified that was nested in one that was not simplified. In that situation, still an unintended ASI could happen which is hereby resolved.
=> Prevent ASI when simplifying a nested logical expression

src/ast/variables/SyntheticNamedExportVariable.ts, src/ast/variables/Variable.ts, test/chunking-form/samples/deprecated/indirect-reexports-preserve-modules/_expected/amd/components/index.js, test/chunking-form/samples/deprecated/indirect-reexports-preserve-modules/_expected/cjs/components/index.js, test/chunking-form/samples/deprecated/preserve-modules-commonjs/_expected/amd/commonjs.js, test/chunking-form/samples/deprecated/preserve-modules-commonjs/_expected/cjs/commonjs.js, test/chunking-form/samples/deprecated/preserve-modules-named-export-mode/_expected/amd/main.js, test/chunking-form/samples/deprecated/preserve-modules-named-export-mode/_expected/cjs/main.js, test/chunking-form/samples/indirect-reexports-preserve-modules/_expected/amd/components/index.js, test/chunking-form/samples/indirect-reexports-preserve-modules/_expected/cjs/components/index.js, test/chunking-form/samples/namespace-reexports/_expected/amd/generated-index.js, test/chunking-form/samples/namespace-reexports/_expected/cjs/generated-index.js, test/chunking-form/samples/preserve-modules-commonjs/_expected/amd/commonjs.js, test/chunking-form/samples/preserve-modules-commonjs/_expected/cjs/commonjs.js, test/chunking-form/samples/preserve-modules-named-export-mode/_expected/amd/main.js, test/chunking-form/samples/preserve-modules-named-export-mode/_expected/cjs/main.js, test/form/samples/deconflict-format-specific-globals/_expected/amd.js, test/form/samples/deconflict-format-specific-globals/_expected/cjs.js, test/form/samples/deconflict-format-specific-globals/_expected/iife.js, test/form/samples/deconflict-format-specific-globals/_expected/umd.js, test/function/samples/deconflict-synthetic-named-export-cross-chunk/_config.js, test/function/samples/deconflict-synthetic-named-export-cross-chunk/foo.js, test/function/samples/deconflict-synthetic-named-export-cross-chunk/main.js, test/function/samples/deconflict-synthetic-named-export/_config.js, test/function/samples/deconflict-synthetic-named-export/foo.js, test/function/samples/deconflict-synthetic-named-export/main.js
Resolves #3746
As it turned out, synthetic named exports were not properly fed into the deconflicting algorithm. This is fixed here.
=> Properly deconflict synthetic named exports

src/ModuleLoader.ts, test/function/samples/external-resolved/_config.js, test/function/samples/external-resolved/main.js
#3743 
As it turned out, when a plugin resolves an id using the object form, the resolved id is not again passed to the `external` option for a second check, which is fixed here. Thus, the examples in the documentation work again :)
=> Also pass resolved ids to external if they use the object form

docs/06-faqs.md
`external` is the one imported twice in `main.js` and later in `other-entry.js`
In the question [Why do additional imports turn up in my entry chunks when code-splitting?](https://github.com/rollup/rollup/blob/31e7348061597fd77f7154e327ec94acbe18fed2/docs/06-faqs.md#why-do-additional-imports-turn-up-in-my-entry-chunks-when-code-splitting) it was stated
>With this optimization, a JavaScript engine will discover all transitive dependencies after parsing an entry module, avoiding the waterfall:
>
>  1.  Load and parse main.js. At the end, imports to other-entry.js and external will be discovered.
>  2.  Load and parse other-entry.js and external. The import of other-entry.js is already loaded and parsed. …
=> Update FAQ: I think it was meant "external" instead of "other-entry.js"

CHANGELOG.md, docs/999-big-list-of-options.md, src/rollup/types.d.ts
Currently, both `include` and `exclude` of the `WatcherOptions` type are typed as only allowing an array of strings
```typescript
export interface WatcherOptions {
....     
exclude?: string[];
include?: string[];
}
```
I found this out by trying to do this:
```typescript
watch: {
exclude: [/dir/] // Type 'RegExp[]' is not assignable to type 'string[]'
```
This would wrongly make you think you can only add a string array.
I've changed the type to:
```typescript
export interface WatcherOptions {
...
exclude?: (string | RegExp)[];
include?: (string | RegExp)[];
}
```
=> add RegExp to the include and exclude fields of the WatcherOptions type

docs/02-javascript-api.md
The docs for `rollup/dist/loadConfigFile` incorrectly state that the `options` property of the object returned by `loadConfigFile` is an "inputOptions" object, when in fact it is an array of "inputOptions" objects. This PR fixes the text and code example in the docs.  
Relevant stackoverflow question: https://stackoverflow.com/questions/62153013/rollup-js-use-rollup-config-js-in-js-api
=> Fix api docs loadconfigfile

src/utils/renderHelpers.ts, test/function/samples/prevent-asi-with-line-comments/_config.js, test/function/samples/prevent-asi-with-line-comments/main.js
Resolves #3761 
When removing line-breaks to prevent automatic semicolon insertion in certain situation, it needs to be taken into account that a line comment before the end of the line can lead to broken or incomplete code. This is fixed here by removing the entire comment in such a situation.
=> Handle line-comments when removing line-breaks to prevent ASI

CHANGELOG.md, src/ast/nodes/IfStatement.ts, test/function/samples/unknown-statement/_config.js, test/function/samples/unknown-statement/main.js
Resolves #3766 
The new logic for if-statement simplification that relies on injecting additional scopes to detect hoisted variables introduced a bug where "unknown" nodes, in this case a debugger statement, were no longer properly handled. This is fixed here.
=> Handle debugger statements as if-statement branches

docs/07-tools.md
[rollup/rollup-plugin-commonjs #247](https://github.com/rollup/rollup-plugin-commonjs/issues/247#issuecomment-370677203)
Due to the previous listed issue and resolution; current documentation was inaccurate. This fixes the issue with Babel specifically, although I'm not sure if the "Note" should exist at all 🤔
=> Docs: Exception for babel plugin and commonjs plugin

CHANGELOG.md, cli/run/getConfigPath.ts, cli/run/loadConfigFile.ts, test/cli/samples/symlinked-config/_config.js, test/cli/samples/symlinked-config/main.js, test/cli/samples/symlinked-config/rollup.config.js, test/cli/samples/symlinked-config/rollup.config.symlinked, test/cli/samples/symlinked-named-config/_config.js, test/cli/samples/symlinked-named-config/main.js, test/cli/samples/symlinked-named-config/my.rollup.config.js, test/cli/samples/symlinked-named-config/rollup.config.symlinked
Resolves #3781 
The reason at its core here is that when using `require.cache` to intercept module loading and requiring a symlink, the filename in the cache will always be the symlink target (i.e. a symlink is treated as the symlinked file by Node). This was already handled when specifying an explicit file name but the logic was missing for the default file names. This is fixed now.
=> Handle loading symlinked config files

src/Chunk.ts
Unfortunately as Windows tests do not run on forks, there was a Windows issue that was not noticed
=> Fix preserveModulesRoot path on Windows

docs/999-big-list-of-options.md
Adds docs that were missed in https://github.com/rollup/rollup/pull/3786
=> [docs] add output.PreserveModulesRoot to big list of options

src/Chunk.ts, test/chunking-form/samples/deconflict-system-default-export-variable/_config.js, test/chunking-form/samples/deconflict-system-default-export-variable/_expected/amd/main.js, test/chunking-form/samples/deconflict-system-default-export-variable/_expected/amd/other.js, test/chunking-form/samples/deconflict-system-default-export-variable/_expected/cjs/main.js, test/chunking-form/samples/deconflict-system-default-export-variable/_expected/cjs/other.js, test/chunking-form/samples/deconflict-system-default-export-variable/_expected/es/main.js, test/chunking-form/samples/deconflict-system-default-export-variable/_expected/es/other.js, test/chunking-form/samples/deconflict-system-default-export-variable/_expected/system/main.js, test/chunking-form/samples/deconflict-system-default-export-variable/_expected/system/other.js, test/chunking-form/samples/deconflict-system-default-export-variable/main.js, test/chunking-form/samples/deconflict-system-default-export-variable/other.js, test/chunking-form/samples/deprecated/preserve-modules-dynamic-namespace/_expected/system/main.js, test/chunking-form/samples/preserve-modules-dynamic-namespace/_expected/system/main.js
resolves rollup/plugins#583
In SystemJS at the moment, every default export is creating a new variable. This is causing issues when by accident the variable name conflicts with the name of an imported namespace, which is fixed here.
=> Fix SystemJS default variable conflict

src/watch/fileWatcher.ts, test/watch/index.js
#3704
As suggested in the linked issue.
After I added the second test I discovered that it passes without this patch as well but decided to keep it to be sure.
=> Watch: listen for new files

docs/05-plugin-development.md
Great feature! When looking at the resolve plugin I was thinking this was a bit fragile using query params. Just fixing a typo
=> fix typo in docs

docs/05-plugin-development.md
Fixes a typo:
import { foo } from '../bar,js';
is now
import { foo } from '../bar.js';
=> Docs: fix code snippet

docs/07-tools.md
Updated documentation on configuring Babel removing the section on passing '{"modules": false}' as that is no longer needed since Babel 7
List any relevant issue numbers: #3717
I'm not sure if I should add some documentation on using `{"modules": false}` for Babel <7, what do you think?
=> feat: Update documentation on configuring Babel

cli/help.md, docs/01-command-line-reference.md, docs/05-plugin-development.md, src/Bundle.ts, src/Chunk.ts, src/ExternalModule.ts, src/Graph.ts, src/Module.ts, src/ModuleLoader.ts, src/ast/nodes/shared/Node.ts, src/rollup/types.d.ts, src/utils/PluginDriver.ts, src/utils/collapseSourcemaps.ts, src/utils/transform.ts, src/utils/traverseStaticDependencies.ts, test/chunking-form/samples/implicit-dependencies/implicitly-dependent-emitted-entry/_config.js, test/chunking-form/samples/implicit-dependencies/implicitly-dependent-entry/_config.js, test/chunking-form/samples/implicit-dependencies/multiple-dependencies/_config.js, test/chunking-form/samples/implicit-dependencies/single-dependency/_config.js, test/function/samples/deprecated/manual-chunks-info/_config.js, test/function/samples/manual-chunks-info/_config.js, test/function/samples/module-parsed-hook/_config.js, test/function/samples/module-parsed-hook/dep.js, test/function/samples/module-parsed-hook/main.js, test/function/samples/plugin-module-information/_config.js, test/incremental/index.js
This adds a new hook `moduleParsed` that is called for each module after the `transform` hook. This is needed to be notified once a cached module is available and will be useful to finally fix the caching for the commonjs plugin. Mainly, this hook will be used to resolve if a module is commonjs or ES both for cached and other modules.
Type: `(moduleInfo: ModuleInfo) => void`<br>
Kind: `async, parallel`<br>
Previous Hook: [`transform`](guide/en/#transform) where the currently handled file was transformed.<br>
NextHook: [`resolveId`](guide/en/#resolveid) and [`resolveDynamicImport`](guide/en/#resolvedynamicimport) to resolve all discovered static and dynamic imports in parallel if present, otherwise …
=> Add moduleParsed plugin hook

docs/05-plugin-development.md
The return value of `this.resolve` will contain the module metadata denoted with `meta` and not `custom`.
=> Fix this.resolve return type in docs

cli/run/batchWarnings.ts, test/cli/samples/warn-plugin-loc/_config.js, test/cli/samples/warn-plugin-loc/main.js, test/cli/samples/warn-plugin-loc/rollup.config.js
Plugin warnings without warning.id but with warning.loc were not emitting loc information
loc information emitting is fundamental for user experience (to locate the source of the error/warning)
Plugin warnings without `warning.id `but with `warning.loc` were not emitting `warning.loc` information
`warning.loc` information emitting is fundamental for user experience (to locate the source of the error/warning)
added 3 lines, to emit the `warning.loc` info if present in a format amicable to IDEs problem matchers: file:line:col
=> fix: plugin warnings not showing warning.loc

src/rollup/types.d.ts
According to the docs, options hook is supposed to be [async](http://rollupjs.org/guide/en/#options), and I checked the [code](https://github.com/rollup/rollup/blob/1fa9374/src/rollup/rollup.ts#L101) as well.
This pull request fixes the corresponding types.
=> [types] add options hook to AsyncPluginHooks

docs/05-plugin-development.md, src/Graph.ts, src/rollup/types.d.ts, src/utils/PluginContext.ts, src/utils/PluginDriver.ts, src/watch/fileWatcher.ts, src/watch/fsevents-importer.ts, src/watch/watch.ts, test/watch/index.js, typings/declarations.d.ts
Closes #3821
1. Implemented `closeWatcher` hook
2. Added `getWatchFiles` method to `PluginContext`
3. Extended `watchChange` hook to get `isDeleted` parameter
4. Also added `this: PluginContext` for `watchChange`
=> Improved watcher hooks

docs/05-plugin-development.md, src/Chunk.ts, src/ExternalModule.ts, src/Module.ts, src/ast/variables/NamespaceVariable.ts, src/rollup/types.d.ts, test/chunking-form/samples/implicit-dependencies/implicitly-dependent-emitted-entry/_config.js, test/chunking-form/samples/implicit-dependencies/implicitly-dependent-entry/_config.js, test/chunking-form/samples/implicit-dependencies/multiple-dependencies/_config.js, test/chunking-form/samples/implicit-dependencies/single-dependency/_config.js, test/function/samples/deprecated/manual-chunks-info/_config.js, test/function/samples/manual-chunks-info/_config.js, test/function/samples/module-parsed-hook/_config.js, test/function/samples/plugin-module-information/_config.js, test/function/samples/synthetic-named-exports/dynamic-import/_config.js, test/function/samples/synthetic-named-exports/non-default-export/_config.js
In [docs](https://rollupjs.org/guide/en/#load) there is line about `meta` and `syntheticNamedExports` in `ModuleInfo`:
=> Expose syntheticNamedExports to ModuleInfo

src/ast/nodes/TryStatement.ts, test/function/samples/conditional-catch/_config.js, test/function/samples/conditional-catch/main.js, test/watch/index.js
Resolves #3869
This solves a tricky issue in the interplay of the default deoptimization of try-catch blocks, see #3869. Basically what was happening is that while during the first tree-shaking run, the break statement with the label was correctly tracked, it was not tracked during the second run as it was nested in a try statement. And try statements are only evaluated once.
This PR fixes this by caching the labels that are used inside a try statement for subsequent runs.
=> Restore labels after included try statement block

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/BUG.md, .github/ISSUE_TEMPLATE/DOCS.md, .github/ISSUE_TEMPLATE/FEATURE.md, .github/ISSUE_TEMPLATE/MODIFICATION.md, .github/ISSUE_TEMPLATE/SUPPORT.md, CONTRIBUTING.md, README.md, docs/08-troubleshooting.md
We've moved chat to Discord and are closing down the Gitter. This updates all of the links in this repo.
=> docs: update chat/support links

src/finalisers/amd.ts, src/finalisers/shared/removeExtensionFromRelativeAmdId.ts, src/finalisers/umd.ts, test/form/samples/guessed-global-names/_expected/umd.js, test/form/samples/relative-external-with-global/_expected/umd.js
I noticed in the UMD finialiser the AMD ids are not run through `removeExtensionFromRelativeAmdId` when in the AMD one they are.
Should't they work the same way?
=> also removeExtensionFromRelativeAmdId in UMD finaliser

.github/workflows/node-windows.yml, package-lock.json, package.json, test/leak/index.js, test/test.js
This tries to make the memory leak test runnable on all Node and OS versions by switching to a different library and restructuring the test.
=> Run memory leak test on all systems

.github/workflows/node-windows.yml
This response from a Github PM https://twitter.com/chrisrpatterson/status/1333434798916980736 suggests that the lack of `pull_request` in our Action config is contributing to our problem. I still think there's a bigger Github bugbear here, but after enabling the Windows checks as mandatory for PR merge, I think this change might get us to where we need to be (and is in line with the plugins repo config)
=> chore: add pull_request to windows github actions

package.json
Resolves #3890 
This follows official Node (14) guidance to prefer a pattern export over a folder export.
=> Replace deprecated folder export with pattern export

package.json
Reverts #3896
As I did not realize, #3896 was a breaking change as it prevented extension-less requires for nested files. This reverts this change.
=> Revert pattern to folder export

cli/run/watch-cli.ts, docs/02-javascript-api.md, src/rollup/types.d.ts, src/watch/watch.ts, test/cli/samples/watch/close-on-generate-error/_config.js, test/cli/samples/watch/close-on-generate-error/main.js, test/cli/samples/watch/close-on-generate-error/rollup.config.js
One oversight from the previous PR #3883 was that when a bundle was successfully created but writing the files threw an error, then there was no way to close the bundle.
This is fixed now: In such a situation, the error event will also contain a reference to the created bundle. And the CLI will make sure, that the bundle is closed.
=> Forward bundle through watch error events

src/ast/nodes/AssignmentExpression.ts, test/form/samples/chained-assignments/_config.js, test/form/samples/chained-assignments/_expected.js, test/form/samples/chained-assignments/main.js, test/form/samples/nested-member-access/_expected.js, test/form/samples/nested-member-access/main.js
This will allow tree-shaking parts of chained assignment expressions. Example:
```js
// input
let a, b, c, d;
a = b = 1;
c = d = 2;
console.log(a, d);
// output
let a, d;
a = 1;
d = 2;
console.log(a, d);
```
Special care is taken so that
- Non-"=" Assignment operators such as "+=" are not tree-shaken
- Side-effects on the left side are still observed
This will be helpful with some planned updates for the commonjs plugin as it will produce nicer output.
=> Treeshake chained assignment expressions

src/ast/nodes/AssignmentExpression.ts, test/function/samples/tree-shake-object-expression-assignment/_config.js, test/function/samples/tree-shake-object-expression-assignment/main.js
Resolves #3920 
As with all "simplification" type optimizations, this adds the necessary information so that when e.g. an object expression becomes an expression statement, it is wrapped in parentheses to avoid being misinterpreted as a block statement. Should also solve similar issues for sequence expressions.
=> Prevent invalid code when removing assignment target of side-effectful object expression

src/ast/nodes/AssignmentExpression.ts, src/utils/renderHelpers.ts, test/function/samples/unused-parenthesed-assignment/_config.js, test/function/samples/unused-parenthesed-assignment/main.js
Resolves #3924
This fixes an issue where Rollup would incorrectly simplify assignment right-hand-sides with parentheses. Also, this improves performance of the non-white-space detection function by using a stateful regular expression instead of a loop.
=> Correctly simplify assignments with parentheses

src/Module.ts, test/function/samples/reexport-from-synthetic/_config.js, test/function/samples/reexport-from-synthetic/main.js, test/function/samples/reexport-from-synthetic/reexport.js, test/function/samples/reexport-from-synthetic/synthetic.js, test/function/samples/reexport-from-synthetic/synthetic1.js, test/function/samples/reexport-from-synthetic/synthetic2.js
#3857
resolves #3928 
This will treat synthetic namespaces as containing "all named exports" also when handling namespace reexports, i.e.
```js
// main.js
import {foo} from './reexport.js';
console.log(foo);
// reexport.js
export * from './synthetic.js';
// synthetic.js
// we assume this is marked as the synthetic namespace
export const __synth = {foo: 'bar'};
```
should work now.
=> Always respect synthetic namespaces in namespace reexports

rollup.config.js, src/utils/options/normalizeInputOptions.ts, typings/declarations.d.ts
When switching to latest rollup-plugin-node-resolve, we suddenly had two copies of acorn in the build as acorn does not use `module` in its export conditions. This fixes it, noticeably reducing file size again.
=> Deduplicate acorn import

README.md
To avoid confusing novices, update  Node.js and webpack references.
* Remove mention of experimental flag in Node.js since last two LTS versions
support ESM without it
* Change webpack 2 to just webpack since 3,4 and 5 also support ESM and webpack 2 docs are not on the webpack
website
=> Modernize references to Node.js and webpack

test/form/index.js
**N/A** - The fix is for the test suite itself.
Took me a little while to track down what was going on here. Basically, if the `emit-uint8array-no-buffer` test fails, then all subsequent tests will fail to execute. This is because the `emit-uint8array-no-buffer` test has a `before` function which deletes `global.Buffer`, and and an `after` function which is supposed to restore it.
However, prior to this PR, the `after` callback is not guaranteed to be called so `global.Buffer` remains undefined. The lack of `global.Buffer` causes issues with, [magic-string](https://github.com/Rich-Harris/magic-string/blob/389c1f1688b5f58db6589601f57b901a2aa43ce1/src/SourceMap.js#L9), but likely elsewhere too. …
=> Ensure test after() callback is always executed

src/ast/nodes/ForStatement.ts, src/ast/nodes/VariableDeclaration.ts, src/ast/nodes/VariableDeclarator.ts, test/function/samples/unused-for-loop-declaration/_config.js, test/function/samples/unused-for-loop-declaration/main.js
Resolves #3941 
This is a fix for an issue introduced by partial declaration tree-shaking in for-loops. The simple solution here is not to tree-shake declarations in the first argument of a for-loop. A more involved solution would be to always include ids here, but I was not sure if it was worth the effort.
=> Do not partially tree-shake unused declarations in for loops

src/Module.ts, src/ast/nodes/shared/Node.ts, test/function/samples/side-effect-free-module-function/_config.js, test/function/samples/side-effect-free-module-function/curry.js, test/function/samples/side-effect-free-module-function/main.js
Resolves #3942 
There was an issue with the inclusion logic for variables in modules without side effects that is fixed here.
=> Correctly include functions with side effects from side-effect-free modules

package-lock.json, package.json
List any relevant issue numbers: -NA-
This PR updates `chokidar` and `fsevents` in package.json.
`fsevents` ~2.1.2 was deprecated, and mentions to use 2.2 or 2.3 instead. This is the message you see when installing rollup as a dependency: `rollup > fsevents@2.1.3: "Please update to latest v2.3 or v2.2"`. The [commits](https://github.com/fsevents/fsevents/commits/master) there imply it's for Apple M1 compatibility.
`chokidar` also updated to that version of `fsevents`, so I updated that here too.
If you see package-lock.json, you'll see the older version of 2.1.3 got added to mocha's dependencies. They use the older version, and haven't released a new version yet.
=> Upgrade chokidar and fsevents for Apple M1 compatibility

src/Module.ts, src/ast/variables/ExportDefaultVariable.ts, src/ast/variables/SyntheticNamedExportVariable.ts, test/chunking-form/samples/synthetic-named-exports/chained-default-reexport/lib-reexport.js, test/chunking-form/samples/synthetic-named-exports/chained-default-reexport/lib-reexport2.js, test/function/samples/synthetic-named-exports/circular-synthetic-exports/_config.js, test/function/samples/synthetic-named-exports/circular-synthetic-exports/dep.js, test/function/samples/synthetic-named-exports/circular-synthetic-exports2/_config.js, test/function/samples/synthetic-named-exports/circular-synthetic-exports2/dep1.js, test/function/samples/synthetic-named-exports/circular-synthetic-exports2/dep2.js, test/function/samples/synthetic-named-exports/circular-synthetic-exports2/main.js, test/function/samples/synthetic-named-exports/synthetic-named-export-as-default/_config.js, test/function/samples/synthetic-named-exports/synthetic-named-export-as-default/dep.js, test/function/samples/synthetic-named-exports/synthetic-named-export-as-default/main.js, test/function/samples/synthetic-named-exports/synthetic-named-export-as-default/synthetic.js
rollup/plugins#658
This is an inconsistency that turned up when looking into https://github.com/rollup/plugins/pull/658#issuecomment-770284420. Basically the following situation:
```js
// main.js
import foo from './dep';
import { update } from './synthetic';
assert.strictEqual(foo, 'original');
update();
// This would fail
assert.strictEqual(foo, 'original');
// dep.js
import { foo } from './synthetic';
// This default export should produce a snapshot of the current value of foo
export default foo;
// synthetic.js
// This should be the synthetic namespace
export const __synthetic = { foo: 'original' };
export const update = () => (__synthetic.foo = 'reassigned');
```
So in short we have a synthetic …
=> Make sure default exports snapshot synthetic named exports

src/ast/nodes/VariableDeclaration.ts, src/ast/nodes/VariableDeclarator.ts, src/utils/reassignedExportsMember.ts, test/form/samples/assignment-to-exports/_expected/amd.js, test/form/samples/assignment-to-exports/_expected/cjs.js, test/form/samples/assignment-to-exports/_expected/es.js, test/form/samples/assignment-to-exports/_expected/iife.js, test/form/samples/assignment-to-exports/_expected/system.js, test/form/samples/assignment-to-exports/_expected/umd.js, test/form/samples/assignment-to-exports/main.js, test/form/samples/render-named-export-declarations/_expected/amd.js, test/form/samples/render-named-export-declarations/_expected/cjs.js, test/form/samples/render-named-export-declarations/_expected/iife.js, test/form/samples/render-named-export-declarations/_expected/umd.js, test/function/samples/create-undefined-export-property-compact/_config.js, test/function/samples/create-undefined-export-property-compact/main.js, test/function/samples/create-undefined-export-property/_config.js, test/function/samples/create-undefined-export-property/main.js, test/function/samples/destructuring-loop/_config.js, test/function/samples/destructuring-loop/main.js
This will make sure that even uninitialised named exports will create properties on the exports object in CJS/IIFE/AMD/UMD formats so that checking for those properties via `.hasOwnProperty` or `Object.keys` works.
This is important for tools that rely on this for e.g. merging and forwarding namespaces.
This was already working properly for constant exports but was broken for exports that were assigned dynamically later, example:
https://rollupjs.org/repl/?version=2.38.5&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGxldCUyMGZvbyUzQiU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjB1cGRhdGVGb28lMjAlM0QlMjAoKSUyMCUzRCUzRSUyMGZvbyUyMCUzRCUyMCd1cGRhdGVkJ …
=> Make sure uninitialised exports turn up via .hasOwnProperty for non-ES formats

src/Chunk.ts, test/form/samples/supports-core-js/_expected.js, test/function/samples/name-conflict-object/_config.js, test/function/samples/name-conflict-object/main.js, test/function/samples/name-conflict-promise/_config.js, test/function/samples/name-conflict-promise/dep.js, test/function/samples/name-conflict-promise/main.js, test/function/samples/name-conflict-symbol/_config.js, test/function/samples/name-conflict-symbol/main.js
Resolves #3969
For various features, Rollup relies on the global variables `Symbol`, `Object` and `Promise` working as intended. This can break if a module declares a variable of the same name in its top-level scope. This PR fixes it by making sure these names are always treated as reserved so that local variables are renamed if necessary.
=> Avoid conflicts with local variables named Symbol, Object, Promise

docs/999-big-list-of-options.md
=> Remove extra word

docs/01-command-line-reference.md, docs/05-plugin-development.md, docs/08-troubleshooting.md, docs/999-big-list-of-options.md
This will add some soft-breaks into long inline code snippets to improve how the docs render on small screens.
=> Add soft breaks to guide to improve mobile experience

src/Graph.ts, src/Module.ts, src/ast/keys.ts, src/ast/nodes/CallExpression.ts, src/ast/nodes/NewExpression.ts, src/ast/nodes/shared/Node.ts, src/utils/PluginContext.ts, src/utils/pureComments.ts, src/utils/treeshakeNode.ts, test/function/samples/call-marked-pure-with-plugin-parse-ast/_config.js, test/function/samples/call-marked-pure-with-plugin-parse-ast/main.js
If a plugin calls `PluginContext.parse` method to parse the AST of the module
rollup ignored the `PURE` annotations. This commit fixes the issue by moving
the annotation functionality to a central location - the `contextParse` method.
Resolves #3979
Resolve #3979 
Move pure comment annotation to Graph.contextParse
If a plugin calls `PluginContext.parse` method to parse the AST of the module
rollup ignored the `PURE` annotations. This commit fixes the issue by moving
the annotation functionality to a central location - the `contextParse` method.
=> Move pure comment annotation to Graph.contextParse

docs/999-big-list-of-options.md, src/ast/nodes/MemberExpression.ts, src/ast/nodes/Property.ts, src/rollup/types.d.ts, src/utils/options/normalizeInputOptions.ts, test/cli/samples/propertyReadSideEffects-always/_config.js, test/cli/samples/propertyReadSideEffects-always/_expected.js, test/cli/samples/propertyReadSideEffects-always/main.js, test/function/samples/propertyReadSideEffects-always/_config.js, test/function/samples/propertyReadSideEffects-always/main.js
#2219
#3234
#3974
#3984
Rollup does not correctly handle code dealing with getters with side effects when `treeshake` is enabled (the default setting). To address this shortcoming, this PR adds an `'always'` setting to `treeshake.propertyReadSideEffects` first proposed in https://github.com/rollup/rollup/issues/3234#issuecomment-554856949.
=> implement --treeshake.propertyReadSideEffects=always to handle getters with side effects

src/Module.ts, src/utils/sourceMappingURL.ts, test/function/samples/plugin-parse-ast-receives-comments/_config.js, test/function/samples/plugin-parse-ast-receives-comments/main.js, test/function/samples/plugin-parse-ast-remove-sourcemapping/_config.js, test/function/samples/plugin-parse-ast-remove-sourcemapping/main.js
Do the removal without relying on the module parsing the code. This way even if
a plugin uses the `parse` method in the PluginContext the comments are removed.
#3982
This PR moves the removal of sourceMappingURL comments away from code parsing. This means that even if a plugin parses the ast, the comment will still be removed.
=> Change removal of sourcemap comment

src/ast/scopes/ParameterScope.ts, test/function/samples/unused-parameter-side-effects/_config.js, test/function/samples/unused-parameter-side-effects/main.js
Resolves #3997 
When a function argument is an empty object pattern, Rollup would see that no variables are declared and falsely assume that it is not necessary. This fix adds special handling for that case (note that when even a single, even unused, variable was declared in the pattern, it was retained correctly).
=> Do not create invalid code if a function argument is an empty object pattern

src/ast/variables/ExternalVariable.ts, test/form/samples/treeshake-namespace-access/_config.js, test/form/samples/treeshake-namespace-access/_expected/amd.js, test/form/samples/treeshake-namespace-access/_expected/cjs.js, test/form/samples/treeshake-namespace-access/_expected/es.js, test/form/samples/treeshake-namespace-access/_expected/iife.js, test/form/samples/treeshake-namespace-access/_expected/system.js, test/form/samples/treeshake-namespace-access/_expected/umd.js, test/form/samples/treeshake-namespace-access/main.js
#3999
This solves a regression introduced in #3999 where accessing properties of external namespaces was considered side-effectful, preventing tree-shaking.
=> Do not count accessing members of an external namespace as side-effects.

browser/resolveId.ts, docs/05-plugin-development.md, src/ModuleLoader.ts, src/utils/PluginContext.ts, src/utils/PluginDriver.ts, src/utils/resolveId.ts, src/utils/resolveIdViaPlugins.ts, test/function/samples/prevent-context-resolve-loop/_config.js, test/function/samples/prevent-context-resolve-loop/dep.js, test/function/samples/prevent-context-resolve-loop/main.js, test/function/samples/prevent-context-resolve-loop/other1.js, test/function/samples/prevent-context-resolve-loop/other2.js, test/function/samples/prevent-context-resolve-loop/other3.js, test/function/samples/prevent-context-resolve-loop/other4.js
This will change the logic when using `skipSelf` in `this.resolve`. With this patch, this will not only skip the current plugin for this call of `this.resolve` but when one of the other plugins calls `this.resolve` again from its resolveId hook with the exact same source and importer, the initial plugin will be skipped as well.
Example:
```js
plugins: [
{
name: 'first',
async resolveId(source, importer) {
const resolved = await this.resolve(source, importer, {skipSelf: true});
if (resolved.id === 'foo1') return 'bar1';
}
},
{
name: 'second',
async resolveId(source, importer) {
const resolved = await this.resolve(source, importer, {skipSelf: true});
if (resolved.id === 'foo2') return 'bar2';
}
}
]
``` …
=> Break infinite loops in this.resolve

src/utils/timers.ts
when perf mode is activated and a plugin hooks throws.
Fixes #3876
This PR ensures the timerEnd promise isn't left unhandled (if the plugin throws - i.e `result` promise is rejected, the combined promise `result.then(...)` needs to be handled).
=> Fixed unhandled promise rejections

cli/run/loadConfigFile.ts, test/cli/samples/config-import-meta/_config.js, test/cli/samples/config-import-meta/_expected.js, test/cli/samples/config-import-meta/main.js, test/cli/samples/config-import-meta/plugin/plugin.js, test/cli/samples/config-import-meta/plugin/test.txt, test/cli/samples/config-import-meta/rollup.config.js
Resolves #3758 
This will make sure `import.meta.url` behaves as expected inside plugins that are imported via relative paths. Previously, `import.meta.url` would be the file url of the config file instead.
=> Use correct import.meta.url in config files

src/utils/pureComments.ts, test/cli/samples/watch/watch-config-initial-error/_config.js, test/form/samples/tree-shake-pure-optional-chaining/_config.js, test/form/samples/tree-shake-pure-optional-chaining/_expected.js, test/form/samples/tree-shake-pure-optional-chaining/main.js
Resolves #4006 
Not really a bug fix but rather an oversight: Since optional chaining call expressions are wrapped in a "ChainExpression" node, the existing logic for marking pure call expressions was skipping it. This is fixed now.
=> Tree-shake pure call expressions with optional chaining

src/utils/timers.ts
Fix after #4004
#4004 replace plugin hooks result promises, and forget to return original promises payload.
For this reason, rollup builds with `perf` option, and with `@rollup/plugin-typescript` for example, was broken - because `load` plugin hook can return modified input, and this input has been discarded.
=> Return hook result inside promise with async timer end

docs/08-troubleshooting.md
It's lowercase in the config.
>Usually, a plugin will only omit the sourcemap if it (the plugin, not the bundle) was configured with `sourcemap: false`
Looks like the [commmonjs plugin uses `sourceMap`](https://github.com/rollup/plugins/tree/master/packages/commonjs#sourcemap) 🙈, so not sure if the line about plugins should be left as is, or maybe CommonJS should also accept `sourcemap` to be more inline with rollup itself?
=> fix `sourcemap` reference in docs

test/cli/index.js
Since SIGINT fails to actually kill them on some platforms under some circumstances,
leading to a whole lot of watch tests sitting around for 40 seconds until they
time out.
See derail in the discussion for issue #3989
=> Use SIGTERM instead of SIGINT to kill test child processes

src/ast/nodes/ArrowFunctionExpression.ts, src/ast/nodes/CallExpression.ts, src/ast/nodes/Identifier.ts, src/ast/nodes/MemberExpression.ts, src/ast/nodes/ObjectExpression.ts, src/ast/nodes/ThisExpression.ts, src/ast/nodes/shared/Expression.ts, src/ast/nodes/shared/FunctionNode.ts, src/ast/nodes/shared/MultiExpression.ts, src/ast/nodes/shared/Node.ts, src/ast/values.ts, src/ast/variables/LocalVariable.ts, src/ast/variables/Variable.ts, test/form/samples/getter-return-values/_expected.js, test/form/samples/object-expression/method-side-effects/_expected.js, test/form/samples/object-expression/method-side-effects/main.js, test/form/samples/object-expression/return-expressions/_expected.js, test/form/samples/object-literal-property-overwrites/_expected.js, test/form/samples/property-setters-and-getters/early-access-getter-return/_expected.js, test/form/samples/recursive-calls/_expected.js, test/form/samples/side-effects-object-literal-calls/_expected.js
Adds a `referencesThis` flag to `FunctionNode` and uses it to avoid the deoptimization around method calls, as discussed in #3989
Instead of new tests, this reverts some of the test changes made by 3e0aa46d723cac0ac.
Let me know if the `FunctionNode.createScope` kludge is within the limits of kludginess accepted in this project. We could also do a conditional initialization of the property in `initialize`, but that'll lead to different object shapes for no real good reason.
List any relevant issue numbers: #3989
=> Disable pessimistic object deoptimization for calls when the called function doesn't ref this

docs/999-big-list-of-options.md
I was reading the rollup doc with a beginner in JavaScript 
and i realized that the meaning of "iife" was not explained anywhere 
I'm adding the meaning in a place that i feel makes sense in the documentation
This is only my best guess
I'm happy to add the explanation elsewhere and write a different text if the one i proposed is not satisfying
=> Add explanation for "iife"

src/ast/nodes/CallExpression.ts, src/ast/nodes/Identifier.ts, src/ast/nodes/MemberExpression.ts, src/ast/nodes/ObjectExpression.ts, src/ast/nodes/shared/Expression.ts, src/ast/nodes/shared/MultiExpression.ts, src/ast/nodes/shared/Node.ts, src/ast/variables/LocalVariable.ts, src/ast/variables/Variable.ts, test/form/samples/recursive-property-call/_config.js, test/form/samples/recursive-property-call/_expected.js, test/form/samples/recursive-property-call/main.js
Resolves #4024
The new method was missing recursion detection, which is added here. cc @marijnh
=> Handle recursive this mutation detection

.vscode/launch.json
Tests will fail to run in vscode debugger if we use `tdd` in `.vscode/launch.json`, because `describe` is not defined in `tdd` style. Changing `tdd` to `bdd` would make tests run normal.
[https://mochajs.org/#interfaces](https://mochajs.org/#interfaces)
=> chore: fix vscode launch config (change tdd to bdd)

src/ast/nodes/ObjectExpression.ts, test/form/samples/object-expression/proto-property/_config.js, test/form/samples/object-expression/proto-property/_expected.js, test/form/samples/object-expression/proto-property/main.js
List any relevant issue numbers: #4014
Works around issues with effect tracking in object literals with a prototype (specified with a `__proto__` or `"__proto__"` property) by completely deoptimizing nodes with such a property.
=> Deoptimize ObjectExpression when a __proto__ property is present

docs/02-javascript-api.md, docs/05-plugin-development.md, src/Chunk.ts, src/rollup/types.d.ts, test/misc/bundle-information.js
This fixes issues i created https://github.com/rollup/rollup/issues/3458. I would like to use this info for simple analysis and better code size estimations in visualizer plugin.
Let me know pls, if it could be done better.
=> Expose rendered module code to generateBundle hook

src/rollup/rollup.ts, test/function/samples/aync-options/_config.js, test/function/samples/aync-options/main.js
Resolves #4038 
Due to a missing `await`, async options hooks with false results were not handled correctly.
=> Do not fail when returning null or undefined from an async options hook

src/Chunk.ts, test/chunking-form/samples/single-file-manual-chunk/_config.js, test/chunking-form/samples/single-file-manual-chunk/_expected/amd/generated-first.js, test/chunking-form/samples/single-file-manual-chunk/_expected/amd/generated-second.js, test/chunking-form/samples/single-file-manual-chunk/_expected/amd/main.js, test/chunking-form/samples/single-file-manual-chunk/_expected/cjs/generated-first.js, test/chunking-form/samples/single-file-manual-chunk/_expected/cjs/generated-second.js, test/chunking-form/samples/single-file-manual-chunk/_expected/cjs/main.js, test/chunking-form/samples/single-file-manual-chunk/_expected/es/generated-first.js, test/chunking-form/samples/single-file-manual-chunk/_expected/es/generated-second.js, test/chunking-form/samples/single-file-manual-chunk/_expected/es/main.js, test/chunking-form/samples/single-file-manual-chunk/_expected/system/generated-first.js, test/chunking-form/samples/single-file-manual-chunk/_expected/system/generated-second.js, test/chunking-form/samples/single-file-manual-chunk/_expected/system/main.js, test/chunking-form/samples/single-file-manual-chunk/a.js, test/chunking-form/samples/single-file-manual-chunk/b.js, test/chunking-form/samples/single-file-manual-chunk/c.js, test/chunking-form/samples/single-file-manual-chunk/main.js
Resolves #3973
If a manual chunk only contains a single dynamic entry point, the manual chunk name would be overridden by the name derived from the dynamic entry. As this is not in the user's interest, this will change the priorities to prefer the user-given name.
Now the only situation where a manual chunk will not receive the expected name is if there is a single explicitly defined entry point in the chunk (which is an optimisation to reduce the number of chunks).
=> Prioritize manual chunk name over dynamic entry id

src/ExternalModule.ts, test/function/samples/unused-import/_config.js
- Resolve https://github.com/rollup/rollup/issues/4052
This patch add to `UNUSED_EXTERNAL_IMPORT` warning information about the origin of the problem
=> Add to `UNUSED_EXTERNAL_IMPORT` warning information about the origin of the problem

src/Graph.ts, src/utils/pureComments.ts, test/form/samples/pure-comment-line-break/_expected.js, test/form/samples/pure-comment-line-break/main.js, test/form/samples/pure-comments-disabled/_expected.js, test/form/samples/pure-comments-disabled/main.js
Ignore invalid trailing pure annotations that were incorrectly associated with subsequent calls.
fixes #4062
Ignore invalid trailing pure annotations that were incorrectly associated with subsequent calls causing those calls to be erroneously dropped.
A valid pure annotation comment must precede a call or new expression and only whitespace characters may appear between the annotation comment and the following call.
=> Ignore invalid trailing pure annotations

src/utils/pureComments.ts
#4068
Fix comment in #4068 and add an example of an invalid annotation.
No code changes.
=> fix comment regarding invalid annotation handling

src/ast/nodes/shared/ArrayPrototype.ts, src/ast/nodes/shared/MethodTypes.ts, test/form/samples/builtin-prototypes/side-effect-free-array-expression/_config.js, test/form/samples/builtin-prototypes/side-effect-free-array-expression/_expected.js, test/form/samples/builtin-prototypes/side-effect-free-array-expression/main.js
#4100 (but does not fully resolve it)
This will no longer track calling array builtin methods such as `filter` as side-effects: [REPL](https://rollupjs.org/repl/?pr=4103&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwZm9vNSUyMCUzRCUyMCU1QjElMkMlMjAyJTJDJTIwMyU1RCUzQiU1Q25mb281LmZpbHRlcih2JTIwJTNEJTNFJTIwdiUyMCUyNSUyMDElMjAlM0QlM0QlM0QlMjAwKSUzQiU1Q25jb25zb2xlLmxvZyhmb281JTVCMCU1RCklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0F …
=> Do not track side-effect-free array methods as side effects

src/Module.ts, test/function/samples/inline-dynamic-no-treeshake/_config.js, test/function/samples/inline-dynamic-no-treeshake/dep.js, test/function/samples/inline-dynamic-no-treeshake/reexport.js
Resolves #4098 
This resolves a crash when
* inlineDynamicImports is used
* A module is set to "no-treeshake"
* That module has a dependency that is completely tree-shaken
=> Fix crash when using inlineDynamicImports with no-treeshake

src/ast/nodes/CatchClause.ts, src/ast/scopes/CatchScope.ts, test/function/samples/catch-block-scope/_config.js, test/function/samples/catch-block-scope/main.js
Resolves #4096 
Resolves #4106 
There was a scoping issue in catch scopes that could lead to incorrect variable associations, see the linked issues. The implemented logic now works like this:
* The body of a catch clause now receives a block scope so that block scoped declarations do not seep into surrounding scopes, including the parameter scope
* Hoisted declarations inside the catch clause that do not match a parameter name will be hoisted to the surrounding scope (as before)
* Hoisted declarations that DO match a parameter will instead be associated with the parameter and are not hoisted to the outside (this is new and indeed correct)
=> Correctly handle catch declarations

src/Module.ts, src/ast/nodes/AssignmentExpression.ts, src/ast/nodes/AssignmentPattern.ts, src/ast/nodes/CallExpression.ts, src/ast/nodes/ForInStatement.ts, src/ast/nodes/ForOfStatement.ts, src/ast/nodes/Identifier.ts, src/ast/nodes/MemberExpression.ts, src/ast/nodes/NewExpression.ts, src/ast/nodes/Property.ts, src/ast/nodes/RestElement.ts, src/ast/nodes/SpreadElement.ts, src/ast/nodes/UnaryExpression.ts, src/ast/nodes/UpdateExpression.ts, src/ast/nodes/YieldExpression.ts, test/function/samples/deoptimize-request-treeshaking-pass/_config.js, test/function/samples/deoptimize-request-treeshaking-pass/main.js
… are first included
Resolves #4097
Now that all deoptimizations happen lazily, there is a now class of issues that can arise, notably when during a tree-shaking pass, no new variables are included but some nodes perform deoptimizations for the first time.
Previously, new passes were only triggered when new variables were included. This has been changed to also trigger new passes when deoptimizations are applied.
=> Always request a new tree-shaking pass when deoptimizations are performed

src/ast/nodes/ObjectExpression.ts, test/form/samples/proto-null/_config.js, test/form/samples/proto-null/_expected.js, test/form/samples/proto-null/main.js, test/function/samples/proto-accessors/_config.js, test/function/samples/proto-accessors/main.js
Resolves #4094 
This replaces the clunky logic that was previously used for `__proto__` object literal properties by actually setting the prototype when such a property is encountered. This will immediately add support for accessors on the new prototype. There is special handling for the case where the property is the literal `null`. Only in this case, a prototype-free object will be created: [REPL](https://rollupjs.org/repl/?pr=4112&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwZm9vJTIwJTNEJTIwJTdCX19wcm90b19fJTNBJTIwbnVsbCU3RCUzQiU1Q25pZiUyMChmb28uaGFzT3duUHJvcGVydHkpJTIwY29uc29sZS5sb2coJ2dvbmUnKSUzQiU1Q24lNUNuY29uc3QlMjBiYXIlMjAlM0Q …
=> Actually set the prototype when using a __proto__ property

src/ast/nodes/SpreadElement.ts, test/cli/samples/watch/watch-config-early-update/_config.js, test/function/samples/object-spread-side-effect/_config.js, test/function/samples/object-spread-side-effect/main.js
Resolves #4093 
This will additionally check for getter side effects when using the spread operator on an object.
=> Track access side effects when using object spread operator

scripts/perf.js
`turbocolor` has been replaced with `colorette` in https://github.com/rollup/rollup/pull/3391, for now it is still used in `perf.js` file
=> fix: use `colorette` instead of `turbocolor` #3391

src/ast/nodes/SpreadElement.ts, test/form/samples/ignore-property-access-side-effects/main.js, test/form/samples/keep-property-access-side-effects/_expected.js, test/form/samples/keep-property-access-side-effects/main.js
#4113
In #4113, we introduced a check for property access side effects when using spread operators. This check was always applied. This PR changes this by respecting `treeshake.propertyReadSideEffects: false`.
=> Respect propertyReadSideEffects in spread elements

src/ast/nodes/ArrowFunctionExpression.ts, src/ast/nodes/SpreadElement.ts, src/ast/nodes/shared/FunctionNode.ts, test/form/samples/async-function-effects/_config.js, test/form/samples/async-function-effects/_expected.js, test/form/samples/async-function-effects/main.js, test/form/samples/ignore-property-access-side-effects/main.js, test/form/samples/keep-property-access-side-effects/_expected.js, test/form/samples/keep-property-access-side-effects/main.js, test/function/samples/async-function-return/_config.js, test/function/samples/async-function-return/main.js
Resolves #4116
This will also detect side effects from accessing the `then` property or calling it when executing an async arrow function.
=> Detect async arrow thenable side effects

docs/01-command-line-reference.md, src/rollup/rollup.ts, src/rollup/types.d.ts
List any relevant issue numbers: https://github.com/rollup/rollup/issues/4125
=> feat: Export defineConfig defines the auxiliary function of the configuration

package.json, src/browser-entry.ts, src/node-entry.ts, test/cli/samples/config-defineConfig-cjs/_config.js, test/cli/samples/config-defineConfig-cjs/main.js, test/cli/samples/config-defineConfig-cjs/rollup.config.js, test/cli/samples/config-defineConfig-mjs/_config.js, test/cli/samples/config-defineConfig-mjs/main.js, test/cli/samples/config-defineConfig-mjs/rollup.config.mjs
- #4133
This PR fixes #4133.
I expose `defineConfig` from entrypoint([node-entry.ts](https://github.com/rollup/rollup/pull/4134/files#diff-11288f92b833075d1381a302bbcf49bd4c62b841c0e6f7ecee04868081f90d41R1), [browser-entry.ts](https://github.com/rollup/rollup/pull/4134/files#diff-591f02c4219ff2edf76baf1560952dfbc5c48a021d8391d1168a9624771b860aR1)).
As a result, [type definition](https://github.com/rollup/rollup/blob/master/src/rollup/types.d.ts#L887) and runtime correspond.
=> fix: export `rollup.defineConfig` at runtime

src/ast/nodes/ArrayExpression.ts, src/ast/nodes/shared/ArrayPrototype.ts, src/ast/nodes/shared/ObjectEntity.ts, src/ast/nodes/shared/ObjectPrototype.ts, test/form/samples/object-expression/reassign-prop-without-proto/_config.js, test/form/samples/object-expression/reassign-prop-without-proto/_expected.js, test/form/samples/object-expression/reassign-prop-without-proto/main.js, test/form/samples/object-expression/unknown-getter-no-side-effect/_config.js, test/form/samples/object-expression/unknown-getter-no-side-effect/_expected.js, test/form/samples/object-expression/unknown-getter-no-side-effect/main.js, test/form/samples/object-expression/unknown-setter-no-side-effect/_config.js, test/form/samples/object-expression/unknown-setter-no-side-effect/_expected.js, test/form/samples/object-expression/unknown-setter-no-side-effect/main.js, test/function/samples/array-double-spread/_config.js, test/function/samples/array-double-spread/main.js, test/function/samples/modify-this-via-getter/unknown-prop-getter/_config.js, test/function/samples/object-deep-access-effect/_config.js, test/function/samples/object-deep-access-effect/main.js, test/function/samples/returned-array-mutation/_config.js, test/function/samples/returned-array-mutation/main.js
Resolves #4140 
Currently, Rollup treats the Array and Object prototypes as singletons. This is problematic as we are still using a stateful helper class to implement this, which can lead to a memory leak when used in watch mode. This hopefully improves the situation. Note that in the future, we might rework this again if we ever get to the point that we track mutations of globals.
=> Make array and object prototype singletons immutable for now

build-plugins/add-cli-entry.ts, build-plugins/conditional-fsevents-import.ts, build-plugins/emit-module-package-file.ts, build-plugins/esm-dynamic-import.ts, build-plugins/generate-license-file.ts, build-plugins/replace-browser-modules.ts, docs/01-command-line-reference.md, package-lock.json, package.json, rollup.config.ts, src/rollup/types.d.ts, src/utils/ensureArray.ts, src/utils/renderChunk.ts, tsconfig.json, typings/declarations.d.ts
To benefit from the new `--configPlugin` option, this will switch Rollup's own config to TypeScript. This immediately uncovered some inconsistencies in the typings that are resolved as well:
* The `renderChunk` hook is allowed to return `undefined`
* Plugins can also be falsy, in which case they are ignored
=> Use TypeScript config and improve some types

.github/workflows/tests.yml, package.json, src/ast/nodes/Identifier.ts, src/ast/scopes/BlockScope.ts, src/ast/scopes/CatchScope.ts, test/form/samples/deoptimize-var-in-hoisted-scopes/_config.js, test/form/samples/deoptimize-var-in-hoisted-scopes/_expected.js, test/form/samples/deoptimize-var-in-hoisted-scopes/main.js, test/function/samples/correct-var-before-declaration-deopt/_config.js, test/function/samples/correct-var-before-declaration-deopt/_expected.js, test/function/samples/correct-var-before-declaration-deopt/main.js
Resolves #4147 
There was already a logic to deoptimize `var` variables that are defined in nested scopes. This logic deoptimized the value of such variables but forgot to also deoptimize the initializer of those variables. It also deoptimizes initializers when vars are deoptimized via `treeshake.correctVarValueBeforeDeclaration`.
While this is a bug fix, it may prove interesting to see if #4148 will offer a way to handle these things differently. This should not prevent release, however.
=> Make sure the initializer of hoisted variables is deoptimized

.github/labels.json, .github/workflows/repl-artefacts.yml, .github/workflows/tests.yml
This will protect the REPL build workflow by only running it on forks if a specific label `x8 ⚙️ build repl artefacts` has been set on a pull request.
=> Only run REPL build on internal branches or when specific label is set

.github/ISSUE_TEMPLATE/bug.yaml
Super minor thing I just noticed after the merge. We shouldn't line wrap manually so that it fills the space better in the actual form.
=> remove manual wrapping in bug issue form

src/Module.ts, test/function/samples/double-namespace-reexport/_config.js, test/function/samples/double-namespace-reexport/first.js, test/function/samples/double-namespace-reexport/main.js, test/function/samples/double-namespace-reexport/second.js
Resolves #4158 
This fixes an issue with the new logic that prefers local namespace reexports over external ones. Basically what was happening that the logic to detect cycles was preventing proper resolution of external namespace reexports if the reexports went over several steps.
=> Properly handle double reexports from external namespaces

src/Module.ts, test/misc/misc.js
=> fix: max stack call error is caught on locate

src/ast/ExecutionContext.ts, src/ast/nodes/ArrowFunctionExpression.ts, src/ast/nodes/AwaitExpression.ts, src/ast/nodes/ReturnStatement.ts, src/ast/nodes/YieldExpression.ts, src/ast/nodes/shared/FunctionNode.ts, test/form/samples/async-function-effects/main.js, test/form/samples/ignore-property-access-side-effects/main.js, test/function/samples/track-awaited-object/_config.js, test/function/samples/track-awaited-object/main.js
Resolves #4161 
Currently, we are not tracking object deoptimizations through await expressions. This PR simplifies the logic here by always deoptimizing await expressions to avoid the complicated promise logic
=> Deoptimize awaited expressions

src/ast/nodes/ArrowFunctionExpression.ts, src/ast/nodes/AwaitExpression.ts, src/ast/nodes/shared/FunctionNode.ts, test/function/samples/track-async-arrow-function-return-value/_config.js, test/function/samples/track-async-arrow-function-return-value/main.js, test/function/samples/track-async-function-return-value/_config.js, test/function/samples/track-async-function-return-value/main.js
This is a follow-up to #4161 resolving https://github.com/rollup/rollup/issues/4161#issuecomment-872168183. The problem is that for async functions, we were not properly deoptimizing the return value, which is fixed here.
=> Deoptimize return values of async functions

src/Module.ts, test/form/samples/no-treeshake-namespace-object/_config.js, test/form/samples/no-treeshake-namespace-object/_expected.js, test/form/samples/no-treeshake-namespace-object/main.js, test/form/samples/no-treeshake-namespace-object/namespace.js
resolves #4174 
When tree shaking was turned off, sometimes namespace objects were not generated. This is fixed here.
=> Generates namespace objects when not tree-shaking

src/ast/nodes/CatchClause.ts, src/ast/scopes/CatchScope.ts, test/function/samples/catch-scope-shadowing/_config.js, test/function/samples/catch-scope-shadowing/main.js
Resolves #4176
Apparently, a `var` declared in a catch clause will always create a hoisted variable, even if the variable name matches the clause parameter. If that is the case, then the initializer goes to the parameter instead of the variable...
This handles this correctly by always creating a hoisted variable while deoptimizing the catch parameter if there is a conflict.
=> Correctly create outside variable when shadowed by catch parameter

docs/999-big-list-of-options.md, src/ast/nodes/Identifier.ts, src/ast/scopes/TrackingScope.ts, test/cli/samples/treeshake-preset-override/_expected.js, test/form/samples/tdz-common/_expected.js, test/form/samples/tdz-common/main.js, test/form/samples/treeshake-presets/preset-with-override/_expected.js, test/form/samples/treeshake-presets/recommended/_expected.js, test/form/samples/treeshake-presets/smallest/_expected.js, test/form/samples/treeshake-presets/true/_expected.js, test/function/samples/use-var-before-decl/main.js
Fix additional variable state change bugs including blockless `if` statement `var` declarations and `let`/`var` use before declaration within same function that do not cross function scopes.
Fixes several outstanding var/let init issues mentioned in #4148 without any code pessimization other than for previously incorrect rollup output, and with minimal overhead.
=> Fix additional let/var init bugs

src/ast/nodes/MetaProperty.ts, test/form/samples/configure-file-url/_expected/umd.js, test/form/samples/deconflict-format-specific-globals/_expected/umd.js, test/form/samples/deprecated/configure-asset-url/_expected/umd.js, test/form/samples/deprecated/emit-asset/_expected/umd.js, test/form/samples/emit-asset-file/_expected/umd.js, test/form/samples/emit-uint8array-no-buffer/_expected/umd.js, test/form/samples/import-meta-url/_expected/umd.js, test/form/samples/import-meta/_expected/umd.js, test/form/samples/resolve-import-meta-url/_expected/umd.js
If I compile a library that uses `import.meta.url` internally using UMD, it will break if I try to use it inside web workers, that happens because today rollup compile `import.meta.url` to use nodejs require or browser document API, but both is unavailable inside web workers. This PR adds a check for it and try to use `location.href`, if available.
=> Fix import.meta.url inside web workers

src/ast/nodes/MemberExpression.ts, src/ast/nodes/shared/ObjectMember.ts, src/ast/variables/LocalVariable.ts, test/form/samples/deep-properties-access/_config.js, test/form/samples/deep-properties-access/_expected.js, test/form/samples/deep-properties-access/main.js, test/form/samples/deep-properties/_config.js, test/form/samples/deep-properties/_expected.js, test/form/samples/deep-properties/main.js, test/form/samples/recursive-property-call/_config.js, test/form/samples/recursive-property-call/_expected.js, test/form/samples/recursive-property-call/main.js, test/form/samples/static-method-deoptimization/_config.js, test/form/samples/static-method-deoptimization/_expected.js, test/form/samples/static-method-deoptimization/main.js
Resolves #4184
This resolves a regression reported when calling class methods that themselves call methods on "this". Here it was possible that Rollup was trying to deoptimize an infinite object path (basically `.prototype.prototype.prototype...`). This is resolved by moving the logic to prevent these things from the LocalVariable class to the MemberExpression class as the latter is actually the one responsible for the issue.
=> Move long path recursion prevention to MemberExpression

cli/run/batchWarnings.ts, docs/08-troubleshooting.md, src/finalisers/shared/warnOnBuiltins.ts, test/cli/samples/warn-multiple/_config.js, test/misc/misc.js
Resolves #2881
I recently went on a wild goose chase trying to figure out the best solution in the current Rollup ecosystem for polyfilling Node builtins. Long story short, this repository https://github.com/snowpackjs/rollup-plugin-polyfill-node looks to be, by far, the best alternative to the currently recommended repository, which has not been maintained for 2 years. I personally migrated to this package and it appears to work extremely well.
Related threads:
* https://github.com/rollup/awesome/pull/92 - Discovery that the old package is not preferred.
* https://github.com/rollup/awesome/pull/94 - Addition of the up to date package to the awesome list.
=> Stop recommending node-builtins

docs/02-javascript-api.md
The watcher event has an `output` property, not an `outputFiles` property.
The watcher event has an `output` property, not an `outputFiles` property.
=> Fix incorrect watcher event documentation

cli/run/batchWarnings.ts, test/cli/samples/warn-import-export/_config.js
The original issue which was closed is https://github.com/rollup/rollup/issues/4052. This finishes addressing that issue
PR https://github.com/rollup/rollup/pull/4054 improved the individual warning, but did not update the batch warning. When I build SvelteKit with Vite, which uses Rollup, I get a warning that I can't understand the origin of or how to fix
After using a locally modified copy, I was quickly able to track down the culprit: https://github.com/ampproject/amphtml/pull/35435
=> Align batch warning for UNUSED_EXTERNAL_IMPORT to individual warning

src/ast/nodes/VariableDeclaration.ts, test/form/samples/simplified-initializer/_config.js, test/form/samples/simplified-initializer/_expected/amd.js, test/form/samples/simplified-initializer/_expected/cjs.js, test/form/samples/simplified-initializer/_expected/es.js, test/form/samples/simplified-initializer/_expected/iife.js, test/form/samples/simplified-initializer/_expected/system.js, test/form/samples/simplified-initializer/_expected/umd.js, test/form/samples/simplified-initializer/main.js, test/function/samples/max-parallel-file-reads-with-plugin/_config.js
Resolves #4201 
Due to an ordering issue, export declarations with an initializer that was a simplified expression would lead to incorrect results.
=> Fix incorrect rendering of export declarations in SystemJS

src/ast/nodes/AssignmentExpression.ts, src/ast/nodes/BinaryExpression.ts, src/ast/nodes/CallExpression.ts, src/ast/nodes/ClassExpression.ts, src/ast/nodes/ConditionalExpression.ts, src/ast/nodes/ExportDefaultDeclaration.ts, src/ast/nodes/FunctionExpression.ts, src/ast/nodes/LogicalExpression.ts, src/ast/nodes/MemberExpression.ts, src/ast/nodes/ObjectExpression.ts, src/ast/nodes/SequenceExpression.ts, src/ast/nodes/VariableDeclarator.ts, src/utils/renderHelpers.ts, test/function/samples/function-expressions-simplified-to-statement/main.js, test/function/samples/simplify-with-destructuring/_config.js, test/function/samples/simplify-with-destructuring/main.js
When simplifying statements that include object pattern assignments, we need to add parentheses when the assignment would end up as an expression statement or arrow function return value. https://rollupjs.org/repl/?version=2.56.1&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmxldCUyMGZvbyUyQyUyMHVudXNlZCUzQiU1Q24lMkYlMkYlMjBUaGUlMjBsZWFkaW5nJTIwJTVDJTIyJTdCJTVDJTIyJTIwd2lsbCUyMGJlJTIwbWlzaW50ZXJwcmV0ZWQlMjBhcyUyMGElMjBibG9jayUyMHN0YXRlbWVudCU1Q25udWxsJTJDJTIwJTdCJTIwZm9vJTIwJTdEJTIwJTNEJTIwJTdCJTIwZm9vJTNBJTIwJ2JhciclMjAlN0QlM0IlNUNuYXNzZXJ0LnN0cmljdEVxdWFsKGZvbyUyQyUyMCdiYXInKSUzQiU1Q24lNUNuJTJGJTJGJTIwQWdhaW4lMkMlMjB0aGUlMjBsZWFkaW5nJTIwJTVDJTI …
=> Do not create invalid code when simplifying object pattern assignments

docs/05-plugin-development.md, src/Module.ts, src/ModuleLoader.ts, test/function/samples/module-parsed-imported-ids/_config.js, test/function/samples/module-parsed-imported-ids/dynamic.js, test/function/samples/module-parsed-imported-ids/main.js, test/function/samples/module-parsed-imported-ids/static.js
I get error (TypeError: Cannot read property 'id' of undefined) when use `moduleInfo.importedIds` in moduleParsed of rollup plugin
after check importedIds source code, fin not compatible `undefined`.
=> fixed: ModuleInfo.importedIds will return null if resolvedIds[source] is undefined

tsconfig.json
just for good house keeping. recommended setting.
https://www.typescriptlang.org/tsconfig/#forceConsistentCasingInFileNames
> TypeScript follows the case sensitivity rules of the file system it’s running on. This can be problematic if some developers are working in a case-sensitive file system and others aren’t. If a file attempts to import fileManager.ts by specifying ./FileManager.ts the file will be found in a case-insensitive file system, but not on a case-sensitive file system.
> When this option is set, TypeScript will issue an error if a program tries to include a file by a casing different from the casing on disk.
=> chore: use forceConsistentCasingInFileNames in ts-config

src/ModuleLoader.ts, test/function/samples/es5-class-called-without-new/main.js, test/function/samples/object-deep-access-effect/_config.js, test/function/samples/object-deep-access-effect/main.js, test/function/samples/warn-on-top-level-this/_config.js
resolves #4217
This fixes an instance where rollup can cause an unhandled rejection during normal programmatic usage. There isn't a simple way to test this since as of Node 15, a test would amount to ensuring that the process doesn't exit when you force a module resolution error.
I temporarily enabled `@typescript-eslint/no-floating-promises` with parserServices to check if there were any other places that had floating promises outside of `ModuleLoader.ts` and saw the following:
```console
❯ npx eslint src --cache
/Users/kherock/Workspaces/rollup/src/ModuleLoader.ts
341:3  error  Promises must be handled appropriately or explicitly marked as ignored with the `void` operator …
```
=> fix: prevent UnhandledPromiseRejectionWarning when module resolution/parsing fails

src/ast/nodes/Identifier.ts, typings/declarations.d.ts
missed this during the **@rollup/plugin-typescript** bump.
also fixed the return type of **is_reference**.
=> chore: remove unused rollup-plugin-typescript ambient module types

browser/resolveId.ts, docs/01-command-line-reference.md, docs/05-plugin-development.md, docs/999-big-list-of-options.md, src/ModuleLoader.ts, src/rollup/types.d.ts, src/utils/PluginContext.ts, src/utils/resolveId.ts, src/utils/resolveIdViaPlugins.ts, test/function/index.js, test/function/samples/resolveid-is-entry/_config.js, test/function/samples/resolveid-is-entry/chunkWithImporter.js, test/function/samples/resolveid-is-entry/chunkWithoutImporter.js, test/function/samples/resolveid-is-entry/dep.js, test/function/samples/resolveid-is-entry/main.js, test/function/samples/resolveid-is-entry/resolutionWithImporter.js, test/function/samples/resolveid-is-entry/resolutionWithImporterEntry.js, test/function/samples/resolveid-is-entry/resolutionWithImporterNonEntry.js, test/function/samples/resolveid-is-entry/resolutionWithoutImporter.js, test/function/samples/resolveid-is-entry/resolutionWithoutImporterEntry.js, test/function/samples/resolveid-is-entry/resolutionWithoutImporterNonEntry.js, test/utils.js
In the past, the way to detect if we are resolving an entry point in the `resolveId` hook was to check if the `importer` was `undefined`. However since we allowed to specify an `importer` in the `this.emitFile` hook, this check does not work in all cases any more.
This is problematic if you want to resolve entry points (and only those!) to proxies in a reliable manner.
This PR adds a new flag `isEntry` to the `resolveId` plugin hook to make this explicit. The same flag is also added to the `this.resolve` plugin context function. So resolving entries to plugins would now work like this:
```js
function onlyDefaultForEntriesPlugin() {
return {
name: 'only-default-for-entries',
async resolveId(source, …
```
=> Add isEntry flag to resolveId and this.resolve

src/utils/sanitizeFileName.ts, test/chunking-form/samples/sanitize-chunk-names/_config.js, test/chunking-form/samples/sanitize-chunk-names/_expected/amd/another-_slug_-_result.js, test/chunking-form/samples/sanitize-chunk-names/_expected/cjs/another-_slug_-_result.js, test/chunking-form/samples/sanitize-chunk-names/_expected/es/another-_slug_-_result.js, test/chunking-form/samples/sanitize-chunk-names/_expected/system/another-_slug_-_result.js
resolves #4222
context: https://github.com/nuxt/framework/issues/1494
This PR removes characters that are excluded from valid URLs (see [RFC 2396](https://datatracker.ietf.org/doc/html/rfc2396)). As rollup-produced files may be consumed by browsers, this is one approach to provide broader ecosystem safety without requiring URL encoding.
The context is [this issue](https://github.com/nuxt/framework/issues/1494). I'm aware we can simply sanitize downstream with [output.sanitizeFilename](https://rollupjs.org/guide/en/#outputsanitizefilename), but felt that RFC2396 might be a reasonable standards-based reasong for excluding these characters.
This PR also serves to solve the issue (solely replicable in ESM …
=> fix(utils): exclude invalid URL chars

build-plugins/esm-dynamic-import.ts, cli/run/commandPlugins.ts, cli/run/index.ts, cli/run/loadConfigFile.ts, cli/run/loadConfigFromCommand.ts, test/cli/samples/plugin/absolute-esm/_config.js, test/cli/samples/plugin/absolute-esm/_expected.js, test/cli/samples/plugin/absolute-esm/my-esm-plugin.mjs, test/cli/samples/plugin/advanced-esm/_config.js, test/cli/samples/plugin/advanced-esm/_expected/cjs.js, test/cli/samples/plugin/advanced-esm/_expected/es.js, test/cli/samples/plugin/advanced-esm/main.js, test/cli/samples/plugin/advanced-esm/node_modules/foo/index.js, test/cli/samples/plugin/advanced-esm/node_modules/print/index.js, test/cli/samples/plugin/advanced-esm/node_modules/rollup-plugin-esm-test/index.mjs, test/cli/samples/plugin/advanced-esm/node_modules/rollup-plugin-esm-test/package.json, test/cli/samples/plugin/advanced-esm/rollup.config.js, test/cli/samples/plugin/relative-esm/_config.js, test/cli/samples/plugin/relative-esm/_expected.js
n/a
Rollup presently only supports CJS plugins from the CLI via `--plugin`. This PR adds seamless ESM plugin support to the CLI. To maintain backwards compatibility rollup will still attempt to resolve the plugin via `require` first, and only upon error will it attempt to load the plugin via a dynamic `import()`. This is due to the different module resolution semantics of CJS and ESM modules in NodeJS.
The use of dynamic import to load ESM plugins works with Node v12+.  No rollup CLI functionality is lost on NodeJS versions that do not support loading ESM via dynamic `import`.
=> support loading ESM plugins from the CLI via `--plugin`

src/Chunk.ts, test/chunking-form/samples/emit-file/emit-chunk/_config.js, test/chunking-form/samples/emit-file/emit-chunk/_expected/amd/main.js, test/chunking-form/samples/emit-file/emit-chunk/_expected/cjs/main.js, test/chunking-form/samples/emit-file/emit-chunk/_expected/es/main.js, test/chunking-form/samples/emit-file/emit-chunk/_expected/system/main.js, test/chunking-form/samples/emit-file/emit-chunk/main.js
This PR addresses issues when using rollup for a project with `'` in the path, for example `/Users/Daniel's Projects/project/`. Although normal imports are escaped correctly, it seems that dynamic imports are treated differently and we need to escape them as well.
Context: https://github.com/nuxt/framework/issues/2192.
=> fix: escape dynamic import paths

.gitattributes, .github/workflows/tests.yml
If I remember correctly, this fixes git line breaks for all windows users, not just the ci.
=> ci: fix git line breaks on windows

rollup.config.ts, src/watch/fsevents-importer.ts
thanks @kzc for digging into this!
ref:
https://github.com/rollup/rollup/pull/4300#issuecomment-997159116
https://github.com/rollup/rollup/pull/4300#issuecomment-999031668
also took the liberty to convert `loadFsEvents` to an async function
=> fix: fsevents integration

.github/workflows/tests.yml
ref: https://github.com/rollup/rollup/pull/4300
=> ci: add macos to pipeline

docs/07-tools.md
=> Add Deno instructions to docs

test/cli/samples/wait-for-bundle-input-object/_config.js, test/cli/samples/wait-for-bundle-input/_config.js, test/cli/samples/watch/bundle-error/_config.js, test/cli/samples/watch/watch-config-early-update/_config.js, test/cli/samples/watch/watch-config-error/_config.js, test/cli/samples/watch/watch-config-initial-error/_config.js, test/cli/samples/watch/watch-config-no-update/_config.js, test/utils.js, test/watch/index.js
#4300
This attempts to follow ideas in https://github.com/rollup/rollup/pull/4300#issuecomment-1000907228 and others to stabilize the watch tests especially on MacOS.
=> Stabilize watch tests

cli/run/index.ts, src/utils/options/mergeOptions.ts, src/utils/options/options.ts, test/cli/samples/watch/no-watch-by-default/_config.js, test/cli/samples/watch/no-watch-by-default/main.js, test/cli/samples/watch/no-watch-by-default/rollup.config.js, test/cli/samples/watch/no-watch-by-default/wrapper.js
Resolves #3967
If someone specifies e.g. `rollup --no-watch.clearScreen` but not `--watch`, we should not watch.
=> Do not watch unless --watch is specified explicitly

src/utils/transform.ts
Typescript found another potential bug during the conversion:
```
[!] (plugin typescript) Error: @rollup/plugin-typescript TS2454: Variable 'curPlugin' is used before being assigned.
src/utils/transform.ts (156:25)
156   throwPluginError(err, curPlugin.name, { hook: 'transform', id });
```
which makes sense, since the assignment is not guaranteed in the `try` block, if the code throws anywhere prior.
=> refactor: convert utils.transform to async function

docs/02-javascript-api.md
Resolves #3955 
Include handling of multiple outputs and errors in example as suggested
=> Improve JS docs example

test/cli/index.js, test/cli/samples/watch/watch-config-early-update/_config.js, test/cli/samples/watch/watch-config-error/_config.js, test/utils.js
Most notably watch-config-early-update still fails sometimes.
=> More watch test stabilization

docs/05-plugin-development.md, docs/build-hooks.mmd, src/ModuleLoader.ts, src/rollup/types.d.ts, src/utils/PluginDriver.ts, src/utils/transform.ts, test/cli/samples/watch/watch-config-early-update/_config.js, test/incremental/index.js, test/utils.js
rollup/plugins#1038
Handling caching can be taxing when a plugin heavily relies on not only transforming in the `transform` hook but also uses the hook to gather data about a module that may affect how other modules are rendered (in the example of rollup/plugins#1038, a wrapped module needs to be imported differently from a "normal" module).
The proposed hook will be called after the `load` hook if a module has a cached copy. It will allow plugins to opt-in to transforming a cached module, basically discarding the cached copy if `true` is returned, as well as give access to a cached module's meta data.
@patak-dev, @antfu, @marvinhagemeister, @yyx990803 I suppose this new hook would not be relevant for …
=> Implement shouldTransformCachedModule hook

src/Module.ts, test/function/samples/reuse-resolve-meta/_config.js, test/function/samples/reuse-resolve-meta/main.js
When returning a meta object from a resolveId hook, Rollup would use this object as the meta property of a module. As it turned out, this is not only inconsistent with the `load` and `transform` hooks (where the object is merged shallowly) but also causes unexpected behaviour. E.g., the meta object returned from a `resolveId` hook can not be safely reused for other modules. But more importantly, it is unsafe to cache the return value of `this.resolve` as the associated `meta` property can change later on. This is fixed here.
The issue turned up in rollup/plugins#1038
=> Create a shallow copy when returning meta from resolveId

cli/logging.ts, cli/run/watch-cli.ts, test/cli/index.js, test/cli/samples/wait-for-bundle-input/_config.js, test/cli/samples/watch/no-config-file/_config.js, test/cli/samples/watch/node-config-file/_config.js, test/cli/samples/watch/watch-config-early-update/_config.js, test/cli/samples/watch/watch-config-error/_config.js, test/cli/samples/watch/watch-config-no-update/_config.js, test/utils.js
As there was another test failure on a branch, this one picks up a suggestion by @kzc to use `fs.fsync` to make sure an updated file is flushed to disk earlier.
=> Directly restart Rollup when config file change is detected

docs/05-plugin-development.md, src/ModuleLoader.ts, src/rollup/types.d.ts, test/function/samples/load-resolve-dependencies/_config.js, test/function/samples/load-resolve-dependencies/first.js, test/function/samples/load-resolve-dependencies/main.js, test/function/samples/load-resolve-dependencies/second.js, test/function/samples/load-resolve-dependencies/third.js
This is the third important addition I want to add to the plugin system around `this.load`. This will make it possible to load and analyze entire dependency sub-graphs from within a single plugin hook.
This PR adds a flag `resolveDependencies` to `this.load` that will make `this.load` wait until `importedIds` and `dynamicallyImportedIds` for the module in question have been resolved. Thus it is no longer necessary to wait for `moduleParsed` to get this information.
Note that I still think that the previous restriction of NOT waiting for this information is still a good default IMO because when waiting for this hook in `resolveId`, it is very easy to accidentally create a dead-lock where the hook waits …
=> Add "resolveDependencies" option to "this.load"

src/Chunk.ts, src/utils/addons.ts, src/utils/exportNames.ts
=> refactor: convert exportsByName object to map

cli/run/getConfigPath.ts, cli/run/index.ts, cli/run/loadConfigFile.ts, cli/run/watch-cli.ts
=> refactor: use fs.promises in cli/run, Part 1

browser/fs.ts, src/ModuleLoader.ts, src/utils/fs.ts, test/function/samples/max-parallel-file-reads-default/_config.js, test/function/samples/max-parallel-file-reads-error/_config.js, test/function/samples/max-parallel-file-reads-infinity/_config.js, test/function/samples/max-parallel-file-reads-set/_config.js, test/function/samples/max-parallel-file-reads-with-plugin/_config.js
=> refactor: use fs.promises in module loader, Part 2

test/form/samples/side-effects-parameter-defaults/_config.js
=> Fix typo in _config.js

src/utils/pureComments.ts, typings/declarations.d.ts
`base` is defined in `acorn-walk` module
=> refactor: remove acorn-walk ambient type definitions

src/Bundle.ts, test/chunking-form/samples/manual-chunks-function/_config.js, test/chunking-form/samples/manual-chunks-function/_expected/amd/generated-chunk-b.js, test/chunking-form/samples/manual-chunks-function/_expected/amd/main-a.js, test/chunking-form/samples/manual-chunks-function/_expected/cjs/generated-chunk-b.js, test/chunking-form/samples/manual-chunks-function/_expected/cjs/main-a.js, test/chunking-form/samples/manual-chunks-function/_expected/es/generated-chunk-b.js, test/chunking-form/samples/manual-chunks-function/_expected/es/main-a.js, test/chunking-form/samples/manual-chunks-function/_expected/system/generated-chunk-b.js, test/chunking-form/samples/manual-chunks-function/_expected/system/main-a.js, test/chunking-form/samples/manual-chunks-function/dep2-a.js, test/chunking-form/samples/manual-chunks-function/dep2-b.js, test/chunking-form/samples/manual-chunks-function/dep3-a.js, test/chunking-form/samples/manual-chunks-function/dep3-b.js, test/chunking-form/samples/manual-chunks-function/main-a.js
Resolves #4394
If a manual chunk function is used, this enforces a sorting order of the generated manual chunks by chunk name to avoid e.g. unintended hash changes.
=> Sort manual chunks generated via a function by name

src/Module.ts
=> refactor: module exports to map

test/function/samples/custom-module-options/_config.js, test/function/samples/deprecated/manual-chunks-info/_config.js, test/function/samples/deprecated/resolve-id-external/_config.js, test/function/samples/deprecated/resolve-id/_config.js, test/function/samples/manual-chunks-info/_config.js, test/function/samples/max-parallel-file-reads-default/_config.js, test/function/samples/max-parallel-file-reads-infinity/_config.js, test/function/samples/max-parallel-file-reads-set/_config.js, test/function/samples/max-parallel-file-reads-with-plugin/_config.js, test/function/samples/module-side-effects/resolve-id-external/_config.js, test/function/samples/module-side-effects/resolve-id/_config.js, test/function/samples/plugin-module-information/_config.js, test/function/samples/preload-module/_config.js, test/incremental/index.js
There were still some cases where module ids in tests were not properly ordered. This fixes this by using objects instead of arrays in some places, which also improves readability.
=> Improve test stability by getting independent of module id ordering in more places

src/Graph.ts, src/Module.ts
=> refactor: use map for import descriptions + re-export descriptions

docs/05-plugin-development.md, docs/build-hooks.mmd
When working on caching the commonjs plugin, I found that it is not documented that caching will not only skip the `load` hook but also the `resolveId` hook of dependencies (which does indeed save a lot).
=> Document how resolveId is cached

src/ExternalModule.ts, src/Module.ts
=> refactor: use map for declarations and name suggestions

browser/path.ts, cli/run/index.ts, docs/05-plugin-development.md, src/Chunk.ts, src/finalisers/iife.ts, src/utils/getExportMode.ts, src/utils/options/mergeOptions.ts, src/utils/path.ts, src/watch/watch.ts, test/browser/index.js, test/chunking-form/index.js, test/cli/samples/external-modules-auto-global/_config.js, test/cli/samples/external-modules/_config.js, test/form/index.js, test/function/samples/function-directive-not-first/_config.js, test/function/samples/member-expression-assignment-in-function/_config.js, test/function/samples/preload-cyclic-module/_config.js, test/function/samples/relative-external-include-once-two-external/_config.js, test/function/samples/transparent-dynamic-inlining/_config.js, test/misc/iife.js, test/misc/umd.js, test/sourcemaps/samples/existing-external-sourcemaps-combined/_config.js, test/sourcemaps/samples/existing-inline-sourcemaps-combined/_config.js, test/utils.js
=> refactor: use includes where appropriate

package.json
Added Typescript 4.5+ Support for nodenext and node12 resolve it will not lookup typings
If we do not apply this changes users of Typescript 4.5 with moduleResolution nodenext and node12 will not be able to get typings
=> chor: feature: bugfix: Add Typescript 4.5 nodenext node12 module resolution support

src/Module.ts, test/function/samples/recursive-reexports/_config.js, test/function/samples/recursive-reexports/main.js, test/function/samples/recursive-reexports/other.js
=> refactor: use map for namespace reexports by name

docs/05-plugin-development.md, src/Module.ts, src/ModuleLoader.ts, src/rollup/types.d.ts, test/function/samples/plugin-error-should-transform/_config.js, test/function/samples/plugin-error-should-transform/main.js, test/incremental/index.js
rollup/plugins#1038
Another small addition to finalize the new commonjs plugin. In order to figure out if cached resolved ids changed, I need to add them to the shouldTransformCachedModule hook.
=> Add resolved sources to shouldTransformCachedModule

cli/run/batchWarnings.ts, cli/run/index.ts, cli/run/timings.ts, src/Bundle.ts, src/Chunk.ts, src/ExternalModule.ts, src/Module.ts, src/ModuleLoader.ts, src/ast/nodes/MetaProperty.ts, src/ast/values.ts, src/rollup/rollup.ts, src/utils/FileEmitter.ts, src/utils/PluginContext.ts, src/utils/PluginDriver.ts, src/utils/hookActions.ts, src/utils/options/normalizeOutputOptions.ts, src/utils/relativeId.ts, src/utils/renderNamePattern.ts, src/watch/watch.ts
=> refactor: some code and type fixes

src/ast/nodes/shared/knownGlobals.ts
=> feat: add object-known-globals

browser/hookActions.ts, src/rollup/rollup.ts, src/utils/PluginDriver.ts, src/utils/hookActions.ts, test/cli/samples/unfulfilled-hook-actions-error/_config.js, test/cli/samples/unfulfilled-hook-actions-error/build.mjs, test/cli/samples/unfulfilled-hook-actions-manual-exit/_config.js, test/cli/samples/unfulfilled-hook-actions-manual-exit/a.js, test/cli/samples/unfulfilled-hook-actions-manual-exit/b.js, test/cli/samples/unfulfilled-hook-actions-manual-exit/c.js, test/cli/samples/unfulfilled-hook-actions-manual-exit/index.js, test/cli/samples/unfulfilled-hook-actions-manual-exit/rollup.config.js, test/cli/samples/unfulfilled-hook-actions/_config.js, test/utils.js
Resolves #4432
By using the `beforeExit` event, this PR solves a key issue with the previous implementation to track unfinished hook actions: They are now reported as regular errors. That means that
* There are no unexpected prints to the console if used from a script
* Regular error formatting logic kicks in, especially when used from custom scripts
* There is no longer any global state, but unfinished actions are tracked per build
* There is no unexpected output when the build is manually aborted via `process.exit()`
=> Track unfinished hook actions as regular errors

package.json
This PR allows to use all files in the dist folder if they get imported directly this is needed to allow custom builds and do some code reuse.
my current usecase is a file called: 
rollup.build.js
```js
// here i need to reimplement or access the function to normalizeOptions that i get back from the rollup.config.js
// see: https://github.com/rollup/rollup/issues/4441
```
- https://github.com/rollup/rollup/issues/4441
=> chor(package.json): unlock dist in exports for programatical code reuse without patching rollup

cli/run/loadConfigFile.ts
tsc Version 4.7.0-dev.20220305
```
cli/run/loadConfigFile.ts:114:4 - error TS2722: Cannot invoke an object which is possibly 'undefined'.
114    defaultLoader(module, requiredFileName);
~~~~~~~~~~~~~
```
Newer Typescript versions will error on build i marked that this includes tests as running typescript nightly already is the test.
=> Fix: tsc did not build

docs/07-tools.md
according to the documentation. I use the `customResolveOptions.moduleDirectory` option, but I get the following warning:
`(!) Plugin node-resolve: node-resolve: The 'customResolveOptions.moduleDirectory' option has been deprecated. Use 'moduleDirectories', which must be an array.`
I think this will also need to update the document.
=> docs: update deprecated option in tools.md

.github/ISSUE_TEMPLATE/bug.yaml
https://github.com/rollup/plugins/pull/1171
All links on git.io will stop redirecting after April 29, 2022: https://github.blog/changelog/2022-04-25-git-io-deprecation/
Replace the `git.io` link with its actual URL.
=> chore(repo): replace `git.io` in the issue template

docs/02-javascript-api.md, package.json
Resolves #4460
As we explicitly state that you can require `loadConfigFile` without extension in the docs, this will add an explicit exports route for this.
In preparation for the next major release where I would like to remove that hack again, `loadConfigFile` can now directly be imported as `rollup/loadConfigFile` as well.
=> Add exports exception for loadConfigFile

src/ast/variables/LocalVariable.ts, test/function/samples/track-reassignments/_config.js, test/function/samples/track-reassignments/main.js, test/function/samples/track-reassignments/patchEventTarget.js
Resolves #4468
This one seemed quite the mystery bug. It seemed code was removed when you arranged things "just the right way". Turns out, the logic to prevent infinite recursions for assignment tracking was accidentally sharing an object with the same logic for property accesses, with the effect that an earlier property access could tell the system that an assignment had no effect even though it had.
=> Fix reassignment tracking

src/ast/nodes/shared/ObjectEntity.ts, test/form/samples/deoptimize-superclass/_config.js, test/form/samples/deoptimize-superclass/_expected.js, test/form/samples/deoptimize-superclass/main.js
We do not want to deoptimize the entire super class when adding a property, it is enough to deoptimize just properties of the given path (actually in a manner of speaking we may not need to deoptimize at all but deoptimization is a more general concept than reassignment and there may be some edge cases we need to cover).
Following a discussion in Twitter https://twitter.com/pschroen/status/1522269915864256512?s=20&t=8igcqT2KuKkLKgGP3hjvVA, see https://rollupjs.org/repl/?version=2.71.1&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNsYXNzJTIwRm9vJTIwJTdCJTdEJTVDbiU1Q24lMkYlMkYlMjB0cnklMjByZW1vdmluZyUyMHRoaXMlMjBwcm90b3R5cGUlMjBwcm9wZXJ0eSU1Q25Gb28 …
=> Do not deoptimize entire super class when adding a property

docs/01-command-line-reference.md
The documentation gives examples for using `@rollup/plugin-typescript` to parse the Rollup configuration file, with a CLI code example. However, that example will fail to build with a somewhat misleading error if the Rollup config is not declared in the `tsconfig.json`'s `include` property, so a note about needing to do so has been added with this commit.
For an example of the error I'm referring to, here is what happened to me:
```
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
rollup.config.ts (5:13)
3: import del from "rollup-plugin-delete";
4:
5: const options: RollupOptions = {
^
6:   input: "src/index.ts",
7:   output: [
Error: Unexpected token …
```
=> Update docs for --configPlugin using typescript

cli/run/loadConfigFile.ts, test/cli/samples/config-cwd-case-insensitive-es6/_config.js, test/cli/samples/config-cwd-case-insensitive-es6/main.js, test/cli/samples/config-cwd-case-insensitive-es6/rollup.config.js
resolves #3949
#4260
#4439
#4440
#4446
resolves #4465
The `loadConfigFromBundledFile` function patches the default `require` algorithm for the `fileName` file. It replaces the [require.extensions](https://nodejs.org/api/modules.html#requireextensions) handler for it. In certain scenarios the file name parameter value in the `require.extensions` handler differs from the required file name (for example for symlinked files). The #3783 fix processed this by preparing the input file name before comparation. It uses the [fsPromises.realpath](https://nodejs.org/api/fs.html#fspromisesrealpathpath-options) function for it. The problem is that the `fsPromises.realpath` result and the file name in the …
=> fix: config path problem on windows

src/utils/hookActions.ts
This avoids the warning about exceeding maxListeners for the `beforeExit` event by using a single event listener that re-emits the event on a local emitter with unlimited listeners.
=> Avoid maximum listeners exceeded warning

src/Chunk.ts, src/Module.ts, test/function/samples/dynamic-imports-shared-exports/_config.js, test/function/samples/dynamic-imports-shared-exports/_expected/amd/generated-dynamic1.js, test/function/samples/dynamic-imports-shared-exports/_expected/amd/generated-dynamic2.js, test/function/samples/dynamic-imports-shared-exports/_expected/amd/main.js, test/function/samples/dynamic-imports-shared-exports/_expected/cjs/generated-dynamic1.js, test/function/samples/dynamic-imports-shared-exports/_expected/cjs/generated-dynamic2.js, test/function/samples/dynamic-imports-shared-exports/_expected/cjs/main.js, test/function/samples/dynamic-imports-shared-exports/_expected/es/generated-dynamic1.js, test/function/samples/dynamic-imports-shared-exports/_expected/es/generated-dynamic2.js, test/function/samples/dynamic-imports-shared-exports/_expected/es/main.js, test/function/samples/dynamic-imports-shared-exports/_expected/system/generated-dynamic1.js, test/function/samples/dynamic-imports-shared-exports/_expected/system/generated-dynamic2.js, test/function/samples/dynamic-imports-shared-exports/_expected/system/main.js, test/function/samples/dynamic-imports-shared-exports/dynamic1.js, test/function/samples/dynamic-imports-shared-exports/dynamic2.js, test/function/samples/dynamic-imports-shared-exports/main.js, test/function/samples/dynamic-imports-shared-exports/shared.js, test/function/samples/dynamic-imports-shared-exports/sharedDynamic.js
Resolves #4490
This fixes an issue where namespaces in dynamic chunks were not referencing reexports correctly because imports were missing. See #4490 for the issue.
The problem was that the logic to make reexported variables available was run before facades were generated, and facade generation could add additional namespaces to the module.
=> Ensure reexports are available for namespaces

cli/run/batchWarnings.ts, docs/08-troubleshooting.md, src/finalisers/shared/warnOnBuiltins.ts, test/cli/samples/warn-multiple/_config.js, test/misc/misc.js
Resolves #4469 
Resolves #4388
Resolves #4346
Resolves #4032
This updates the links to the abandoned `snowpackjs/rollup-plugin-polyfill-node` and replaces it with the at least fundamentally maintained [FredKSchott/rollup-plugin-polyfill-node](https://github.com/FredKSchott/rollup-plugin-polyfill-node). See linked issues.
=> Update link to node polyfill repo

src/ast/nodes/ArrowFunctionExpression.ts, src/ast/nodes/shared/FunctionBase.ts, src/ast/nodes/shared/FunctionNode.ts, test/function/samples/parameter-defaults/function-as-default/_config.js, test/function/samples/parameter-defaults/function-as-default/main.js
Resolves #4514
Currently, we do not deoptimize parameter default values, which means we do not track deoptimizations or calls. This fixes it. See the linked issue for an example.
=> Ensure parameter defaults are deoptimized

src/ast/nodes/CallExpression.ts, src/ast/nodes/LogicalExpression.ts, src/ast/nodes/NewExpression.ts, src/utils/renderCallArguments.ts, test/form/samples/side-effect-es5-classes/_expected.js, test/function/samples/unused-constructor-argument-fallback/_config.js, test/function/samples/unused-constructor-argument-fallback/main.js
Resolves #4517
Turns out that while unused arguments of new expressions were not included, they were still rendered, which was causing issues for certain types of arguments like logical expressions. This is fixed here. As a result, unused arguments of new expressions at the end of the call are now removed, just like unused arguments of call expressions.
=> Try to make logical expression deoptimization more robust

.github/workflows/tests.yml, codecov.yml
To make the deprecation of Node 10 and Node 12 easier, this changes the Node CI versions so that each platform includes Node 14 and Node 18
=> Adapt Node versions on CI to prepare for v3

src/utils/PluginDriver.ts, test/form/samples/runs-output-plugins-last/_config.js, test/form/samples/runs-output-plugins-last/_expected.js, test/form/samples/runs-output-plugins-last/main.js, test/function/samples/options-in-renderstart/_config.js
- #3845 
Output plugins will run after input plugins.
Technically a breaking change, but it wasn't documented, so maybe it could be released in a patch version?
=> [v3.0] Run output plugins last

cli/run/commandPlugins.ts, test/cli/samples/plugin/absolute-esm/_config.js, test/cli/samples/plugin/absolute-esm/main.js, test/cli/samples/plugin/absolute/_config.js, test/cli/samples/plugin/absolute/main.js
Plugins can only be specified as package names or relative paths on the command line. This doesn't meet my requirements. When using rollup packaged in my tool application, I need to specify the absolute installation path of a plugin. No other solution will work for me.
I have verified that this change satisfies this requirement in my local installed copy of the code. I don't have any environment for TypeScript or rollup development, so I can only provide the backport of my patched JavaScript source code. I'm unable to provide anything more than this. It's a trivial change though and should be easy to review.
If necessary, I can try to locate the relevant documentation in this repository and update it, …
=> Add support for absolute plugin paths

src/ast/nodes/CallExpression.ts, src/ast/nodes/shared/MultiExpression.ts, test/form/samples/builtin-prototypes/literal/_expected.js, test/form/samples/builtin-prototypes/literal/main.js, test/form/samples/builtin-prototypes/template-literal/_expected.js, test/form/samples/builtin-prototypes/template-literal/main.js, test/form/samples/return-after-error/_config.js, test/form/samples/return-after-error/_expected.js, test/form/samples/return-after-error/main.js, test/function/samples/class-prop-returns/_config.js, test/function/samples/class-prop-returns/main.js, test/function/samples/conditionals-deoptimization/_config.js, test/function/samples/conditionals-deoptimization/main.js, test/function/samples/long-path-deopt/_config.js, test/function/samples/long-path-deopt/main.js
Resolves #4542 
When a function contains a return expression after an error, the argument of this return would be included even though it is unused in the final bundle. This is fixed here.
=> Do not include unused return expressions

LICENSE.md, cli/run/loadConfigFile.ts, docs/01-command-line-reference.md, docs/999-big-list-of-options.md, package-lock.json, package.json, scripts/perf-init.js, scripts/perf.js, test/cli/samples/config-no-module/_config.js, test/cli/samples/config-no-module/rollup.config.js, test/cli/samples/config-type-module/_config.js, test/cli/samples/config-type-module/sub/main.js, test/cli/samples/config-type-module/sub/package.json, test/cli/samples/config-type-module/sub/rollup.config.js, typings/declarations.d.ts
- #4055 
- closes #4123 
This PR supersedes #4123 as unfortunately the original author removed their branch before the PR was merged.
It changes the logic in the following way:
* I reduced the cases to "transpile or use import()" where the logic is
* We transpile (to CommonJS) if config plugins are used (because then we MUST transpile) or if the extension is .js and the type is not explicitly "module". The reason we transpile the latter is because there is a huge number of "legacy" code bases that use an ES module for Rollup's config file without setting "type": "module", and I would want to avoid the churn. We could consider warning in that case, though, but I am undecided. Thoughts?
* Otherwise we …
=> [v3.0] Better esm config file support

src/utils/options/normalizeInputOptions.ts, test/function/samples/deprecated/max-parallel-file-reads/infinity/_config.js, test/function/samples/deprecated/max-parallel-file-reads/set/_config.js, test/function/samples/deprecated/max-parallel-file-reads/with-plugin/_config.js, test/misc/sanity-checks.js
Actually show a deprecation warning when `maxParallelFileReads` is used (that prompts the user to use `maxParallelFileOps`).
=> [v3.0] Fully deprecate maxParallelFileReads

src/Bundle.ts, src/Chunk.ts, src/Graph.ts, src/Module.ts, src/ModuleLoader.ts, src/rollup/rollup.ts, src/utils/renderChunks.ts, src/utils/timers.ts
This restructures some aspects of the timings displayed when running `rollup --perf`.
* The measuring points now better reflect the new algorithm
* async plugin hook time is no longer measured as those numbers were always completely misleading anyway
* ALL plugin hooks are measured, not just a small selection
=> [v3.0] Restructure perf timings

.eslintrc.js, src/ast/nodes/ImportExpression.ts, test/cli/node_modules_rename_me/bar/lib/config.js, test/cli/node_modules_rename_me/rollup-config-foo/lib/config.js, test/misc/misc.js, test/typescript/index.ts
- Resolves #4586
- Resolves #4415
- Resolves vitejs/vite#9310
The problem was that when Rollup generated an output with `inlineDynamicImports: true`, it would leave a flag on the (shared) ImportExpression AST node that would mark it is `inlined` which would not be removed for the next output. The result was that for the next output, the import would be rendered both as "inlined" and as "non-inlined", resulting in an error. The fix was indeed simple.
Admittedly, the state handling behind this is not ideal, but resolving this is a much bigger topic for another time.
=> Handle generating outputs with non-inlined dynamic imports after inlined ones

.github/workflows/repl-artefacts.yml, .gitignore, package.json
This is a small change to the CI process for Rollup 2 so that the Rollup 3 browser build is able to generate REPL artifacts on CI even before Rollup 3 is on master.
=> Change REPL artefact generation so that browser build will work on CI

docs/01-command-line-reference.md
- Ports doc changes from #4572 and #4583 to the 3.0 branch.
- Shortened some code examples to focus on the relevant parts (hope that's ok)
- The changes from #4584 have _not_ been ported. I expect they will get picked up in a merge with `master`.
=> Port doc changes from #4572 and #4583 to 3.0

src/utils/identifierHelpers.ts, test/function/samples/escape-arguments/_config.js, test/function/samples/escape-arguments/arguments.js, test/function/samples/escape-arguments/main.js
Resolves #4612
While "arguments" is not a reserved word in JavaScript, it cannot be used for declaring variables in strict mode, so this adds some special logic to prevent this.
=> Prevent using "arguments" for generated variable names

test/form/samples/quote-id/_config.js
Don't know if this is the right fix?
Failure looks like:
```
1) rollup
form
quote-id: handles escaping for external ids
generates amd:
AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected ... Lines skipped
"define(['quoted\\'\\\r\\\n" +
+   "\\ \\ external1', './C:/code/others/rollup/test/form/samples/quote-id/quoted\\'\\\r\\\n" +
-   "\\ \\ external1', './quoted\\'\\\r\\\n" +
"\\ \\ external2', './C:/File/Path'], (function (quoted_____external1, quoted_____external2, Path_js) { 'use strict';\n" +
...
'\tconsole.log(quoted_____external1.foo, quoted_____external2.bar, Path_js.baz);\n' +
'\n' +
'}));'
+ expected - actual
\      define(['quoted\'\
\ …
```
=> Fix test/form/samples/quote-id on Windows

docs/02-javascript-api.md, src/Graph.ts, src/rollup/types.d.ts, src/watch/WatchEmitter.ts, src/watch/watch.ts, test/watch/index.js
This replaces the watch emitter, that used to be based on a NodeJS event emitter, with a custom implementation that allows the user to return a Promise from any listener to make Rollup wait at that stage before continuing.
=> [v3.0] Custom awaiting watch emitter

cli/help.md, docs/01-command-line-reference.md, docs/999-big-list-of-options.md, src/Chunk.ts, src/finalisers/amd.ts, src/finalisers/shared/addJsExtension.ts, src/finalisers/shared/removeExtensionFromRelativeAmdId.ts, src/finalisers/shared/updateExtensionForRelativeAmdId.ts, src/finalisers/umd.ts, src/rollup/types.d.ts, src/utils/options/normalizeOutputOptions.ts, test/form/samples/amd-keep-extension/_config.js, test/form/samples/amd-keep-extension/_expected/amd.js, test/form/samples/amd-keep-extension/_expected/cjs.js, test/form/samples/amd-keep-extension/_expected/es.js, test/form/samples/amd-keep-extension/_expected/iife.js, test/form/samples/amd-keep-extension/_expected/system.js, test/form/samples/amd-keep-extension/_expected/umd.js, test/form/samples/amd-keep-extension/bar.js, test/form/samples/amd-keep-extension/main.js, test/function/samples/output-options-hook/_config.js
=> feat: add option to keep extensions for amd

.github/workflows/repl-artefacts.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
=> GitHub Workflows security hardening

src/Bundle.ts, src/Chunk.ts, src/rollup/rollup.ts, src/rollup/types.d.ts, src/utils/FileEmitter.ts, src/utils/PluginDriver.ts, src/utils/outputBundle.ts, src/utils/renderNamePattern.ts, test/function/samples/generate-bundle-mutation/_config.js, test/function/samples/generate-bundle-mutation/main.js
- resolves #4642 
When creating many chunks (> 1000), the name collision check for case-insensitive file systems was exploding, leading to terrible performance. This is solved by using a proxy to build a lower-case looking table for file names as the bundle is created.
=> Improve performance of chunk naming collision check

tsconfig.json
https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping
Transpiled code should get smaller (nullish coalescing, optional chaining) and run at native speed.
=> [v3.0] use compiler target ES2020

package.json
remove lint:js:nofix script redundancy options.
the `lint:nofix`script does not contain `--fix` options
=> fix: remove lint:js:nofix script redundancy options

src/ast/nodes/VariableDeclaration.ts, test/function/samples/for-loop-parameter/_config.js, test/function/samples/for-loop-parameter/main.js, test/watch/index.js
- resolves #4654
There were cases where in a declaration `let { x } = y`, `y` would not be included. This can result in invalid code or broken, which is hereby fixed.
=> Ensure the initializer of a destructuring declaration is always included if the id is included

src/rollup/rollup.ts, src/utils/options/mergeOptions.ts, src/utils/options/normalizeInputOptions.ts, src/utils/options/normalizeOutputOptions.ts, src/utils/options/options.ts
Enhance types of internal functions, stricter.
=> refactor: improve types

src/ast/nodes/ArrowFunctionExpression.ts, src/ast/nodes/NewExpression.ts, src/ast/nodes/TaggedTemplateExpression.ts, src/ast/nodes/TemplateLiteral.ts, src/ast/nodes/shared/FunctionBase.ts, src/ast/nodes/shared/FunctionNode.ts
=> refactor: merge duplicate imports

docs/09-migration.md
List any relevant issue numbers: no
I think this is the correct change, I assume it was meant to be "no longer" instead of "now longer"
=> docs: fix minor typo in migration documentation

src/rollup/rollup.ts, test/function/samples/nested-plugin/_config.js
I was missing some places of the normalizing plugins before.
=> fix: nested plugin in options stage

src/ast/nodes/ClassDeclaration.ts, src/ast/nodes/VariableDeclarator.ts, test/chunking-form/samples/circular-entry-points/_expected/amd/generated-main1.js, test/chunking-form/samples/circular-entry-points/_expected/cjs/generated-main1.js, test/chunking-form/samples/circular-entry-points/_expected/es/generated-main1.js, test/chunking-form/samples/circular-entry-points/_expected/system/generated-main1.js, test/chunking-form/samples/circular-entry-points2/_expected/amd/main2.js, test/chunking-form/samples/circular-entry-points2/_expected/cjs/main2.js, test/chunking-form/samples/circular-entry-points2/_expected/es/main2.js, test/chunking-form/samples/circular-entry-points2/_expected/system/main2.js, test/chunking-form/samples/circular-entry-points3/_expected/amd/generated-main1.js, test/chunking-form/samples/circular-entry-points3/_expected/cjs/generated-main1.js, test/chunking-form/samples/circular-entry-points3/_expected/es/generated-main1.js, test/chunking-form/samples/circular-entry-points3/_expected/system/generated-main1.js, test/form/samples/exported-class-declaration-conflict/_config.js, test/form/samples/exported-class-declaration-conflict/_expected/amd.js, test/form/samples/exported-class-declaration-conflict/_expected/cjs.js, test/form/samples/exported-class-declaration-conflict/_expected/es.js, test/form/samples/exported-class-declaration-conflict/_expected/iife.js, test/form/samples/exported-class-declaration-conflict/_expected/system.js, test/form/samples/exported-class-declaration-conflict/_expected/umd.js, test/form/samples/exported-class-declaration-conflict/first.js, test/form/samples/exported-class-declaration-conflict/main.js, test/form/samples/exported-class-declaration-conflict/second.js, test/function/samples/class-name-conflict/_config.js, test/function/samples/class-name-conflict/declaration1.js, test/function/samples/class-name-conflict/declaration2.js, test/function/samples/class-name-conflict/expression1.js, test/function/samples/class-name-conflict/expression2.js, test/function/samples/class-name-conflict/main.js
- Resolves #4637
This PR preserves the `name` property of classes even if the class needs to be renamed due to conflicts. The solution is to rewrite both `class foo {}` and `let foo = class {}` to e.g. `let foo$1 = class foo {}` if `foo` needs to be renamed.
=> Preserve rendered class names

src/Chunk.ts, src/Graph.ts, src/ModuleLoader.ts, src/rollup/types.d.ts, src/utils/options/mergeOptions.ts, src/utils/options/normalizeInputOptions.ts, src/utils/options/normalizeOutputOptions.ts, src/utils/renderChunks.ts
=> refactor: improve & simplify types

src/ast/nodes/Program.ts, test/form/samples/hashbang/_config.js, test/form/samples/hashbang/_expected.js, test/form/samples/hashbang/main.js, test/form/samples/hashbang/other.js
- Resolves #4672
This supports hashbang comments in input files by adjusting the rendering so they are always removed. In the future, it could be an interesting idea to preserve them in entry points for certain output formats, but I will postpone this investigation for another day. For now if you want a hashbang in your output, add it in a `renderChunk` hook.
=> Ignore hashhbang comments

src/ast/variables/NamespaceVariable.ts, test/function/samples/namespace-literal-value/_config.js, test/function/samples/namespace-literal-value/main.js, test/function/samples/namespace-literal-value/namespace.js
- resolves #4680
For some reason, I assumed the logic to retrieve explicit values from namespaces would only be relevant for `Symbol.toStringTag`. No idea why I thought that, here is the fix.
=> Return correct values for unkown namespace members

build-plugins/get-banner.ts, src/Chunk.ts, src/ast/nodes/MetaProperty.ts, test/chunking-form/samples/import-meta-numeric-paths/0/1/nested.js, test/chunking-form/samples/import-meta-numeric-paths/_config.js, test/chunking-form/samples/import-meta-numeric-paths/_expected/amd/0/1/nested.js, test/chunking-form/samples/import-meta-numeric-paths/_expected/amd/main.js, test/chunking-form/samples/import-meta-numeric-paths/_expected/cjs/0/1/nested.js, test/chunking-form/samples/import-meta-numeric-paths/_expected/cjs/main.js, test/chunking-form/samples/import-meta-numeric-paths/_expected/es/0/1/nested.js, test/chunking-form/samples/import-meta-numeric-paths/_expected/es/main.js, test/chunking-form/samples/import-meta-numeric-paths/_expected/system/0/1/nested.js, test/chunking-form/samples/import-meta-numeric-paths/_expected/system/main.js, test/chunking-form/samples/import-meta-numeric-paths/main.js, test/cli/samples/watch/clearScreen/wrapper.js, test/cli/samples/watch/no-clearScreen-command/wrapper.js, test/cli/samples/watch/no-clearScreen/wrapper.js, test/cli/samples/watch/no-watch-by-default/wrapper.js, test/cli/samples/watch/watch-event-hooks-error/wrapper.js, test/cli/samples/watch/watch-event-hooks/wrapper.js
- resolves #4681
Ensure that backslashes are converted to slashes when preserving modules. Ensure that filenames are properly escaped when using `import.meta.url`.
=> Use correct import.meta.url slashes on Windows

src/ast/nodes/ClassDeclaration.ts, src/ast/nodes/VariableDeclarator.ts, src/ast/scopes/ChildScope.ts, src/ast/variables/Variable.ts, src/utils/deconflictChunk.ts, src/utils/safeName.ts, test/function/samples/class-name-conflict2/_config.js, test/function/samples/class-name-conflict2/bar.js, test/function/samples/class-name-conflict2/declaration.js, test/function/samples/class-name-conflict2/expression.js, test/function/samples/class-name-conflict2/foo.js, test/function/samples/class-name-conflict2/main.js
- Resolves #4696
In #4674, we introduced a logic that would rewrite classes to have an id so that in case of name conflicts, they would retain the correct `class.name`. Unfortunately, this could lead to shadowed variables because the name of this new id was not considered when deconflicting variable names. This is now fixed.
=> Prevent class ids from shadowing other variables

src/ast/nodes/shared/knownGlobals.ts, test/form/samples/big-int/_config.js, test/form/samples/object-freeze-effects/_config.js, test/form/samples/object-freeze-effects/_expected.js, test/form/samples/object-freeze-effects/main.js
- See https://github.com/rollup/rollup/issues/4327#issuecomment-1321482349
This will change the side effect logic used for `Object.freeze` to be similar to the logic we currently use for `Object.defineProperty`: If the argument or return value is used, it is included in the bundle, otherwise it is removed. Also, we assume that the argument is deoptimized, i.e. all properties are treated as "unknown" after being passed to that function.
=> Only consider Object.freeze a side effect if the argument is used

src/Chunk.ts, src/utils/FileEmitter.ts, src/utils/renderChunks.ts, test/function/samples/emit-chunk-hash/_config.js, test/function/samples/emit-chunk-hash/emitted.js, test/function/samples/emit-chunk-hash/main.js
- resolves #4744
I completely forgot about `this.getFileName` with the new hashing logic. Now you get the file name with the hash instead of the placeholder in `generateBundle`.
=> Provide hashed file name when using this.getFileName in generateBundle

src/ast/nodes/Literal.ts, src/ast/values.ts, test/form/samples/builtin-prototypes/check-tree-shake-on-regexp-if-it-is-used/_config.js, test/form/samples/builtin-prototypes/check-tree-shake-on-regexp-if-it-is-used/_expected.js, test/form/samples/builtin-prototypes/check-tree-shake-on-regexp-if-it-is-used/main.js, test/form/samples/builtin-prototypes/literal/_expected.js, test/form/samples/builtin-prototypes/literal/main.js
=> fix: check whether RegExp have the global or sticky flags set

cli/logging.ts, test/cli/samples/custom-frame-with-pos/_config.js, test/cli/samples/custom-frame/_config.js, test/cli/samples/watch/bundle-error/_config.js
=> feat: simplify `stack` info in cli error

docs/08-troubleshooting.md
=> docs: update outdated info

src/utils/FileEmitter.ts, test/function/samples/emit-chunk-manual-asset-source/_config.js, test/function/samples/emit-chunk-manual-asset-source/main.js, test/function/samples/emit-chunk-manual-asset-source/manual.js, test/function/samples/emit-chunk-manual/_config.js, test/function/samples/emit-chunk-manual/main.js, test/function/samples/emit-chunk-manual/manual.js
- resolves #4746
This changes the logic for emitting files to handle files emitted during output generation phase via a transform hooks that is triggered for the first time by the `manualChunks` option of that output. This may not be exactly what users expect, but it is difficult to differentiate legitimate uses of the file emitter from illegitimate uses, especially with new features in the pipeline.
As a follow-up, it would be worthwhile to add a way for assets to obey tree-shaking in so far that assets that are never referenced are not emitted.
=> Support emitting files via manualChunks in output

src/Chunk.ts, test/chunking-form/samples/preserve-modules-namespace-reexport-reexport/_config.js, test/chunking-form/samples/preserve-modules-namespace-reexport-reexport/_expected/amd/dep.js, test/chunking-form/samples/preserve-modules-namespace-reexport-reexport/_expected/amd/main.js, test/chunking-form/samples/preserve-modules-namespace-reexport-reexport/_expected/amd/reexport.js, test/chunking-form/samples/preserve-modules-namespace-reexport-reexport/_expected/cjs/dep.js, test/chunking-form/samples/preserve-modules-namespace-reexport-reexport/_expected/cjs/main.js, test/chunking-form/samples/preserve-modules-namespace-reexport-reexport/_expected/cjs/reexport.js, test/chunking-form/samples/preserve-modules-namespace-reexport-reexport/_expected/es/dep.js, test/chunking-form/samples/preserve-modules-namespace-reexport-reexport/_expected/es/main.js, test/chunking-form/samples/preserve-modules-namespace-reexport-reexport/_expected/es/reexport.js, test/chunking-form/samples/preserve-modules-namespace-reexport-reexport/_expected/system/dep.js, test/chunking-form/samples/preserve-modules-namespace-reexport-reexport/_expected/system/main.js, test/chunking-form/samples/preserve-modules-namespace-reexport-reexport/_expected/system/reexport.js, test/chunking-form/samples/preserve-modules-namespace-reexport-reexport/dep.js, test/chunking-form/samples/preserve-modules-namespace-reexport-reexport/main.js, test/chunking-form/samples/preserve-modules-namespace-reexport-reexport/reexport.js, test/chunking-form/samples/preserve-modules-namespace-reexport-reexport/reexport2.js
- resolves #4765
Apparently, one assumption from me was wrong about what does or does not occur in a chunks dependencies.
=> Fix handling of namespace reexports when preserving modules

CONTRIBUTING.md
=> docs: add a instruction about how to run one test on your local machine

docs/999-big-list-of-options.md
The sentence:
> If you want to convert a set of **file** to...
Should read:
> If you want to convert a set of **files** to...
=> Fix small typo in 999-big-list-of-options.md

docs/05-plugin-development.md, src/rollup/types.d.ts
Checking the version of a fellow plugin is a common task in inter-plugin communication scenarios - as an example, [`@rollup/plugin-commonjs` checks what version of `@rollup/plugin-node-resolve` is present](https://github.com/rollup/plugins/blob/master/packages/commonjs/src/index.js#L203):
```javascript
const nodeResolve = plugins.find(({ name }) => name === 'node-resolve');
if (nodeResolve) {
validateVersion(nodeResolve.version, '^13.0.6', '@rollup/plugin-node-resolve');
}
```
This works because `@rollup/plugin-node-resolve` has an unofficial `version` field added to it. This PR just proposes to make this property official (and discoverable for Intellisense users) by adding a `version?: string` …
=> Add 'version' property on Plugin type

src/Module.ts, src/ast/nodes/ExportSpecifier.ts, src/ast/nodes/ImportSpecifier.ts, test/function/samples/arbitrary-module-namespace-identifiers/_config.js, test/function/samples/arbitrary-module-namespace-identifiers/foo.js, test/function/samples/arbitrary-module-namespace-identifiers/main.js, test/function/samples/arbitrary-module-namespace-identifiers/reexport.js
- resolves #4322 
This adds support for ES2022 arbitrary module namespace identifiers, i.e.
```js
import { '=>' as foo } from './foo.js';
export { foo as '=>' };
export { '=>' as '<=' } from './foo.js';
```
=> Add support for arbitrary module namespace identifiers

LICENSE.md, browser/LICENSE.md, package-lock.json, package.json, src/utils/decodedSourcemap.ts, test/function/samples/warning-low-resolution-location/_config.js, test/sourcemaps/samples/transform-low-resolution/_config.js
none
The `sourcemap-codec` package has been deprecated in favour of `jridgewell/sourcemap-codec`, which provides extra perf optimizations. The API is interchangable so it's a matter of renaming the imports.
Though Rollup only [uses the decode API](https://github.com/bluwy/rollup/blob/09bcf369f8b5dea7f3937b98ce2d25062ba0c1e3/src/utils/decodedSourcemap.ts#L1), and there's only [slight decode perf](https://github.com/jridgewell/sourcemap-codec#benchmarks), I think it's still worth the change.
=> Use @jridgewell/sourcemap-codec

.eslintrc.js, src/Bundle.ts, src/Module.ts, src/utils/PluginDriver.ts, src/utils/options/normalizeInputOptions.ts, test/function/samples/options-hook/_config.js
just some stuff I noticed when looking through: https://github.com/rollup/rollup/issues/4784
`allowHashBang` and `allowAwaitOutsideFunction` are default with `ecmaVersion: "latest"`
=> Remove default acorn options + other fixes

src/utils/error.ts
find a import statement can be shortened in file `src/utils/error.ts`
=> fix: import can be shortened

docs/08-troubleshooting.md
The docs for increasing memory point to an incorrect `bin` folder.
=> fix: rollup bin file is in dist folder

src/ast/nodes/CallExpression.ts, src/ast/nodes/ChainExpression.ts, src/ast/nodes/MemberExpression.ts, src/ast/nodes/shared/Node.ts, test/form/samples/optional-chaining-namespace/_config.js, test/form/samples/optional-chaining-namespace/_expected.js, test/form/samples/optional-chaining-namespace/main.js, test/form/samples/optional-chaining-namespace/util.js, test/form/samples/optional-chaining/_expected.js, test/form/samples/optional-chaining/main.js, test/function/samples/optional-chaining-side-effect/_config.js, test/function/samples/optional-chaining-side-effect/main.js
- Resolves #4810 
- Resolves #4806 
This PR reworks the support for tree-shaking in optional chaining by better reflecting the optional chaining logic and adding proper support for properties of namespaces.
Missing properties of namespaces are now also treated as `undefined` for optional chaining.
=> Rework tree-shaking support for optional chaining

src/Chunk.ts, src/ast/nodes/ClassDeclaration.ts, src/ast/nodes/Identifier.ts, src/ast/nodes/StaticBlock.ts, src/ast/variables/Variable.ts, src/utils/renderHelpers.ts, test/form/samples/use-class-name-in-static-block/_config.js, test/form/samples/use-class-name-in-static-block/_expected/amd.js, test/form/samples/use-class-name-in-static-block/_expected/cjs.js, test/form/samples/use-class-name-in-static-block/_expected/es.js, test/form/samples/use-class-name-in-static-block/_expected/iife.js, test/form/samples/use-class-name-in-static-block/_expected/system.js, test/form/samples/use-class-name-in-static-block/_expected/umd.js, test/form/samples/use-class-name-in-static-block/main.js, test/form/samples/use-class-name-in-static-block/test1.js, test/form/samples/use-class-name-in-static-block/test2.js, test/function/samples/use-class-name-in-static-block/_config.js, test/function/samples/use-class-name-in-static-block/main.js, test/function/samples/use-class-name-in-static-block/test1.js, test/function/samples/use-class-name-in-static-block/test2.js
resolves #4811 
The `Variable` renders a proper name according to the return of the `useOriginalName` function.
=> fix: use the original class name in the class body

src/Chunk.ts, src/utils/error.ts, test/function/samples/circular-missed-reexports/_config.js, test/function/samples/circular-namespace-reexport-manual-chunks/_config.js, test/function/samples/circular-namespace-reexport-manual-chunks/formatters.js, test/function/samples/circular-namespace-reexport-manual-chunks/index.js, test/function/samples/circular-namespace-reexport-manual-chunks/main.js, test/function/samples/circular-namespace-reexport-manual-chunks/types.js, test/function/samples/circular-namespace-reexport-preserve-modules/_config.js, test/function/samples/circular-namespace-reexport-preserve-modules/formatters.js, test/function/samples/circular-namespace-reexport-preserve-modules/index.js, test/function/samples/circular-namespace-reexport-preserve-modules/main.js, test/function/samples/circular-namespace-reexport-preserve-modules/types.js, test/function/samples/circular-preserve-modules/_config.js
- closes #4804 
The root cause of #4804 was that namespace exports do not have an export name. This fixes the warning by using "*" as the export name. It also shows the warning in more situations as it was omitted if one export was a namespace and we were preserving modules.
=> Improve and fix cross-chunk-reexport warning

src/ast/variables/LocalVariable.ts
I think these assertions are incorrect, because the result could be `null`. To align with the boolean returned by the `hasEffectsOnInteractionAtPath` function, I added a `!!` operation.
=> fix: correct incorrect assertions

build-plugins/add-cli-entry.ts, build-plugins/conditional-fsevents-import.ts, package-lock.json, package.json, src/rollup/types.d.ts, src/utils/collapseSourcemaps.ts
The type of `sourcesContent` changed to allow for `null` elements, and rollup needs to be adjusted to that as well.
This PR updates `magic-string` past 0.27, addressing the breaking change in the `sourcesContent` type (going from `string[]` to `(string|null)[]`).
=> Update magic-string and adjust types.

docs/configuration-options/index.md, docs/plugin-development/index.md
Rollup api's Type filed write in .md  table, but some api's Type field are very complex, so they look very ugly in .md table. 
I don't know would you like to make them more readable, so i just try to modify one of this api params.
before:
after:
if you like this, please reply me, i will modify other api.
=> docs: make api params more readable

src/ast/nodes/Identifier.ts, test/form/samples/super-class-no-side-effects/_config.js, test/form/samples/super-class-no-side-effects/_expected.js, test/form/samples/super-class-no-side-effects/main.js, test/form/samples/super-class-no-side-effects/other.js
- resolves #4808 
The logic to deoptimize variables when accessed in their temporal dead zone did not take module boundaries into account, leading to falsely deoptimized variables and wrongly attributed side effects.
=> Do not mark variable access in files without side effects as TDZ

src/rollup/types.d.ts
#4805 introduced `needsCodeReference` property. The documentation describes it is intended to be used like:
```js
const referenceId = this.emitFile({
type: 'asset',
name: path.basename(id),
needsCodeReference: true,
source: fs.readFileSync(id)
});
```
But because `EmittedAsset` doesn't have `needsCodeReference` property, I get a type error.
https://github.com/rollup/rollup/blob/e0701d799b7ab0ede72a789c4359b79faf08f03d/src/rollup/types.d.ts#L187
https://github.com/rollup/rollup/blob/e0701d799b7ab0ede72a789c4359b79faf08f03d/src/rollup/types.d.ts#L154
https://github.com/rollup/rollup/blob/e0701d799b7ab0ede72a789c4359b79faf08f03d/src/rollup/types.d.ts#L152 …
=> Add `needsCodeReference` property to `EmittedAsset`

src/Module.ts, test/function/samples/module-side-effect-reexport/_config.js, test/function/samples/module-side-effect-reexport/foo.js, test/function/samples/module-side-effect-reexport/index.js, test/function/samples/module-side-effect-reexport/main.js, test/function/samples/module-side-effect-reexport/reexport-effect.js
- resolves #4470
- resolves vitejs/vite#7635
- resolves vitejs/vite#10735
- resolves rollup/plugins#1159
If a module with `moduleSideEffects:false` is reexporting from a module with `moduleSideEffects:true` that again is reexporting from another file, currently neither side effects in the first reexporter nor in the second reexporter are included.
As this defeats expectations of many, this PR changes the logic so that in this case, side effects of the reexporter with `moduleSideEffects:true` ARE indeed included, hopefully solving the issues that many people had.
Note that as before, side effects are always included if the module does not use a reexport but rather imports the value and then directly …
=> Include side effects of re-exporters unless they have no moduleSideEffects

docs/repl/components/BundleOptions.vue
=> fix: style optimization in dark mode

docs/plugin-development/index.md
The params of the `transform` hook should be `(code: string, id: string)`, not `({code: string, id: string})`.
=> fix: wrong params of the transform hook

docs/configuration-options/index.md, src/rollup/types.d.ts, src/utils/options/normalizeOutputOptions.ts, src/utils/renderChunks.ts, test/sourcemaps/samples/ignore-list-default/_config.js, test/sourcemaps/samples/ignore-list-default/main.js, test/sourcemaps/samples/ignore-list-default/node_modules/lib.js, test/sourcemaps/samples/ignore-list-false/_config.js, test/sourcemaps/samples/ignore-list-false/main.js, test/sourcemaps/samples/ignore-list-false/node_modules/lib.js
https://github.com/rollup/rollup/issues/4847
Following up on the addition of the `sourcemapIgnoreList` output option, this adds a default which marks all files within a `node_modules` folder as ignore-listed. This way most projects using rollup will need no additional configuration regarding the ignore-listing and automatically benefit.
Doc: https://goo.gle/devtools-ignoreList-adoption
=> feat: mark files in a `node_modules` as ignore-listed by default

build-plugins/replace-browser-modules.ts, docs/.vitepress/config.ts
A refactoring did not take all usages of the replaced object into account. This broke the local REPL for `npm run dev`.
=> Fix `npm run dev`

src/ast/nodes/Program.ts, test/chunking-form/samples/manual-chunk-not-included/_config.js, test/chunking-form/samples/manual-chunk-not-included/_expected/amd/generated-manual.js, test/chunking-form/samples/manual-chunk-not-included/_expected/amd/main.js, test/chunking-form/samples/manual-chunk-not-included/_expected/cjs/generated-manual.js, test/chunking-form/samples/manual-chunk-not-included/_expected/cjs/main.js, test/chunking-form/samples/manual-chunk-not-included/_expected/es/generated-manual.js, test/chunking-form/samples/manual-chunk-not-included/_expected/es/main.js, test/chunking-form/samples/manual-chunk-not-included/_expected/system/generated-manual.js, test/chunking-form/samples/manual-chunk-not-included/_expected/system/main.js, test/chunking-form/samples/manual-chunk-not-included/main.js, test/chunking-form/samples/manual-chunk-not-included/manual-entry.js, test/chunking-form/samples/manual-chunk-not-included/manual-included.js
- resolves #4908
In the course of #4723, I accidentally removed a conditional that was important to handle manual chunks where the entry point is not part of the module graph. This is fixed here and now properly tested.
=> Handle manual chunks where the entry is not part of the module graph

src/utils/getCodeFrame.ts, test/function/samples/warning-incorrect-sourcemap-location/_config.js, test/function/samples/warning-incorrect-sourcemap-location/constants.js, test/function/samples/warning-incorrect-sourcemap-location/main.js
- resolves #4920
When a plugin transforms a file without generating a source map, it can be that the location when reporting a warning or error is outside the original source. This fix does not detect this case (locations will still be wrong), but ensures the warning or error is not covered by an out-of-bounds error.
=> Do not fail if the location of a warning is outside the original source

docs/repl/components/ReplMain.vue
The repl style does not add scoped, and the button style will affect the copy button, causing the content to be misplaced
=> chore: repl style add scoped

docs/.vitepress/config.ts, docs/.vitepress/mermaid.ts, docs/.vitepress/puppeteer-config.json
Apparently, Vercel loves to run their deployment containers as root, which puppeteer does not like...
=> Disable puppeteer sandbox to fix Vercel deployment

docs/plugin-development/index.md, src/rollup/types.d.ts
Allow `shouldTransformCachedModule` to return null. The hook uses the `hookFirst` approach, which only delegates other plugins if the return value is null.
https://github.com/rollup/rollup/blob/0bcf0a672ac087ff2eb88fbba45ec62389a4f45f/src/utils/PluginDriver.ts#L141-L154
Since the types only restricts returning a `boolean`, it makes it that the first plugin that implements this will take precedence over everything. Allowing to return null should fix this.
Perhaps there could be discussion if this was intentional.
=> Allow shouldTransformCachedModule to return null

browser/package.json, package-lock.json, package.json, src/ast/NodeInteractions.ts, src/ast/nodes/CallExpression.ts, src/ast/nodes/ConditionalExpression.ts, src/ast/nodes/LogicalExpression.ts, src/ast/nodes/MemberExpression.ts, src/ast/nodes/NewExpression.ts, src/ast/nodes/TaggedTemplateExpression.ts, src/ast/nodes/ThisExpression.ts, src/ast/nodes/shared/CallExpressionBase.ts, src/ast/nodes/shared/Expression.ts, src/ast/nodes/shared/FunctionBase.ts, src/ast/nodes/shared/FunctionNode.ts, src/ast/nodes/shared/MethodBase.ts, src/ast/nodes/shared/MethodTypes.ts, src/ast/nodes/shared/Node.ts, src/ast/nodes/shared/ObjectEntity.ts, src/ast/nodes/shared/knownGlobals.ts, src/ast/utils/PathTracker.ts, src/ast/values.ts, src/ast/variables/LocalVariable.ts, src/ast/variables/ParameterVariable.ts, src/utils/blank.ts
- resolves #4904
This PR tries to reduce memory usage by
- fully removing some caches when they are no longer needed
- limiting the maximum size of some caches
- tracking deoptimizations more thoroughly in some places
I hope this helps.
=> Improve memory usage for parameter deoptimizations

src/ast/nodes/ForOfStatement.ts, test/function/samples/deoptimize-loop-element/_config.js, test/function/samples/deoptimize-loop-element/main.js
- resolves #4901 
- closes #4902
This implements the solution outlined in #4902, which appears to be abandoned.
=> Deoptimize right side in for-of loops

src/ast/nodes/ExportDefaultDeclaration.ts, test/form/samples/default-export-anonymous-class-extends/_config.js, test/form/samples/default-export-anonymous-class-extends/_expected.js, test/form/samples/default-export-anonymous-class-extends/main.js
- resolves #4783
The logic that automatically adds ids when default exporting anonymous classes was not prepared to handle `extends` properly, which lead to an instance where Rollup stalled due to an infinite loop.
=> Support default exported classes that extend other classes

build-plugins/replace-browser-modules.ts, docs/.vitepress/config.ts, test/watch/index.js
Due to changes in latest Vite, module resolution changed so that our browser module plugin needed to be adjusted. This fixes the REPL in `npm run dev`.
=> Fix REPL in dev

src/ast/nodes/shared/FunctionBase.ts, src/ast/nodes/shared/FunctionNode.ts, src/ast/variables/ArgumentsVariable.ts, test/function/samples/deoptimize-via-arguments/_config.js, test/function/samples/deoptimize-via-arguments/main.js
- resolves #4960
The new selective call argument deoptimization logic did not take usages of "arguments" into account, which is fixed here.
=> Ensure arguments are deoptimized when arguments variable is used

cli/cli.ts, cli/run/index.ts, cli/run/watch-cli.ts, rollup.config.ts
- resolves #4213
As many people were reporting issues, this implements the proposed force quite via `process.exit` that some proposed.
=> Automatically force close Rollup when done

src/Module.ts, test/function/samples/missing-export-preserve-modules/_config.js, test/function/samples/missing-export-preserve-modules/foo.js, test/function/samples/missing-export-preserve-modules/main.js
- resolves #4884
This ensures that modules with shimmed missing exports always get a chunk created when preserving modules
=> Handle shimming missing exports when preserving modules

src/ast/nodes/Program.ts, src/utils/renderHelpers.ts, test/form/samples/leading-comments/_config.js, test/form/samples/leading-comments/_expected.js, test/form/samples/leading-comments/dep.js, test/form/samples/leading-comments/main.js, test/form/samples/pure-comment-scenarios-complex/_expected.js, test/form/samples/remove-treeshaken-banners/_expected.js, test/form/samples/render-removed-statements/_expected.js
- resolves #4953
Previously, only comments on the first line of a module were guaranteed to be included while subsequent comments were only retained if the first statement remained part of the bundle. This was a problem when leadings comments were written as a series of line comments instead of a block comment, or there was more than one comment.
This PR changes the logic so that all leadings comments are retained provided that
- there are no empty lines in between
- each line that is not already part of a comment starts with a comment
=> Keep leading comments on consecutive lines

package.json, src/ast/nodes/SwitchStatement.ts, test/function/samples/switch-scope/_config.js, test/function/samples/switch-scope/main.js
- resolves #4976 
Rollup wrongly used the inner "switch case" scope for the switch statement discriminant while it should have used the outer scope. This lead to wrong variable associations and invalid code, see the linked issue.
=> Use correct scope in switch statements

cli/cli.ts, test/cli/index.js
- resolves #4982
This will ensure that stdout is closed and drained before manually exiting Rollup. Unfortunately, I am not sure if it is possible to test this properly.
=> Prevent exit before stdout is drained

cli/run/watch-cli.ts, test/cli/samples/handles-uncaught-errors/_config.js, test/cli/samples/handles-uncaught-errors/main.js, test/cli/samples/handles-uncaught-errors/rollup.config.js
- #4986
There was a bug in the uncaughtException handler in that it accidentally passed the error as exit code, swallowing the actual error. This is fixed here.
=> Properly quit on uncaught exceptions

src/ast/variables/NamespaceVariable.ts, test/function/samples/self-referencing-namespace/_config.js, test/function/samples/self-referencing-namespace/main.js
- resolves #4325
This ensures that using "export * as variable" will use a getter for the namespace itself inside the namespace to avoid accessing the namespace variable before it is created.
https://rollup-8btvtg165-rollup-js.vercel.app/repl/?pr=4991&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwKiUyMGFzJTIwbnMlMjBmcm9tJTIwJy4lMkZtYWluLmpzJyUzQiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwJ2ZvbyclM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlN0QlN0Q=
=> Handle self-referencing namespaces

cli/cli.ts, rollup.config.ts, src/utils/hookActions.ts
reverts #4969, #4983
- resolves #4998 
- resolves #4995 
This basically reverts #4969 and #4983 as calling `process.exit()` or `process.stdout.end()` seems to break various workflows. Instead, we should find out what keeps Rollup from quitting in the first place, maybe some plugins?
=> Do not force quit Rollup or close stdout

src/ast/nodes/shared/knownGlobals.ts, test/form/samples/tree-shake-global-variables/_config.js, test/form/samples/tree-shake-global-variables/_expected.js, test/form/samples/tree-shake-global-variables/main.js
=> feat: mark Set, Map, WeakSet and WeakMap with array arguments as pure

src/utils/options/normalizeOutputOptions.ts, src/utils/url.ts, test/sourcemaps/samples/sourcemap-base-url-without-trailing-slash/_config.js, test/sourcemaps/samples/sourcemap-base-url-without-trailing-slash/main.js
=> fix: add a trailing slash automatically for sourcemapBaseUrl

src/Module.ts, test/chunking-form/samples/chunk-assigment-in-dynamic/_config.js, test/chunking-form/samples/chunk-assigment-in-dynamic/_expected/amd/generated-a.js, test/chunking-form/samples/chunk-assigment-in-dynamic/_expected/amd/generated-b.js, test/chunking-form/samples/chunk-assigment-in-dynamic/_expected/amd/generated-c.js, test/chunking-form/samples/chunk-assigment-in-dynamic/_expected/amd/main.js, test/chunking-form/samples/chunk-assigment-in-dynamic/_expected/cjs/generated-a.js, test/chunking-form/samples/chunk-assigment-in-dynamic/_expected/cjs/generated-b.js, test/chunking-form/samples/chunk-assigment-in-dynamic/_expected/cjs/generated-c.js, test/chunking-form/samples/chunk-assigment-in-dynamic/_expected/cjs/main.js, test/chunking-form/samples/chunk-assigment-in-dynamic/_expected/es/generated-a.js, test/chunking-form/samples/chunk-assigment-in-dynamic/_expected/es/generated-b.js, test/chunking-form/samples/chunk-assigment-in-dynamic/_expected/es/generated-c.js, test/chunking-form/samples/chunk-assigment-in-dynamic/_expected/es/main.js, test/chunking-form/samples/chunk-assigment-in-dynamic/_expected/system/generated-a.js, test/chunking-form/samples/chunk-assigment-in-dynamic/_expected/system/generated-b.js, test/chunking-form/samples/chunk-assigment-in-dynamic/_expected/system/generated-c.js, test/chunking-form/samples/chunk-assigment-in-dynamic/_expected/system/main.js, test/chunking-form/samples/chunk-assigment-in-dynamic/a.js, test/chunking-form/samples/chunk-assigment-in-dynamic/b.js, test/chunking-form/samples/chunk-assigment-in-dynamic/c.js, test/chunking-form/samples/chunk-assigment-in-dynamic/main.js
resolves #5025
Maybe we should call the `getAndExtendSideEffectModules` function to get the correct `sideEffectModules` even though `variable` is included.
=> fix: get right sideEffectModules

src/ast/nodes/ArrowFunctionExpression.ts, src/ast/nodes/shared/FunctionBase.ts, src/ast/nodes/shared/FunctionNode.ts, test/form/samples/no-side-effects-function-declaration/functions.js, test/form/samples/no-side-effects-function-declaration/main.js
Thanks to @evanw for his finding: https://github.com/evanw/esbuild/issues/3149#issuecomment-1585820844. I missed async functions and generators in the initial PR. I think `__NO_SIDE_EFFECTS__` should take higher priority than `super.hasEffectsOnInteractionAtPath`.
=> fix: `__NO_SIDE_EFFECTS__` annotation for async function

src/rollup/types.d.ts, src/utils/logs.ts, test/function/samples/plugin-error-with-numeric-code/_config.js, test/function/samples/plugin-error-with-numeric-code/main.js
=> fix: a plugin error can contains numeric code

browser/package.json
The package exports for `@rollup/browser` have `"types"` pointing to `"./dist/rollup.d.ts"`, however the actual location of the bundled dts is `"./dist/rollup.browser.d.ts"`.
=> @rollup/browser: fix types export map entry

docs/tutorial/index.md
resolves #5060 
Currently, If users study Rollup with the tutorial docs, they will encounter an error that described in issue #5060. This PR changes `.js` extension of the config file to `.mjs`, It can fix this issue.
=> docs(tutorial): change the .js extension to .mjs

src/Module.ts, src/rollup/types.d.ts, src/utils/collapseSourcemaps.ts, src/utils/decodedSourcemap.ts, src/utils/getOriginalLocation.ts
By deferring the decoding of the sourcemap mappings field, we can avoid extra computation and garbage generation, both of which appear to save a significant amount of time.
In my test application (using vite), I saw a reduction in total vite build time of about **28.4%** _(8.76s)_, and a reduction in peak heap size of **19.6%** _(706 MB)_. [Update] The latest commit reduces the peak heap size by 36.6% in total (1,300 MB) for projects that deal with large sourcemaps. While the first commit reduces allocations, the second commit technically allocates more, but frees up more data to be garbage collected which has a net positive effect. The stats below reflect only the first commit, a summary of the two …
=> perf(sourcemap): lazy compute decoded mappings

src/rollup/types.d.ts, test/typescript/index.ts
=> fix: the type of RenderedModule.code is readonly

docs/javascript-api/index.md, docs/plugin-development/index.md, src/Chunk.ts, src/rollup/types.d.ts, src/utils/FileEmitter.ts, test/chunking-form/samples/render-chunk-transform/_config.js, test/function/samples/emit-file/prebuilt-chunk/_config.js
=> feat: add `preliminaryFileName` to `OutputChunk`

src/utils/relativeId.ts, test/chunking-form/samples/relative-external-outside-output/_config.js, test/chunking-form/samples/relative-external-outside-output/_expected/amd/main.js, test/chunking-form/samples/relative-external-outside-output/_expected/amd/nested/main.js, test/chunking-form/samples/relative-external-outside-output/_expected/cjs/main.js, test/chunking-form/samples/relative-external-outside-output/_expected/cjs/nested/main.js, test/chunking-form/samples/relative-external-outside-output/_expected/es/main.js, test/chunking-form/samples/relative-external-outside-output/_expected/es/nested/main.js, test/chunking-form/samples/relative-external-outside-output/_expected/system/main.js, test/chunking-form/samples/relative-external-outside-output/_expected/system/nested/main.js, test/chunking-form/samples/relative-external-outside-output/main.js, test/chunking-form/samples/relative-external-outside-output/nested/main.js
This resolves an issue I hit when implementing the ESM build for the SWC conversion.
Basically when an external file with a relative path would be outside the target directory, imports from chunks not at the top level would be rendered wrong, e.g. `./foo` instead of `../../foo`.
=> Fix resolution of relative external files outside target directory 

src/rollup/types.d.ts
Add a generic type for Plugin.api
=> feat(types): add generic type for plugin api

src/ast/nodes/shared/knownGlobals.ts, test/form/samples/custom-event-detail/_config.js, test/form/samples/custom-event-detail/_expected.js, test/form/samples/custom-event-detail/main.js
- resolves #5122
This deoptimizes the `detail` property of custom events as that can be mutated later.
=> Deoptimize custom event detail

CONTRIBUTING.md
I ran into issues running the tests on my windows machine, and it came down to git not being configured to create symlinks out of the box. I have updated the contributing guide to provide the additional steps required to be able to run the tests on windows.
=> docs: steps to enable symlinks on windows

src/rollup/types.d.ts
Closes: #5128
Exports `TreeshakingPreset` to fix `tsup` `--dts-resolve` flag.
=> fix: exports `TreeshakingPreset`

scripts/postpublish.js, scripts/prepublish.js, scripts/test-options.js
This is a PR to test if the pipeline runs for forks.
=> Minor changes for a test PR

src/rollup/types.d.ts, src/utils/options/mergeOptions.ts, src/utils/options/normalizeInputOptions.ts, test/function/samples/logging/log-from-plugin-options-onlog-onwarn/_config.js, test/function/samples/logging/log-from-plugin-options-onlog/_config.js, test/function/samples/logging/log-from-plugin-options-onwarn/_config.js, test/function/samples/logging/log-from-plugin-options-simple/_config.js
As we have `onLog` now, there is no reason to expose and maintain `onwarn` as well on the normalized input options. Also removes the `RollupWarning` type.
=> [v4.0] Remove onwarn from normalized input options

src/ast/variables/ParameterVariable.ts, test/function/samples/track-mutated-in-callback/_config.js, test/function/samples/track-mutated-in-callback/main.js
Resolves #5152
There was an asymmetry in the deoptimization logic that falsely marked parameter properties as "deoptimized" even though only their nested properties were deoptimized.
=> Fully deoptimize first level path when deoptimizing nested parameter paths

rust/parse_ast/src/convert_ast/converter.rs, test/form/samples/empty-export/_config.js, test/form/samples/empty-export/_expected/amd.js, test/form/samples/empty-export/_expected/cjs.js, test/form/samples/empty-export/_expected/es.js, test/form/samples/empty-export/_expected/iife.js, test/form/samples/empty-export/_expected/system.js, test/form/samples/empty-export/_expected/umd.js, test/form/samples/empty-export/main.js
There was a small bug in the code that prevented parsing of the empty export `export {}`.
=> [v4.0] Handle empty exports

src/ast/nodes/shared/FunctionBase.ts, test/function/samples/mutate-via-parameter/_config.js, test/function/samples/mutate-via-parameter/main.js
- resolves #5156
I wonder why this did not turn up earlier. Basically we need to assume a function can be called with arbitrary values when we lose track of it e.g. because it is exported.
=> Deoptimize all parameters when losing track of a function

docs/configuration-options/index.md, src/ast/nodes/VariableDeclaration.ts, src/ast/nodes/shared/Node.ts, src/utils/convert-ast.ts, src/utils/logs.ts, src/utils/urls.ts, test/form/samples/nested-pure-comments/_config.js, test/form/samples/no-side-effects-function-declaration-preserve/_config.js, test/form/samples/pure-comment-line-break/_config.js, test/form/samples/pure-comment-scenarios-complex/_config.js, test/form/samples/pure-comment-scenarios-simple/_config.js, test/form/samples/pure-comments-disabled/_config.js, test/form/samples/remove-invalid-pure-comments/_config.js, test/form/samples/remove-no-side-effects-variable/_config.js, test/form/samples/remove-no-side-effects-variable/_expected.js, test/form/samples/remove-no-side-effects-variable/main.js, test/form/samples/remove-tree-shaken-pure-comments/_config.js, test/function/samples/warn-misplaced-annotations/_config.js, test/function/samples/warn-misplaced-annotations/main.js
This adds a warning when Rollup encounters a `@__PURE__` or `@__NO_SIDE_EFFECTS__` annotations in an invalid position. The warning contains a link to the documentation to educate users how to place annotations.
The warning looks like this:
```
(!) A comment
"/*@__NO_SIDE_EFFECTS__*/"
in "src/main.js" contains an annotation that Rollup cannot interpret due to the position of the comment. The comment will be removed to avoid issues.
https://rollupjs.org/https://rollupjs.org/configuration-options/#no-side-effects
src/main.js (4:0)
2: /*@__NO_SIDE_EFFECTS__*/ const foo = 1,
3:   bar = () => console.log();
4: /*@__NO_SIDE_EFFECTS__*/ assert.ok(true);
^
```
=> [v4.0] warn for invalid annotations

build-plugins/copy-types.ts, docs/javascript-api/index.md, docs/plugin-development/index.md, package.json, rollup.config.ts, src/Bundle.ts, src/Graph.ts, src/Module.ts, src/rollup/types.d.ts, src/utils/PluginContext.ts, src/utils/convert-ast.ts, src/utils/logs.ts, src/utils/parseAst.ts, src/utils/parseAstType.d.ts, test/function/samples/double-default-export/_config.js, test/function/samples/double-named-export/_config.js, test/function/samples/double-named-reexport/_config.js, test/function/samples/duplicate-import-fails/_config.js, test/function/samples/duplicate-import-specifier-fails/_config.js, test/function/samples/error-parse-json/_config.js, test/function/samples/error-parse-unknown-extension/_config.js, test/function/samples/export-not-at-top-level-fails/_config.js, test/function/samples/import-not-at-top-level-fails/_config.js, test/function/samples/parse-return-outside-function/_config.js, test/function/samples/reassign-import-fails/_config.js, test/function/samples/reassign-import-not-at-top-level-fails/_config.js, test/function/samples/update-expression-of-import-fails/_config.js, test/misc/index.js, test/misc/parse-ast.js
This exposes the parser as a separate export e.g. for tools like Vite. You can use it like this:
```js
import { parseAst } from 'rollup/parseAst';
import assert from 'node:assert';
assert.deepEqual(
parseAst('return 42;', { allowReturnOutsideFunction: true }),
{
type: 'Program',
start: 0,
end: 10,
body: [
{
type: 'ReturnStatement',
start: 0,
end: 10,
argument: {
type: 'Literal',
start: 7,
end: 9,
raw: '42',
value: 42
}
}
],
sourceType: 'module'
}
);
```
=> [v4.0] Expose parser

rust/parse_ast/src/convert_ast/converter.rs, src/ast/nodes/EmptyStatement.ts, test/form/samples/empty-statament-class-member/_config.js, test/form/samples/empty-statament-class-member/_expected/amd.js, test/form/samples/empty-statament-class-member/_expected/cjs.js, test/form/samples/empty-statament-class-member/_expected/es.js, test/form/samples/empty-statament-class-member/_expected/iife.js, test/form/samples/empty-statament-class-member/_expected/system.js, test/form/samples/empty-statament-class-member/_expected/umd.js, test/form/samples/empty-statament-class-member/main.js
resolves #5171 
~~This PR also defines the default rendering of the `EmptyStatement` node~~
=> fix: ignores empty statements in class body that is returned by SWC parser

rust/parse_ast/src/convert_ast/annotations.rs, test/form/samples/handles-special-comments/_config.js, test/form/samples/handles-special-comments/_expected.js, test/form/samples/handles-special-comments/main.js
- resolves #5174
The logic to efficiently detect pure comments was assuming that the character preceding a double underscore always had a by length of 1, which is fixed here.
=> Handle special characters before double underscores

docs/configuration-options/index.md
I think `log` is meant to be passed through? There is no `info` variable.
=> docs: fix code example for `onLog`

rust/Cargo.lock, rust/bindings_napi/Cargo.toml, rust/bindings_napi/src/lib.rs
This PR swaps the memory allocator with [mimalloc](https://github.com/microsoft/mimalloc).
This allocator seems to be common in napi-rs world ([swc](https://github.com/swc-project/swc/blob/1c67df55f52f229beeed487066b577b2c3fb40e5/crates/swc_node_base/src/lib.rs), [@napi-rs/fast-escape](https://github.com/napi-rs/fast-escape/blob/03191e7628a44c856275f21bc10745c0d24ff4d6/src/lib.rs#L10-L15), [parcel](https://github.com/parcel-bundler/parcel/blob/b521cfbdaace01674b7919d41201bb523cc14e41/crates/node-bindings/src/lib.rs#L4-L10), [@resvg/resvg-js](https://github.com/yisibl/resvg-js/blob/4e689705eb1416d0aa25a058cc7074e3b3a9a642/src/lib.rs#L38-L45)).
Some projects uses jemallocator on some OS/architectures …
=> perf: use mimalloc for bindings_napi

rust/Cargo.lock, rust/bindings_wasm/Cargo.toml, rust/parse_ast/Cargo.toml, rust/parse_ast/src/convert_ast/converter.rs, rust/parse_ast/src/lib.rs, wasm/bindings_wasm.d.ts, wasm/bindings_wasm_bg.wasm.d.ts
This PR **reduces the wasm size by ~70%** by avoid importing browserslist.
swc crate imports browserslist-rs indirectly and because browserslist-rs has `#[wasm_bindgen]`that function was exposed and the dependencies of that function was included in the wasm binary.
**wasm**: 5.20MB -> 1.54MB
**node (windows)**: 3.32MB -> 3.31MB
=> perf: shrink wasm size by avoid importing browserslist

src/ModuleLoader.ts, test/chunking-form/samples/implicit-dependencies/implicitly-dependent-emitted-entry/_config.js, test/chunking-form/samples/implicit-dependencies/implicitly-dependent-emitted-entry2/_config.js, test/chunking-form/samples/implicit-dependencies/implicitly-dependent-emitted-entry2/_expected/amd/generated-dep.js, test/chunking-form/samples/implicit-dependencies/implicitly-dependent-emitted-entry2/_expected/amd/generated-lib.js, test/chunking-form/samples/implicit-dependencies/implicitly-dependent-emitted-entry2/_expected/amd/main.js, test/chunking-form/samples/implicit-dependencies/implicitly-dependent-emitted-entry2/_expected/cjs/generated-dep.js, test/chunking-form/samples/implicit-dependencies/implicitly-dependent-emitted-entry2/_expected/cjs/generated-lib.js, test/chunking-form/samples/implicit-dependencies/implicitly-dependent-emitted-entry2/_expected/cjs/main.js, test/chunking-form/samples/implicit-dependencies/implicitly-dependent-emitted-entry2/_expected/es/generated-dep.js, test/chunking-form/samples/implicit-dependencies/implicitly-dependent-emitted-entry2/_expected/es/generated-lib.js, test/chunking-form/samples/implicit-dependencies/implicitly-dependent-emitted-entry2/_expected/es/main.js, test/chunking-form/samples/implicit-dependencies/implicitly-dependent-emitted-entry2/_expected/system/generated-dep.js, test/chunking-form/samples/implicit-dependencies/implicitly-dependent-emitted-entry2/_expected/system/generated-lib.js, test/chunking-form/samples/implicit-dependencies/implicitly-dependent-emitted-entry2/_expected/system/main.js, test/chunking-form/samples/implicit-dependencies/implicitly-dependent-emitted-entry2/dep.js, test/chunking-form/samples/implicit-dependencies/implicitly-dependent-emitted-entry2/lib.js, test/chunking-form/samples/implicit-dependencies/implicitly-dependent-emitted-entry2/main.js, test/test.js, test/watch/index.js
When working on async parsing, I found that there is a race condition where when a file is emitted both as an actual entry and an implicitly dependent entry, then it could be that it would still be emitted only as an implicitly dependent entry and not as an independent entry.
=> Fix race condition when emitting implicitly dependent entries

src/utils/renderHelpers.ts, test/form/samples/empty-block-comment/_config.js, test/form/samples/empty-block-comment/_expected.js, test/form/samples/empty-block-comment/main.js
- resolves #5230
There was a subtle bug in the statement list tree-shaking logic that has been there for years but strangely did not yet come up, basically an off-by-one error.
=> Render emtpy block comments after tree-shaken statements

src/ast/scopes/CatchBodyScope.ts, src/ast/scopes/FunctionBodyScope.ts, src/ast/scopes/ParameterScope.ts, src/ast/scopes/Scope.ts, test/function/samples/ast-validations/redeclare-block-function-function/_config.js, test/function/samples/ast-validations/redeclare-block-function-function/main.js, test/function/samples/ast-validations/redeclare-top-level-function-function/_config.js, test/function/samples/ast-validations/redeclare-top-level-function-function/main.js, test/function/samples/ast-validations/redeclare-top-level-var-function/_config.js, test/function/samples/ast-validations/redeclare-top-level-var-function/main.js, test/function/samples/ast-validations/redeclare-var-function/_config.js, test/function/samples/ast-validations/redeclare-var-function/main.js
- resolves #5247 
Apparently, the semantics for duplicate function names differ between function scopes and other scopes: In function scopes, `function` can redeclare `function` and `var` while in other scopes it is forbidden
=> Allow functions to redeclare vars and functions in function scopes

docs/plugin-development/index.md
Hello this PR allows you to update the documentation page: API plugin development.
https://rollupjs.org/plugin-development/#generatebundle
Indeed, the documentation still uses the term `assertions` whereas we must now use `attributes`.
there is also a small correction in an example where it was necessary to use the `resolveId` hook instead of `load`.
=> doc fix import assertions to attributes in API plugin development page

.github/PULL_REQUEST_TEMPLATE.md, src/ast/nodes/ArrowFunctionExpression.ts, src/ast/nodes/BlockStatement.ts, src/ast/nodes/CatchClause.ts, src/ast/nodes/ClassBody.ts, src/ast/nodes/ForInStatement.ts, src/ast/nodes/ForOfStatement.ts, src/ast/nodes/ForStatement.ts, src/ast/nodes/FunctionExpression.ts, src/ast/nodes/IfStatement.ts, src/ast/nodes/StaticBlock.ts, src/ast/nodes/SwitchStatement.ts, src/ast/nodes/shared/ClassNode.ts, src/ast/nodes/shared/FunctionNode.ts, src/ast/scopes/BlockScope.ts, src/ast/scopes/CatchBodyScope.ts, src/ast/scopes/ClassBodyScope.ts, src/ast/scopes/FunctionBodyScope.ts, src/ast/scopes/FunctionScope.ts, src/ast/scopes/ParameterScope.ts, test/form/samples/function-id-as-parameter/_config.js, test/form/samples/function-id-as-parameter/_expected.js, test/form/samples/function-id-as-parameter/main.js
- resolves #5259
In order for the new conflict detection logic to work, function expression ids need to be in a separate scope from the parameters.
=> Allow function expression parameters to shadow the function id

src/Module.ts, src/ModuleLoader.ts, test/function/samples/strip-bom-1/_config.js, test/function/samples/strip-bom-1/main.js
=> fix: strip BOM before calling transform hook

src/ast/scopes/BlockScope.ts, test/function/samples/ast-validations/redeclare-var-parameter-nested/_config.js, test/function/samples/ast-validations/redeclare-var-parameter-nested/main.js
- resolves #5274 
When a parameter is redeclared as a `var` several times in the same nested scope (or in several child scopes of the same nested scope), then this caused a conflict due to some aspects of the var-conflict detection logic. This is fixed here by adding an exception when a var redeclares a parameter.
=> Allow to redeclare parameters multiple times in nested scopes

LICENSE.md, docs/repl/components/OutputStatus.vue, docs/repl/components/ReplEditor.vue, docs/repl/components/ReplMain.vue, docs/repl/helpers/editor.ts, docs/repl/stores/options.ts, docs/repl/stores/rollupOutput.ts
This will add the `experimentalLogsSideEffects` option to the REPL and allow the REPL to display logs.
=> Add logs and experimentalLogSideEffects to REPL

native.js
- https://github.com/vitejs/vite/discussions/15108
- https://github.com/vitejs/vite/discussions/15209
- https://github.com/nodejs/help/issues/4297
- https://github.com/vitest-dev/vitest/discussions/4622
- https://github.com/containers/podman-desktop-e2e/issues/81
(searching with `ERR_DLOPEN_FAILED vite OR rollup site:stackoverflow.com` gives 7 hits too)
I saw many people facing `ERR_DLOPEN_FAILED` error caused by missing DLL on Windows.
This PR adds a message about that. I didn't find a way to obtain which DLL is missing, so I made the message a bit general.
=> Add friendly error for missing MSVC redistributable

src/watch/watch.ts
It typically changed between Node 18.13 and 18.19
=> Do not assume setTimeout return type

package-lock.json, package.json, scripts/declarations.d.ts, scripts/find-config.js, scripts/helpers.js, scripts/perf-init.js, scripts/perf.js, scripts/postpublish.js, scripts/prepare-release.js, scripts/publish-wasm-node-package.js, scripts/release-helpers.js, scripts/test-options.js, scripts/tsconfig.json, typings/declarations.d.ts, typings/fsevents.d.ts
This adds (strict) JSDocs types to all scripts in the `scripts` folder. This will hopefully help as I want to add some scripts to generate AST transformation code to ensure that encoders and decoders are always synced.
=> Add JSDoc types to internal scripts

package-lock.json, package.json, test/cli/samples/config-mjs-plugins/nested/plugin.mjs, test/cli/samples/config-mjs-plugins/rollup.config.mjs
Because Rollup V4 preserves the shebang, I believe we no longer need this plugin.
=> Remove rollup-plugin-thatworks from devDeps

src/ast/nodes/Identifier.ts, test/form/samples/tree-shake-nested-call-no-module-side-effects/_config.js, test/form/samples/tree-shake-nested-call-no-module-side-effects/_expected.js, test/form/samples/tree-shake-nested-call-no-module-side-effects/alpha.js, test/form/samples/tree-shake-nested-call-no-module-side-effects/main.js
- resolves #5317 
This ignores the TDZ detection logic when the variable is inside a module with moduleSideEffects=false as the logic would otgherwise detect false positives.
=> Do not handle declarations in modules without side effects as TDZ

rust/parse_ast/src/convert_ast/annotations.rs, rust/parse_ast/src/convert_ast/converter/utf16_positions.rs, test/form/samples/pure-comment-not-first/_config.js, test/form/samples/pure-comment-not-first/_expected.js, test/form/samples/pure-comment-not-first/main.js
- resolves #5324
This extends the annotation logic to handle comments that separate annotations from the annotated code.
=> Handle pure annotations that are separated by a comment

src/utils/commondir.ts
`segements` is an incorrect word.
=> Fix typo in commondir.ts

.github/workflows/build-and-tests.yml
Ref: https://github.com/vercel/next.js/pull/55505
Reported issues:
- https://discord.com/channels/874290842444111882/874290843262021705/1193789627828543559
- Close https://github.com/rollup/rollup/issues/5333
- Close https://github.com/rollup/rollup/issues/5325
=> build: static link msvc runtime on Windows x64 platform

docs/tsconfig.json, package-lock.json, package.json, scripts/tsconfig.json, test/typescript/tsconfig.json, tsconfig.json
Changing module-resolution to "Bundler" indeed solve all issues
Apparently, we no longer need "skipLibCheck: true" if we change moduleResolution to "Bundler" in relevant places. This allows us to type check all d.ts files, which might be important for some forthcoming type changes.
=> Also type-check d.ts files

rollup.config.ts, src/ast/nodes/shared/ArrayPrototype.ts, src/ast/nodes/shared/MethodTypes.ts, test/function/samples/deoptimize-pushed-array-element/_config.js, test/function/samples/deoptimize-pushed-array-element/main.js
- resolves #5343
This deoptimizes elements that are pushed into arrays as the element may later be modified via the array.
=> Track mutations of elements pushed into arrays

package-lock.json, package.json, renovate.json
This avoids updating node types to the next minor version as that introduces an incompatibility with Vite and chokidar types
=> Fix dependency range for Node types

src/ast/nodes/MetaProperty.ts, test/form/samples/emit-asset-file/_config.js, test/form/samples/emit-asset-file/_expected/amd.js, test/form/samples/emit-asset-file/_expected/cjs.js, test/form/samples/emit-asset-file/_expected/es.js, test/form/samples/emit-asset-file/_expected/iife.js, test/form/samples/emit-asset-file/_expected/system.js, test/form/samples/emit-asset-file/_expected/umd.js, test/form/samples/emit-asset-file/logo_reverse'.svg, test/form/samples/emit-asset-file/main.js
- refs https://github.com/vitejs/vite/issues/13116
`import.meta.ROLLUP_FILE_URL_referenceId` with a file with single quote generated an invalid code. For example:
```js
""+new URL('javascript'-8dac5379.svg', import.meta.url).href+""
```
=> fix: escape ids in `import.meta.ROLLUP_FILE_URL_referenceId` correctly

src/utils/chunkAssignment.ts
None
I highly appreciate the comment documenting the chunking algorithm in `chunkAssignment.ts`. Thanks!!
At the same time, the comment line breaks seemed off, and it contained a typo.
This PR fixes those superficial issues.
=> Chunk assignment - Fix comment line breaks and typo

src/ExternalModule.ts, src/Graph.ts, src/Module.ts, src/utils/getter.ts
According to [`this.getModuleInfo`](https://rollupjs.org/plugin-development/#this-getmoduleinfo):
> During the build, this object represents currently available information about the module which may be inaccurate before the [buildEnd](https://rollupjs.org/#buildend) hook
After that, during the output generation phase, the props will no longer change and are stable. However, the internal implementation still keeps them as getters, so there's a cost later even if they don't change.
This PR implements caching for the getters after the build ends (or specifically at the start of output generation). This way accessing the module info will be fast.
---
Usage in the wild:
1. Vite reads the module graph to [analyze ineffective dynamic …
=> Cache module info getters before output generation

native.js, npm/linux-powerpc64le-gnu/package.json
See also https://nodejs.org/api/process.html#processarch
- resolves #5350
While the actual target is ppc64le, it is called ppc64 in Node's process.arch
=> Fix ppc64le target

.github/workflows/build-and-tests.yml
The goal here is to add smoke tests for most Linux architectures that we currently cannot test natively via emulation.
=> Try to run emulated smoke tests for Linux environments

src/ast/nodes/ConditionalExpression.ts, src/ast/nodes/LogicalExpression.ts, test/form/samples/request-tree-shaking-before-render/_config.js, test/form/samples/request-tree-shaking-before-render/_expected.js, test/form/samples/request-tree-shaking-before-render/main.js
- resolves #5480
While we should not request a tree-shaking in `ConditionalExpression` or `LogicalExpression` if nothing happens; we should request one if anything changes.
One way to validate this fix is to use example from #5480, see [repl](https://rollupjs.org/repl/?version=4.16.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMnVua25vd25fZ2xvYmFsJTVDbiU1Q25mdW5jdGlvbiUyMHModCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwdCh1bmtub3duX2dsb2JhbCklNUNuJTdEJTNCJTVDbiU1Q25mdW5jdGlvbiUyMGYoYiklMjAlN0IlNUNuJTIwJTIwJTIwJTIwcmV0dXJuJTIwdW5rbm93bl9nbG9iYWwuY29uY2F0KChiJTIwJTNGJTIwMSUyMCUzQSUyMDApKSU1Q24lN0QlNUNuJTVDbmZ1bmN0aW9uJTIwdyhiKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjBmKGIpJTVDbiU3 …
=> fix: conditional/logical expression should request a new tree-shaking

src/ast/nodes/ArrowFunctionExpression.ts, src/ast/nodes/FunctionExpression.ts, src/ast/nodes/shared/FunctionBase.ts, test/form/samples/tree-shake-literal-parameter/iife/_expected.js, test/form/samples/tree-shake-literal-parameter/iife/main.js, test/function/samples/acorn-walk/_config.js, test/function/samples/acorn-walk/main.js
- resolves #5484
If a IIFE has a name, it may lose track. In this case we probably should not consider to optimize them.
=> fix: only optimize annoymous iife

src/ast/nodes/NewExpression.ts, src/ast/nodes/TaggedTemplateExpression.ts, test/function/samples/recursive-parameter-assignments/main.js, test/function/samples/recursive-parameter-binding/_config.js, test/function/samples/recursive-parameter-binding/main.js
- resolves #5499
The function parameter will only get a known value when it is the callee of a function call. It is also where the `hasEffects` of function body gets called (and the only place?), we need to make sure the known value is set first, then `hasEffects` of function body gets called for `NewExpression` and `TaggedTemplateExpression` too. In that case, we can get exactly a "call tree" instead of a "call graph", so the known value of a parameter is guaranteed to come from somewhere outside the function and is guaranteed to from a "analyzed" code/function.
=> fix: parameter variable infinite recursion error

cli/run/loadConfigFile.ts, test/cli/samples/config-import-meta/_config.js, test/cli/samples/config-import-meta/plugin/plugin.js
List any relevant issue numbers: N/A
Back in #4005, rollup was taught how to resolve `import.meta.url` in files imported into the rollup config using a relative path - making `import.meta.url` refer the file it's used in, rather than the config file.
[node 20.11.0](https://nodejs.org/en/blog/release/v20.11.0) introduced two new import meta fields - `import.meta.filename` and `import.meta.dirname` - that act the same as __filename and __dirname in commonjs.
This PR teaches rollup config transpilation how to transform `import.meta.filename` and `import.meta.dirname` so they behave as expected inside plugins that are imported via relative paths. Previously, import.meta.filename and import.meta.dirname would be the file/directory of the …
=> Resolve import.meta.{filename,dirname} in files imported from config

docs/configuration-options/index.md
I am submitting a pull request to correct a typographical error in [the configuration options documentation](https://rollupjs.org/configuration-options/#output-hashcharacters). The description of the output.hashCharacters option incorrectly states "base32" instead of "base36".
=> docs: correct base32 to base36 in documentation

LICENSE.md, rust/parse_ast/src/ast_nodes/import_attribute.rs, rust/parse_ast/src/ast_nodes/method_definition.rs, rust/parse_ast/src/ast_nodes/property.rs, rust/parse_ast/src/ast_nodes/rest_element.rs, rust/parse_ast/src/ast_nodes/return_statement.rs, rust/parse_ast/src/ast_nodes/shared/class_node.rs, rust/parse_ast/src/ast_nodes/spread_element.rs, rust/parse_ast/src/ast_nodes/switch_case.rs, rust/parse_ast/src/ast_nodes/yield_expression.rs, rust/parse_ast/src/convert_ast/converter.rs, test/utils.js
I discovered that most of the enums implement a Spanned trait that provides derived positions for the SWC AST enums. Using this, we can simplify the logic in some places.
=> Use Spanned trait to simplify logic

src/ast/nodes/ClassBody.ts, src/ast/nodes/StaticBlock.ts, src/ast/nodes/shared/ClassNode.ts
I am working on implementing decorator support. During this process, I found that `ClassBody` did not consider that `body` might be of type `StaticBlock`. This PR fixes this issue.
The estree link:https://github.com/estree/estree/blob/master/es2022.md#classbody
=> Consider that the body of ClassBody might be of type StaticBlock

src/ast/nodes/LogicalExpression.ts, src/utils/renderHelpers.ts, test/form/samples/remove-whitespace-of-logical-expression/_config.js, test/form/samples/remove-whitespace-of-logical-expression/_expected.js, test/form/samples/remove-whitespace-of-logical-expression/main.js
=> fix: find whitespace from operator position to start

src/ast/nodes/MemberExpression.ts, test/function/samples/optional-chaining-namespace/_config.js, test/function/samples/optional-chaining-namespace/main.js, test/function/samples/optional-chaining-namespace/other.js
There is a bug when using optional chaining on namespaces which is fixed here, see test case.
cc @FlorianRohm
=> Fix retrieval of literal values for chained namespaces

docs/configuration-options/index.md, docs/plugin-development/index.md, src/rollup/types.d.ts, src/utils/FileEmitter.ts, src/utils/renderChunks.ts, test/chunking-form/samples/emit-file/filenames-function-patterns/_config.js, test/function/samples/emit-file/original-file-name/_config.js, test/function/samples/emit-file/original-file-name/main.js, test/function/samples/sourcemap-true-generatebundle/_config.js, test/watch/index.js
- resolves #4724 
This is a long-requested feature for emitting assets. It adds a new optional property `originalFileName` to `this.emitFile({type: 'asset'})` calls that will be present in the `output.assetFileNames` option and in the `generateBundle` hook to identify from which file an asset was emitted.
This was a long-requested feature, but I was hesitant to implement it because it requires changes in plugins that emit files to work. In short:
Plugins that use `this.emitFile` for an asset that corresponds to an actual source file should not set the `originalFileName` property to the absolute path of the source file.
Not only will this property then passed on, the source file will also automatically …
=> Add originalFIleName property to emitted assets

docs/repl/stores/options.ts
*nope*
In the REPL, the `noConflict` option is erroneously written as `noConflice`.
>  Rollup completed with warnings:
Unknown output options: noConflice. Allowed options: amd, assetFileNames, banner, chunkFileNames, compact, dir, dynamicImportInCjs, entryFileNames, esModule, experimentalMinChunkSize, exports, extend, externalImportAssertions, externalImportAttributes, externalLiveBindings, file, footer, format, freeze, generatedCode, globals, hashCharacters, hoistTransitiveImports, importAttributesKey, indent, inlineDynamicImports, interop, intro, manualChunks, minifyInternalExports, name, noConflict, outro, paths, plugins, preserveModules, preserveModulesRoot, reexportProtoFromExternal, …
=> chore: fix the `noConflict` option in REPL.

package-lock.json, src/utils/interopHelpers.ts, test/function/samples/import-meta-url-with-compact/_config.js, test/function/samples/import-meta-url-with-compact/main.js
resolves #5623
Add appropriate spaces to DOCUMENT_CURRENT_SCRIPT template as this [commnet](https://github.com/rollup/rollup/issues/5623#issue-2482520133) suggested.
=> fix: add space for DOCUMENT_CURRENT_SCRIPT template

src/Chunk.ts, test/cli/samples/get-chunk-name/_config.js, test/cli/samples/get-chunk-name/main.js, test/cli/samples/get-chunk-name/rollup.config.mjs
resolves #5620 
remove the Windows drive prefix if the inputBase is `/`.
=> fix: get the right chunk name for preserve modules in Windows

src/utils/logs.ts, test/cli/samples/config-type-module/_config.js, test/utils.js
related #5635 
We can see that the error message in the description of the issue above is incomplete. It lacks some tips, such as `(Note that you need @rollup/plugin-json to import JSON files)`. The reason is that the stack message is outdated, so this PR ensures that the stack message is always up-to-date.
=> fix: keep the message of stack up-to-date

src/ast/nodes/CallExpression.ts, src/ast/nodes/MemberExpression.ts, test/form/samples/optional-chaining-with-smallest-treeshake/_config.js, test/form/samples/optional-chaining-with-smallest-treeshake/_expected.js, test/form/samples/optional-chaining-with-smallest-treeshake/main.js
resolves #5633
It seems that we forget to check out left-side effect of optional chaining in the end of `hasEffectsAsChainElement` method.
=> fix: include left-side effect of optional chaining in the end of hasEffectsAsChainElement

docs/repl/components/InputHeader.vue, package-lock.json, package.json
prettier-plugin-organize-imports was removing the import without vue-tsc installed
Via the introduction of prettier-plugin-organize-imports, an import in one of the REPL Vue files was removed that broke the example selection dropdown. This is fixed by also making vue-tsc a dependency. I hope at some time I will find some time to set up some E2E Tests for the REPL to avoid such things in the future...
=> Fix example selection in REPL

src/Graph.ts, src/Module.ts, src/ast/nodes/Identifier.ts, test/function/samples/tree-shake-module-side-effects-update/_config.js, test/function/samples/tree-shake-module-side-effects-update/dep.js, test/function/samples/tree-shake-module-side-effects-update/dep2.js, test/function/samples/tree-shake-module-side-effects-update/main.js
- resolves #5408 
- resolves #5650
The bug was quite intricate:
- a mutable export from a module is used that is marked with moduleSideEffects: false
- it is used in a place where its initial value can be used to simplify an expression in such a way that the value is no longer needed
- then neither the value nor the code that changes the value are included as the module is marked as having no side effects and no import is included
This took me quite some thinking to fix. The problem is that while the contract of `moduleSideEffects: false` means that we check the module for side-effectful code if at least one export is used, there are situations in Rollup where we "use" an export without including it …
=> Detect variable reassignments in modules without side effects

src/finalisers/shared/setupNamespace.ts
This PR includes the following improvements:
1. **Refactoring the use of the `in` operator**: Replaced the use of the `in` operator on an empty object `{}` with `Object.prototype` to properly check if `parts[0]` is a property of JavaScript's built-in objects. The previous approach always returned `false`, making the check ineffective.
2. **Optimization of null assignment logic**: When `isReserved` is `true`, assigning `null` to `parts[0]` was unnecessary. Instead, `parts[0]` is now retained to avoid redundant null assignments and improve the overall logic.
=> refactor: Use object.prototype to check for reserved properties

.github/workflows/build-and-tests.yml
- #5491
- #5704
`publish` job needs `build-freebsd`. That change was missing in PR #5698.
Without the change, `publish` would run before `build-freebsd` finishes and the workflow can't find an napi artifact for FreeBSD arm64 when downloading. That leads to the following error when one tries to install rollup using yarn as reported at https://github.com/rollup/rollup/issues/5491#issuecomment-2439891799
```
error Couldn't find package "@rollup/rollup-freebsd-arm64@4.24.1" required by "rollup" on the "npm" registry.
```
=> Fix "Couldn't find package" error when installing rollup using yarn

scripts/ast-types.js, scripts/generate-buffer-parsers.js, scripts/generate-buffer-to-ast.js, src/Bundle.ts, src/ast/bufferParsers.ts, src/ast/nodes/ClassBody.ts, src/ast/nodes/shared/Node.ts, src/finalisers/es.ts, src/utils/astConverterHelpers.ts, src/utils/bufferToAst.ts, src/utils/chunkAssignment.ts
When the final size of an array is known, it would be more performant to use a pre-allocated array. This will prevent the internal resizing that happens when `Array.prototype.push` exceeds the array's memory allocation, which the JS engine will then internally re-allocate and apply unnecessary pressure on the GC to clean up the "dead" memory.
Note: This PR is a draft because I will add all relevant files in this single PR, which might take some time
=> perf: use pre-allocated arrays for known result sizes

cli/run/build.ts, docs/javascript-api/index.md, src/rollup/rollup.ts, src/rollup/types.d.ts, test/misc/misc.js, tsconfig.json
resolves #5714 
Since this is a new `TypeScript` feature, I'm not sure how to add additional test cases on the `JavaScript` side.
=> feat: support `using` for `RollupBuild`

src/ast/nodes/ArrayPattern.ts, src/ast/nodes/AssignmentPattern.ts, src/ast/nodes/Property.ts, test/function/samples/object-expression-treeshaking/deconflict-destructured-array-pattern/_config.js, test/function/samples/object-expression-treeshaking/deconflict-destructured-array-pattern/dep.js, test/function/samples/object-expression-treeshaking/deconflict-destructured-array-pattern/main.js, test/function/samples/object-expression-treeshaking/deconflict-destructured-for-default-side-effects-array/_config.js, test/function/samples/object-expression-treeshaking/deconflict-destructured-for-default-side-effects-array/dep.js, test/function/samples/object-expression-treeshaking/deconflict-destructured-for-default-side-effects-array/main.js, test/function/samples/object-expression-treeshaking/deconflict-destructured-for-default-side-effects/_config.js, test/function/samples/object-expression-treeshaking/deconflict-destructured-for-default-side-effects/dep.js, test/function/samples/object-expression-treeshaking/deconflict-destructured-for-default-side-effects/main.js, test/function/samples/object-expression-treeshaking/deconflict-destructured-for-key-side-effects/_config.js, test/function/samples/object-expression-treeshaking/deconflict-destructured-for-key-side-effects/dep.js, test/function/samples/object-expression-treeshaking/deconflict-destructured-for-key-side-effects/main.js
…key or default side effect
This resolves various situations I found where the corresponding variables would not be included in a necessary situation, leaving to situations where the deconflicting logic fails.
=> Fix more variable deconflicting issues

.github/workflows/build-and-tests.yml
The FreeBSD build is very slow as it is running a non-native image. In this PR, I see if we can use the same caching technique we use for the other builds to save and restore the Cargo cache.
=> Test if saving the Cargo cache can speed up FreeBSD

.github/workflows/build-and-tests.yml, .github/workflows/performance-report.yml, .github/workflows/repl-artefacts.yml
This will allow restoring an older node_modules folder if we do not have a cache hit and using `npm install` for a faster dependency update in those cases.
The exception are build jobs on master that create the cache. This will hopefully also speed up FreeBSD quite a bit.
=> Improve CI caching for node_modules

cli/run/watch-cli.ts, test/cli/index.js, test/cli/samples/unfulfilled-hook-actions-error/_config.js, test/cli/samples/watch/close-stdin/_config.js, test/cli/samples/watch/close-stdin/wrapper.js, test/cli/samples/watch/signal-close-watcher/_config.js, test/cli/samples/watch/watch-config-no-update/_config.js, test/types.d.ts
- resolves #5649
- resolves #5331
There was a logic to stop watch mode when stdin closes when running in a non-TTY context. I think this logic was not really serving a purpose as it does not make sense to run watch mode in a pipe IMO. However, it was breaking watch mode when running it from yarn, gradle, or docker containers. This is fixed here.
=> Support watch mode in yarn, gradle and containers

cli/run/batchWarnings.ts, test/cli/samples/logs/_config.js
Not yet, I'll check how to do that
Urls are currently prefixed with `https://rollupjs.org/` twice
```
(!) If you do not supply "output.name", you may not be able to access the exports of an IIFE bundle.
https://rollupjs.org/https://rollupjs.org/configuration-options/#output-name
```
I'm removing it here, but we could also remove all other `getRollupUrl` calls
=> fix: avoid duplicate rollupjs.org prefix

src/ast/nodes/LogicalExpression.ts, test/function/samples/deoptimize-logical-expressions-2/_config.js, test/function/samples/deoptimize-logical-expressions-2/main.js
related https://github.com/rollup/rollup/issues/5770#issuecomment-2598186894
Unfortunately, it seems quite difficult to create a minimal reproduction for this issue. If there really is a problem, it’s likely caused by `expression.deoptimizeCache()` re-triggering the current `getLiteralValueAtPath` method. So, In this PR, `hasDeoptimizedCache` is set to true as early as possible to check if that fixes the issue.
=> fix: set hasDeoptimizedCache to true as early as possible

src/ast/nodes/ThrowStatement.ts, test/function/samples/object-expression-treeshaking/throw-object/_config.js, test/function/samples/object-expression-treeshaking/throw-object/main.js
- resolves #5824
Currently, there is no mechanism to ensure throw statements include all properties.
=> Ensure that all properties of throw statements are included

src/Module.ts, test/function/samples/object-expression-treeshaking/include-namespace-reexport-path/_config.js, test/function/samples/object-expression-treeshaking/include-namespace-reexport-path/dep.js, test/function/samples/object-expression-treeshaking/include-namespace-reexport-path/lib.js, test/function/samples/object-expression-treeshaking/include-namespace-reexport-path/main.js, test/function/samples/object-expression-treeshaking/include-namespace-reexport-path/object.js
- resolves #5828
When we include a namespace object, we always include all paths of all exports and reexports. However to avoid infinite recursions when a namespace references itself, there was a check to only include reexports when they were not included yet. This could lead to a situation where a reexport was already included, but not with all possible paths.
This PR fixes this by replacing it with a general check if all exports of a namespace have already been included. This should also benefit performance slightly.
=> Include all paths of reexports if namespace is used

docs/plugin-development/index.md, src/rollup/rollup.ts, src/rollup/types.d.ts, test/hooks/index.js
Hello!
- Closes #5858
- Closes #5868
The `closeBundle` hook now receives the last error:
```js
const plugin = {
name: 'example',
closeBundle(error) {
if (error) console.warn('Oh no :(')
}
}
```
If an error is thrown in `buildEnd`, `closeBundle` will receive this error:
```js
const plugin = {
name: 'example',
buildEnd(error) {
throw new Error('build end')
},
closeBundle(error) {
// error comes from buildEnd
}
}
```
In case the build fails and `buildEnd` also fails, `closeBundle` will receive a compound error created out of both previous errors.
=> feat(5858): make closeBundle hook receive the last error

src/Module.ts, test/function/samples/no-treeshake-react/_config.js, test/function/samples/no-treeshake-react/main.js, test/function/samples/no-treeshake-react/node_modules/react/cjs/react.production.js, test/function/samples/no-treeshake-react/node_modules/react/index.js, test/function/samples/no-treeshake-react/node_modules/react/package.json
- resolves #5899
`setMergedNamespaces` is skipped if `includeAllExports(false)` is called prior to `includeAllExports(true)`, which somehow only happens with `treeshake: false`.
=> Fix `treeshake: false` breaking destructured namespace imports

src/utils/pluginFilter.ts, test/function/samples/plugin-hook-filters/_config.js
When multiple filter options were specified for a transform hook, the hook ran when either of it matched.
For example, the following filter matched for modules that whose id is `foo` or whose code contains `a`.
```js
{
filter: { id: ['foo'], code: 'a' }
}
```
This is not useful.
This PR fixes that behavior. After this PR, the filter above only matches if the module id is `foo` **and** the code contains `a`.
The previous behavior (that is probably rarely needed) can be achieved by using multiple plugins:
```js
const filters = [{ id: ['foo'] }, { code: 'a' }]
const plugins = filters.map(filter => ({ name: 'plugin', transform: { filter, handler() { /* process the module */ } } }))
```
refs …
=> Correct the behavior when multiple transform filter options are specified

src/utils/chunkAssignment.ts, test/chunking-form/samples/top-level-await-import-2/_config.js, test/chunking-form/samples/top-level-await-import-2/_expected/es/generated-foo-prefix.js, test/chunking-form/samples/top-level-await-import-2/_expected/es/generated-foo.js, test/chunking-form/samples/top-level-await-import-2/_expected/es/main.js, test/chunking-form/samples/top-level-await-import-2/_expected/system/generated-foo-prefix.js, test/chunking-form/samples/top-level-await-import-2/_expected/system/generated-foo.js, test/chunking-form/samples/top-level-await-import-2/_expected/system/main.js, test/chunking-form/samples/top-level-await-import-2/foo-prefix.js, test/chunking-form/samples/top-level-await-import-2/foo.js, test/chunking-form/samples/top-level-await-import-2/lib.js, test/chunking-form/samples/top-level-await-import-2/main.js
=> Avoid chunks TLA dynamic import circular when TLA dynamic import used in non-entry modules

src/ast/utils/identifyNode.ts, src/ast/variables/LocalVariable.ts, test/form/samples/treeshake-deterministic-dynamic-import/_expected.js, test/form/samples/treeshake-deterministic-dynamic-import/main.js
resolves #5975 
This issue occurred because we overlooked the possibility of function expression in thenable in #5954.
=> fix: consider function expression in thenable when tree-shaking dynamic imports

docs/configuration-options/index.md, src/utils/options/normalizeInputOptions.ts, test/function/samples/options-hook/_config.js
- resolves #5989
Apparently, removing the limit caused issues for quite a few people. As a quick fix, this will set the limit to a much higher value. We will try to find a better solution in the mid term.
=> Set maxParallelFileOps to 1000

src/ast/nodes/BinaryExpression.ts, src/ast/nodes/UnaryExpression.ts, src/ast/utils/renderLiteralValue.ts, test/form/samples/namespace-optimization-in-operator/_config.js, test/form/samples/namespace-optimization-in-operator/_expected.js, test/form/samples/namespace-optimization-in-operator/foo.js, test/form/samples/namespace-optimization-in-operator/main.js
Currently, using the `in` operator on a namespace completely disables treeshaking, even if the left hand-side of the expression can be statically resolved. This makes checking for the existence of an export annoying, as demonstrated [here](https://rollupjs.org/repl/?version=4.45.1&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMHQlMjBmcm9tJTIwJy4lMkZ0ZXN0LmpzJyU1Q24lNUNuZXhwb3J0JTIwZnVuY3Rpb24lMjBmbigpJTIwJTdCJTVDbiUyMCUyMGlmJTIwKCdtYXliZSclMjBpbiUyMHQpJTVDbiUyMCUyMCUyMCUyMHQubWF5YmUoKSU1Q24lN0QlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSUyQyUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTdEJTJDJTdCJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGZ1bmN0aW9uJTIwYSgpJTIwJTdCJTVDbiUyMCUyMGNvbnNvbGUubG9n …
=> feat: optimize `in` checks on namespaces to keep them treeshake-able

src/ast/nodes/BinaryExpression.ts, test/form/samples/external-namespace-optimzation-in-operator/_config.js, test/form/samples/external-namespace-optimzation-in-operator/_expected.js, test/form/samples/external-namespace-optimzation-in-operator/ext.js, test/form/samples/external-namespace-optimzation-in-operator/main.js, test/form/samples/external-namespace-optimzation-in-operator/passthrough.js, test/form/samples/namespace-optimization-in-operator/_expected.js, test/form/samples/namespace-optimization-in-operator/main.js, test/form/samples/optimization-in-operator/_config.js, test/form/samples/optimization-in-operator/_expected.js, test/form/samples/optimization-in-operator/foo.js, test/form/samples/optimization-in-operator/main.js
resolves #6040
There was an issue with the previous `BinaryExpression` include logic: if `included` was set to `true` before calling `super.include()`, the `include()` logic for `left` and `right` would not be executed.
Include changes from #6042.
=> Correct the logic of include in BinaryExpression and don't optimize external references away

rust/bindings_napi/Cargo.toml
- closes #6047 (hopefully for good)
initially introduced by #6055 for linux, this did not include android devices as it is considerd its own operating system with linux being the "vendor"; triplets are quite inconsistent and confusing at times!
this change conservatively disables arch-specific optimizations for all aarch64 targets, to ensure broad compatibility.
=> build(rust): mimalloc-safe/no_opt_arch on aarch64

docs/.vitepress/verify-anchors.ts, docs/repl/helpers/query.ts, scripts/test-options.js, src/Chunk.ts, src/utils/getLogFilter.ts, src/utils/options/normalizeInputOptions.ts, test/function/samples/external-ignore-reserved-null-marker/_config.js, test/testHelpers.js
When determining the value of the first letter of a string, using strict equality is more efficient than startsWith. refer to [link](https://perf.link/#eyJpZCI6InpyZjd5OHg5Mm13IiwidGl0bGUiOiJGaW5kaW5nIG51bWJlcnMgaW4gYW4gYXJyYXkgb2YgMTAwMCIsImJlZm9yZSI6ImNvbnN0IGRhdGEgPSBbLi4uQXJyYXkoMTAwMCkua2V5cygpXS5tYXAoKCkgPT4gTWF0aC5yYW5kb20oKS50b1N0cmluZygxNikpIiwidGVzdHMiOlt7Im5hbWUiOiJGaW5kIGl0ZW0gMTAwIiwiY29kZSI6ImRhdGEuZmluZCh4ID0%2BIHguc3RhcnRzV2l0aCgnLicpKSIsInJ1bnMiOls2MDAwMCw1NTAwMCw1NzAwMCw3MjAwMCwyNzAwMCw5MzAwMCw5NjAwMCw4MTAwMCwxMTEwMDAsMzAwMCwyODAwMCwxMzAwMDAsMTUwMDAsMjEwMDAsMTU0MDAwLDEwMDAsNTYwMDAsODkwMDAsMzkwMDAsMzMwMDAsMTIwMDAsMzAwMCwyNDAwMCw0MDAwMCwxMjAwMCwxMjAwMCwzNjAwMCwxNTYwMDAsMTA3MDAwLDIwMDAwL …
=> perf: replace startsWith with strict equality

src/ast/nodes/ArrayPattern.ts, src/ast/nodes/AssignmentPattern.ts, src/ast/nodes/Identifier.ts, src/ast/nodes/MemberExpression.ts, src/ast/nodes/ObjectPattern.ts, src/ast/nodes/Property.ts, src/ast/nodes/RestElement.ts, test/function/samples/keep-the-non-first-assignment-in-destructuring-unknown-array-variables/_config.js, test/function/samples/keep-the-non-first-assignment-in-destructuring-unknown-array-variables/main.js
resolves #6075 
By directly assigning the `included` value of a child node (e.g., element.included = true), the first include logic of that child in `includeNode` may be bypassed. Therefore, this PR uses `childNode.includeNode` instead of setting `element.included = true` directly. In addition, `includeNode` is also executed on the current node itself in `includeDestructuredIfNecessary` for the same reason. Finally, this PR fixes incorrect logic in `ObjectPattern` and simplifies the logic in `ArrayPattern`.
=> Call includeNode for self or children nodes in includeDestructuredIfNecessary

.github/workflows/performance-report.yml, .github/workflows/repl-artefacts.yml
In order to reduce the opportunity to abuse this label, I want to directly remove it when added to a pull request and only run on non-Rollup repos when the label was just added.
=> Automatically remove REPL artefacts label from PRs
