rollup/rollup

src/Module.js
src/Statement.js
src/finalisers/umd.js

Without this change, you can get malformed stuff like this:
```js
var foo = function() {
return "foo";
}var bar = function() {
return "bar";
}
```
(Uncaught SyntaxError: Unexpected token var.)
By appending a newline, a semicolon is implicitly inserted between statements when necessary:
```js
var foo = function() {
return "foo";
}
var bar = function() {
return "bar";
}
```
The indentation as a result of this commit is off, but I’m not sure how to fix it because the build fails for me. (I tested this by editing dist directly.)

Fix for malformed output.

---

CHANGELOG.md
package.json

I noticed this error in the test description string, so I thought I'd just go ahead and fix it (synchronous -> asynchronous).

Fix typo in tests

---

src/Bundle.js
src/Module.js
src/utils/resolvePath.js
test/function/custom-path-resolver-async/_config.js
test/function/custom-path-resolver-on-entry/_config.js
test/function/custom-path-resolver-on-entry/bar.js
test/function/custom-path-resolver-on-entry/foo.js
test/function/custom-path-resolver-sync/_config.js

**not ready for merge**
This enables #30, and by extension #25 (eventually), by applying the `resolvePath` hook to `options.entry`. `resolvePath` is now a misnomer; it should become `resolveId` or something similar, and there are a few other bits of internal terminology that will probably need updating as well.
Something to note: `bundle.entryPath` and `bundle.base` no longer exist. These were used for the purposes of generating non-conflicting identifiers by restricting the 'available' path parts to those within the source directory (i.e. `_foo` to deconflict with `foo`, rather than `Users_rharris_code_someProject_src_foo`) - for now, that's being worked around, but it'll need a more robust approach eventually.

Apply resolve hook to entry module

---

src/Bundle.js
test/form/block-comments/_expected/amd.js
test/form/block-comments/_expected/cjs.js
test/form/block-comments/_expected/es6.js
test/form/block-comments/_expected/iife.js
test/form/block-comments/_expected/umd.js
test/form/self-contained-bundle/_expected/amd.js
test/form/self-contained-bundle/_expected/cjs.js
test/form/self-contained-bundle/_expected/es6.js
test/form/self-contained-bundle/_expected/iife.js
test/form/self-contained-bundle/_expected/umd.js
test/function/retains-sort-order/_config.js
test/function/retains-sort-order/baz.js
test/function/retains-sort-order/foobar.js
test/function/retains-sort-order/main.js

This is a potential fix for #34. It simply sorts statements within a bundle according to their original order with a module. It feels like a filthy hack though, so I'm just going to leave it here and not merge until alternatives have been explored.
In particular, a hypothetical bundle that looked like this...
```js
[
{ module: 'a', index: 1 },
{ module: 'b', index: 1 },
{ module: 'b', index: 0 },
{ module: 'a', index: 0 }
]
```
...wouldn't be sorted in such a way that the first in the list appeared after the last in the list. I'm not sure if such a situation could arise though.

fix #34, albeit kludgily

---

.babelrc
browser/sander.js
gobblefile.js
package.json
src/Bundle.js
src/Module.js
src/rollup.js
src/utils/normalizePlatform.js
src/utils/path.js
src/utils/resolveId.js

This is a first crack at #25. Could possibly be simplified further (Browserify seems to include a lot of unnecessary gubbins, need to investigate), but it works (am building https://github.com/rollup/rollupjs.org with it... work-in-progress), at least on OS X.
Will need to check that the path utils continue to work on Windows. Though I suppose an alternative option would be to continue using node's built-in path utils in node, and only use our own in the browser bundle.

Browser-friendly version

---

test/function/top-level-side-effects-are-preserved/_config.js
test/function/top-level-side-effects-are-preserved/asap.js
test/function/top-level-side-effects-are-preserved/config.js
test/function/top-level-side-effects-are-preserved/defer.js
test/function/top-level-side-effects-are-preserved/main.js
test/function/top-level-side-effects-are-preserved/rsvp.js

I ran into this trying to use rollup with [LGTM](https://github.com/square/lgtm) where I bundle only the parts of RSVP that I need. The problem is that rollup seems not to consider the side effect of setting `config.async = asap;` worth preserving because the file that contains is pretty much just passes an import directly into an export.
Perhaps rollup should consider the statement referenced above worth preserving if it uses something that is also used by any of its exports, namely `defer`.
For reference, this is the output that rollup generates:
```js
'use strict';
const config = {};
function defer() {
config.async();
}
defer();
```

Add a failing test that illustrates a problem with RSVP.

---

src/Statement.js
test/function/object-dynamic-properties/_config.js
test/function/object-dynamic-properties/main.js
test/function/object-dynamic-properties/tags.js

When I bundled some code with a few functions of a modern, ES build of Lodash (similar to the README example), I encountered a ReferenceError at runtime.
It is caused by Lodash defining a number of variables with string tags, which are used to populate an object. Extract from Lodash [here](https://github.com/lodash/lodash/blob/master/lodash.js#L49) and [here](https://github.com/lodash/lodash/blob/master/lodash.js#L168):
```js
/** `Object#toString` result references. */
var argsTag = '[object Arguments]',
arrayTag = '[object Array]',
boolTag = '[object Boolean]',
...
// Later...
/** Used to identify `toStringTag` values supported by `_.clone`. */
var cloneableTags = {};
cloneableTags[argsTag] = cloneableTags[arrayTag] =
cloneableTags[arrayBufferTag] = cloneableTags[boolTag] = …
```

Dynamically defined object properties

---

test/function/top-level-side-effect-on-imported/_config.js
test/function/top-level-side-effect-on-imported/lib.js
test/function/top-level-side-effect-on-imported/main.js
test/function/top-level-side-effect-on-imported/obj.js
test/function/top-level-side-effects-are-preserved/_config.js

With the current implementation of rollup, this test fails. To make it pass, you can replace `import obj from './obj;` in lib.js with `var obj = {};`, suggesting that it's the import itself that somehow confuses rollup.

Test that top-level side effects involving imports are preserved.

---

bin/help.md
bin/rollup
bin/runRollup.js

Also:
* Sorted minimalist aliases alphabetically
* Updated help.md to include correct format default (ES6).
* Removed unused requires and variables from `bin/runRollup.js`.
* Added missing definition of `map` for outputting inline source maps.
* Grabs external names from globals option. These are equivalent:
```
rollup -f iife --globals lodash:_,jquery:jQuery
rollup -f iife --globals lodash:_,jquery:jQuery --external lodash,jquery
```

Add globals option to rollup executable.

---

src/Statement.js
test/function/shorthand-properties/_config.js
test/function/shorthand-properties/foo.js
test/function/shorthand-properties/main.js

This fixes #61 by rewriting `var foo = { bar }` as `var foo = { bar: _bar }` as necessary

expand shorthand properties (#61)

---

src/Statement.js
test/function/shorthand-properties/_config.js
test/function/shorthand-properties/foo.js
test/function/shorthand-properties/main.js

Reverts rollup/rollup#63.
After merging #64 I re-ran the tests on Travis. I thought they'd take the changes for #64 into account, which they didn't. The result was test that failed when testing locally. Had #63 been rebased on current master, the failing test `unused-var-d` would have been detected.

Revert "expand shorthand properties (#61)"

---

test/function/named-external-method-in-prototype/_config.js
test/function/named-external-method-in-prototype/bar.js
test/function/named-external-method-in-prototype/foo.js
test/function/named-external-method-in-prototype/main.js

I managed to reduce the failure from #68, with some comments about some observations I made trying to reduce the testcase.
In summary:
you have a relative default import that exports a typical constructor/prototype pattern, where one of the prototype methods is calling a property on a named external import.
* if we do not call the property of the named import but the named import itself, it compiles but generates wrong code
* if we do not define the prototype method but call the property of the named import in the constructor function it compiles but generates wrong code
* if we do not use a relative local import but copy-paste the code right into the `main.js` it compiles but generates wrong code
The compile error is like this:
```
TypeError: Cannot read property 'bar' of undefined
at …
```

Add failing testcase for #68

---

LICENSE.md
README.md

([Rendered](https://github.com/rollup/rollup/blob/better-readme/README.md))
This PR tries to do a better job of explaining the value of Rollup, and removes all the outdated 'you probably shouldn't use this' warnings. The CLI and API examples have been moved to the wiki, so that there's a central place for documentation.
It also adds an MIT license file.
Any thoughts?

Better readme

---

README.md

Follows #87. I thought it might be better *not* to include an example of dynamic exports, because that's the kind of bad habit that ES6 modules forbid but which some developers maintain is an advantage of legacy formats!

add minifier example and link to starter project

---

appveyor.yml
src/utils/path.js

Hi,
I started using Rollup recently, but encountered some issues that __were__ initially preventing me from using its full range of capabilities. _(I'm using Windows because I'm a bit of a masochist.)_
When there is an external module to load like so:
```javascript
// src/main.js
import Evil from "@pandora/box";
```
It fails with this error:
```sh
>> rollup -f cjs -i src/main.js -o build/main.js
Cannot read property '0' of null
TypeError: Cannot read property '0' of null
at Object.defaultExternalResolver [as resolveExternal]
(F:\Sourcecode\JavaScript\evil\node_modules\rollup\dist\rollup.js:2692:40)
...
```
Browserify + Babelify handles this without problems. JSHint doesn't shout at me either.  
The Rollup CLI creates __valid bundles__ for me on Windows when there are __no__ modules to …

Using Rollup on Windows

---

src/Bundle.js
src/Module.js
src/Scope.js
src/Statement.js
test/form/export-all-from-internal/_config.js
test/form/export-all-from-internal/_expected/amd.js
test/form/export-all-from-internal/_expected/cjs.js
test/form/export-all-from-internal/_expected/es6.js
test/form/export-all-from-internal/_expected/iife.js
test/form/export-all-from-internal/_expected/umd.js
test/form/export-all-from-internal/internal.js
test/form/export-all-from-internal/main.js
test/test.js

I noticed today that it wasn't possible to from the entry `export * from './internal.js'`. This PR fixes that.

Export all from bundle

---

src/rollup.js
test/function/has-modules-array/_config.js
test/function/has-modules-array/foo.js
test/function/has-modules-array/main.js
test/test.js

This PR adds a `bundle.modules` property, where each module is an object with an `id` property (which in normal circumstances is the module's resolved path), and room for future growth. See #128

add bundle.modules - fixes #128

---

.gitignore
.travis.yml
gobblefile.js
package.json
src/Module.js
src/rollup.js
src/utils/sourceMappingURL.js

https://codecov.io/github/rollup/rollup?branch=istanbul
This PR adds code coverage reports via [Istanbul](https://gotwarlost.github.io/istanbul/) and [codecov.io](https://codecov.io). Couple of questions/things to consider before merging:
* It instruments the built file (dist/rollup.js), not the src files, which is ignored in this repo – meaning we can't actually *see* on codecov.io which bits aren't covered
* Is there some sourcemap magic that'll fix that? I don't know
* Should dist/rollup.js be checked in? Should the coverage reports be generated on `npm test` automatically and checked in, so they can be viewed on GitHub? Or is that daft?
* `npm install` inexplicably runs `prepublish` scripts, meaning that Travis CI ends up having to run the build and tests twice. This is an …

Add code coverage with Istanbul and Codecov

---

src/Module.js
src/Scope.js
test/function/import-of-unexported-fails/_config.js
test/function/import-of-unexported-fails/main.js
test/testScope.js

I have never been fond of the `placeholder`s I've had to add in Scope's index method. It's been difficult to know what module doesn't define what identifier. This makes it much easier. We should get better error messages.
Fixes #140

Made Scope.reference stricter. Helps to catch undefined/missing exports.

---

test/function/has-modules-array/_config.js

both paths come out of rollup differently, with mixed seperators on windows..
```
1) rollup function has-modules-array:
AssertionError: [ { id: 'c:/git/rollup/test/function/has-modules-array/foo.js' },
{ id: 'c:\\git\\rollup\\test\\function/has-modules-array/mai deepEqual [ { id: 'c:\\git\\rollup\\test\\function\\has-modules-array\\foo.js' },
{ id: 'c:\\git\\rollup\\test\\function\\has-modules-ar
+ expected - actual
[
{
-    "id": "c:/git/rollup/test/function/has-modules-array/foo.js"
+    "id": "c:\\git\\rollup\\test\\function\\has-modules-array\\foo.js"
}
{
-    "id": "c:\\git\\rollup\\test\\function/has-modules-array/main.js"
+    "id": "c:\\git\\rollup\\test\\function\\has-modules-array\\main.js"
}
]
```
The alternative fix would be to keep the test as-is but add some path …

Fix test for windows

---

package.json

Couldn't run rollup after a clean installation. I needed to install these two modules separately. I found a reference to an older bug: https://github.com/rollup/rollup/issues/23
However this seems to be broken (again?)

chalk and source-map-support are always needed

---

src/Module.js
test/function/namespace-missing-export/_config.js
test/function/namespace-missing-export/main.js

`Error: Export 'foo' is not defined by '<module name>'`, instead of
`TypeError: Cannot read property 'addReference' of undefined`.

Informative error message when namespace property doesn't exist

---

package.json
src/Bundle.js
src/Module.js
src/utils/collapseSourcemaps.js
src/utils/first.js
src/utils/load.js
src/utils/transform.js
test/form/intro-and-outro/_config.js
test/form/intro-and-outro/_expected/amd.js
test/form/intro-and-outro/_expected/cjs.js
test/form/intro-and-outro/_expected/es6.js
test/form/intro-and-outro/_expected/iife.js
test/form/intro-and-outro/_expected/umd.js
test/form/intro-and-outro/main.js
test/function/custom-loaders/_config.js
test/function/custom-loaders/bar.js
test/function/custom-loaders/baz.js
test/function/custom-loaders/foo.js
test/function/custom-loaders/main.js
test/function/custom-path-resolver-on-entry/_config.js
test/function/custom-path-resolver-plural-b/_config.js
test/function/custom-path-resolver-plural/_config.js
test/function/custom-path-resolver-plural/globals-math.js
test/function/custom-path-resolver-plural/main.js
test/sourcemaps/basic-support/_config.js
test/sourcemaps/transforms/_config.js
test/sourcemaps/transforms/foo.js
test/sourcemaps/transforms/main.js
test/test.js

This needs some more battle-testing before it gets merged in, but this is a first step towards #107 – if all transformers return a `{ code, map }` object, the `map.mappings` will be traced so that the resulting sourcemap points to the correct locations in the original source.
Some things we'll have to worry about eventually:
* names, the fifth member of each segment. At present these are disregarded
* what to do if one of the transformers doesn't generate a sourcemap (e.g. it's just doing some simple string replacement to replace some `<@template@>` tags or something)?
* what to do if a sourcemap is imprecise (e.g. it just maps lines, rather than characters) – do we still try and trace segments? probably not
No reason they should delay this from being released though. *Should* make it …

sourcemap aware transforms

---

src/Bundle.js
src/utils/attempt.js
test/function/custom-path-resolver-on-entry/_config.js
test/function/custom-path-resolver-plural/_config.js
test/function/custom-path-resolver-plural/globals-math.js
test/function/custom-path-resolver-plural/main.js

It would be really nice to be able to "fall back" to some other implementation of `resolveId`, `resolveExternal` etc. This PR (which should be considered an RFC) includes one possible way to implement this in a backwards-compatible manner.
Let the resolvers handle what they can, and delegate everything else to some other function. It may not do anything to help #107, but could be something in the right direction. Thought?
Fixes #108

RFC: Resolver fallbacks

---

src/Module.js
test/function/namespaces-are-frozen/_config.js
test/function/namespaces-are-frozen/main.js
test/function/namespaces-are-frozen/mod.js

Fixes #202
I discovered another bug while adding this test.
`main.js` currently looks like
```js
// import * as ns from './mod';
// export { ns };
export var ns = Object.freeze({ a: 1, b: 2 });
```
Writing it how we want
```js
// export * as ns from './mod';
import * as ns from './mod';
export { ns };
```
yields nothing but
```js
'use strict';
var ns = Object.freeze({
a: a,
b: b
});
exports.ns = ns;
```
resulting in a `ReferenceError: a is not defined`

Prevent namespace abuse by freezing them

---

CHANGELOG.md
package.json

We might as well release 0.19.2 to include these fixes (#203, #205) along with the Promise related `ReferenceError` for those running node v0.10 (#189).

Release 0.19.2

---

src/Module.js
test/function/confused-default-identifier/_config.js
test/function/confused-default-identifier/foo.js
test/function/confused-default-identifier/main.js

Disallow 'default' as an identifier name in `addReference`

---

bin/help.md
bin/rollup
bin/runRollup.js
package.json
test/cli/config-es6/_config.js
test/cli/config-es6/main.js
test/cli/config-es6/rollup.config.js
test/cli/config-override/_config.js
test/cli/config-override/main.js
test/cli/config-override/rollup.config.js
test/cli/config-true/_config.js
test/cli/config-true/main.js
test/cli/config-true/rollup.config.js
test/cli/config/_config.js
test/cli/config/_expected.js
test/cli/config/main.js
test/cli/config/rollup.config.js

This adds support for a `--config` option in the CLI, which, by extension, enables support for plugins (#226).
`rollup -c` or `rollup --config` will load options from a `rollup.config.js` config file in the current directory. You can override this file with `rollup -c some.other.file.js`.
Any additional arguments will override those specified in the config file (i.e. `rollup -c -f umd` will create a UMD build regardless of the config file.)
The config file is processed with Rollup before being required, so it can look like this...
```js
import babel from 'rollup-plugin-babel';
export default {
entry: 'src/main.js',
plugins: [ babel() ],
format: 'umd'
};
```
...or this:
```js
var babel = require( 'rollup-plugin-babel' );
module.exports = {
entry: 'src/main.js',
plugins: [ babel() ], …
```

[RFC] add --config option to CLI (#226)

---

src/Module.js
test/function/export-all-multiple/_config.js
test/function/export-all-multiple/bar.js
test/function/export-all-multiple/foo.js
test/function/export-all-multiple/main.js
test/function/namespace-missing-export/_config.js
test/function/namespace-missing-export/empty.js
test/function/namespace-missing-export/main.js

Found a couple of bugs while trying to use Rollup on Babel 6 (because I'm having some startup performance issues with it, which I'm fairly sure are related to the level of modularisation combined with the fact that [require is dog slow](https://kev.inburke.com/kevin/node-require-is-dog-slow/) – other people are [experiencing similar issues](https://news.ycombinator.com/item?id=10474175), though it looks as though npm 3 may help a lot).
1. you can't have multiple `export *` declarations in a module
2. missing namespace exports are treated as an error, when they should really be treated as a warning, I think

Export all bugs

---

src/Statement.js
test/function/warn-on-eval/_config.js
test/function/warn-on-eval/main.js

If Rollup sees `eval`, it will warn the user about it and suggest some [alternatives](https://github.com/rollup/rollup/wiki/Troubleshooting#avoiding-eval) – fixes #186. It turns out we don't need to warn about `with`, even though it has the same result with UglifyJS, because ES6 modules are always strict, and `with` is banned in strict mode.

warn on eval

---

browser/fs.js
src/utils/defaults.js
src/utils/fs.js
test/function/non-extension-dot/_config.js
test/function/non-extension-dot/foo.bar.js
test/function/non-extension-dot/main.js

This PR changes the behaviour of the default resolver such that it checks whether a path exists at resolution time rather than waiting for failure at load time. This allows us to add `.js` to an import path like `./foo.bar` (where previously `.bar` was assumed to be the extension), thereby working around the ongoing consequences of Node's biggest design flaw (allowing extensions to be omitted).

handle filenames with .foo, where foo is not an extension

---

src/Module.js
src/Statement.js
test/function/export-from-no-local-binding-var/_config.js
test/function/export-from-no-local-binding-var/foo.js
test/function/export-from-no-local-binding-var/main.js

Because `export { x as y } from './whatever.js'` doesn't create a local binding, we need to ignore it when analysing statements. This PR is based off #270

Disregard re-export statements

---

bin/runRollup.js

When using `rollup -c` with an invalid rollup.config.js file, no warnings are logged. It should.

Log errors when using `rollup -c`

---

.eslintrc
package.json
src/utils/defaults.js
src/utils/first.js

* Lint before test
* Lint browser source files
* Fix lint errors
~~Setting the `Promise` global to `false` should prevent us from forgetting to import it again.~~
I misunderstood the .eslintrc setting.

More eslint

---

test/test.js

The test as it's currently written won't fail under any circumstances. This pull request fixes that and splits it up into two tests, one for `options` and one for `options.entry`.

Fix test for rejection when options or options.entry isn't passed

---

src/Bundle.js
src/utils/path.js
test/function/no-relative-external/_config.js
test/function/no-relative-external/main.js

treat missing relative imports as error not warning - fixes #321

---

src/finalisers/es6.js
src/finalisers/shared/getExportBlock.js
test/form/export-default-2/_config.js
test/form/export-default-2/_expected/amd.js
test/form/export-default-2/_expected/cjs.js
test/form/export-default-2/_expected/es6.js
test/form/export-default-2/_expected/iife.js
test/form/export-default-2/_expected/umd.js
test/form/export-default-2/bar.js
test/form/export-default-2/main.js
test/form/export-default-3/_config.js
test/form/export-default-3/_expected/amd.js
test/form/export-default-3/_expected/cjs.js
test/form/export-default-3/_expected/es6.js
test/form/export-default-3/_expected/iife.js
test/form/export-default-3/_expected/umd.js
test/form/export-default-3/bar.js
test/form/export-default-3/main.js

We should have used the same methods in `es6.js` and `getExportBlock.js`; they made one mistake each.
What we want: `module.traceExport( 'default' ).render( direct )`
Mistakes:
1. `module.declarations.default` instead of `module.traceExport( 'default' )`
1. `declaration.name` instead of `declaration.render( direct )`
Fixes #339

Fix default exports

---

src/finalisers/es6.js
test/form/external-imports/_expected/amd.js
test/form/external-imports/_expected/cjs.js
test/form/external-imports/_expected/es6.js
test/form/external-imports/_expected/iife.js
test/form/external-imports/_expected/umd.js
test/form/external-imports/main.js

It is a syntax error to combine namespace import specifiers with named or default specifiers.
Fixes #355.

Ensure namespace imports are not combined with other import types.

---

src/rollup.js
src/utils/validateKeys.js
test/test.js

These are all the keys needed to make the test pass, but I may have missed something.

Prevent invalid keys from being passed in options.

---

src/Bundle.js
src/utils/defaults.js

This fixes #362 by keeping track of what warnings a bundle emits

squelch duplicate warnings per-bundle (#362)

---

src/Bundle.js
test/function/plugins-can-manipulate-options/_config.js
test/function/plugins-can-manipulate-options/answer.js

Follow-up to @eventualbuddha's idea on #345 – allows plugins to register an `options` hook that either manipulates the `options` object, or return a replacement one.

allow plugins to manipulate options

---

src/rollup.js
test/test.js

* Add missing `moduleId` key.
* Remove deprecated `transform`, `load`, `resolveId` and `resolveExternal`

Fixes #379

---

bin/help.md
bin/runRollup.js
test/cli/config-env/_config.js
test/cli/config-env/main.js
test/cli/config-env/rollup.config.js

Closes #376. Adds an `--environment` option to the CLI with the following syntax, modelled after the syntax for `-g`:
```bash
rollup -c --environment PRODUCTION,FOO:bar,BAZ:qux
```
This results in the following conditions inside the `rollup.config.js` file:
```js
process.env.PRODUCTION === 'true'; // all process.env properties must be strings
process.env.FOO === 'bar';
process.env.BAZ === 'qux';
```

support --environment in CLI

---

CHANGELOG.md
bin/help.md
bin/runRollup.js
package.json
src/Module.js
src/ast/Scope.js
src/ast/extractNames.js
test/cli/config-env/_config.js
test/cli/config-env/main.js
test/cli/config-env/rollup.config.js
test/function/export-destruction/_config.js
test/function/export-destruction/main.js
test/function/vars-not-removed/_config.js
test/function/vars-not-removed/bar.js
test/function/vars-not-removed/foo.js
test/function/vars-not-removed/main.js

The `ObjectPattern` in `extractors` targeted the `key` when `value` was required.
Fixes #374 
I'm not sure whether `extractNames` should be moved out of `ast/Scope` now that it's used in more than one place?

Destruction in exports

---

src/finalisers/iife.js
src/finalisers/shared/getGlobalNameMaker.js
src/finalisers/umd.js
test/form/external-imports-custom-names-function/_config.js
test/form/external-imports-custom-names-function/_expected/amd.js
test/form/external-imports-custom-names-function/_expected/cjs.js
test/form/external-imports-custom-names-function/_expected/es6.js
test/form/external-imports-custom-names-function/_expected/iife.js
test/form/external-imports-custom-names-function/_expected/umd.js
test/form/external-imports-custom-names-function/main.js

Follow-up to #293. Allows `options.globals` to be a function as opposed to an object. In addition, if a global name isn't provided for an external module (in IIFE or UMD mode), Rollup will print a warning along these lines:
```
No name was provided for external module 'my-lib' in options.globals – guessing 'MyLib'
```
The 'guess' is based on how the external library is referenced in the bundle – if the code has something like...
```js
import MyLib from 'my-lib';
```
...it's a pretty safe bet that `MyLib` is the correct name. But in cases like this...
```js
import { foo } from 'named-only';
```
...we're forced to guess on the basis of the module ID. Either way, the recommendation is to be explicit.

allow options.globals to be a function, warn on miss

---

.gitignore
src/Bundle.js
test/function/external-ids-not-resolved/_config.js
test/function/external-ids-not-resolved/main.js
test/node_modules/external.js

See #410. This ensures that Rollup doesn't attempt to resolve IDs that are in `options.external`.

prevent resolution of external IDs

---

src/Bundle.js

Since `resolveId` and `load` always return Promises we don't need these! :raised_hands:

Remove 3 unused Promise.resolve calls

---

bin/runRollup.js
src/Bundle.js
test/cli/config-external/_config.js
test/cli/config-external/_expected.js
test/cli/config-external/main.js
test/cli/config-external/rollup.config.js

Force ids specified in `external` to actually _be_ external.
Fixes #410
Builds on top of #417

Force external

---

src/Bundle.js
src/Module.js
src/Statement.js
src/utils/pureFunctions.js
src/utils/run.js
test/form/side-effect-n/_config.js
test/form/side-effect-n/_expected/amd.js
test/form/side-effect-n/_expected/cjs.js
test/form/side-effect-n/_expected/es6.js
test/form/side-effect-n/_expected/iife.js
test/form/side-effect-n/_expected/umd.js
test/form/side-effect-n/main.js
test/form/side-effect-o/_config.js
test/form/side-effect-o/_expected/amd.js
test/form/side-effect-o/_expected/cjs.js
test/form/side-effect-o/_expected/es6.js
test/form/side-effect-o/_expected/iife.js
test/form/side-effect-o/_expected/umd.js
test/form/side-effect-o/main.js
test/function/cycles-pathological/_config.js
test/function/iife-comments/_config.js
test/function/iife-strong-dependencies/_config.js

This PR addresses #435 and #440. Possibly not the most elegant code in the world, but it makes the ordering of modules adhere to the spec without sacrificing information needed to determine that the resulting bundle may not run.
A future improvement (besides better code) could be to illustrate the actual lines containing the import statements that need to be swapped.

Fix module ordering

---

src/Module.js
test/form/object-destructuring-default-values/_config.js
test/function/deconstructed-exported-vars/_config.js
test/function/deconstructed-exported-vars/main.js
test/function/removes-empty-exported-vars/_config.js
test/function/removes-empty-exported-vars/main.js

#426. Turns out there was a semi-related bug involving destructuring syntax, which is also fixed by this PR.

fix `var exports.foo`

---

src/Bundle.js
test/function/cycles-stack-overflow/_config.js
test/function/cycles-stack-overflow/b.js
test/function/cycles-stack-overflow/c.js
test/function/cycles-stack-overflow/d.js
test/function/cycles-stack-overflow/main.js

This does raise the question of *why* the modules in question are being identified as mutual strong dependencies (references inside the returned function expressions should presumably be *weak* dependencies), but I'll leave that for an occasion when I have a bit more time to scratch my head.

prevent stack overflow with mutual strong dependencies – fixes #425

---

src/Declaration.js
src/utils/error.js
src/utils/run.js
test/function/cannot-call-external-namespace/_config.js
test/function/cannot-call-external-namespace/main.js
test/function/cannot-call-internal-namespace/_config.js
test/function/cannot-call-internal-namespace/foo.js
test/function/cannot-call-internal-namespace/main.js

This PR fixes #446 (see also #442), whether the namespace is internal or external.
It also adds an `error` helper that makes it very slightly easier to deal with these sorts of errors, by adding properties like `file` and `loc`. We could perhaps make this helper specific to code-related errors and make it do more work, e.g. figuring out the location and including a snippet of the offending code in the error message, with a location marker. In an ideal world it would also handle sourcemap chains, so that it could show the location in the original code rather than transformed code. For now though I wanted to keep this PR focused on #446.

error if namespace is called

---

src/Bundle.js
src/finalisers/cjs.js
test/form/external-imports-custom-names/_expected/cjs.js
test/form/external-imports/_expected/cjs.js

Closes #419 .  Also makes async's modular builds a bit smaller. :)

use an interopDefault function for external CJS deps

---

src/utils/fs.js

#450 is looking good. :+1:
The only eye-sore I see are all the `export const xxx = fs.xxx`s at the bottom of `fs.js`. Let's just re-export them. :smile:

Reexport fs functions directly

---

src/Bundle.js
src/Declaration.js
src/Module.js
test/function/aliased-not-exported-twice/_config.js
test/function/aliased-not-exported-twice/foo.js
test/function/aliased-not-exported-twice/main.js

This fixes half of #438. There's a second bug which I've only got a failing test for, for now – PR inbound

Fix double export of aliased names

---

src/Module.js
test/function/skips-dead-branches-f/_config.js
test/function/skips-dead-branches-g/_config.js
test/function/skips-dead-branches-g/main.js

This allows replacement of inline conditions such as in `export const resolve = isWindows ? win32Resolve : posixResolve;`.

Skip dead branches of a conditional expression.

---

src/Bundle.js
src/Declaration.js
src/Module.js
src/utils/object.js
test/function/export-global/_config.js
test/function/export-global/main.js

I encountered an error when attempting to export a global variable, like so:
```js
export { Promise };
```
```
TypeError: Cannot set property 'isExported' of null
...
```
Rollup requires each exported binding to have a corresponding Declaration. This PR introduces a SyntheticGlobalDeclaration to circumvent this problem.

Support export { global }

---

src/ast/isReference.js
test/form/computed-properties/_expected/amd.js
test/form/computed-properties/_expected/cjs.js
test/form/computed-properties/_expected/es6.js
test/form/computed-properties/_expected/iife.js
test/form/computed-properties/_expected/umd.js
test/form/computed-properties/main.js

(fixes #504, similar fix as #439)

Retain symbols of computed properties defined on classes.

---

src/rollup.js
test/function/exports-flag-allowed-in-options/_config.js
test/function/exports-flag-allowed-in-options/foo.js
test/function/exports-flag-allowed-in-options/main.js
test/test.js

Apparently this isn't used much, but we need it whitelisted for our gulp-rollup plugin integration.

Allow 'exports' key

---

src/Bundle.js
test/function/configure-relative-external-module/_config.js
test/function/configure-relative-external-module/main.js

See #532 for a detailed explanation of the problem this pull requests solves, and also the use case for non-existent, relative files to be treated as external dependencies.

Allow external files to be non-existent, relative files. Fixes #532.

---

src/rollup.js
test/test.js

Because it is [documented](https://github.com/rollup/rollup/wiki/JavaScript-API#usestrict) but not allowed.

Add useStrict option to ALLOWED_KEYS.

---

.eslintrc

This prevents eslint from taking user's eslint config files that are
higher in the directory structure into consideration.

Add root: true to eslint config.

---

src/utils/transform.js
test/function/report-transform-error-file/_config.js
test/function/report-transform-error-file/foo.js
test/function/report-transform-error-file/main.js

Does what it says on the tin – if a transform fails on a particular file, this PR augments the error message to include the filename. An `id` property is also added to the error object.
Thoughts on whether this is the right approach?

report files causing transform errors

---

bin/help.md
bin/runRollup.js
src/finalisers/umd.js
src/rollup.js
test/form/umd-noconflict/_config.js
test/form/umd-noconflict/_expected/amd.js
test/form/umd-noconflict/_expected/cjs.js
test/form/umd-noconflict/_expected/es6.js
test/form/umd-noconflict/_expected/iife.js
test/form/umd-noconflict/_expected/umd.js
test/form/umd-noconflict/main.js
test/test.js

I don't know if this was even something on the radar for rollup, but it seemed like a better solution than regexp hacking build output. So feel free to ignore this if it's not something rollup should handle :smile:
This _should_ only affect UMD modules when they're used as a global. I'm not 100% sure this is the best way to handle it, or if I've even put all the right things in the right places, but I did do a test build with this with Ractive and it seems to work as intended. 
Linking - ractivejs/ractive#2066

Add an option to add noConflict method to umd global

---

src/ast/attachScopes.js
test/form/assignment-to-exports-class-declaration/_config.js
test/form/assignment-to-exports-class-declaration/_expected/amd.js
test/form/assignment-to-exports-class-declaration/_expected/cjs.js
test/form/assignment-to-exports-class-declaration/_expected/es6.js
test/form/assignment-to-exports-class-declaration/_expected/iife.js
test/form/assignment-to-exports-class-declaration/_expected/umd.js
test/form/assignment-to-exports-class-declaration/main.js

Fixes #626.
It works by creating a new scope for classes (declarations and expressions), so that if a class expression has an ID, the ID belongs to that scope:
```js
let Foo = 'nope';
let MyClass = class Foo {
constructor () {
assert.equal( this instanceof Foo );
}
}
```
In other words, it behaves similarly to function expressions (except that the class expression ID is the only name that can belong directly to the scope, since any further declarations take place inside the class's methods).
As a side-effect, the `Foo` in `class Foo` isn't seen as a reference to an external declaration, and thus isn't erroneously rewritten.
I'm fairly sure this is semantically correct but will leave this here for a while in case anyone wants to correct me...

create new scope for classes, with class expression ID (if any) as sole name

---

src/Bundle.js
src/utils/getExportMode.js
test/function/confused-default-identifier/_config.js
test/function/warn-on-auto-named-default-exports/_config.js
test/function/warn-on-auto-named-default-exports/main.js

Addresses #587. If you have an entry module like this...
```js
function foo () {
console.log( 'foo' );
}
function bar () {
console.log( 'bar' );
}
export default foo;
export { bar };
```
...and you don't specify an export mode, you'll end up with the dreaded `exports['default'] = foo` if you're creating anything other than an ES2015 bundle, which is bad for interoperability.
This PR adds a warning if that situation is encountered, pointing to the relevant documentation.

warn if default and named exports are used together in auto mode

---

src/finalisers/cjs.js
src/finalisers/shared/esModuleExport.js
src/finalisers/umd.js
test/form/assignment-to-exports-class-declaration/_expected/cjs.js
test/form/assignment-to-exports-class-declaration/_expected/umd.js
test/form/computed-properties/_expected/cjs.js
test/form/computed-properties/_expected/umd.js
test/form/dedupes-external-imports/_expected/cjs.js
test/form/dedupes-external-imports/_expected/umd.js
test/form/export-all-from-internal/_expected/cjs.js
test/form/export-all-from-internal/_expected/umd.js
test/form/export-default-import/_expected/cjs.js
test/form/export-default-import/_expected/umd.js
test/form/exports-at-end-if-possible/_expected/cjs.js
test/form/exports-at-end-if-possible/_expected/umd.js
test/form/multiple-exports/_expected/cjs.js
test/form/multiple-exports/_expected/umd.js
test/form/namespaced-named-exports/_expected/cjs.js
test/form/namespaced-named-exports/_expected/umd.js
test/form/no-treeshake/_expected/cjs.js
test/form/no-treeshake/_expected/umd.js
test/form/preserves-comments-after-imports/_expected/cjs.js
test/form/preserves-comments-after-imports/_expected/umd.js
test/form/umd-noconflict/_expected/cjs.js
test/form/umd-noconflict/_expected/umd.js
test/function/deconflicts-exports/_config.js
test/function/export-destruction/_config.js

This is a follow-up PR for issue https://github.com/rollup/rollup/issues/650.
One thing that I'm not sure about is if I have broken sourcemaps. Since I have just added to the end of the output, the mapping should still be valid. But can somebody who is more knowledgeable confirm that I have not?
Also, should I add new test cases to explicitly test this behaviour?
EDIT: I see that [magic-string] takes care of keeping source maps correct.
[magic-string]: https://github.com/Rich-Harris/magic-string

Exported __esModule when bundling to CJS or UMD in named mode.

---

src/Bundle.js
src/Module.js
test/function/custom-resolver-non-string/_config.js
test/function/custom-resolver-non-string/main.js

The purpose of this is to allow plugins like rollup-plugin-commonjs and rollup-plugin-babel to supply 'helper' modules (which transformed modules then depend on) without having to use daft string IDs like `__babelHelpers__` and hoping that there are no collisions.
The larger goal is to make it easier for to plugins to be stateless, which advances the goal of incremental rebuilds (see https://github.com/rollup/rollup/pull/658#issuecomment-224107907).

allow resolved module IDs to be non-strings

---

src/Declaration.js
test/function/legal-suggested-names/_config.js
test/function/legal-suggested-names/bar.js
test/function/legal-suggested-names/foo.js
test/function/legal-suggested-names/helpers.js
test/function/legal-suggested-names/main.js

This fixes a bug exposed by https://github.com/rollup/rollup-plugin-babel/issues/55 – it's possible for a module to export a binding that is a reserved word, and for another module to import that reserved word, without ever writing a syntax error...
```js
// helpers.js
var _typeof = x => typeof x;
export { _typeof as typeof };
// main.js
import * as helpers from './helpers.js';
console.log( helpers.typeof( 1 ) );
```
(The export from `helpers.js` might be against spec, I'm not sure. That would be a separate issue if it is.)
This PR ensures that the use of `helpers.typeof` doesn't cause the `var _typeof` to be rewritten as `var typeof`.

ensure name suggestions are legal identifiers

---

src/Bundle.js
src/Module.js
src/rollup.js
test/incremental/not-transform-twice/expected.js
test/incremental/not-transform-twice/foo.js
test/incremental/not-transform-twice/main.js
test/incremental/transform-changed/expected.js
test/incremental/transform-changed/foo-changed.js
test/incremental/transform-changed/foo.js
test/incremental/transform-changed/main.js
test/test.js

This builds on #658 (and is a PR to merge this into that branch) – a few small tweaks:
* I think the property should be `cache` rather than `bundle` – it's a lot more explicit about what it does, and I think it'll make more sense when we get round to serializing the cache object to disk for fast cold builds
* ASTs and sourcemap chains are preserved – this will allow us to skip parsing in many cases, and should mean sourcemaps are unaffected
* The tests were a little brittle for me – because they relied on resetting the state of the input files, any changes that resulted in tests failing would also cause the state of the test itself to get borked up. So now modules are served from memory rather than the filesystem when testing – makes life a bit easier
If @rollup/collaborators are on board …

Incremental rebuilds

---

src/Statement.js
test/form/this-is-undefined/_config.js
test/form/this-is-undefined/_expected/amd.js
test/form/this-is-undefined/_expected/cjs.js
test/form/this-is-undefined/_expected/es6.js
test/form/this-is-undefined/_expected/iife.js
test/form/this-is-undefined/_expected/umd.js
test/form/this-is-undefined/main.js
test/function/this-is-undefined/_config.js

We didn't catch that this wasn't already happening (pretty sure it did at one point), because Babel was doing it for us in the test (and we needed Babel, because we need to test behaviour inside arrow functions...)

rewrite top-level this as undefined

---

src/Bundle.js
src/Module.js
src/rollup.js
src/utils/object.js
test/function/allow-reserved/_config.js
test/function/allow-reserved/main.js

One way to fix #564 – allow arbitrary options to be passed through to acorn

allow user-specified acorn options

---

bin/src/handleError.js
bin/src/runRollup.js

closes #712 (though it'd be nice to improve the logging eventually, i.e. show snippet surrounding a parse error etc)

handle errors emitted by rollup-watch

---

src/Bundle.js
src/Module.js
src/utils/collapseSourcemaps.js
src/utils/transform.js
src/utils/transformBundle.js
test/sourcemaps/loaders/_config.js
test/sourcemaps/loaders/bar.js
test/sourcemaps/loaders/foo.js
test/sourcemaps/loaders/main.js

With this pull request, a loader can return either a `code` string or a `{ code, map }` object, just like a transformer.
The sourcemap can reference whatever sources it wants, or it can provide no sources, in which case it will be assumed to have one source which is the same as the module's ID.
One source can be referenced by multiple modules' sourcemaps; if no sourcemap provides the source content or if some sourcemaps provide source content while others don't, that will work, but an error will be thrown if multiple sourcemaps provide conflicting content for one source.
Sources, source roots, and module IDs are all assumed to function like normal paths. I'm not sure that's a good way to handle them, since a plugin could produce a sourcemap referencing a URI or maybe even some exotic …

Make it possible for plugin loaders to provide sourcemaps.

---

package.json
rollup.config.js

Fixes #725 by adding a build target for ES modules, and pointing the `jsnext:main` field to it.

Add build target for ES modules

---

bin/src/runRollup.js
test/cli/config-external-function/_config.js
test/cli/config-external-function/_expected.js
test/cli/config-external-function/main.js
test/cli/config-external-function/rollup.config.js

Rollup generate TypeError when options.external is a function in rollup.config.js
bin/rollup:746:4
```
TypeError: (options.external || []).concat is not a function
```

Handle options.external is a function.

---

.gitignore
bin/src/handleError.js
bin/src/runRollup.js
test/cli/node-config-auto-prefix/_config.js
test/cli/node-config-auto-prefix/_expected.js
test/cli/node-config-auto-prefix/main.js
test/cli/node-config-auto-prefix/node_modules/rollup-config-foo/lib/config.js
test/cli/node-config-auto-prefix/node_modules/rollup-config-foo/package.json
test/cli/node-config/_config.js
test/cli/node-config/_expected.js
test/cli/node-config/main.js
test/cli/node-config/node_modules/foo/lib/config.js
test/cli/node-config/node_modules/foo/package.json

See #736. This PR allows you to do this...
```bash
rollup -c node:some-plugins-i-like -i src/main.js -o dist/bundle.js
```
...and as long as either `some-plugins-i-like` or `rollup-config-some-plugins-i-like` is a package that exports a [config file](https://github.com/rollup/rollup/wiki/Command-Line-Interface#using-a-config-file), Rollup will use it.

Use config files installed in `node_modules`

---

src/Module.js
src/utils/collapseSourcemaps.js
test/sourcemaps/excludes-plugin-helpers/_config.js
test/sourcemaps/excludes-plugin-helpers/helper.js
test/sourcemaps/excludes-plugin-helpers/main.js

Via https://github.com/rollup/rollup-plugin-babel/issues/64 – including helpers (e.g. `babelHelpers`) in sourcemaps causes all sorts of chaos. It makes more sense to exclude these virtual modules from the sourcemap.
In magic-string, you can exclude a source from the `sources` array by not giving it a filename, so this just filters out sources that have the `\0` character (convention to indicate plugin helpers/virtual modules).

exclude plugin helpers from sourcemaps

---

src/Bundle.js
src/utils/array.js
src/utils/collapseSourcemaps.js
src/utils/transform.js
src/utils/transformBundle.js
test/sourcemaps/transform-without-sourcemap/_config.js
test/sourcemaps/transform-without-sourcemap/main.js
test/test.js

Ref #746. This PR does two things:
* If a sourcemap is requested but a transformer plugin failed to generate a sourcemap for its transformation, Rollup will warn that the sourcemap is likely to be incorrect, but won't fail the build
* If a plugin has a `name` property, it'll be used in warnings and errors where possible
No plugin (that I'm aware of!) currently has a `name` property, but we can add it to the ones owned by the rollup organisation. Eventually it'll probably make sense to print warnings for plugins that don't supply a name, to incentivise plugin authors to add it, but no reason to do that just yet.

indicate source of transform error where possible, and downgrade non-sourcemap-generating transforms to a warning

---

bin/src/runRollup.js
test/cli/no-strict/_config.js
test/cli/no-strict/_expected.js
test/cli/no-strict/main.js

I've found `--no-strict` option is not mapping from cli, this PR fix it.
Also added test for this.

FIX: --no-strict command line option not map bug

---

bin/src/runRollup.js
rollup.config.cli.js
test/cli/config-cwd-case-insensitive/_config.js
test/cli/config-cwd-case-insensitive/main.js
test/cli/config-cwd-case-insensitive/rollup.config.js
test/sourcemaps/relative-paths/_config.js
test/test.js

It's possible for the require.extensions['.js'] override to fail on Windows because path.resolve(...) might return "c:\..." while fs.realpath(...) returns "C:\...", and the exact match fails.

Use fs.realpathSync() rather than path.resolve() on the config path

---

src/rollup.js
test/test.js

This proposal came out of the conversation in #742 to try and pass a bit more information along to `ongenerate`/`onwrite` so that they can be more useful. Specifically trying to make it so that `ongenerate` is able to add values to the output of `.generate()` so that `onwrite` or API users can see it. This would allow me to clean up some gross stuff I'm doing in the `modular-css` rollup plugin, and hopefully will allow clearer differentiation between the use-cases for `ongenerate` and `onwrite`.
@Rich-Harris @TrySound would love your thoughts on whether or not this improves things. It's a small change & all tests still pass w/o modification.

Give ongenerate/onwrite more access

---

src/Bundle.js
src/rollup.js
test/form/paths-function/_config.js
test/form/paths-function/_expected/amd.js
test/form/paths-function/_expected/cjs.js
test/form/paths-function/_expected/es.js
test/form/paths-function/_expected/iife.js
test/form/paths-function/_expected/umd.js
test/form/paths-function/main.js
test/form/paths-relative/_config.js
test/form/paths-relative/_expected/amd.js
test/form/paths-relative/_expected/cjs.js
test/form/paths-relative/_expected/es.js
test/form/paths-relative/_expected/iife.js
test/form/paths-relative/_expected/umd.js
test/form/paths-relative/main.js
test/form/paths/_config.js
test/form/paths/_expected/amd.js
test/form/paths/_expected/cjs.js
test/form/paths/_expected/es.js
test/form/paths/_expected/iife.js
test/form/paths/_expected/umd.js
test/form/paths/main.js
test/test.js

closes #754. Allows you to specify the path of an external module, making it straightforward to (for example) create an AMD bundle that loads specific libraries from a CDN

support paths config

---

src/Bundle.js
src/Module.js

This might do the trick.
But since fetchAllDependencies() and fetchModule() call each other, this may just hide the real bug / introduce new ones... not sure.

Initialize member in constructor, fixes #813

---

src/Bundle.js
test/function/does-not-mangle-entry-point/_config.js

Normalizing the entry ID before passing it to any plugins is redundant, because if it's a path, it will be normalized in resolveId like any other ID. If it isn't a path, normalizing it before passing it to resolveId may mangle it in a surprising way, such as by replacing backslashes with forward slashes.

Leave it up to resolveId to normalize the entry path.

---

src/finalisers/umd.js

Most javascript engines do a lazy parsing optimization. For example if they see:
function X() {...}
They won't parse the contents of X until it is executed. However they often have to read the contents of X so that they can see if X uses any variables from the outer scope. Thus X ends up getting parsed twice.
Realizing that often one immediately executes a function, browser have optimized statements of the form:
(function X() {...})()
So that X is not parsed lazily. Traditionally this optimization looks for an open paren before the function. For example, here's the optimization in v8:
https://github.com/v8/v8/blob/203391bcc0e970d3cae27ba99afd337c1c5f6d42/src/parsing/parser.cc#L4256
Since the factory is immediately executed (at least in the commonJS and global export case), this change …

Avoid lazy parsing by adding parens around factory

---

src/Module.js

This should allow comments to stay above the imported module code when bundled. I did this so that my file name and code coverage specific comments would be preserved.

Preserve comments ahead of import statements.

---

src/Module.js
test/test.js

It looks like https://github.com/rollup/rollup/commit/ebd5ead5e6f9b40960f73d03027c9ef2ad1e4c4d has caused some bugs related to leaky state, e.g. https://github.com/rollup/rollup/issues/875 (have verified that this PR fixes the issue). @TrySound I think we should revert that change until we're confident we can prevent unnecessary cloning without causing those bugs – this PR changes the tests so that the bundle is shared between targets, which will make that easier

prevent leaky state, always clone magic-string

---

src/ast/nodes/ClassDeclaration.js
test/function/deconflicts-classes/_config.js
test/function/deconflicts-classes/a.js
test/function/deconflicts-classes/b.js
test/function/deconflicts-classes/main.js

Bug in 0.35 – deconflicted class IDs weren't being rendered. (Funnily enough, didn't see this until I tried to use Rollup 0.35 to roll up Rollup.)

deconflict classes

---

src/utils/flushTime.js

I was upgrading the version of Rollup used by gulp-rollup when suddenly almost all of my tests started failing on Travis with the error `process.hrtime() only accepts an Array tuple.`.
Turns out Rollup had been updated again while I was working, introducing this error. Tracking that down was fun. So here's a fix&mdash;enjoy.

Fix "process.hrtime() only accepts an Array tuple." error.

---

src/ast/scopes/ModuleScope.js
test/function/namespacing-in-sub-functions/_config.js
test/function/namespacing-in-sub-functions/main.js
test/function/namespacing-in-sub-functions/problematicFunc.js

This fixes #910. I've added a failing test that succeeds once the fix is in place. I also tested this PR on PouchDB, and it fixes https://github.com/pouchdb/pouchdb/pull/5673#issuecomment-246186805 .
Apparently what was happening here was that functions re-assigned upon import were not causing proper deshadowing in other variables inside of subfunctions. So in the test, this:
```js
// problematicFunc.js
function problematicFunc() {
return 'foobar';
}
export { problematicFunc };
```
```js
// main.js
import { problematicFunc as otherFunc } from './problematicFunc';
function innerFunc() {
function problematicFunc () {
return otherFunc();
}
return problematicFunc();
}
var res = innerFunc();
export default res;
```
Would get (incorrectly) compiled to:
```js
function problematicFunc() {
return …
```

Correctly deshadow re-assigned module functions

---

.travis.yml
appveyor.yml
rollup.config.js
test/function/deconflicts-classes/_config.js
test/function/identifiers-in-template-literals/_config.js
test/function/rename-conditional-expression-children/_config.js

Emoji reactions please... Turns out this wasn't at all hard to do, and has minimal impact on the build. So I'm 👍 if it makes life easier for Ember folks.
Ember is dropping support for 0.12 on Jan 1 2017, so we could probably do likewise then.

Reinstate support for Node 0.12

---

src/Bundle.js
test/form/namespace-optimization-b/_expected/amd.js
test/form/namespace-optimization-b/_expected/cjs.js
test/form/namespace-optimization-b/_expected/es.js
test/form/namespace-optimization-b/_expected/iife.js
test/form/namespace-optimization-b/_expected/umd.js
test/function/namespacing-collisions-2/Material.js
test/function/namespacing-collisions-2/MaterialAgain.js
test/function/namespacing-collisions-2/Something.js
test/function/namespacing-collisions-2/SomethingAgain.js
test/function/namespacing-collisions-2/_config.js
test/function/namespacing-collisions-2/main.js
test/function/namespacing-collisions/Material.js
test/function/namespacing-collisions/Something.js
test/function/namespacing-collisions/_config.js
test/function/namespacing-collisions/main.js

As @Benjamin-Dobell pointed out in https://github.com/rollup/rollup/issues/910#issuecomment-246220533, there's another case where deshadowing was not working correctly.
If you do `import * as Foo` in one place, and then `import { Foo }` in another, then those two `Foo` declarations aren't checked for namespace collisions. In fact, the problem is with the `import * as Foo`, because `Foo` doesn't get added to the list of usages and therefore isn't checked when doing `getSafeName()`.
I fixed that issue; the two new added tests fail before the fix but succeed after. (In fact they throw an error if you try to execute them.)  Unfortunately there's an aesthetic regression in this PR in that it can too-aggressively deshadow, as shown by the fact that I had to change one of the `form` tests to use …

Correctly deshadow star imports when conflicting

---

LICENSE.md
src/finalisers/amd.js
src/finalisers/iife.js
src/finalisers/shared/getInteropBlock.js
src/finalisers/umd.js
src/rollup.js
test/form/interop-false/_config.js
test/form/interop-false/_expected/amd.js
test/form/interop-false/_expected/cjs.js
test/form/interop-false/_expected/es.js
test/form/interop-false/_expected/iife.js
test/form/interop-false/_expected/umd.js
test/form/interop-false/main.js
test/test.js

Hey,
https://github.com/rollup/rollup/issues/939
I've added the interop option, so that there's a possibility to disable it if necessary. I have three small concerns:
1) I needed to add a `/*eslint import/no-unresolved: 0*/` comment to the `interop-false/main.js` file to mark the dependency as unresolved, but that doesn't seems to be pretty and causes the comment to be in the result files, is there anything we can do to remove it in this case?
2) the interop works a little bit differently in the `src/finalisers/cjs.js` file and the implementation is split into few lines, do you have any suggestions for this part? It would be great if you could provide me with some background on this one.
3) should I add it to the docs? What's the best place?
Best,
Emil

add: interop option

---

src/Bundle.js
src/ast/nodes/UpdateExpression.js
test/function/if-statement-with-assignment/_config.js
test/function/if-statement-with-assignment/main.js
test/function/if-statement-with-update/_config.js
test/function/if-statement-with-update/main.js

Fixes #930. In cases where a statement is included for its effects, and those effects aren't known to be relevant until late in the process, but it lives inside a statement (such as an if statement) that doesn't *independently* have any effects, the child statement would be marked for inclusion but the parent wouldn't – meaning the whole lot got stripped out.
This fixes that by including all ancestors of an expression with effects, up to the closest function boundary.

include all ancestors of expression with effects, up to function boundary

---

src/rollup.js
src/utils/validateKeys.js

Hi @Rich-Harris @TrySound ,
in this PR I extracted options validation into a function according to single responsibility principle. 
There is `checkOptions` function now, which returns an error if options are incorrect, otherwise `null`. Function `rollup` is responsible to return promise, so it wraps error from `checkOptions` into rejection.
Also in this PR I removed dependency on `key` both from `validateKeys` function and module.
If something wrong please tell me, I ready to fix it according your recommendations.

Extract options validation into a method

---

src/Module.js
src/utils/relativeId.js
test/function/import-of-unexported-fails/_config.js
test/test.js

Addresses #1033 – changes the error message from
> Module /path/to/my/project/src/foo.js does not export bar (imported by /path/to/my/project/src/baz.js)
to
> 'bar' is not exported by src/foo.js (imported by src/baz.js). For help fixing this error see https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module

better error for missing export (#1033)

---

src/ast/nodes/ThisExpression.js
test/function/warn-on-top-level-this/_config.js
test/function/warn-on-top-level-this/main.js

When during a bundling I get a cryptic message stating `The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten`, it's not very helpful to find actual problematic module especially since it can occur anywhere inside node_modules.
Adding module ID to the message should help locate and possibly remove the problem.

Add module id when warning about top level this

---

README.md

To help folks who are less comfortable with CLI help dialogs, this adds a link to [this tutorial series](https://code.lengstorf.com/learn-rollup-js/) to help new developers get up-to-speed quickly with Rollup.

docs(tutorial): added a reference to the tutorial series

---

src/Bundle.js

Hi,
I explored the repo and I found serial `options` updates  by plugins in `Bundle` constructor. I suppose this case is more suitable for `reduce`, not for `forEach`. With `reduce` `options` will be rewritten once.
I think this code looks more declarative and shows that meaning of this block is more about `options` update and less about `plugins` iteration. As side effect there is performance micro-optimisation.
/cc @Rich-Harris @TrySound @Victorystick

reduce instead forEach to update options 

---

src/Declaration.js
test/form/prefer-const/_expected/amd.js
test/form/prefer-const/_expected/cjs.js
test/form/prefer-const/_expected/es.js
test/form/prefer-const/_expected/iife.js
test/form/prefer-const/_expected/umd.js

gracefully fallback for `Object.freeze` to make it more compatible in browser that don't support it.

ADD: fallback for Object.freeze

---

src/Declaration.js
test/form/legacy-getter/_config.js
test/form/legacy-getter/_expected/amd.js
test/form/legacy-getter/_expected/cjs.js
test/form/legacy-getter/_expected/es.js
test/form/legacy-getter/_expected/iife.js
test/form/legacy-getter/_expected/umd.js
test/form/legacy-getter/browserStuff.js
test/form/legacy-getter/main.js

This prevents rollup from outputting object getters for reassigned exports (which will trigger a syntax error when `Object.freeze()` is skipped).
Related to #1068, based on comments from https://github.com/futurist/rollup-plugin-es3/issues/3 , ~~will try to add~~ added a test for this.

Do not output getter defs when in legacy mode

---

bin/src/index.js
bin/src/runRollup.js
src/finalisers/amd.js
src/finalisers/cjs.js
src/finalisers/umd.js
test/form/legacy/_config.js
test/form/legacy/_expected/amd.js
test/form/legacy/_expected/cjs.js
test/form/legacy/_expected/es.js
test/form/legacy/_expected/iife.js
test/form/legacy/_expected/umd.js
test/form/legacy/main.js
test/form/legacy/namespace.js

This PR does below things for `option.legacy=true`
1. Remove `Object.define` esModule line
2. Also pass the `legacy` option to CLI
3. Test for the new code, fix previously legacy test use case.

[fix] remove Object.define for legacy; pass into cli; test legacy

---

src/Declaration.js
test/form/legacy/_expected/amd.js
test/form/legacy/_expected/cjs.js
test/form/legacy/_expected/es.js
test/form/legacy/_expected/iife.js
test/form/legacy/_expected/umd.js

In addition to pull request #989.
This adds single quotes around property names inside module definition, if `legacy` option is set, to prevent reserved words to appear in object keys.
Example output:
``` javascript
var foo = (Object.freeze || Object)({
'default': bar
});
```

Quote names in module definition if legacy option is set

---

src/finalisers/iife.js
src/finalisers/shared/propertyStringFor.js
src/finalisers/umd.js
test/form/module-name-scoped-package/_config.js
test/form/module-name-scoped-package/_expected/amd.js
test/form/module-name-scoped-package/_expected/cjs.js
test/form/module-name-scoped-package/_expected/es.js
test/form/module-name-scoped-package/_expected/iife.js
test/form/module-name-scoped-package/_expected/umd.js
test/form/module-name-scoped-package/main.js
test/form/module-name-wat/_config.js
test/form/module-name-wat/_expected/amd.js
test/form/module-name-wat/_expected/cjs.js
test/form/module-name-wat/_expected/es.js
test/form/module-name-wat/_expected/iife.js
test/form/module-name-wat/_expected/umd.js
test/form/module-name-wat/main.js
test/form/module-name-with-dashes/_config.js
test/form/module-name-with-dashes/_expected/amd.js
test/form/module-name-with-dashes/_expected/cjs.js
test/form/module-name-with-dashes/_expected/es.js
test/form/module-name-with-dashes/_expected/iife.js
test/form/module-name-with-dashes/_expected/umd.js
test/form/module-name-with-dashes/main.js

Allow arbitrary `moduleName` (including names with dashes like `ui-router` or scoped npm packages like `@angular/core`) to be added to the global object.
Closes #582
Closes #584

Access global.* using array notation

---

src/ast/nodes/ExportDefaultDeclaration.js

Likely workaround for #1146 (incorrect `ExportDefaultDeclaration.start` generated by `rollup-plugin-json`)

accomodate incorrect ExportDefaultDeclaration.start produced by rollup-plugin-json

---

src/ast/nodes/CallExpression.js
src/ast/nodes/NewExpression.js
src/ast/nodes/shared/callHasEffects.js
test/form/side-effect-es5-classes/_config.js
test/form/side-effect-es5-classes/_expected/amd.js
test/form/side-effect-es5-classes/_expected/cjs.js
test/form/side-effect-es5-classes/_expected/es.js
test/form/side-effect-es5-classes/_expected/iife.js
test/form/side-effect-es5-classes/_expected/umd.js
test/form/side-effect-es5-classes/arrow.js
test/form/side-effect-es5-classes/bar.js
test/form/side-effect-es5-classes/baz.js
test/form/side-effect-es5-classes/corge.js
test/form/side-effect-es5-classes/foo.js
test/form/side-effect-es5-classes/main.js
test/form/side-effect-es5-classes/qux.js
test/form/unmodified-default-exports/_expected/amd.js
test/form/unmodified-default-exports/_expected/cjs.js
test/form/unmodified-default-exports/_expected/es.js
test/form/unmodified-default-exports/_expected/iife.js
test/form/unmodified-default-exports/_expected/umd.js
test/form/unmodified-default-exports/foo.js
test/function/es5-class-called-without-new/_config.js
test/function/es5-class-called-without-new/foo.js
test/function/es5-class-called-without-new/main.js

This PR adds in the following optimization (which fixes https://github.com/rollup/rollup/issues/179#issuecomment-250903867):
When using `new Foo(...)` and the `Foo` function is "pure", then the `new Foo(...)` is removed.
A function is pure if it meets all of the following conditions:
- It is called with `new Foo(...)`
- The only side effects it contains are of the form `this.foo = bar` or `this[foo] = bar` (the expressions `foo` and `bar` can be anything, but they may not contain side effects)
- It does not have any other side effects
- It is an ES5 function (e.g. not an arrow function)
This detection is currently very limited: it requires the assignment to occur at the top level of the function, and it does not support nested assignment (e.g. `this.foo.bar = qux`)
The detection can be …

Removes `new Foo(...)` when Foo is a pure function

---

src/Bundle.js
src/Module.js
test/function/sourcemapping-url-multiline/_config.js
test/function/sourcemapping-url-multiline/main.js

Fixes https://github.com/rollup/rollup/issues/988#issuecomment-251017219

prevent false positives for sourcemapping url comments with newlines

---

src/Module.js
src/ast/nodes/ExportNamedDeclaration.js
test/function/default-export-as-is-bound/_config.js
test/function/default-export-as-is-bound/foo.js
test/function/default-export-as-is-bound/main.js
test/function/export-as-default/_config.js
test/function/export-as-default/foo.js
test/function/export-as-default/main.js

fixes #1078. One of those rare, happy cases where implementing the correct behaviour is achieved by deleting a few dozen lines of code.

[BREAKING] fix behaviour of export { foo as default }

---

src/Module.js
test/form/async-function-unused/_config.js
test/form/async-function-unused/_expected/amd.js
test/form/async-function-unused/_expected/cjs.js
test/form/async-function-unused/_expected/es.js
test/form/async-function-unused/_expected/iife.js
test/form/async-function-unused/_expected/umd.js
test/form/async-function-unused/main.js
test/form/async-function-unused/utils.js

Ref #492. This won't fix the issue (which is that Babel transpiles async functions to something hard to treeshake), but it provides an alternative – treeshaking the async function in Rollup *then* running Babel on the bundle, rather than on individual modules.
(In many cases you'd need a hybrid approach – transpiling with Babel beforehand so that Rollup can parse the module but *not* using any plugins that transpile async functions, then running the async transformation afterwards.)

support async functions

---

src/ast/nodes/ExportDefaultDeclaration.js
test/function/warn-on-ambiguous-function-export/_config.js
test/function/warn-on-ambiguous-function-export/foo.js
test/function/warn-on-ambiguous-function-export/main.js
test/function/wraps-ambiguous-default-export/_config.js
test/function/wraps-ambiguous-default-export/foo.js
test/function/wraps-ambiguous-default-export/main.js

Fixes two things related to #1011.
Firstly, in a situation like this...
```js
export default function foo () {}
(function iife () {
// code goes here
}())
```
...it will print a warning that you're exporting a call expression when you probably thought you were exporting the `foo` declaration.
Secondly, [this valid (if unusual) JavaScript](http://rollupjs.org/?version=0.38.1&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJy4lMkZmb28uanMnJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmZvby5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBkZWZhdWx0JTIwZnVuY3Rpb24lMjBmb28lMjAoJTIweCUyMCklMjAlN …

warn if exporting an IIFE that looks like a function declaration, and wrap in parens if necessary

---

bin/src/runRollup.js
src/Bundle.js
src/utils/relativeId.js
test/function/custom-path-resolver-async/_config.js
test/function/custom-path-resolver-sync/_config.js
test/function/does-not-hang-on-missing-module/_config.js
test/function/unused-import/_config.js

This started out as a response to https://github.com/rollup/rollup/issues/1051#issuecomment-267878171 but I decided it makes more sense to just have a better warning than 'Treating xxx as external dependency'. It now tells you the importing module, and points you to [this wiki section](https://github.com/rollup/rollup/wiki/Troubleshooting#treating-module-as-external-dependency).

more informative warning for implicit external dependencies

---

src/finalisers/amd.js
src/finalisers/iife.js
src/finalisers/shared/warnOnBuiltins.js
src/finalisers/umd.js
test/test.js

More #1051. This warns if the bundle has external dependencies on Node.js builtins, but only if the bundle is a browser bundle (AMD, UMD or IIFE) since the assumption otherwise is that you're either running the bundle in Node or running it through another tool like Webpack.

warn about using node built-ins in browser bundle (#1051)

---

src/Module.js
src/ast/clone.js
src/utils/object.js
test/test.js

This fixes the dreaded 'Maximum call stack size exceeded' error that occurs with rollup-watch when a file with an error is subsequently fixed. It does so by preventing mutations of the cached AST, which is reused between incremental builds for files that *don't* have errors.
Fixes #1153, #1010, and https://github.com/rollup/rollup-watch/issues/21.

prevent mutation of cached ASTs

---

bin/src/handleError.js
bin/src/runRollup.js
rollup.config.cli.js

apply kzc patch to prevent escape codes and emojis appearing in non-TTY stderr

---

src/ast/nodes/MemberExpression.js
test/form/namespace-optimization-computed-string/_config.js
test/form/namespace-optimization-computed-string/_expected/amd.js
test/form/namespace-optimization-computed-string/_expected/cjs.js
test/form/namespace-optimization-computed-string/_expected/es.js
test/form/namespace-optimization-computed-string/_expected/iife.js
test/form/namespace-optimization-computed-string/_expected/umd.js
test/form/namespace-optimization-computed-string/bar.js
test/form/namespace-optimization-computed-string/foo.js
test/form/namespace-optimization-computed-string/main.js
test/form/namespace-optimization-computed-string/quux.js

This is #841 revisited (since that PR was against an ancient version of the codebase and would be hopeless to try and merge). It means that `namespace['foo']` and `namespace.foo` are treated the same way for the purposes of tree-shaking.

optimize namespace["foo"]

---

src/ast/nodes/MemberExpression.js
test/function/this-not-namespace/_config.js
test/function/this-not-namespace/main.js

don't treat this.foo as possible namespace

---

src/Bundle.js

- only add named exports to module.exportsAll
\* I didn't add any tests to this since it's only a warning and is really  just an extension of [the fix](https://github.com/rollup/rollup/pull/1038) for #1028
If you would prefer me to write a test and re-send the PR, I will certainly do that.

fixes #1278

---

src/Bundle.js
test/function/warn-on-namespace-conflict/_config.js

- only set module.exportsAll when no conflict is found
- fix warning in test

fix incorrect namespace conflict warning

---

bin/src/logging.js

Before this change, in plugins like this: 
https://github.com/rollup/rollup-plugin-babel/blob/master/src/index.js#L39
will just get `undefined` in the output when running standalone rollup cli
I haven't have the time to to look very in depth at all the code, but I found a couple of places (both in rollup itself and in external plugins) where the caller is passing a string, so since fixing all the plugins is probably a non-starter, I figure making the API support strings was the easiest.
You might want to change the param name of the function or do a more strict type check maybe.

Allowing logging message to be of string type

---

src/ast/nodes/BinaryExpression.js
test/function/allows-unknown-binary-operators/_config.js
test/function/allows-unknown-binary-operators/main.js

- fix issue #1416
- the issue exposes rollup's assumption that it knows
about all binary operators which is untrue for future
ES versions.  The fix is to return UNKNOWN when
the operator is not in the hardcoded hash.
- the test must have the subtraction symbol before the
exponent operator in order for the
<Binary Operator>.getValue code to run

allow unknown binary operators

---

bin/src/runRollup.js

This PR adds support for rolling multiple bundles (with their own configs, or at least with their own entry/dest options) in parallel. `rollup.config.js` can now export an array of objects, or a single object.

Support multiple configs/bundles in parallel

---

src/ast/scopes/ModuleScope.js
test/function/already-deshadowed-import/_config.js
test/function/already-deshadowed-import/alice.js
test/function/already-deshadowed-import/bob.js
test/function/already-deshadowed-import/main.js

previously deshadowed names if available
Fixes issue in https://github.com/rollup/rollup/issues/1384

When collecting imported names to deshadow the current ModuleScope, use

---

src/ast/nodes/ClassDeclaration.js

main.js
```js
import { Foo } from './foo'
console.log(Foo.name)
```
foo.js
```js
export class Foo {
}
```
output
```js
console.log(Foo.name)
```
This bug comes from 173cfc0d

fix class removed when `treeshake: false`

---

src/finalisers/amd.js
src/finalisers/umd.js
src/rollup.js
test/form/define-replacement/_config.js
test/form/define-replacement/_expected/amd.js
test/form/define-replacement/_expected/cjs.js
test/form/define-replacement/_expected/es.js
test/form/define-replacement/_expected/iife.js
test/form/define-replacement/_expected/umd.js
test/form/define-replacement/a.js
test/form/define-replacement/main.js
test/test.js

Alternative to #1363. I think it probably makes sense to group `moduleId` and `defineReplacement` under a single `amd` option, since it feels a bit neater and is possibly a bit more 'discoverable'.
Also, this ought to apply to UMD output as well as AMD.
@stefanpenner thoughts?

options.amd

---

src/rollup.js
test/function/watch-option/_config.js
test/function/watch-option/main.js
test/test.js

This adds `watch` to the list of expected options. We need this so that we can pass through options to `rollup-watch`, such as `useChokidar` (without which we can't even test whether chokidar is working — it currently isn't, which will be fixed soon), and potentially other things we might add in future

add a watch option

---

src/finalisers/shared/getInteropBlock.js
test/form/export-default-import/_expected/amd.js
test/form/export-default-import/_expected/iife.js
test/form/export-default-import/_expected/umd.js
test/form/external-imports-custom-names/_expected/amd.js
test/form/external-imports-custom-names/_expected/iife.js
test/form/external-imports-custom-names/_expected/umd.js
test/form/external-imports/_expected/amd.js
test/form/external-imports/_expected/iife.js
test/form/external-imports/_expected/umd.js
test/form/paths-function/_expected/amd.js
test/form/paths-function/_expected/iife.js
test/form/paths-function/_expected/umd.js
test/form/paths-relative/_expected/amd.js
test/form/paths-relative/_expected/iife.js
test/form/paths-relative/_expected/umd.js
test/form/paths/_expected/amd.js
test/form/paths/_expected/iife.js
test/form/paths/_expected/umd.js
test/form/relative-external-with-global/_expected/amd.js
test/form/relative-external-with-global/_expected/iife.js
test/form/relative-external-with-global/_expected/umd.js

Resolves https://github.com/rollup/rollup/issues/1341
Most interopts I've seen, babel, webpack, and rollup's [cjs interop](https://github.com/rollup/rollup/blob/master/src/finalisers/cjs.js#L42) check for the existence of the imported value prior to checking for `default`.
I tried to read the ecma specs but they're pretty confusing.  Is this expected to throw an error?
```js
import foo from 'file-does-not-exist';
// or would it just be undefined?
foo === undefined;
```
Even _if_ it would throw an error in ES2015 modules, if I know my target is UMD anyways, why not allow it to import without an error?

Allow undefined import in interop

---

src/Bundle.js
src/Declaration.js
src/ExternalModule.js
src/rollup.js
test/form/prune-pure-unused-import/_config.js
test/form/prune-pure-unused-import/_expected/amd.js
test/form/prune-pure-unused-import/_expected/cjs.js
test/form/prune-pure-unused-import/_expected/iife.js
test/form/prune-pure-unused-import/_expected/umd.js
test/form/prune-pure-unused-import/main.js
test/test.js

Resolves https://github.com/rollup/rollup/issues/1352
I didn't get a chance to fully get familiarized with the codebase so not sure if this is the best way to implement it, but this seems to work. I'll definitely need to add a few more tests, but figured I'd throw this up in the meantime.
I've made this feature  configurable based on the config I described in  https://github.com/rollup/rollup/issues/1352, reproduce below:
```js
{
// The default option. Assume all external modules have side effects and don't remove unused imports
pureExternalImports: false, 
// Assume all external modules don't have side effects and remove unused imports
pureExternalImports: true, 
// Assume all external modules but 'foo' and 'bar' have imports with side effects
pureExternalImports: {
pure: ['foo', 'bar'] …
```

Prune unused pure external imports

---

CHANGELOG.md

Looks like the option is actually named `pureExternalModules`

`pureExternalImports` -> `pureExternalModules` in Changelog

---

bin/src/logging.js
src/utils/error.js

issue ref: #1433
Improved the error logging a little bit so that you can see where an error is located.
old (rollup v0.43.0)
```
$ rollup -c -f iife -i src/app.js -o bundle.js
🚨   (buble plugin) Unexpected token (1:24)
undefined (1:24)
```
new (needs to be `npm version patch`ed if merged)
```
$ /Users/mollie/temp/rollup/bin/rollup -c -f iife -i src/app.js -o bundle.js
🚨   (buble plugin) SyntaxError: Unexpected token (1:24)
src/subdir/mod.js (1:24)
````

better error logging information

---

src/rollup.js

Some recent changes introduced in `0.43.0` breaks the amd named module generation.
The checkOptions function is applied only on the main entry point (rollup), but not in the generate() function.
Basically when passing this options:
```js
// Passing a set of options
rollup({ entry, plugins, ..otherOptions }).then(() => {
... 
// Passing another set of options
bundle.generate({ format: 'amd', moduleId: 'something' });
...
```
The output does respect the `moduleId` option, nor does it error out.
This change addresses this inconsistency, and it will give the same warning.
We tried to add a tests but the tests makes the assumption that both entry points rollup and bundle will receive the same options object, which is not necessarily imposed in the API.
//cc @pmdartus who coPR this.

Run same options transform on generate for bundle

---

package-lock.json
package.json
test/sourcemaps/names-transformed/_config.js
test/sourcemaps/transform-bundle/_config.js

This PR updates Uglify-JS from v2 to v3, while also adjusting the code to conform the new API.
Uglify-JS is only used for internal testing, namely in two `_config.js` files.
All tests work after updating; `npm run lint` runs with success.

update uglify-js to v3

---

src/Bundle.js

Should fix https://github.com/rollup/rollup/issues/883
"options" argument is captured by closures in Bundle constructor, so passing "cache" leads to chain of bundles in memory. 
Similar bug is described here: https://blog.meteor.com/an-interesting-kind-of-javascript-memory-leak-8b47d2e7f156
I've created gist with test script, but don't known how to properly integrate it here.
https://gist.github.com/dmitrage/fff3d30280688356194c137323ea4e02

Fix closure memory leak in Bundle constructor

---

bin/src/runRollup.js
src/Bundle.js
src/rollup.js
src/utils/transformBundle.js
test/function/bundle-transformer-async/_config.js
test/function/bundle-transformer-async/main.js
test/test.js

Attempt at solving the https://github.com/rollup/rollup/issues/1474 issue.
A real-life scenario where this could be useful is if you need to build the same code (same entry) with different parameters and minify the resulting bundles with Google Closure Compiler.
Because Google Closure Compiler is a java program, it needs to be started via a `spawn` call. At the moment, rollup only allows for synchronous `transformBundle` methods with means that we need to use the sync version of `spawn`: `spawnSync`.
This change essentially wraps the `transformBundle` calls into promises, and propagate the behaviour all the way up to the `generate` function. As a result, this means changing the signature of `generate` to return a promise, making this feature a **breaking change**.
I guess the code could …

Support for async transformBundle

---

package.json
src/finalisers/shared/getInteropBlock.js
test/form/export-default-import/_expected/amd.js
test/form/export-default-import/_expected/iife.js
test/form/export-default-import/_expected/umd.js
test/form/external-imports-custom-names/_expected/amd.js
test/form/external-imports-custom-names/_expected/iife.js
test/form/external-imports-custom-names/_expected/umd.js
test/form/external-imports/_expected/amd.js
test/form/external-imports/_expected/iife.js
test/form/external-imports/_expected/umd.js
test/form/paths-function/_expected/amd.js
test/form/paths-function/_expected/iife.js
test/form/paths-function/_expected/umd.js
test/form/paths-relative/_expected/amd.js
test/form/paths-relative/_expected/iife.js
test/form/paths-relative/_expected/umd.js
test/form/paths/_expected/amd.js
test/form/paths/_expected/iife.js
test/form/paths/_expected/umd.js
test/form/relative-external-with-global/_expected/amd.js
test/form/relative-external-with-global/_expected/iife.js
test/form/relative-external-with-global/_expected/umd.js

Addresses #1486 
Fixes the issue with TypeError that occurs when using `'default' in string`

Error occurs when using webpack loader query string as import in rollup

---

src/ast/nodes/SwitchStatement.js
src/ast/nodes/index.js
test/form/switch-scopes/_config.js
test/form/switch-scopes/_expected/amd.js
test/form/switch-scopes/_expected/cjs.js
test/form/switch-scopes/_expected/es.js
test/form/switch-scopes/_expected/iife.js
test/form/switch-scopes/_expected/umd.js
test/form/switch-scopes/main.js

In Javascript, switch statements introduce a local scope which means that variables can be re-declared inside of them. This pull request implements this behaviour and includes several test cases. To illustrate:
**Test cases:**
```javascript
const x = globalFunction;
function y () {}
switch ( anotherGlobal ) {
case 1:
const x = function () {};
x();
}
switch ( anotherGlobal ) {
case 2:
x();
}
switch ( anotherGlobal ) {
case 3:
const y = globalFunction;
}
y();
switch ( globalFunction() ) {
case 4:
}
```
**Previous output:**
```javascript
const x = globalFunction;
switch ( anotherGlobal ) { // Could have been removed as there are no side-effects
case 1:
const x = function () {};
x();
}
switch ( anotherGlobal ) {
case 2:
x();
}
y(); // This is REALLY bad!
switch ( globalFunction() ) {
case 4: …
```

Correctly handle variables introduced in switch scopes

---

bin/src/help.md
bin/src/run/mergeOptions.js
test/cli/node_modules/foo/lib/config.js
test/cli/node_modules/foo/package.json
test/cli/node_modules/rollup-config-foo/lib/config.js
test/cli/node_modules/rollup-config-foo/package.json
test/cli/samples/interop/_config.js
test/cli/samples/interop/_expected.js
test/cli/samples/interop/main.js
test/cli/samples/silent/_config.js

fixes #1524 , sorry for the other stuff, didn't disable prettier in time. but seems to fail. Rollup does not support `--no-` prefix?
also, there was 2 failing tests before i start.

allow passing interop through cli - true/false

---

package-lock.json
package.json
rollup.config.js
src/browser-entry.js
src/finalisers/es.js
src/node-entry.js
test/form/samples/reexports-name-from-external/_config.js
test/form/samples/reexports-name-from-external/_expected/amd.js
test/form/samples/reexports-name-from-external/_expected/cjs.js
test/form/samples/reexports-name-from-external/_expected/es.js
test/form/samples/reexports-name-from-external/_expected/iife.js
test/form/samples/reexports-name-from-external/_expected/umd.js
test/form/samples/reexports-name-from-external/main.js

`export { foo } from 'bar'` was getting changed to `export { foo }` in `es` output, without the accompanying import that would have made it work.

Export name from

---

bin/src/run/alternateScreen.js
bin/src/run/watch.js
package.json
rollup.config.js

Recently, the output of `rollup --watch` was modified to reset the buffer when changes caused a rebuild. Works brilliantly when invoked in an active terminal, e.g. `rollup -cw`.
However, this really doesn't play nicely with processes that pipe the output from a child process (such as [`lerna exec`](https://github.com/lerna/lerna#exec)), which is effectively a _non_-interactive terminal. Clearing the screen repeatedly causes a bunch of thrashing, as well as unwanted removal of other process logging.
I was unable to locate examples of testing both CLI _and_ watching, so I did a bunch of local testing with npm-linked rollup in several lerna repos where I was using rollup. Here's an example repo I whipped up that demonstrates the problem and solution: …

Do not open alternate buffer during piped --watch

---

src/utils/fs.js

This introduces an additional guard for a situation where 2 instances of rollup being run in parallel try to create the same directory and thus failing, because 1 succeeds and the other one throws.
While I could restructure my scripts I do not see any potential harm in guarding against this and at the moment this causes failing builds from time to time on CI server.
To illustrate better why its even the case, please take look at the configuration in `package.json`:
```json
"scripts": {
"build:umd:min": "cross-env BABEL_ENV=es NODE_ENV=production rollup -c -i src/index.js -o dist/module.min.js",
"build:umd": "cross-env BABEL_ENV=es NODE_ENV=development rollup -c -i src/index.js -o dist/module.js",
"build:cjs": "cross-env BABEL_ENV=cjs babel src --out-dir lib",
"build:es": "cross-env …
```

Guard against 2 parallel rollups trying to make the same dir

---

src/ast/Node.js
src/ast/nodes/AssignmentExpression.js
src/ast/nodes/AwaitExpression.js
src/ast/nodes/CallExpression.js
src/ast/nodes/ExpressionStatement.js
src/ast/nodes/Identifier.js
src/ast/nodes/UnaryExpression.js
src/ast/nodes/UpdateExpression.js
test/form/samples/side-effects-expressions-as-statements/_config.js
test/form/samples/side-effects-expressions-as-statements/_expected/amd.js
test/form/samples/side-effects-expressions-as-statements/_expected/cjs.js
test/form/samples/side-effects-expressions-as-statements/_expected/es.js
test/form/samples/side-effects-expressions-as-statements/_expected/iife.js
test/form/samples/side-effects-expressions-as-statements/_expected/umd.js
test/form/samples/side-effects-expressions-as-statements/main.js

This will resolve #1589 and #1592.
For #1589: In Identifier.js, I assumed that all declarations have assignedExpressions, which is certainly not true for SyntheticNamespaceDeclarations. To be cautious, for now we assume that those always have effects when mutated.
For #1592: It seems that people are calling getters for side-effects and this is something that rollup is not (and was never) prepared for yet. The better solution, as suggested by @kzc , is probably to start adding flags for certain more aggressive aspects of tree-shaking such as assuming that all getters are pure. Until then with this PR, rollup will keep all expression statements that are not usually called as statements because we assume that they are called for side-effects. That seems to cover the cases listed in #1592 and …

Fix regressions when handling assignments and expression statements with side effects

---

CHANGELOG.md

Minor text correction in the CHANGELOG.

Fix typo: outpot -> output

---

bin/src/run/mergeOptions.js

Fix #1573 , #1600 
Both command line and config file can set `output` option, they should be merged but instead of used separately.

merge command & config's output options

---

bin/src/run/mergeOptions.js

Fixes https://github.com/rollup/rollup/issues/1596
The following option now applies.
`
watch: {
chokidar: {
usePolling: true
}
}
`

mergeOptions inputOptions includes config.watch option.

---

bin/src/run/watch.js
package.json

Previously, it was not clear when work had been completed.  This sets clearer expectations for someone monitoring the watcher output as to when they can expect their code to have updated.

Print timestamps on "END" events.

---

src/ast/nodes/ConditionalExpression.js
src/ast/nodes/SequenceExpression.js
src/ast/nodes/index.js
test/form/samples/conditional-expression/_config.js
test/form/samples/conditional-expression/_expected/amd.js
test/form/samples/conditional-expression/_expected/cjs.js
test/form/samples/conditional-expression/_expected/es.js
test/form/samples/conditional-expression/_expected/iife.js
test/form/samples/conditional-expression/_expected/umd.js
test/form/samples/conditional-expression/main.js
test/form/samples/conditional-put-parens-around-sequence/_expected/amd.js
test/form/samples/conditional-put-parens-around-sequence/_expected/cjs.js
test/form/samples/conditional-put-parens-around-sequence/_expected/es.js
test/form/samples/conditional-put-parens-around-sequence/_expected/iife.js
test/form/samples/conditional-put-parens-around-sequence/_expected/umd.js
test/form/samples/conditional-put-parens-around-sequence/main.js
test/form/samples/sequence-expression/_config.js
test/form/samples/sequence-expression/_expected/amd.js
test/form/samples/sequence-expression/_expected/cjs.js
test/form/samples/sequence-expression/_expected/es.js
test/form/samples/sequence-expression/_expected/iife.js
test/form/samples/sequence-expression/_expected/umd.js
test/form/samples/sequence-expression/main.js

This resolves #1649 
The resulting code may have spurious parentheses that wrapped the sequence. For example `var a = (1,2,3)` becomes `var a = (3)` instead of `var a = 3`. Other than that, all cases covered in #1649 are covered.

Treeshake sequence expression

---

src/ast/variables/ExternalVariable.js
test/function/samples/keep-used-imports-from-pure-external-modules/_config.js
test/function/samples/keep-used-imports-from-pure-external-modules/main.js

Due to a failed refactoring, imports of external modules were never included for modules listed in `pureExternalModules`. This fixes that (and adds a test 😜)

Fix regression when using pureExternalModules flag

---

README.md

The Readme was pointing to an out of date starter project. This PR points it to the two starter projects mentioned at [https://rollupjs.org/#quick-start](https://rollupjs.org/#quick-start)

Point Readme to up-to-date starter projects

---

src/ast/ExecutionPathOptions.js
test/function/samples/handle-labels-inside-functions/_config.js
test/function/samples/handle-labels-inside-functions/main.js

Previously, using labels inside functions would trigger a "keypath" error due to some option cleared in the wrong way. This resolves #1706.

Fix issue when using labels inside functions

---

src/ast/nodes/SequenceExpression.js
test/form/samples/sequence-expression/_expected/amd.js
test/form/samples/sequence-expression/_expected/cjs.js
test/form/samples/sequence-expression/_expected/es.js
test/form/samples/sequence-expression/_expected/iife.js
test/form/samples/sequence-expression/_expected/umd.js
test/form/samples/sequence-expression/foo.js
test/form/samples/sequence-expression/main.js

With the recent changes to sequence (i.e. comma) expression handling, variables in sequence expressions were no longer renamed as the new render logic did not call `.render()` on its included children. This PR fixes it. Thanks for everyone who provided input, broken tests, reproductions and who knows what! You are great 👍
This PR is based on and closes #1716.

Fix sequence expressions

---

src/ast/nodes/BlockStatement.js
src/ast/nodes/ReturnStatement.js
src/ast/nodes/UnaryExpression.js
src/ast/scopes/ModuleScope.js
src/ast/scopes/Scope.js
src/ast/values.js
src/ast/variables/ArgumentsVariable.js
src/ast/variables/LocalVariable.js
src/ast/variables/VariableShapeTracker.js
test/form/samples/computed-member-expression-assignments/main.js
test/form/samples/side-effects-getters-and-setters/_expected/amd.js
test/form/samples/side-effects-getters-and-setters/_expected/cjs.js
test/form/samples/side-effects-getters-and-setters/_expected/es.js
test/form/samples/side-effects-getters-and-setters/_expected/iife.js
test/form/samples/side-effects-getters-and-setters/_expected/umd.js
test/form/samples/side-effects-getters-and-setters/main.js
test/form/samples/side-effects-object-literal-mutation/main.js
test/function/samples/recursive-parameter-assignments/_config.js
test/function/samples/recursive-parameter-assignments/main.js

This resolves #1710 and #1711 .
In this update, the object analysis logic is limited to a depth of 2 as it could have a huge performance impact in code bases with many object assignments. Also, computed expression logic has been greatly simplified. Quite a few situations involving computed object keys are now no longer tree-shaken. At the same time, getters will no longer properly detect getters when computed expressions are used.

Resolves issues when dealing with complex object assignments

---

src/ast/nodes/ConditionalExpression.js
test/form/samples/conditional-expression/main.js

Fixes #1719.
**Problem:** Dead branch nodes of conditional expressions were not initialized. i.e. when condition test is known to be true, test node is not initialized.
**Fix:** Initialize all children of conditional expressions similar to how it's done for if statements.
**Test:** Check unit test, it fails before this fix. 
Another approach would be to remove pruned nodes in logical expressions. E.g. `true || foo()` would be pruned to `true`, `false && foo()` would be pruned to `false`.

Fix uninitialized child nodes for conditional expressions

---

src/Module.js
test/function/samples/error-after-transform-should-throw-correct-location/_config.js
test/function/samples/error-after-transform-should-throw-correct-location/main.js

Fixes #1697
Where `error.loc` was not showing the location of the original file but showing the location of the code after transform plugins.

Fix error.loc object to match location with the real file after transform plugins

---

src/ast/nodes/SequenceExpression.js
test/form/samples/sequence-expression/_expected/amd.js
test/form/samples/sequence-expression/_expected/cjs.js
test/form/samples/sequence-expression/_expected/es.js
test/form/samples/sequence-expression/_expected/iife.js
test/form/samples/sequence-expression/_expected/umd.js
test/form/samples/sequence-expression/main.js
test/function/samples/sequence-expression/_config.js
test/function/samples/sequence-expression/main.js

Maintain this context when sequence is callable

---

bin/src/run/watch.js

This fixes #1687.
The default stays the same. This is the first simple solution, not sure if this is ok for you.
I'm also making a pull request to update the guide.

set watch.clearScreen to false to disable clearing the screen in watch mode

---

bin/src/run/loadConfigFile.js

fixes #1758
test preparation:
```bash
npm run build
cat <<EOF >test.js
const a = {b: 1}
const c = {...a}
EOF
```
test execution:
```./bin/rollup --config ./test.js```
<pre>
if it works:
[!] Config file must export an options object, or an array of options objects
https://github.com/rollup/rollup/wiki/Command-Line-Interface#using-a-config-file
if it fails:
[!] Error: Unexpected token
test.js (2:11)
1: const a = {b: 1}
2: const c = {...a}
^
</pre>

Support ES.Next object rest spread in config files like rollup.config.js

---

bin/src/run/index.js
test/cli/samples/config-env-multiple/_config.js
test/cli/samples/config-env-multiple/main.js
test/cli/samples/config-env-multiple/rollup.config.js

Fixes #1764 
Later instances of `--environment` that contain already-defined keys will simply overwrite the previous value, which is what I expect. The test covers this behavior, if that isn't wanted I can change it but it'll complicate the code.
`npm run lint` shows me 18k errors, I don't think that's right? I did use array destructuring so if that isn't kosher in the codebase I'm happy to rewrite it in the longer-form version.

feat: let --environment be specified multiple times

---

bin/src/run/watch.js

As per https://github.com/rollup/rollup-watch/pull/57
Without the added line the previous listener will never be triggered.

Let process.stdin actually trigger it’s end event

---

src/finalisers/es.js
test/form/samples/export-default-2/_expected/es.js
test/form/samples/re-export-default-external/_config.js
test/form/samples/re-export-default-external/_expected/amd.js
test/form/samples/re-export-default-external/_expected/cjs.js
test/form/samples/re-export-default-external/_expected/es.js
test/form/samples/re-export-default-external/_expected/iife.js
test/form/samples/re-export-default-external/_expected/umd.js
test/form/samples/re-export-default-external/first.js
test/form/samples/re-export-default-external/main.js

This is a bug fix for https://github.com/rollup/rollup/issues/1794 (which includes replication).
`default` can be re-exported just like any other export, so this removes the special casing handling that doesn't respect these scenarios.
The only case default export doesn't work through is `export {default} from 'x'` where x contains `export * from 'y'` and y contains `export default 'y'`. The `default` export can't travel through these export * boundaries, but otherwise just acts like any other named export.

Default re-export fix for #1794

---

src/ast/nodes/ExportDefaultDeclaration.js
test/form/samples/export-default-anonymous-declarations/_config.js
test/form/samples/export-default-anonymous-declarations/_expected/amd.js
test/form/samples/export-default-anonymous-declarations/_expected/cjs.js
test/form/samples/export-default-anonymous-declarations/_expected/es.js
test/form/samples/export-default-anonymous-declarations/_expected/iife.js
test/form/samples/export-default-anonymous-declarations/_expected/umd.js
test/form/samples/export-default-anonymous-declarations/async.js
test/form/samples/export-default-anonymous-declarations/class.js
test/form/samples/export-default-anonymous-declarations/fn.js
test/form/samples/export-default-anonymous-declarations/generator.js
test/form/samples/export-default-anonymous-declarations/main.js

Fixes #1798
I updated the regular expressions to match comments, async functions and generators.
They are built at runtime to make them more readable; they are built only once so the performance overhead shouldn't be noticeable.
The built regexes are these:
```js
/^(?:\s|\/\/.*[\n\r]|\/\*[^]*?\*\/)*export(?:\s|\/\/.*[\n\r]|\/\*[^]*?\*\/)+default(?:\s|\/\/.*[\n\r]|\/\*[^]*?\*\/)*/
/^(?:\s|\/\/.*[\n\r]|\/\*[^]*?\*\/)*export(?:\s|\/\/.*[\n\r]|\/\*[^]*?\*\/)+default(?:\s|\/\/.*[\n\r]|\/\*[^]*?\*\/)+(?:(?:async(?:\s|\/\/.*[\n\r]|\/\*[^]*?\*\/)+)?function(?:(?:\s|\/\/.*[\n\r]|\/\*[^]*?\*\/)*\*)?|class)/
```

Fix export default regexs

---

src/Bundle.js
test/function/samples/external-alias-parent/_config.js
test/function/samples/external-alias-parent/first/main.js
test/function/samples/external-alias-parent/first/module.js

Externals as a name space kind of cross various concerns.
This is because the external check is done both pre and post resolve, so that names that exist in both namespaces can conflict between them (eg say `jquery` is an external in resolved space, but some module will have `jquery` resolve to a valid internal name which isn't `jquery`).
It's very much an edge case but I've hit across some scenarios like this already in handling correct external resolution.
To help narrow these cases very specifically this PR adds two new arguments to the external function to make it of the form:
```js
external (name, parent, isResolved)
```
* `parent` is the parent module Id of the module we are check whether it is external.
* `isResolved` is a boolean indicating if the external check is being done pre …

External function parent and resolved argument

---

src/rollup/index.ts
src/utils/transformBundle.ts
test/form/samples/transform-bundle-plugin-options/_config.js
test/form/samples/transform-bundle-plugin-options/_expected/amd.js
test/form/samples/transform-bundle-plugin-options/_expected/cjs.js
test/form/samples/transform-bundle-plugin-options/_expected/es.js
test/form/samples/transform-bundle-plugin-options/_expected/iife.js
test/form/samples/transform-bundle-plugin-options/_expected/umd.js

See #1583 . Reopening this as #1808 was closed accidently after TS branch was merged.

Shares output options with plugins `transformBundle`. Fixes #1583

---

bin/src/run/batchWarnings.ts
bin/src/run/index.ts
bin/src/run/watch.ts
src/rollup/index.ts
src/utils/mergeOptions.ts
test/cli/samples/config-deprecations/rollup.config.js
test/misc/index.js

See #1826. In instances when there's an `unrecognized option` we throw an error and it has bitten us in the past (when I accidently broke the REPL, I'm sorry!).
In this PR, I've instead changed it to a warning, so that we don't break out and try to bundle it with showing a warning to the user. I feel this approach is safer. Also, we're checking for the error only in `src/rollup/index.ts` not at other places.
There was no test which checked multiple targets for `rollup.rollup API`, I've added that too. Let me know if this (`changing Errors to warnings`) approach seems okay to you? @lukastaegert

Removes errors when output options is an array.

---

src/Graph.ts
test/function/samples/custom-path-resolver-async/_config.js
test/function/samples/custom-path-resolver-sync/_config.js

This keeps the warnings fine when a module is not found through the resolver, but an explicit `false` return is taken to mean that the resolver expects the given module to be an external, and as such no warning should be necessary.

Disable external warnings when resolve returns false

---

package-lock.json
package.json
src/ast/ExecutionPathOptions.d.ts
src/ast/ExecutionPathOptions.ts
tsconfig.json

`immutable` now has it's own types

chore: remove `@types/immutable`

---

bin/src/logging.ts

Use [`chalk.supportsColors`](https://github.com/chalk/chalk#chalksupportscolor) rather than checking if `stderr` is a `TTY`. 
This should be equivalent to the current code except when `--colors` or `--no-colors` is passed as a command line option or `FORCE_COLORS` is an environment variable. This allows users to force colors in non-interactive shells. 
I am working with `rollup` and `child_processes` and I want to be able to edit the `child` `stderr`/`stdout` but I also want colors to show up. There isn't a good way to do that right now without using a [`node-pty`](https://github.com/Tyriar/node-pty) but that gets rid of the notion of `stderr` and `stdout`, which also won't work.

fix: use chalk.supportColors rather than isTTY so colors can be forced

---

src/ast/variables/GlobalVariable.ts
test/form/samples/removes-unused-babel-helpers/_config.js
test/form/samples/removes-unused-babel-helpers/main.js

Resolves #1823
This will declare accesses to members of `Reflect` as safe und thus enable tree-shaking babel helpers again. This is just a quick fix which will be replaced by a proper solution once I have finished reworking the handling of global variables and which I will put into the next release if there are no objections.

Quick fix to enable tree-shaking babel-helpers again

---

package.json
src/Module.ts
src/node-entry.ts
src/utils/mergeOptions.ts
typings/declarations.d.ts
typings/package.json.d.ts

fixes #1862
To fix all compiler errors mentioned in #1862 a TypeScript project that imports Rollup additionally needs to add theses `devDependencies`:
- `@types/chokidar`
- `@types/source-map`
- `magic-string` (brings its own typing)

fix typescript compiler errors based on emitted d.ts files

---

package.json
src/rollup/index.ts

This is a follow-up PR from #1864 that addresses the issue mentioned by @lukastaegert in [this comment](https://github.com/rollup/rollup/issues/1862#issuecomment-357146735) as well as fixes the wrong `files` entry for `typings/package.json.d.ts` as [noticed](https://github.com/rollup/rollup/pull/1864#issuecomment-357158638) by @alan-agius4.

Fix two more ts compiler errors based on emitted d.ts files

---

src/Graph.ts
src/Module.ts
src/rollup/index.ts
src/utils/first-sync.ts
test/hooks/index.js

It would be great to override the behavior of what to do when an export is not found. In most cases, an error is what you want, but in the Ember.js world, leniency would be better.
In Ember.js, ES6 code is transpiled to AMD modules for the browser. This has the side-effect of jamming all exports into a default export. This means that you can write invalid ES6 export/import code that "just works" because of the AMD transpilation.
I would like to gracefully handle this case with a hook. I will then be printing a deprecation warning to Ember users so that invalid Ember code will eventually self-correct,

RFC: add missingExport hook

---

src/watch/index.ts

Some minor typescript cleanup, with this it will remove `Watcher_base` and `InputAndOutputOptions` as an export

refactor: refactor watch to use `extends` directly

---

bin/src/run/loadConfigFile.ts

This will revert #1759 to resolve #1873 and resolve #1875 as outlined in the discussions of #1875 and #1759.

No longer use buble when parsing config files

---

bin/src/run/build.ts
bin/src/run/index.ts
src/Chunk.ts
src/Module.ts
src/ast/nodes/Import.ts
src/utils/mergeOptions.ts
test/chunking-form/index.js
test/chunking-form/samples/dynamic-import-chunking/_expected/cjs/main.js

In the process of putting together some example material these came up that were missed with some of the changes.

Fix CLI and dynamic import workflow bugs

---

src/Graph.ts
src/Module.ts
test/function/samples/dynamic-import-duplicates/_config.js
test/function/samples/dynamic-import-duplicates/foo.js
test/function/samples/dynamic-import-duplicates/main.js

This fixes #1909.
The exact issue here is that the fetch cache in https://github.com/rollup/rollup/blob/master/src/Graph.ts#L500 continues in the null case, resulting in duplicate module loads. The other issue is that the dynamic import use of `fetchModule` expects to be able to get back a Module object so that it can store the reference, which can't work out in the null return case.
One option would be to store all the fetch promises here in their own fetch registry, but simpler was just to instantiate Module upfront so we can make the references, then separate out the source-setting part of the module construction into a separate function which is what I've done here.
Test case is exactly from #1909.

Fix dynamic import module deduplication

---

src/Chunk.ts
src/ast/scopes/Scope.ts
src/ast/variables/Variable.ts
test/form/samples/import-specifier-deshadowing/_config.js
test/form/samples/import-specifier-deshadowing/_expected/amd.js
test/form/samples/import-specifier-deshadowing/_expected/cjs.js
test/form/samples/import-specifier-deshadowing/_expected/es.js
test/form/samples/import-specifier-deshadowing/_expected/iife.js
test/form/samples/import-specifier-deshadowing/_expected/umd.js
test/form/samples/import-specifier-deshadowing/main.js

This fixes #1910.
The main fix is just the line in `src/Chunk.ts`, but in the process this exposed an idempotency bug in the deshadowing process itself in that `safeName` results from previous deshadowing runs can affect future runs.
I've fixed the idempotency bug with a reliable but hacky approach for now, hopefully we can put some thought to something better here, but correctness comes first I feel. Just let me know if I can help explain it at all further.

Import specifier deshadowing fix

---

src/Graph.ts
test/function/samples/load-returns-empty-string/_config.js
test/function/samples/load-returns-empty-string/bar.js
test/function/samples/load-returns-empty-string/foo.js
test/function/samples/load-returns-empty-string/main.js

Previously, this was only allowed when returning a source code string, not a `{ code, map }` object, because `source.code` was checked for truthiness.

Allow plugin load() to return empty string

---

src/rollup/index.ts
src/utils/mergeOptions.ts

This is a follow-up PR of #1316.
Summary: Apparently some plugins call the given `onwarn` function with a string instead of an object. (e.g. [rollup-plugin-babel](https://github.com/rollup/rollup-plugin-babel/blob/master/src/index.js#L59)) leading to logged `undefined`s.
This PR enhances the `defaultOnWarn` handler to be able to handle a `string` as well as a `RollupWarning` object.

fix undefined warn output from a plugin

---

src/Graph.ts
src/rollup/index.ts
src/utils/defaults.ts
src/utils/mergeOptions.ts
test/cli/samples/config-deprecations/rollup.config.js
test/function/samples/preserve-symlink/_config.js
test/function/samples/preserve-symlink/bar.js
test/function/samples/preserve-symlink/foo.js
test/function/samples/preserve-symlink/main.js
test/function/samples/preserve-symlink/symlinked/foo.js
test/misc/index.js

I believe symlinks used to be preserved, but now are followed. This is hurting me because in broccolijs land, everything is a symlink. This makes using the node-resolve plugin a nightmare.
Can we discuss an opt-in option for preserving symlinks? This PR is just a sample of what would change, not a final product. I would like the option to by system-wide public API, because several rollup plugins also follow rollup's example and follow symlinks. It would be nice if they could inherit the public option.

Add option to not follow symlinks

---

.travis.yml
appveyor.yml

In #1670 a `prepare` script with `npm run build` was introduced. This means for ci runs that `npm run build` is called twice: the first time after `npm install` and the second time before `npm test`. Using `npm install --ignore-scripts` disables the `prepare` script (and all other scripts) for the install run.

Avoid duplicate `npm run build` on ci

---

bin/src/run/alternateScreen.ts

Fixes #1739 
Check the preconditions before alternate screen buffer.
The terminal crashes because cmd or PowerShell can't process ANSI escape sequences correctly for now.
Fortunately, ANSI escape sequences, including CSI codes, is supported by [Mintty](https://mintty.github.io/) and [ConEmu](https://conemu.github.io/) on the Windows platforms.
Mintty is the default terminal emulator of Cygwin/MYSY2/MinGW-w64/Git for Windows(Git Bash)/Babun/etc. Users can get environment variable `SHELL` or `TERM` on mintty, just like on Unix-like systems. ConEmu can process ANSI sequences too (when the environment variable `ConEmuANSI` is set to `ON`).
- [CtrlSeqs - Mintty](https://github.com/mintty/mintty/blob/master/wiki/CtrlSeqs.md)
- [ANSI X3.64 and Xterm 256 colors - …

Fix rollup watch crashes in cmd or PowerShell

---

src/Graph.ts
test/function/samples/already-deshadowed-import/_config.js
test/function/samples/can-import-self-treeshake/_config.js
test/function/samples/can-import-self/_config.js
test/function/samples/cycles-default-anonymous-function-hoisted/_config.js
test/function/samples/cycles-defaults/_config.js
test/function/samples/cycles-immediate/_config.js
test/function/samples/cycles-pathological-2/_config.js
test/function/samples/cycles-pathological/_config.js
test/function/samples/cycles-stack-overflow/_config.js
test/function/samples/iife-strong-dependencies/_config.js

See #1941. This is very primitive and doesn't warn through rollup's logging system.

Add simple warning for circular dependencies

---

src/Graph.ts
src/Module.ts
src/rollup/index.ts
src/utils/transform.ts
test/function/samples/plugin-parse/_config.js
test/function/samples/plugin-parse/main.js

This is motivated by #1512 and basically implements what @Rich-Harris [was suggesting a few weeks ago](https://github.com/rollup/rollup/pull/1816#issuecomment-356946057).
By exposing rollup's `parse` function to plugins (via the `transform` context) these plugins can use the same acorn configuration (including injected plugins) if they need to operate on an ast. The most prominent example for this is probably `rollup-plugin-commonjs`, as mentioned in #1512. I opened a [PR](https://github.com/rollup/rollup-plugin-commonjs/pull/287) there as well to switch to the `parse` method of the transform context.

Expose parse function to plugins

---

src/ast/scopes/ModuleScope.ts
src/ast/scopes/Scope.ts
test/form/samples/reexport-star-deshadow/_config.js
test/form/samples/reexport-star-deshadow/_expected/amd.js
test/form/samples/reexport-star-deshadow/_expected/cjs.js
test/form/samples/reexport-star-deshadow/_expected/es.js
test/form/samples/reexport-star-deshadow/_expected/iife.js
test/form/samples/reexport-star-deshadow/_expected/umd.js
test/form/samples/reexport-star-deshadow/foo.js
test/form/samples/reexport-star-deshadow/main.js
test/form/samples/reexport-star-deshadow/reexport.js

This fixes #1338 ensuring namespace exports which are in turn reexported are properly traced during deshadowing.

Reexport namespace deshadow

---

src/utils/flushTime.ts

There's some weird stuff happening with iterators due to use using an old version of TypeScript... somehow the `entries()` gets converted into a `values()` incorrectly.

Fix performance timers

---

src/Chunk.ts
test/chunking-form/samples/chunk-export-renaming/_config.js
test/chunking-form/samples/chunk-export-renaming/_expected/amd/chunk1.js
test/chunking-form/samples/chunk-export-renaming/_expected/amd/main1.js
test/chunking-form/samples/chunk-export-renaming/_expected/amd/main2.js
test/chunking-form/samples/chunk-export-renaming/_expected/cjs/chunk1.js
test/chunking-form/samples/chunk-export-renaming/_expected/cjs/main1.js
test/chunking-form/samples/chunk-export-renaming/_expected/cjs/main2.js
test/chunking-form/samples/chunk-export-renaming/_expected/es/chunk1.js
test/chunking-form/samples/chunk-export-renaming/_expected/es/main1.js
test/chunking-form/samples/chunk-export-renaming/_expected/es/main2.js
test/chunking-form/samples/chunk-export-renaming/_expected/system/chunk1.js
test/chunking-form/samples/chunk-export-renaming/_expected/system/main1.js
test/chunking-form/samples/chunk-export-renaming/_expected/system/main2.js
test/chunking-form/samples/chunk-export-renaming/main1.js
test/chunking-form/samples/chunk-export-renaming/main2.js
test/chunking-form/samples/chunk-export-renaming/one.js
test/chunking-form/samples/chunk-export-renaming/two.js

This provides a fix for #1976 where the re-export handling needs to be adjusted to deal with internally renamed exports instead of exporting the original variable name.

Export naming fix for #1976

---

package-lock.json
package.json
tsconfig-types.json

This enable us to use the new flag `emitDeclarationOnly` which emits only `d.ts` when building the types

chore(build): update to `TypeScript 2.7.2`

---

README.md

The first example in the README fails with the error `You must supply output.name for IIFE bundles`.  A brief review of the git history indicates this has been required for quite some time.

Add name option to iife example in README

---

test/chunking-form/index.js

Extracted from #1922. Reverted from #1975.
`fixturify` comparisons where brought in because of the preserve modules work, where there can be a directory tree. The change to this file doesn't work because it only iterates top-level entries.

revert chunking form test change

---

src/Chunk.ts
src/finalisers/amd.ts
src/finalisers/iife.ts
src/finalisers/shared/getGlobalNameMaker.ts
src/finalisers/shared/getInteropBlock.ts
src/finalisers/shared/trimEmptyImports.ts
src/finalisers/umd.ts

Resolves #1992.
The fix for #1992 was relatively straightforward here.
While I was at it I noticed `chunk.externalModules` is a kind of semi-public interface used by finalisers, which could easily get out of sync with further optimization, so I refactored the usage here to be entirely dependent on the data structure created by chunks for their boundaries instead of needing to reach into internals like this. It's not the prettiest of code, but it provides the encapsulation which is necessary to separate thinking about the input graph from thinking about the output graph.

Fix for #1992, along with chunk interface refactoring

---

src/ast/nodes/VariableDeclaration.ts
test/form/samples/render-declaration-semicolons/_config.js
test/form/samples/render-declaration-semicolons/_expected/amd.js
test/form/samples/render-declaration-semicolons/_expected/cjs.js
test/form/samples/render-declaration-semicolons/_expected/es.js
test/form/samples/render-declaration-semicolons/_expected/iife.js
test/form/samples/render-declaration-semicolons/_expected/umd.js
test/form/samples/render-declaration-semicolons/main.js

This was a regression from 0.56.0 due to the semicolon insertion code being put into the wrong place when rendering declarations where nothing was removed. Resolves #1993.

Do not add superfluous semicolons after declarations

---

test/chunking-form/index.js
test/cli/index.js
test/form/index.js
test/function/index.js
test/sourcemaps/index.js
test/utils.js

This removes a common nuisance when switching between different branches. Previously when there was no `_config.js` file in a test folder, an error would be thrown and the tests would not execute at all until the folder in question was removed.
As in 100% of the cases I experienced this folder could always be safely removed, this will now just display a warning and remove the folder in question. My hope is that if this should ever misfire (due to e.g. larger refactorings of the test system), we will always have the git history to rely on.

Automatically remove directories of missing tests

---

src/ast/nodes/ExportDefaultDeclaration.ts
src/ast/nodes/Identifier.ts
test/chunking-form/samples/entrypoint-facade/_expected/amd/chunk1.js
test/chunking-form/samples/entrypoint-facade/_expected/cjs/chunk1.js
test/chunking-form/samples/entrypoint-facade/_expected/es/chunk1.js
test/chunking-form/samples/entrypoint-facade/_expected/system/chunk1.js
test/chunking-form/samples/entrypoint-facade/dep.js

Fixes the `export default { obj }` case being output as `exports('default', { obj )}` instead of `exports('default', { obj })`.

Fix for #2018

---

src/Chunk.ts
test/chunking-form/samples/import-variable-duplicates/_config.js
test/chunking-form/samples/import-variable-duplicates/_expected/amd/first.js
test/chunking-form/samples/import-variable-duplicates/_expected/amd/head.js
test/chunking-form/samples/import-variable-duplicates/_expected/amd/main1.js
test/chunking-form/samples/import-variable-duplicates/_expected/amd/main2.js
test/chunking-form/samples/import-variable-duplicates/_expected/cjs/first.js
test/chunking-form/samples/import-variable-duplicates/_expected/cjs/head.js
test/chunking-form/samples/import-variable-duplicates/_expected/cjs/main1.js
test/chunking-form/samples/import-variable-duplicates/_expected/cjs/main2.js
test/chunking-form/samples/import-variable-duplicates/_expected/es/first.js
test/chunking-form/samples/import-variable-duplicates/_expected/es/head.js
test/chunking-form/samples/import-variable-duplicates/_expected/es/main1.js
test/chunking-form/samples/import-variable-duplicates/_expected/es/main2.js
test/chunking-form/samples/import-variable-duplicates/_expected/system/first.js
test/chunking-form/samples/import-variable-duplicates/_expected/system/head.js
test/chunking-form/samples/import-variable-duplicates/_expected/system/main1.js
test/chunking-form/samples/import-variable-duplicates/_expected/system/main2.js
test/chunking-form/samples/import-variable-duplicates/first.js
test/chunking-form/samples/import-variable-duplicates/head.js
test/chunking-form/samples/import-variable-duplicates/main1.js
test/chunking-form/samples/import-variable-duplicates/main2.js

The issue here is that because we do tracing and deshadowing with variable as the unit of deshadowing, we always need to ensure that imports of chunks always dedupe to one usage of a variable even if that same variable is imported multiple times.

Isolated test case and fix for #2015

---

src/Chunk.ts
test/chunking-form/samples/reexport-shortpaths/_config.js
test/chunking-form/samples/reexport-shortpaths/_expected/amd/chunk1.js
test/chunking-form/samples/reexport-shortpaths/_expected/amd/chunk2.js
test/chunking-form/samples/reexport-shortpaths/_expected/amd/main1.js
test/chunking-form/samples/reexport-shortpaths/_expected/amd/main2.js
test/chunking-form/samples/reexport-shortpaths/_expected/amd/main3.js
test/chunking-form/samples/reexport-shortpaths/_expected/cjs/chunk1.js
test/chunking-form/samples/reexport-shortpaths/_expected/cjs/chunk2.js
test/chunking-form/samples/reexport-shortpaths/_expected/cjs/main1.js
test/chunking-form/samples/reexport-shortpaths/_expected/cjs/main2.js
test/chunking-form/samples/reexport-shortpaths/_expected/cjs/main3.js
test/chunking-form/samples/reexport-shortpaths/_expected/es/chunk1.js
test/chunking-form/samples/reexport-shortpaths/_expected/es/chunk2.js
test/chunking-form/samples/reexport-shortpaths/_expected/es/main1.js
test/chunking-form/samples/reexport-shortpaths/_expected/es/main2.js
test/chunking-form/samples/reexport-shortpaths/_expected/es/main3.js
test/chunking-form/samples/reexport-shortpaths/_expected/system/chunk1.js
test/chunking-form/samples/reexport-shortpaths/_expected/system/chunk2.js
test/chunking-form/samples/reexport-shortpaths/_expected/system/main1.js
test/chunking-form/samples/reexport-shortpaths/_expected/system/main2.js
test/chunking-form/samples/reexport-shortpaths/_expected/system/main3.js
test/chunking-form/samples/reexport-shortpaths/dep1.js
test/chunking-form/samples/reexport-shortpaths/dep2.js
test/chunking-form/samples/reexport-shortpaths/main1.js
test/chunking-form/samples/reexport-shortpaths/main2.js
test/chunking-form/samples/reexport-shortpaths/main3.js

This fixes an issue with imports over reexport short-circuit paths in chunk tracing not showing up properly in the rendered imports of the module, as well as a slightly more consistent shortpath tracing method.
@kellyselden this should resolve the issue you were getting in #1922 as well with the latest adjustments.

Reexport tracing shortpaths fix

---

rollup.config.js

Whilst working on the Reproducible Builds effort [0], we noticed
that node-rollup could not be built reproducibly as it encodes
the current build time via "new Date()".
This was originally filed in Debian as #891899.
[0] https://reproducible-builds.org/
[1] https://bugs.debian.org/891899
Signed-off-by: Chris Lamb <chris@chris-lamb.co.uk>

Make the build reproducible

---

src/finalisers/es.ts
test/form/samples/namespace-import-reexport/_config.js
test/form/samples/namespace-import-reexport/_expected/amd.js
test/form/samples/namespace-import-reexport/_expected/cjs.js
test/form/samples/namespace-import-reexport/_expected/es.js
test/form/samples/namespace-import-reexport/_expected/iife.js
test/form/samples/namespace-import-reexport/_expected/system.js
test/form/samples/namespace-import-reexport/_expected/umd.js
test/form/samples/namespace-import-reexport/main.js

This fixes https://github.com/rollup/rollup/issues/2033.
Again, rebased to prettier and Rollup update PRs to ensure passing tests and noise-free diff!

fixes #2033 namespace import reexport case

---

src/Graph.ts
src/Module.ts
src/rollup/index.ts
src/utils/defaults.ts

Closes #1973.
I don't think calling `Module` functions is going to be necessary after all.

remove private api from MissingExport hook

---

src/Graph.ts
src/rollup/index.ts
src/watch/index.ts
test/watch/index.js
test/watch/samples/code-splitting/main1.js
test/watch/samples/code-splitting/main2.js
test/watch/samples/code-splitting/shared.js

Enable watcher in code-splitting mode

---

bin/src/run/index.ts
bin/src/run/loadConfigFile.ts
bin/src/run/watch.ts
test/cli/samples/config-function/_config.js
test/cli/samples/config-function/main.js
test/cli/samples/config-function/rollup.config.js

Please see #1925 for a discussion relating to this pull request
If config file exports a function then call this function with `commandOptions` object. We expect this function to return a `config` object or `configs` array, the same as existing config files

Optionally pass CLI command arguments to config

---

src/Module.ts

While digging through the source map generation, I noticed that the `source-map` dependency, which was only used for locating errors, can be easily replaced but using `mappings` directly. This makes the final Rollup bundle ~10% smaller.
```bash
~/projects/rollup master → gz dist/rollup.js
orig: 839.13KB
gzip: 176.09KB
~/projects/rollup master → gz dist/rollup.js
orig: 769.00KB
gzip: 158.63KB
```

Remove source-map from Rollup bundle

---

package.json
src/Chunk.ts
src/ast/nodes/Literal.ts
src/ast/nodes/TemplateLiteral.ts
src/finalisers/amd.ts
src/finalisers/cjs.ts
src/finalisers/es.ts
src/finalisers/iife.ts
src/finalisers/system.ts
src/finalisers/umd.ts
src/rollup/index.ts
src/utils/collapseSourcemaps.ts

This was finally released so nice to clean up some of the typing issues.

Magic string typing updates

---

package-lock.json
package.json
src/Chunk.ts
src/utils/collapseSourcemaps.ts

Removes redundant source map encoding roundtrip between `magic-string` and `rollup`, which should speed up source map generation by up to 40%. For example, Mapbox GL JS bundle takes ~400-500ms less time after this PR. 
Also contains some minor code clean up in `collapseSourcemaps.ts` that I forgot to commit separately.
Fixes #2061. cc @guybedford @lukastaegert

Faster source map generation

---

bin/src/run/watch.ts
src/watch/index.ts

Also sorts the timing output by start time

Print --perf timings in --watch mode

---

README.md

These badges are currently both repeated. In addition the links in these repeated ones don't work when clicked.

Remove duplicate and broken link readme badges

---

src/Chunk.ts
test/chunking-form/samples/chunk-deshadowing-reassignment/_expected/amd/main1.js
test/chunking-form/samples/chunk-deshadowing-reassignment/_expected/amd/main2.js
test/chunking-form/samples/chunk-deshadowing-reassignment/_expected/cjs/main1.js
test/chunking-form/samples/chunk-deshadowing-reassignment/_expected/cjs/main2.js
test/chunking-form/samples/chunk-deshadowing-reassignment/_expected/es/main1.js
test/chunking-form/samples/chunk-deshadowing-reassignment/_expected/es/main2.js
test/chunking-form/samples/chunk-deshadowing-reassignment/_expected/system/main1.js
test/chunking-form/samples/chunk-deshadowing-reassignment/_expected/system/main2.js
test/chunking-form/samples/chunking-star-external/_expected/amd/main1.js
test/chunking-form/samples/chunking-star-external/_expected/cjs/main1.js
test/chunking-form/samples/chunking-star-external/_expected/es/main1.js
test/chunking-form/samples/chunking-star-external/_expected/system/main1.js
test/chunking-form/samples/preserve-modules/_expected/amd/main1.js
test/chunking-form/samples/preserve-modules/_expected/amd/main2.js
test/chunking-form/samples/preserve-modules/_expected/cjs/main1.js
test/chunking-form/samples/preserve-modules/_expected/cjs/main2.js
test/chunking-form/samples/preserve-modules/_expected/es/main1.js
test/chunking-form/samples/preserve-modules/_expected/es/main2.js
test/chunking-form/samples/preserve-modules/_expected/system/main1.js
test/chunking-form/samples/preserve-modules/_expected/system/main2.js
test/chunking-form/samples/reexport-shortpaths/_expected/amd/main2.js
test/chunking-form/samples/reexport-shortpaths/_expected/cjs/main2.js
test/chunking-form/samples/reexport-shortpaths/_expected/es/main2.js
test/chunking-form/samples/reexport-shortpaths/_expected/system/main2.js

As described in #2071, this will minimize the latency waterfall problem for deep chunkings chains, making code splitting workflows faster.
Note this will likely have merge conflicts with #2068. Either can be merged first and I'll fix up the conflicts for the other.

Inline deep dependencies for entry points

---

README.md

I'm not pushing hard on this, but just think it may be a nicer interface to encourage ease-of-use? Although it is nice to make users aware of the output options distinction from the start too.

Update readme examples not to use --output. pattern

---

src/utils/error.ts
test/misc/index.js

For some reason — not entirely sure what I was thinking — plugin errors get recreated in the default error handler, instead of just being thrown. This is causing problems with funky custom errors that do (admittedly unadvisable) things like having multiple arguments to the constructor.
The proposed fix is to just throw the error, and only create a new one if a plugin does something like:
```js
this.error({
message: 'something went wrong!'
});
```
Does this seem reasonable?

use existing plugin error, rather than wrapping

---

bin/src/run/batchWarnings.ts

Fix option name in warning to use "output" prefix

---

bin/src/run/build.ts
src/rollup/index.ts

The issue is that when providing `input: 'file.js', output: { dir: 'dist' }`, Rollup thinks it is doing a single-file build, but the CLI was providing the error: "You must specify an --output (-o) option when creating a file with a sourcemap" which is completely useless.
With this change, the error now provided in this case is "You must specify output.file when doing a single-file input build".
We could perhaps clarify this even more as well.
To clarify the code-splitting logic here:
1. The experimental code splitting flag is treated as an experimental feature flag - that is, it doesn't imply a code splitting workflow on its own as the idea is that this flag will just be removed entirely one day.
2. We thus use the fact that the `input` is an array or object to indicate that this is a …

Correct error in #2101

---

src/utils/renderHelpers.ts
test/form/samples/comment-start-inside-comment/_config.js
test/form/samples/comment-start-inside-comment/_expected/amd.js
test/form/samples/comment-start-inside-comment/_expected/cjs.js
test/form/samples/comment-start-inside-comment/_expected/es.js
test/form/samples/comment-start-inside-comment/_expected/iife.js
test/form/samples/comment-start-inside-comment/_expected/system.js
test/form/samples/comment-start-inside-comment/_expected/umd.js
test/form/samples/comment-start-inside-comment/foo.js
test/form/samples/comment-start-inside-comment/main.js

Resolves #2127
Previously, line-break detection outside comments was faulty in that since line comments cannot contain line-breaks, it would only scan the code for block comments. This approach failed if a block comment start `/*` was nested inside a line comment.
The new logic now scans for all types of comments and ignores any markup inside both types of comments.

Improve line-break detection to handle "/*" inside "//" comments,

---

src/Chunk.ts
src/finalisers/cjs.ts
src/finalisers/shared/getInteropBlock.ts
src/finalisers/shared/trimEmptyImports.ts
test/form/samples/import-external-namespace-and-default/_expected/amd.js
test/form/samples/import-external-namespace-and-default/_expected/iife.js
test/form/samples/import-external-namespace-and-default/_expected/umd.js

This fixes #2081 allowing external modules imported as both default and namespaces can still have default interop applied to them in the default import case (matching the AMD, IIFE and UMD interop cases to CommonJS in the process).
This replaces #2080, while including a lot of simplification in the interop handling code.

Simplify namespace interop

---

src/Chunk.ts
src/ExternalModule.ts
src/chunk-optimization.ts
src/rollup/index.ts
test/form/samples/relative-external-with-global/_expected/amd.js
test/form/samples/relative-external-with-global/_expected/cjs.js
test/form/samples/relative-external-with-global/_expected/es.js
test/form/samples/relative-external-with-global/_expected/system.js
test/form/samples/relative-external-with-global/_expected/umd.js
test/form/samples/url-external/_config.js
test/form/samples/url-external/_expected/amd.js
test/form/samples/url-external/_expected/cjs.js
test/form/samples/url-external/_expected/es.js
test/form/samples/url-external/_expected/iife.js
test/form/samples/url-external/_expected/system.js
test/form/samples/url-external/_expected/umd.js
test/form/samples/url-external/main.js

In the shift to code-splitting, there was a regression in https://github.com/rollup/rollup/commit/f59e310fcedeef36f5a75506f1614e50dfeb51ee#diff-a1d1f47eb8dcd4b0026545f1e89b1b95.
The issue here has been making the conceptual model of single file builds adapt to the output model of a file structure in code splitting builds, while handling external naming in a way that can be reliably hashed as well as renormalized into the output folder.
In short the fix is to:
1. Adapt the `inputBase` we're already using for preserveModules to be an input into the preRender function
2. Marking which external modules should be "renormalized" (those that aren't absolute or set by options.paths)
3. Normalizing the external module id relative to the inputBase into a "virtual file space" for code splitting
4. …

Fix external renormalization regression (#2153)

---

.travis.yml
appveyor.yml

master has regressed in lower node versions https://travis-ci.org/rollup/rollup/jobs/378107881
```
Error: 'crypto' is imported by node_modules/math-random/node.js, but could not be resolved – treating it as an external dependency
```
This is because the lower envs don't use npm 5 and version drift occurred.

use npm 5 in lower node versions

---

src/Chunk.ts
src/finalisers/amd.ts
src/finalisers/cjs.ts
src/finalisers/iife.ts
src/finalisers/index.ts
src/finalisers/shared/getExportBlock.ts
src/finalisers/shared/getInteropBlock.ts
src/finalisers/umd.ts
src/rollup/index.ts
test/chunking-form/samples/chunking-reexport/_expected/amd/chunk-849a022f.js
test/chunking-form/samples/entry-chunk-export-mode/_config.js
test/chunking-form/samples/entry-chunk-export-mode/_expected/amd/main1.js
test/chunking-form/samples/entry-chunk-export-mode/_expected/amd/main2.js
test/chunking-form/samples/entry-chunk-export-mode/_expected/cjs/main1.js
test/chunking-form/samples/entry-chunk-export-mode/_expected/cjs/main2.js
test/chunking-form/samples/entry-chunk-export-mode/_expected/es/main1.js
test/chunking-form/samples/entry-chunk-export-mode/_expected/es/main2.js
test/chunking-form/samples/entry-chunk-export-mode/_expected/system/main1.js
test/chunking-form/samples/entry-chunk-export-mode/_expected/system/main2.js
test/chunking-form/samples/entry-chunk-export-mode/main1.js
test/chunking-form/samples/entry-chunk-export-mode/main2.js
test/chunking-form/samples/import-variable-duplicates/_expected/amd/head.js
test/chunking-form/samples/import-variable-duplicates/_expected/amd/main1.js
test/chunking-form/samples/import-variable-duplicates/_expected/amd/main2.js
test/chunking-form/samples/import-variable-duplicates/_expected/cjs/head.js
test/chunking-form/samples/import-variable-duplicates/_expected/cjs/main1.js

This fixes #2176.
I've refactored the exportMode a little into `namedExportsMode` and `hasExports` booleans for the finalizers.
The `namedExportsMode` could equally be considered the exact converse of a `defaultExportMode`.
We then effectively treat the default export mode as an extra interop case where we know the interop path already so don't need to do a check here.

Chunk export mode fix for #2176

---

src/ast/ExecutionPathOptions.ts
src/ast/nodes/BinaryExpression.ts
src/ast/nodes/ConditionalExpression.ts
src/ast/nodes/Identifier.ts
src/ast/nodes/IfStatement.ts
src/ast/nodes/Literal.ts
src/ast/nodes/LogicalExpression.ts
src/ast/nodes/MemberExpression.ts
src/ast/nodes/ObjectExpression.ts
src/ast/nodes/Property.ts
src/ast/nodes/SequenceExpression.ts
src/ast/nodes/UnaryExpression.ts
src/ast/nodes/shared/Expression.ts
src/ast/nodes/shared/Node.ts
src/ast/variables/LocalVariable.ts
src/ast/variables/Variable.ts
test/form/samples/recursive-values/_config.js
test/form/samples/recursive-values/_expected.js
test/form/samples/recursive-values/main.js

This adds logic to handle circular structures when retrieving literal values similar to how this is done in other situations.
Resolves #2192 (hopefully).

Add circularity prevention to value detection

---

CHANGELOG.md
package-lock.json
package.json
src/ast/nodes/ForInStatement.ts
src/ast/nodes/ForOfStatement.ts
test/function/samples/for-loops-as-assignments/_config.js
test/function/samples/for-loops-as-assignments/main.js

The issue was that in contrast to `for..of` loops, the logic for `for..in` loops did not mark non-declaration loop variables as "reassigned".
In the current situation if the the loop variable previously evaluated to a boolean, this value would not change and thus conditionals would be wrongly simplified.

Reassign for-in loop variable; resolves #2199

---

CHANGELOG.md
package-lock.json
package.json
src/ast/nodes/NewExpression.ts
test/function/samples/reassign-constructor-parameter-property/_config.js
test/function/samples/reassign-constructor-parameter-property/main.js

Resolves #2213
Previously, mutating a parameter inside a constructor (in contrast to normal call expressions) would not be respected by the tree-shaking logic. This is fixed here.

Make sure, properties of constructor parameters are reassigned

---

bin/src/run/watch.ts

Fixes #1804
This is the beginning of a PR to fixes #1804 based on some of the work that people did in that thread with minimal changes. Thanks @evocateur and @JimPanic
I think the changes are good but there's one thing that I'm not sure if there are any side-effects for but would love to get this merged in.

fix(watch): don't use alternate screen if clearScreen is set

---

bin/src/run/watch.ts
src/rollup/types.d.ts
test/watch/index.js

The watcher defines it's own type for the `input` option which predictably went out of sync with the "official" `InputOptions.input` type - which led to this passing unnoticed:
When using `experimentalCodeSplitting` and setting `input` to be an object, then the watcher threw an error.

fix: Using -w flag fails when config.input is an object

---

src/utils/collapseSourcemaps.ts

Fixes #1553. Fixes #1700.
For some builds like in the issues above, `traceSegment` in `collapseSourcemaps.ts` took unreasonably long time because some of the source maps contained very long lines (e.g. one example line had 50k segments), and linearly searching through them for every segment that needed tracing was too slow. This PR switches `traceSegment` to use simple binary search, fixing the issue.
Bundle times for the [repro case](https://github.com/houli/rollup-sourcemap-repro) in #1553:
- `sourceMap: false` (`master` rollup): 2.1s
- `sourceMap: true` (`master` rollup): 15.5s
- `sourceMap: true` (this branch): 2.4s
cc @lukastaegert

Fix unreasonably slow bundle time on sourcemaps with long lines

---

src/Graph.ts
src/Module.ts
test/function/samples/externally-reassigned-default-exports/_config.js
test/function/samples/externally-reassigned-default-exports/main.js
test/function/samples/externally-reassigned-globals/_config.js
test/function/samples/externally-reassigned-globals/main.js
test/function/samples/externally-reassigned-named-exports/_config.js
test/function/samples/externally-reassigned-named-exports/main.js
test/function/samples/externally-reassigned-named-reexports/_config.js
test/function/samples/externally-reassigned-named-reexports/foo.js
test/function/samples/externally-reassigned-named-reexports/main.js
test/function/samples/externally-reassigned-star-reexports/_config.js
test/function/samples/externally-reassigned-star-reexports/foo.js
test/function/samples/externally-reassigned-star-reexports/main.js

Resolves #2237
As it turns out, there was nothing to do for objects attached to globals as the global variable handling has always been very conservative here. Added a regression test nonetheless.
External exports are now properly marked as reassigned.

Handle external reassignments

---

src/ast/variables/ExportDefaultVariable.ts
test/form/samples/default-identifier-deshadowing/_config.js
test/form/samples/default-identifier-deshadowing/_expected/amd.js
test/form/samples/default-identifier-deshadowing/_expected/cjs.js
test/form/samples/default-identifier-deshadowing/_expected/es.js
test/form/samples/default-identifier-deshadowing/_expected/iife.js
test/form/samples/default-identifier-deshadowing/_expected/system.js
test/form/samples/default-identifier-deshadowing/_expected/umd.js
test/form/samples/default-identifier-deshadowing/dep.js
test/form/samples/default-identifier-deshadowing/main.js

This ensures that the name of the default variable is kept as its declaration name for function and class declarations, instead of using reference hints.

Fix #2230, default identifier renaming issue

---

src/rollup/index.ts
src/utils/mergeOptions.ts

1. I seem to have messed up the signature of this function in the process by mistake - this returns it to its usual form as expected (resolves #2245)
2. I've also included a closure fix for the chunk.id handling, which must be read synchronously (resolves #2243)
3. I've fixed the multiple input validation to happen after the options hook call (resolves #2247)

Fix plugin regressions

---

src/utils/assetHooks.ts
test/hooks/index.js

This allows `generateBundle` to still have calls to:
```js
const assetId = this.emitAsset('name');
this.setAssetsource(assetId, source);
```
whereas currently this throws due to expectations on assets already being finalised, while we should be extending this case to be supported in the extended finalisation of assets.

Allow setAssetSource being called in generateBundle

---

src/rollup/types.d.ts

Here's a reproduction of the issue: https://github.com/dherges/rollup-output-options-array
The javascript API allows to set `rollup.watch({ output: [{ .. }, { .. }])`, see
https://github.com/dherges/rollup-output-options-array/blob/master/build.js
It's documented in the section "Configuration Files": https://rollupjs.org/guide/en#configuration-files 
The typescript API does not reflect that int he types, a build will fail. See https://github.com/dherges/rollup-output-options-array/blob/master/build.ts
```bash
$ ts-node build.ts
/home/david/Projects/github/dherges/rollup-output-options-array/node_modules/ts-node/src/index.ts:250    return new TSError(diagnosticText, diagnosticCodes)
^
TSError: ⨯ Unable to compile TypeScript:
build.ts(3,14): error TS2345: Argument of type '{ input: string; …
```

Fix RollupWatchOptions.output may be an array of OutputOptions

---

src/ast/nodes/ArrayExpression.ts
src/ast/nodes/ArrowFunctionExpression.ts
src/ast/nodes/CallExpression.ts
src/ast/nodes/ConditionalExpression.ts
src/ast/nodes/Identifier.ts
src/ast/nodes/Literal.ts
src/ast/nodes/LogicalExpression.ts
src/ast/nodes/MemberExpression.ts
src/ast/nodes/NewExpression.ts
src/ast/nodes/ObjectExpression.ts
src/ast/nodes/Property.ts
src/ast/nodes/SequenceExpression.ts
src/ast/nodes/TaggedTemplateExpression.ts
src/ast/nodes/shared/Expression.ts
src/ast/nodes/shared/FunctionNode.ts
src/ast/nodes/shared/Node.ts
src/ast/scopes/FunctionScope.ts
src/ast/scopes/ReturnValueScope.ts
src/ast/values.ts
src/ast/variables/ArgumentsVariable.ts
src/ast/variables/LocalVariable.ts
src/ast/variables/ReplaceableInitializationVariable.ts
src/ast/variables/Variable.ts
test/form/samples/conditional-expression/main.js
test/form/samples/recursive-return-value-assignments/_expected.js
test/function/samples/trace-inclusion-of-virtual-literals/_config.js
test/function/samples/trace-inclusion-of-virtual-literals/main.js

This resolves #2253 by internally using instances that can track their own inclusion status for return values of literal methods. E.g. in this example:
```js
const virtual = [1, 2].slice();
virtual.push(3);
const otherVirtual = virtual.slice();
console.log(virtual);
```
the line `virtual.push(3)` will be included as `virtual` itself is included due to the `console.log` statement. The third line, on the other hand, is still removed as it is no side-effect.
To be able to do that, a larger refactoring was necessary. The main issue was that in order to track the inclusion status of an entity that is not represented by an AST node, another AST node needed to take up that responsibility. In this case, the respective `CallExpression` seemed the natural choice (each call to …

Track inclusion of entities returned by literal methods

---

src/rollup/types.d.ts

I beleive it's a typo and it causes issue:
```
Argument of type 'String' is not assignable to parameter of type 'string'. 'string' is a primitive, but 'String' is a wrapper object. Prefer using 'string' when possible.
```

Use primitive string type in TransformHook

---

src/Graph.ts
src/node-entry.ts
src/rollup/index.ts
src/rollup/types.d.ts
src/utils/first-sync.ts
src/utils/first.ts
src/watch/index.ts
test/watch/index.js

This allows for plugins that can track the watcher lifecycle like notifiers. Resolves #2117.

Provide the watcher on the plugin context

---

src/ast/nodes/Literal.ts
src/ast/scopes/ModuleScope.ts
src/ast/values.ts
test/form/samples/undefined-var/_config.js
test/form/samples/undefined-var/_expected.js
test/form/samples/undefined-var/main.js

Resolves #2223
This extends the `UNDEFINED_EXPRESSION` to return a `undefined` literal value which can be treeshaken.

Handle undefined expressions in treeshaking

---

src/ast/nodes/ArrayExpression.ts
src/ast/nodes/ArrayPattern.ts
src/ast/nodes/ArrowFunctionExpression.ts
src/ast/nodes/AssignmentPattern.ts
src/ast/nodes/CatchClause.ts
src/ast/nodes/Identifier.ts
src/ast/nodes/ObjectPattern.ts
src/ast/nodes/Property.ts
src/ast/nodes/RestElement.ts
src/ast/nodes/VariableDeclarator.ts
src/ast/nodes/shared/FunctionNode.ts
src/ast/scopes/Scope.ts
src/ast/variables/LocalVariable.ts
test/function/index.js
test/function/samples/handles-double-declarations/_config.js
test/function/samples/handles-double-declarations/foobar.js
test/function/samples/handles-double-declarations/main.js
test/function/samples/reassign-array-literal-elements/_config.js
test/function/samples/reassign-array-literal-elements/main.js
test/function/samples/reassign-double-declarations/_config.js
test/function/samples/reassign-double-declarations/main.js
test/function/samples/reassign-pattern-defaults/_config.js
test/function/samples/reassign-pattern-defaults/main.js

Resolves #2275.
When a variable has more than one declaration, the reassignment tracking logic could trigger a bug as it was engaged before the inter module bindings were set up.
While fixing this, some other issues popped up that are fixed as well:
* When a variable has more than one declaration, reassignments were not tracked properly for all initialisers
* Reassignments of pattern defaults were not tracked properly
* Reassignments of elements of array literals were not tracked properly. For this one, a very simple logic was implemented that just marks all array elements as "reassigned". In the future, a more elaborate logic could be implemented similar to the object expression logic which would allow values to be tracked across tuples.
All of these issues are now properly tested and …

Double declarations

---

.vscode/launch.json

I use this in my branches to debug in vscode. I figured you all might benefit from it too.

add vscode debugger settings

---

package-lock.json
src/Chunk.ts
src/finalisers/amd.ts
src/finalisers/cjs.ts
src/finalisers/umd.ts
src/rollup/types.d.ts
src/utils/mergeOptions.ts
src/utils/renderHelpers.ts
test/form/samples/define-es-modules-false/_config.js
test/form/samples/define-es-modules-false/_expected/amd.js
test/form/samples/define-es-modules-false/_expected/cjs.js
test/form/samples/define-es-modules-false/_expected/es.js
test/form/samples/define-es-modules-false/_expected/iife.js
test/form/samples/define-es-modules-false/_expected/system.js
test/form/samples/define-es-modules-false/_expected/umd.js
test/form/samples/define-es-modules-false/main.js

Ref https://github.com/rollup/rollup/issues/708
This option will be useful for projects who distribute only cjs
and would like to migrate their codebase from default to named
exports but don't loose the ability to import in both ways.
For example react makes a hacky reexport right now
```js
module.exports = React.default ? React.default : React;
```
Disabling __esModule will allow react to prepare their packages to esm.

Allow to disable __esModule

---

package-lock.json
src/ast/scopes/GlobalScope.ts
src/ast/scopes/ModuleScope.ts
src/ast/scopes/Scope.ts
src/ast/variables/UndefinedVariable.ts
test/function/samples/allow-undefined-as-parameter/_config.js
test/function/samples/allow-undefined-as-parameter/main.js
test/function/samples/does-not-deconflict-undefined/_config.js
test/function/samples/does-not-deconflict-undefined/foo.js
test/function/samples/does-not-deconflict-undefined/main.js

Resolves #2290
With the new "undefined" literal logic, undefined was tracked as a variable on module level which lead to instances in different modules being deconflicted. Very simple reproduction:
https://rollupjs.org/repl?version=0.61.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QmZvbyU3RCUyMGZyb20lMjAnLiUyRmZvby5qcyclM0IlNUNuJTVDbmNvbnNvbGUubG9nKGZvbyUyQyUyMHVuZGVmaW5lZCklM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyZm9vLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNvbnN0JTIwZm9vJTIwJTNEJTIwdW5kZWZpbmVkJTNCJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXB …

Hotfix: Do not deconflict "undefined"

---

bin/src/run/watch.ts
src/watch/index.ts
test/watch/index.js
test/watch/samples/multiple/main1.js
test/watch/samples/multiple/main2.js

This fixes up some error handling in the watcher to ensure that any errors on start are properly thrown and also that input options errors (missing file and dir in this case) throw their proper messages.
In addition the issue raised in https://github.com/rollup/rollup/issues/2294#issuecomment-399275223 is also resolved which was a regression in the transform dependencies PR.
The `outputFiles` logic isn't there yet, I think it will need reworking, but that is a bigger job I'd like to work on on the 1.0 branch since it simplifies the logic of working out the output files.

Watcher fixes (#2294)

---

src/Chunk.ts
src/Graph.ts
src/utils/entryHashing.ts
test/chunking-form/samples/dynamic-import-inline-colouring/_config.js
test/chunking-form/samples/dynamic-import-inline-colouring/_expected/amd/main.js
test/chunking-form/samples/dynamic-import-inline-colouring/_expected/cjs/main.js
test/chunking-form/samples/dynamic-import-inline-colouring/_expected/es/main.js
test/chunking-form/samples/dynamic-import-inline-colouring/_expected/system/main.js
test/chunking-form/samples/dynamic-import-inline-colouring/foo.js
test/chunking-form/samples/dynamic-import-inline-colouring/main.js
test/form/samples/dynamic-import-inlining/_expected.js

This solves the issue described by @eight04 in https://github.com/rollup/rollup/issues/2284#issuecomment-398801336.
If a the time of checking a dynamic import, its already in the same static graph as the parent, then we don't treat it as a dynamic import at that point.
Only if later on we discover that the dynamic import is imported uniquely from a colouring where it is not already in that colouring's static graph do we properly raise it to the status of entry point.

Support static inline colouring for dynamic import

---

src/Graph.ts
src/Module.ts
src/rollup/types.d.ts
src/utils/assetHooks.ts
src/utils/collapseSourcemaps.ts
src/utils/getOriginalLocation.ts
src/utils/transform.ts
src/watch/index.ts
test/watch/index.js

There are some fine details about ensuring caching expectations around `emitAsset` ensuring things work out with cached builds and watched builds.
Managing all the wiring here gets a bit complex, but the overall expectations seem in line with precedent and the API in a way that is at least consistent.
Putting this up now for review, ~~but tests are still pending~~. Based against the transform dependencies PR - https://github.com/rollup/rollup/pull/2259.
Firstly, we need `emitAsset` to generate a reliably predictable `assetId` to ensure build consistency. In order to ensure this, the assetId is taken as the hash of the asset name, with collision handling.
Most plugin hooks will run each build, so we get re-emission of assets fine, except for the transform hook so this then needs special …

Asset invalidation and cache handling

---

bin/src/run/watch.ts

Related https://github.com/rollup/rollup/issues/2314
Hey, when trying to fix related issue I removed the first version output to remove duplication. There is a `START` event which does the same so the output is duplicated.
Is there any case where `START` event doesn't fire or fires not first so you actually need the first version output? If there is, I will fix this another way.

Remove duplicated rollup version output

---

src/Chunk.ts
src/rollup/index.ts
src/utils/getExportMode.ts
src/watch/index.ts
test/chunking-form/index.js
test/cli/index.js
test/form/index.js
test/function/index.js
test/function/samples/compact/_config.js
test/function/samples/export-type-mismatch-b/_config.js
test/function/samples/export-type-mismatch-c/_config.js
test/function/samples/export-type-mismatch/_config.js
test/function/samples/handles-stringified-sourcemaps/_config.js
test/function/samples/import-meta-url-compact/_config.js
test/misc/index.js
test/sourcemaps/index.js
test/utils.js

This unifies the basic setup of chunking-form, cli, form, function and sourcemaps test. With these changes, all of these tests can now be grouped into sub-folders. They also share the two common options `minNodeVersion` and `skipIfWindows`.
Beyond that, the options in function tests have been changed to have nested output options, similar to the other tests.
Also, some warning/error strings have been changed to correctly refer to `output.<optionName>` instead of `options.<optionName>`.

Unify sample-based tests

---

src/ast/nodes/ForInStatement.ts
src/ast/nodes/ForOfStatement.ts
test/function/samples/for-of-with-in-operator/_config.js
test/function/samples/for-of-with-in-operator/main.js

Turns out it was a simple ordering issue in the bind phase

Fix bind order in for-loops, resolves #2337

---

src/ast/nodes/BinaryExpression.ts
test/form/samples/invalid-binary-expressions/_config.js
test/form/samples/invalid-binary-expressions/_expected.js
test/form/samples/invalid-binary-expressions/main.js

Resolves #2342 
Both the "in" and "instanceof" operator will throw a type error if the right side is a primitive value. Thus this PR changes the handling for these two to assume they always return an unknown value.

Do not fail for binary expressions involving "in" and "instanceof"

---

bin/src/logging.ts
bin/src/run/batchWarnings.ts
bin/src/run/build.ts
bin/src/run/loadConfigFile.ts
bin/src/run/timings.ts
bin/src/run/watch.ts
package-lock.json
package.json
scripts/perf.js
test/cli/samples/interop/_expected.js
test/cli/samples/interop/main.js

This PR swaps chalk for [turbocolor](https://github.com/jorgebucaran/turbocolor). It ought to give us a humble perf boost as turbocolor loads _>20x_ faster and applies styles _>18x_ [faster](https://github.com/jorgebucaran/turbocolor/tree/master/bench#benchmarks) than chalk. Terminal color detection is also built-in, so I was able to simplify the code in one place. 
I let some comments in the diff to explain a few other things. 
Let me know if this looks good to you and if you'd like to take my contribution.
<pre>
chalk: 15.190ms
<em>turbocolor: 0.777ms</em>
chalk × 8,729 ops/sec
<em>turbocolor × 158,383 ops/sec</em>
chalk × 1,838 ops/sec
<em>turbocolor × 39,830 ops/sec</em>
chalk × 4,049 ops/sec
<em>turbocolor × 59,833 ops/sec</em>
</pre>
Cheers! 👋 
@Rich-Harris @lukastaegert @TrySound

Swap chalk for turbocolor

---

src/rollup/types.d.ts

Error: The `es6` output format is deprecated – use `es` instead

fix(types): `es6` output format is deprecated

---

src/Chunk.ts
test/misc/index.js

When the dictionary lookup or function look up return undefined or null, a warning should be emitted and the module name should be guessed.
If the user, doesn't receive a warning that the global name was not found, they won't be able to fix a possible issue. If the global name is incorrect or later set to null.
Closes: #2358
Some more context
https://github.com/dherges/ng-packagr/pull/1026#issuecomment-408605437

fix: no longer warns when no name was provided for global module

---

src/rollup/index.ts
test/hooks/index.js

This ensure onwrite executes in sequence, and fixes up the test case for that to fail if it doesn't.

Fix regression #2305

---

package.json
src/rollup/types.d.ts
test/typescript/index.ts

If plugin author want's to use TypeScript, he is missing official type for plugin implementation type. 
This PR addresses lack of proper type for implementation.

feat(types): add plugin implemenation type

---

bin/src/run/build.ts
src/Graph.ts
test/function/samples/external-conflict/_config.js
test/function/samples/external-conflict/main.js

This ensures the right diagnostic information is available for https://github.com/rollup/rollup/issues/2317, now outputting:
```
main.js → build.js...
(!) Unresolved dependencies
https://github.com/rollup/rollup/wiki/Troubleshooting#treating-module-as-external-dependency
node_modules/vue/dist/vue.esm.js (imported by  commonjs-proxy:node_modules/vue/dist/vue.esm.js)
[!] Error: 'node_modules/vue/dist/vue.esm.js' is imported as an external by  commonjs-proxy:node_modules/vue/dist/vue.esm.js, but is already an existing non-external module id.
Error: 'node_modules/vue/dist/vue.esm.js' is imported as an external by  commonjs-proxy:node_modules/vue/dist/vue.esm.js, but is already an existing non-external module id.
```

Ensure CLI warnings still show on errors, add an error for externalId collissions

---

src/Graph.ts
test/function/samples/external-resolve-false/_config.js
test/function/samples/external-resolve-false/main.js

Fix for https://github.com/rollup/rollup/issues/2350 - handle `resolvedId === false` like `isExternal === true`.

Fixed faulty logic related to handling externals when resolver returns false

---

bin/src/index.ts
bin/src/run/watch.ts

This PR fixes #2324. Note that the version output in the CLI was updated to match the output in watch. I went with the `rollup v0.0.0` notation rather than the full `rollup version 0.0.0` notation, as it's personally seen as cleaner and seems to be a standard by consensus in the biz. eg:
```console
→ node --version
v10.1.0
```

fix: version in watch mode + silent option, should not be displayed

---

src/Chunk.ts
test/chunking-form/samples/filenames-patterns/_config.js
test/chunking-form/samples/filenames-patterns/_expected/amd/chunk-main2-bff49b9a-amd.js
test/chunking-form/samples/filenames-patterns/_expected/amd/entry-main1-bad4fd49-amd.js
test/chunking-form/samples/filenames-patterns/_expected/amd/entry-main2-cc8b7fec-amd.js
test/chunking-form/samples/filenames-patterns/_expected/cjs/chunk-main2-4b102ef6-cjs.js
test/chunking-form/samples/filenames-patterns/_expected/cjs/entry-main1-0af20c04-cjs.js
test/chunking-form/samples/filenames-patterns/_expected/cjs/entry-main2-f433c6bb-cjs.js
test/chunking-form/samples/filenames-patterns/_expected/es/chunk-main2-e628225d-esm.js
test/chunking-form/samples/filenames-patterns/_expected/es/entry-main1-1a6a749d-esm.js
test/chunking-form/samples/filenames-patterns/_expected/es/entry-main2-137367cc-esm.js
test/chunking-form/samples/filenames-patterns/_expected/system/chunk-main2-4b538eea-system.js
test/chunking-form/samples/filenames-patterns/_expected/system/entry-main1-d020ac3e-system.js
test/chunking-form/samples/filenames-patterns/_expected/system/entry-main2-e24445f6-system.js
test/chunking-form/samples/filenames-patterns/dep.js
test/chunking-form/samples/filenames-patterns/main1.js
test/chunking-form/samples/filenames-patterns/main2.js

Well, there is possible (but HIGHLY unlikely) breakage. If somebody has uses `[format]` in their filenames.
They are super simple, I've just added support for `[format]` in file names patterns.

Allow [format] pattern for ID generation

---

src/Graph.ts
src/rollup/index.ts
src/rollup/types.d.ts
src/utils/assetHooks.ts
src/utils/pluginDriver.ts
src/utils/transform.ts
src/utils/transformChunk.ts
src/watch/index.ts
test/hooks/index.js
test/watch/index.js

Fixes https://github.com/rollup/rollup/issues/2383 adding a watch hook for change events.
The idea here as well is to then deprecate the `this.watcher` as we should now have all the info we need here.

Emit watch changes as a plugin hook

---

bin/src/logging.ts
test/cli/samples/custom-frame-log-stack/_config.js
test/cli/samples/custom-frame-log-stack/main.js
test/cli/samples/custom-frame-log-stack/rollup.config.js

List any relevent issue numbers:
Error stacks are IMHO way too important to just swallow them, if present they should always be logged.

Always log err.stack, even if err.frame is present

---

src/Graph.ts
test/function/samples/external-ignore-reserved-null-marker/_config.js
test/function/samples/external-ignore-reserved-null-marker/main.js

Paths like `\0external` are reserved in rollup plugins and shouldn't be
considered as external.

Don't test ids started with null marker in external

---

src/ast/nodes/Identifier.ts
test/function/samples/consistently-renames-destructured-parameters/_config.js
test/function/samples/consistently-renames-destructured-parameters/main.js
test/function/samples/consistently-renames-destructured-parameters/module_1.js

List any relevent issue numbers:
Resolves #2418
The issue was that in certain situations, cf. #2418, shorthanded properties in assignment patterns (all of this was necessary to trigger the bug) were renamed without keeping the original property name.
This one was tricky as to *why* this was broken between 0.57.1 and 0.58.0. The relevant change was the new logic to no longer switch AST prototypes but copy the AST into rollup.
The actual reason was that even though the pattern `{property = defaultVale}` produces the AST nodes `ObjectPattern > Property > AssignmentPattern > Identifier`, the old logic before 0.58.0 would mark the `Property` as the parent of the `Identifier`.
The changed logic starting with 0.58.0 unknowingly corrected …

Properly rename destructured parameters

---

package.json
test/hooks/index.js
test/watch/index.js

If yes, please describe the breakage.
This will lint JavaScript test files on commit via lint-staged the same way it is done for TypeScript files.

Lint test configs on commit

---

src/Graph.ts
src/watch/index.ts
test/watch/index.js

Resolves #2440
In watch mode if a plugin has a watchChange hook, the hook would be re-attached to the watcher for each new run resulting in an ever increasing number of watchers.
This fixes this by removing all change listeners directly before each run.
Additionally, watchers are now only every triggered once per run. This is done by accumulating changed ids until a new run starts and then triggering the plugin hooks directly before the new run starts.

Do not accumulate change listeners in watch mode

---

src/rollup/index.ts
test/hooks/index.js

https://github.com/rollup/rollup/issues/2434
`renderStart` hook is called in the beginning of a generation
`renderError ` hook is called when anything in generation is thrown an error
This is useful to achieve processing chunks inside workers and be able to start worker before any chunk is generated and end after generation or error.
@guybedford I'm not sure about `hookSeq`/`hookParallel` choice. Need your review here.

Add renderStart and renderError hooks

---

package-lock.json
src/Module.ts
src/ast/nodes/CatchClause.ts
test/function/samples/optional-catch-binding/_config.js
test/function/samples/optional-catch-binding/main.js

As described in issue #2454, acorn supports optional catch bindings but Rollup unconditionally expected the parameter to exist.
This may be a terrible pull request — I’m not very familiar with TypeScript and I haven’t contributed before, so I may not have approached this correctly.
However build/test seems to be working correctly.

Support optional catch binding (stage 4 / ES2019)

---

src/ast/nodes/AssignmentPattern.ts
src/ast/nodes/Identifier.ts
src/ast/nodes/Property.ts
src/utils/renderHelpers.ts
test/form/samples/renamed-pattern-defaults/_config.js
test/form/samples/renamed-pattern-defaults/_expected.js
test/form/samples/renamed-pattern-defaults/dep.js
test/form/samples/renamed-pattern-defaults/main.js

Resolves #2445
Resolves #2453 
In case of pattern properties, the previous deconflicting logic for identifiers contained a piece of special logic to detect if the identifier is a property in a shorthand pattern which faultily also triggered for identifiers in pattern defaults and caused #2445.
I replaced this with the IMO "proper" fix, which is adding a property to the node render options so that the parent can tell the child whether it is the name of a shorthand property. "Proper" because I expect these kinds of things to be much more stable in case we do syntax simplifications if the parent passes information to the child instead of the child querying the parent.

Correctly deconflict pattern defaults

---

src/rollup/index.ts
test/misc/index.js

I ticked the 'feature' box but this could also be considered a bugfix. Rollup ignores plugins that are `false`...
```js
// rollup.config.js
const dev = process.env.ROLLUP_WATCH === 'true';
export default {
input: 'src/index.js',
output: {
file: 'dist/index.js',
format: 'iife'
},
plugins: [
dev && someDevModeOnlyPlugin()
]
};
```
...but it would be nice if it disregarded *all* falsy values so that we could do this sort of thing:
```diff
// rollup.config.js
-const dev = process.env.ROLLUP_WATCH === 'true';
+const dev = process.env.ROLLUP_WATCH;
export default {
input: 'src/index.js',
output: {
file: 'dist/index.js',
format: 'iife'
},
plugins: [
dev && someDevModeOnlyPlugin()
]
};
```
I trip up on this …

ignore falsy plugins

---

bin/src/logging.ts
src/Module.ts
test/function/samples/error-parse-json/_config.js
test/function/samples/error-parse-json/file.json
test/function/samples/error-parse-json/main.js
test/function/samples/error-parse-unknown-extension/_config.js
test/function/samples/error-parse-unknown-extension/file.css
test/function/samples/error-parse-unknown-extension/main.js
test/misc/index.js

One of the most common gotchas which quickly leads to people despairing is if one of their dependencies (or they themselves) imports a JSON file which leads to a syntax error, cf. e.g. #1652.
This patch subtly improves our error messages by checking for PARSE_ERRRORs whether they happened in a file with an extension that does not end with "js" (to catch both .js and .mjs). If so, the error message reads either
`Unexpected token (Note that you need plugins to import files that are not JavaScript)`
or
`Unexpected token (Note that you need rollup-plugin-json to import JSON files)`
specifically for .json files. Feedback e.g. on the wording of the messages is very much welcome!

Throw better error messages for parse errors in non-JS files

---

src/utils/pluginDriver.ts
test/hooks/index.js

This error message should probably use a template string so that `pluginName` is not a literal but it's value is printed instead.

Fix template string

---

package-lock.json
package.json
src/ast/nodes/VariableDeclaration.ts
src/utils/collapseSourcemaps.ts

Recently, the TypeScript test was failing on node 6 due to version drift caused by the lack of lock-file support. This updates TypeScript and fixes the underlying type issues.

Update TypeScript and fix type errors

---

src/rollup/index.ts
test/hooks/index.js

#2461 
The `chunk` object that is passed to the `renderChunk` hook (and which forms the properties of the output bundle object) contains, inter alia, an `imports` array specifying the IDs of the external modules and chunks the chunk depends on.
Currently, the loop that assigns the IDs to the chunk is the same as the loop that gets the imported IDs; consequently the imported IDs are frequently `undefined`.
This PR separates ID assignation into a separate loop.

Assign chunk IDs before creating outputBundle chunks

---

src/ast/values.ts
test/function/samples/builtin-prototypes/argument-side-effects/_config.js
test/function/samples/builtin-prototypes/argument-side-effects/main.js

Resolves #2475 
As it turns out, the logic to detect side-effects when arguments of string prototype are called was present but not wired up properly in the case where the string itself was the return value of another prototype method. I.e.
```js
'abc'.replace('b', () => console.log('effect'));
```
was retained but
```js
'abc'.trim().replace('b', () => console.log('effect'));
```
was removed. This PR fixes this.

Detect side-effects in method arguments of virtual string literals

---

src/rollup/index.ts

This prevent memory usage to blow up with incremental builds.
fixes #2494

Remove previous cache from memory after graph creation

---

src/Module.ts
src/ast/nodes/ExportDefaultDeclaration.ts
src/ast/variables/ExportDefaultVariable.ts
test/function/samples/deconflict-ids/_config.js
test/function/samples/deconflict-ids/conflict1.js
test/function/samples/deconflict-ids/conflict2.js
test/function/samples/deconflict-ids/main.js
test/function/samples/deconflict-ids/used.js

Resolves #2414 
See also #2414. The logic for handling default exports of function and class declarations did not properly take into account that those not only declare a local variable as well but that reassigning this local variable *will* reassign the default export. Cf. these examples:
```js
// the default export will be 42 because it is the value of a that is exported
var a = 42;
export default a;
a = 43;
```
vs.
```js
// the default export will return 43 because it is the binding of a that is exported
export default function a() {return 42;};
a = () => 43;
```
Previously, only the first case was handled properly while this PR also handles the second case right. This also cleans up some logic so …

Properly deconflict ids of default exports that have been reassigned

---

src/ast/nodes/AssignmentExpression.ts
src/ast/nodes/shared/Node.ts
test/form/samples/modify-export-semi/_config.js
test/form/samples/modify-export-semi/_expected/system.js
test/form/samples/modify-export-semi/main.js

#2527
Fixes #2527.
Currently, semicolons are inserted using `appendLeft`. But this means that any code inserted after the end of the line will be inserted _after_ the semicolon, which is not what we want.
This fixes the issue by using `appendRight` instead.

Fix placement of inserted semicolon when using SystemJS

---

bin/src/run/index.ts
test/chunking-form/index.js
test/cli/index.js
test/cli/samples/deconflict-entry-point-in-subdir/_config.js
test/cli/samples/deconflict-entry-point-in-subdir/_expected/main.js
test/cli/samples/deconflict-entry-point-in-subdir/_expected/main2.js
test/cli/samples/deconflict-entry-point-in-subdir/main.js
test/cli/samples/deconflict-entry-point-in-subdir/sub/main.js
test/utils.js

Resolves #2543 
The special logic for naming entry points via the CLI by using "=" in the name always kicked in regardless if "=" was used or not. This lead to entry points overwriting each other. This PR only uses this naming logic in case at least one input uses "="

Make sure cli entry points with the same name but on different paths are deconflicted

---

src/utils/collapseSourcemaps.ts
test/form/samples/render-chunk-plugin-sourcemaps/_config.js
test/form/samples/render-chunk-plugin-sourcemaps/_expected/amd.js
test/form/samples/render-chunk-plugin-sourcemaps/_expected/amd.js.map
test/form/samples/render-chunk-plugin-sourcemaps/_expected/cjs.js
test/form/samples/render-chunk-plugin-sourcemaps/_expected/cjs.js.map
test/form/samples/render-chunk-plugin-sourcemaps/_expected/es.js
test/form/samples/render-chunk-plugin-sourcemaps/_expected/es.js.map
test/form/samples/render-chunk-plugin-sourcemaps/_expected/iife.js
test/form/samples/render-chunk-plugin-sourcemaps/_expected/iife.js.map
test/form/samples/render-chunk-plugin-sourcemaps/_expected/system.js
test/form/samples/render-chunk-plugin-sourcemaps/_expected/system.js.map
test/form/samples/render-chunk-plugin-sourcemaps/_expected/umd.js
test/form/samples/render-chunk-plugin-sourcemaps/_expected/umd.js.map
test/form/samples/render-chunk-plugin-sourcemaps/main.js

#2557 
Fixes #2557.
Previously, if source maps were enabled and a renderChunk hook returned just the transformed code (i.e., an `undefined` source map), Rollup would throw an error -- this was because `undefined` source maps are replaced with a placeholder object, used to signal that the source map is missing, and which plugin generated it. These objects were not being detected everywhere, so they would sometimes be used as source maps when they should not be.
This fixes the issue by reusing an existing block of code to detect these placeholder objects, issue a warning, and replace them with an empty source map.

Fix crash when returning undefined sourcemaps from renderChunk hook

---

package.json
rollup.config.js

At the moment, both the browser esm build as well as the generated sourcemaps are not published to npm. This will change the configuration to include those files as well.

Add more files to npm distribution

---

src/ast/nodes/ArrayPattern.ts
src/ast/nodes/AssignmentExpression.ts
src/ast/nodes/AssignmentPattern.ts
src/ast/nodes/Identifier.ts
src/ast/nodes/ObjectPattern.ts
src/ast/nodes/RestElement.ts
src/ast/nodes/VariableDeclaration.ts
src/ast/nodes/shared/Pattern.ts
src/rollup/types.d.ts
src/utils/systemJsRendering.ts
test/form/samples/system-export-destructuring-assignment/_config.js
test/form/samples/system-export-destructuring-assignment/_expected.js
test/form/samples/system-export-destructuring-assignment/main.js
test/form/samples/system-export-destructuring-declaration/_config.js
test/form/samples/system-export-destructuring-declaration/_expected.js
test/form/samples/system-export-destructuring-declaration/main.js

Closes #2556
This will make sure variables defined via a destructuring assignment are exported when building SystemJS output. Example:
```js
// input
export const {x, y: {z: a}, [u, v]} = someObject;
export const {w} = someOtherObject;
// output
const {x, y: {z: a}, [u, v]} = someObject; exports({x: x, a: a, u: u, v: v});
const {w} = someOtherObject; exports('w', w);
```
The exports are added inline with the declaration as otherwise the rendering logic would have become quite a bit more complex to get the indentation right.
**Update**: This will now also update exported variables which are reassigned in a non-declaration destructuring assignment via injecting an IIFE! Example:
```js
// input
export …
```

Properly export destructured export declarations in SystemJS

---

src/Chunk.ts
src/utils/relativeId.ts
src/utils/sanitize-file-name.ts
test/chunking-form/samples/sanitize-chunk-names/_config.js
test/chunking-form/samples/sanitize-chunk-names/_expected/amd/_virtual:entry-1.js
test/chunking-form/samples/sanitize-chunk-names/_expected/amd/_virtual:entry-2.js
test/chunking-form/samples/sanitize-chunk-names/_expected/cjs/_virtual:entry-1.js
test/chunking-form/samples/sanitize-chunk-names/_expected/cjs/_virtual:entry-2.js
test/chunking-form/samples/sanitize-chunk-names/_expected/es/_virtual:entry-1.js
test/chunking-form/samples/sanitize-chunk-names/_expected/es/_virtual:entry-2.js
test/chunking-form/samples/sanitize-chunk-names/_expected/system/_virtual:entry-1.js
test/chunking-form/samples/sanitize-chunk-names/_expected/system/_virtual:entry-2.js
test/chunking-form/samples/sanitize-chunk-names/main1.js

This will allow plugins to use virtual modules (i.e. starting with a `\0`) as entry points. This will enable `rollup-plugin-multi-entry` to work with rollup@1.0 as it creates such a virtual entry point,.

Sanitize chunk names to allow for virtually created chunks

---

src/rollup/types.d.ts

https://github.com/rollup/rollup/issues/2621
Removes `input` and `cache` properties from `RollupOptions` interface in [`types.d.ts`](https://github.com/rollup/rollup/blob/master/src/rollup/types.d.ts)
Closes https://github.com/rollup/rollup/issues/2621

Simplify RollupOptions

---

docs/999-big-list-of-options.md

The most common Rollup plugins are pretty fast to import (by Node standards), but even those will commonly add on a handful of milliseconds, and it’s not unheard of to have imports literally take seconds. If you don’t need it, why load it? I think that this is a good pattern to recommend.
eslint and stylelint are two good examples of unreasonably slow modules that will commonly be optional. stylelint can take a second or two, and eslint a few hundred milliseconds, because neither of them care enough about startup time. https://github.com/stylelint/stylelint/issues/2454 was me reporting it for stylelint. I wish more people used Rollup on their packages before submitting them to npm.

Show how to skip imports for optional plugins

---

src/rollup/types.d.ts

Closes #2618 
The `code` property was accidentally made required for rollup@1.0 which caused typing issues for custom warnings thrown by plugins.

Make `code` optional again in rollup warnings

---

src/Chunk.ts
test/chunking-form/samples/tree-shaken-dynamic-hash/_config.js
test/chunking-form/samples/tree-shaken-dynamic-hash/_expected/amd/5654511d.js
test/chunking-form/samples/tree-shaken-dynamic-hash/_expected/cjs/69b0b1f3.js
test/chunking-form/samples/tree-shaken-dynamic-hash/_expected/es/21d179d7.js
test/chunking-form/samples/tree-shaken-dynamic-hash/_expected/system/8714c598.js
test/chunking-form/samples/tree-shaken-dynamic-hash/foo.js
test/chunking-form/samples/tree-shaken-dynamic-hash/main.js

Resolves #2625
When a dynamic import is tree-shaken, trying to calculate a hash for the importing chunk will result in an error as there is no rendered chunk for the dynamic import. This is a very simple fix.

Do not fail when generating hashes for tree-shaken dynamic imports

---

package-lock.json
package.json
src/ast/nodes/BinaryExpression.ts
src/ast/nodes/Literal.ts
test/form/samples/big-int/_config.js
test/form/samples/big-int/_expected.js
test/form/samples/big-int/main.js

Closes #2626 
This should address the following issues when using the acorn-bigint plugin:
- bigint numbers wrongly being treated like "null" when checking conditionals for tree-shakeability on older environments
- bigints being passed to `Math.pow` when checking conditionals on newer environments
At the moment to ensure Node 6 compatibility, "**" will be transpiled to `Math.pow` which does not support bigints. At the same time, the acorn plugin will wrongly mark bigint literals to have the value "null" on older systems that do not support them. This solves those issues by treating bigint literals as "unknown" on all systems. Theoretically, it would also be possible to leave them as literals on newer …

Fix support for BigInt literals when using the acorn plugin

---

bin/src/help.md
docs/01-command-line-reference.md

Closes #2639 
This is an attempt to make the CLI docs a little less confusing

Make sure all CLI options are listed in the summary

---

docs/999-big-list-of-options.md

n/a
The "Big List of Options" documentation has a typo in the text which precedes the `entryFileNames` example.
The config results in chunks named "entry-a.js" and "entry-b.js", not "index-*".

Fix typo related to entryFileNames example

---

docs/05-plugins.md
src/rollup/index.ts
src/rollup/types.d.ts
test/hooks/index.js

Resolves #2617 
This will add a new `writeBundle` hook that will be executed after files have been written to disk to allow plugins to e.g. modify file attributes.
Also, the plugin documentation is changed to list how plugin hooks are executed (sync/async/sequential/parallel...)

writeBundle hook

---

docs/05-plugins.md
src/rollup/index.ts
src/rollup/types.d.ts
test/hooks/index.js

Resolves #2624 
This makes this.meta and thus the rollup version available to the `options` hook. It also passes the input options to the `buildStart` hook (which was already part of the signature).

Make this.meta available in options hook, pass input options to buildStart hook

---

docs/999-big-list-of-options.md

While working on plugin stuff I noticed that I was using `[extname]` and seeing a leading period in the result, which the docs said I shouldn't. I went and looked at the rollup source for this functionality:
https://github.com/rollup/rollup/blob/00d752181ca2a582b03911646be0f7a4ea44bda6/src/utils/assetHooks.ts#L34-L37
Which sure makes it look like the docs were wrong. So I swapped `[extname]` and `[ext]` so now they line up correctly based on what they do.

docs: swap descriptions for [extname] and [ext]

---

src/ast/nodes/ObjectExpression.ts
test/function/samples/builtin-prototypes/truthiness/_config.js
test/function/samples/builtin-prototypes/truthiness/main.js

Resolves #2651 
This will make sure that when checking the value of object expression members, builtin prototype methods will not be considered to be falsy

Make sure object prototype methods are not considered to be falsy

---

src/Chunk.ts
test/misc/bundle-information.js

Resolves #2659 
Before, tree-shaken dynamic imports would leave `undefined` in the `dynamicImports` section of the importing chunk in the bundle information.

Completely remove tree-shaken dynamic imports from bundle information

---

test/form/samples/export-globals/Number.js
test/form/samples/export-globals/_expected/amd.js
test/form/samples/export-globals/_expected/cjs.js
test/form/samples/export-globals/_expected/es.js
test/form/samples/export-globals/_expected/iife.js
test/form/samples/export-globals/_expected/system.js
test/form/samples/export-globals/_expected/umd.js

#2691 introduced a small typo in the `exports-globals` form test. This fixes the typo, so the test does the right thing once again.

Fix typo in export-globals test

---

package-lock.json
package.json
rollup.config.js

Resolves #2704 
The fix for the ESM version got messed up by the renamed import

Fix ESM version of Rollup

---

src/Chunk.ts
src/ExternalModule.ts
test/function/samples/mixed-external-paths/_config.js
test/function/samples/mixed-external-paths/main.js
test/misc/misc.js

Resolves #2675 
There is a bug where if different outputs use different paths for external dependencies, then the path used by the first output is used for all other outputs as well. This fixes this by recreating the path for each output.

Always recreate paths for external modules

---

src/Chunk.ts
test/chunking-form/samples/dynamic-import-only-reexports/_config.js
test/chunking-form/samples/dynamic-import-only-reexports/_expected/amd/generated-chunk.js
test/chunking-form/samples/dynamic-import-only-reexports/_expected/amd/main.js
test/chunking-form/samples/dynamic-import-only-reexports/_expected/cjs/generated-chunk.js
test/chunking-form/samples/dynamic-import-only-reexports/_expected/cjs/main.js
test/chunking-form/samples/dynamic-import-only-reexports/_expected/es/generated-chunk.js
test/chunking-form/samples/dynamic-import-only-reexports/_expected/es/main.js
test/chunking-form/samples/dynamic-import-only-reexports/_expected/system/generated-chunk.js
test/chunking-form/samples/dynamic-import-only-reexports/_expected/system/main.js
test/chunking-form/samples/dynamic-import-only-reexports/dep.js
test/chunking-form/samples/dynamic-import-only-reexports/dynamic.js
test/chunking-form/samples/dynamic-import-only-reexports/main.js

Resolve #2713 
The logic to render dynamic imports was only looking if the directly imported module was empty while it should have been looking at the whole chunk. Thus such a chunk would be treated as tree-shaken by some (but not all) parts of the logic, resulting in the wrong import.

Properly render dynamic imports when imported module is empty

---

CHANGELOG.md
src/Chunk.ts
src/ast/variables/ExportDefaultVariable.ts
test/chunking-form/samples/deduplicate-imports-referencing-originals/_config.js
test/chunking-form/samples/deduplicate-imports-referencing-originals/_expected/amd/generated-chunk.js
test/chunking-form/samples/deduplicate-imports-referencing-originals/_expected/amd/main1.js
test/chunking-form/samples/deduplicate-imports-referencing-originals/_expected/amd/main2.js
test/chunking-form/samples/deduplicate-imports-referencing-originals/_expected/cjs/generated-chunk.js
test/chunking-form/samples/deduplicate-imports-referencing-originals/_expected/cjs/main1.js
test/chunking-form/samples/deduplicate-imports-referencing-originals/_expected/cjs/main2.js
test/chunking-form/samples/deduplicate-imports-referencing-originals/_expected/es/generated-chunk.js
test/chunking-form/samples/deduplicate-imports-referencing-originals/_expected/es/main1.js
test/chunking-form/samples/deduplicate-imports-referencing-originals/_expected/es/main2.js
test/chunking-form/samples/deduplicate-imports-referencing-originals/_expected/system/generated-chunk.js
test/chunking-form/samples/deduplicate-imports-referencing-originals/_expected/system/main1.js
test/chunking-form/samples/deduplicate-imports-referencing-originals/_expected/system/main2.js
test/chunking-form/samples/deduplicate-imports-referencing-originals/foo.js
test/chunking-form/samples/deduplicate-imports-referencing-originals/main1.js
test/chunking-form/samples/deduplicate-imports-referencing-originals/main2.js
test/chunking-form/samples/deduplicate-imports-referencing-originals/proxy.js

Resolves #2715
There has always been an optimization in Rollup where default exports are treated as a placeholder for another variable that has been exported in certain situations (e.g. default exporting a function declaration or a variable that is not mutated)
After the latest refactoring of the scope hoisting, this could cause rendering issues as both variables would be rendered using the same name.
This fixes this by manually deduplicating imports. This is probably not the best possible fix, which would be to add a step where those variables are replaced by their originals. Such a solution, however, would have touched many more places for possibly dubious improvements. The only known downside of …

Deduplicate imports referencing default exports and their original variables

---

src/Graph.ts
src/Module.ts
src/rollup/types.d.ts
src/utils/pluginDriver.ts
test/incremental/index.js
test/utils.js

List any relevant issue numbers: 2670
I use a plugin that marks some imports as external by returning false from resolveId. This doesn't work in watch-mode. On all subsequent builds after initial, rollup will try to load the external modules, and fail. This seems to be the same problem as in #2670.
I solved it by explicitly storing external state in the cache.

Incremental external

---

src/finalisers/shared/getExportBlock.ts
test/chunking-form/samples/entry-point-without-own-code/_expected/amd/generated-m1.js
test/chunking-form/samples/entry-point-without-own-code/_expected/amd/m1.js
test/chunking-form/samples/entry-point-without-own-code/_expected/cjs/generated-m1.js
test/chunking-form/samples/export-default-from-entry/_config.js
test/chunking-form/samples/export-default-from-entry/_expected/amd/dep.js
test/chunking-form/samples/export-default-from-entry/_expected/amd/main.js
test/chunking-form/samples/export-default-from-entry/_expected/cjs/dep.js
test/chunking-form/samples/export-default-from-entry/_expected/cjs/main.js
test/chunking-form/samples/export-default-from-entry/_expected/es/dep.js
test/chunking-form/samples/export-default-from-entry/_expected/es/main.js
test/chunking-form/samples/export-default-from-entry/_expected/system/dep.js
test/chunking-form/samples/export-default-from-entry/_expected/system/main.js
test/chunking-form/samples/export-default-from-entry/dep.js
test/chunking-form/samples/export-default-from-entry/main.js
test/function/samples/code-splitting-export-default-from-entry/_config.js
test/function/samples/code-splitting-export-default-from-entry/dep.js
test/function/samples/code-splitting-export-default-from-entry/main.js

Resolves #2721 
As stated in the title, the finaliser always assumed chunks to use named exports mode (which is true for internal chunks but not necessarily true for entry points). This is now taken into account, fixing this:
https://rollupjs.org/repl?version=1.3.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiUyRiUyMFRoaXMlMjBpcyUyMGFjY2Vzc2luZyUyMGRlcC5kZWZhdWx0JTIwd2hpbGUlMjBpdCUyMHNob3VsZCUyMGJlJTIwdXNpbmclMjBkZXAlNUNuZXhwb3J0JTIwJTdCZGVmYXVsdCUyMGFzJTIwdmFsdWUlN0QlMjBmcm9tJTIwJy4lMkZkZXAnJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyZGVwLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGRlZmF1bHQlMjA0MiUzQiUyMiUyQyU …

Take chunk export mode into account when reexporting default

---

src/utils/mergeOptions.ts
test/function/samples/empty-string-as-module-name/_config.js
test/function/samples/empty-string-as-module-name/main.js
test/function/samples/empty-string-as-module-name/main.js#.js

I'm not sure which category to put test about this bug.

fix: the empty string importee should not always be treated as external module id

---

src/Chunk.ts
test/chunking-form/samples/deduplicate-imports-referencing-originals-2/_config.js
test/chunking-form/samples/deduplicate-imports-referencing-originals-2/_expected/amd/generated-chunk.js
test/chunking-form/samples/deduplicate-imports-referencing-originals-2/_expected/amd/main1.js
test/chunking-form/samples/deduplicate-imports-referencing-originals-2/_expected/amd/main2.js
test/chunking-form/samples/deduplicate-imports-referencing-originals-2/_expected/cjs/generated-chunk.js
test/chunking-form/samples/deduplicate-imports-referencing-originals-2/_expected/cjs/main1.js
test/chunking-form/samples/deduplicate-imports-referencing-originals-2/_expected/cjs/main2.js
test/chunking-form/samples/deduplicate-imports-referencing-originals-2/_expected/es/generated-chunk.js
test/chunking-form/samples/deduplicate-imports-referencing-originals-2/_expected/es/main1.js
test/chunking-form/samples/deduplicate-imports-referencing-originals-2/_expected/es/main2.js
test/chunking-form/samples/deduplicate-imports-referencing-originals-2/_expected/system/generated-chunk.js
test/chunking-form/samples/deduplicate-imports-referencing-originals-2/_expected/system/main1.js
test/chunking-form/samples/deduplicate-imports-referencing-originals-2/_expected/system/main2.js
test/chunking-form/samples/deduplicate-imports-referencing-originals-2/foo.js
test/chunking-form/samples/deduplicate-imports-referencing-originals-2/main1.js
test/chunking-form/samples/deduplicate-imports-referencing-originals-2/main2.js
test/chunking-form/samples/deduplicate-imports-referencing-originals-2/proxy1.js
test/chunking-form/samples/deduplicate-imports-referencing-originals-2/proxy2.js

Hopefully resolves #2726 
This is basically a generalization of #2719. When two different default exports reference the same variable, it is possible that both are rendered as separate imports.
This is just again a fix for the import situation; the exports will still be rendered several times. The problem is that it is only known after tree-shaking if a default export can be identified with the original variable, at which point many other things have already been initialized using the separate variables.
A proper fix for the future might include
* calculating module dependencies AFTER tree-shaking
* before doing that
- replacing default exports in the same module with exports of their original …

Fix a situation where two different imports with the same name are rendered

---

docs/05-plugins.md
src/Graph.ts
src/Module.ts
src/rollup/types.d.ts
test/function/samples/resolve-id-object/_config.js
test/function/samples/resolve-id-object/foo.js
test/function/samples/resolve-id-object/main.js
test/function/samples/unused-import/_config.js
test/misc/misc.js

This change will extend the syntax of the `resolveId` hook to support returning an object
```ts
interface ResolvedId {
// the absence of this property is interpreted the same as "false"
external?: boolean;
id: string;
}
```
The immediate advantage of this change is to allow plugins to resolve an import to a new id while marking it as `external` at the same time. Previously, this required the user to also add the new `id` as an external id manually.
The main reason for this addition, however, is that I want to have an extended format that allows you to pass more meta information with this hook in the future (say, package side-effects... 😜).
A minor side-effects of this change is that you will only be …

Allow resolveId to return an object

---

docs/05-plugins.md
src/rollup/index.ts
src/rollup/types.d.ts
src/utils/pluginDriver.ts
test/hooks/index.js

#2735
This PR adds `outputOptions` hook for plugins, that allows overriding of `OutputOptions` passed to `bundle.generate`. I've based the code on the existing `options` hook. The hook is run inside `normalizeOutputOptions`, as it seemed to be the place, where the final form of output options is created.

Add hook for modifying OutputOptions

---

src/ast/nodes/ExportDefaultDeclaration.ts
test/form/samples/no-treeshake-default-export-conflict/_config.js
test/form/samples/no-treeshake-default-export-conflict/_expected.js
test/form/samples/no-treeshake-default-export-conflict/foo.js
test/form/samples/no-treeshake-default-export-conflict/main.js

Resolves #2752 
The algorithm used when skipping tree-shaking did not include variables reflecting unused default exports which resulted in those exports being ignored for deconflicting.

Make sure unused default exports are deconflicted when not tree-shaking

---

src/ast/nodes/ArrayPattern.ts
src/ast/nodes/ExportDefaultDeclaration.ts
src/ast/nodes/MemberExpression.ts
test/form/samples/pattern-member-expressions/_config.js
test/form/samples/pattern-member-expressions/_expected/amd.js
test/form/samples/pattern-member-expressions/_expected/cjs.js
test/form/samples/pattern-member-expressions/_expected/es.js
test/form/samples/pattern-member-expressions/_expected/iife.js
test/form/samples/pattern-member-expressions/_expected/system.js
test/form/samples/pattern-member-expressions/_expected/umd.js
test/form/samples/pattern-member-expressions/main.js

#2750 
Honestly, I was not aware that you could do this:
```js
const a = [1];
const b = {};
([a[1], b.value] = [8, 9]);
console.log(a); // [1, 8]
console.log(b); // {value: 9}
```
But as it seems, even the maintainers of the ESTree AST spec are struggling with this: https://github.com/estree/estree/issues/162
This triggered an issue in SystemJS builds, which rely on a special method present on those nodes.

Handle member expressions in array patterns

---

src/Graph.ts
test/form/samples/relative-external-ids/_config.js
test/form/samples/relative-external-ids/_expected.js
test/form/samples/relative-external-ids/main.js
test/form/samples/relative-external-ids/nested/nested.js

Resolves #2762 
A previous refactoring had broken the functionality that Rollup normalizes relative external ids to the common parent directory of all entry points. This PR restores this functionality and adds proper tests.

Resolve relative external ids

---

src/rollup/types.d.ts

This is what the docs are telling me the types should be: https://rollupjs.org/guide/en#treeshake
I was using the Node API in typescript and typescript was telling me:
```
Type '{ pureExternalModules: boolean; }' is not assignable to type 'boolean | TreeshakingOptions'.
Type '{ pureExternalModules: boolean; }' is missing the following properties from type 'TreeshakingOptions': annotations, propertyReadSideEffectsts(2322)
rollup.d.ts(286, 2): The expected type comes from property 'treeshake' which is declared here on type 'RollupOptions'
```
I was able to fix the warning by adding all 3 properties to the `TreeshakingOptions`.
Looking at the docs, I concluded that the interface is actually wrong.
I'm unsure this qualifies as a bugfix.

Make all properties in TreeshakingOptions optional

---

src/rollup/types.d.ts
src/utils/mergeOptions.ts

Now that Node.js --experimental-modules has been updated, it has moved to longer names for formats as a standard in use in flags, package.json and loaders. So instead of `"cjs"` it is `"commonjs"` and instead of `"esm"` it is `"module"`.
I know it's a pain, but I think it would be beneficial if we can support these aliases now, and possibly even consider them as the defaults in the long terms.
Apologies for whatever role I've played in churn here too :)

Support Node-style format aliases

---

bin/src/run/loadConfigFile.ts

This inlines the interopDefault handling.
Note that we don't need to explicitly handle the null case (the rare chance of `module.exports = undefined`), because that would fail anyway in subsequent code paths.
The benefit of this approach is that as discussed previously I'm working on supporting Rollup itself in a transformation that can convert CJS packages to ESM packages, and we can support dynamic require fine when it is detected as `Promise.resolve(require(x))`, but the `interopDefault` wrapper stops this from working out.
Would be amazing to merge this to support the dynamic import conversion for full Rollup support in this work here.

Inline interopDefault in config loading

---

src/rollup/index.ts
test/hooks/index.js
test/misc/write-bundle.js

resolves #2801 
When checking if `file` or `dir` had been passed in `bundle.write`, Rollup did not use the normalized output options that had been run through the `outputOptions` hook but the raw output options.

Observe modified output options in bundle.write

---

src/ast/nodes/Identifier.ts
test/form/samples/simplify-return-expression/_config.js
test/form/samples/simplify-return-expression/_expected.js
test/form/samples/simplify-return-expression/main.js

Resolves #2799 
It is possible that Rollup needs to analyze values of identifiers before they have been bound to their variables, which can cause in sub-optimal tree-shaking results. This is fixed here by allowing out-of-order binding of identifiers if their value is needed earlier. This allows for the following:
```js
// input
export const test = () => {
console.log(foo());
console.log(bar());
};
const foo = () => {
return BUILD ? A : B;
};
const bar = () => {
return getBuild() ? A : B;
};
const getBuild = () => BUILD;
const BUILD = true;
// output
const test = () => {
console.log(foo());
console.log(bar());
};
const foo = () => {
return A;
};
const bar = () => {
return A;
};
export { test };
```

Handle out-of-order binding of identifiers to improve tree-shaking

---

src/rollup/index.ts

Before, it'd nebulously crash when trying to dereference `RESERVED_NAMES_BY_FORMAT` instead.
(It'd be nice if the formats were centrally defined, but since they aren't I decided to just add another list.)

Catch invalid options.format values

---

src/Module.ts
test/misc/bundle-information.js

closes #2834
The `RenderedModule.removedExports/renderedExports` now correctly track the *item* being exported, and not the export declaration itself.

Fix `removedExports` to correctly track the exported item

---

src/Module.ts
test/function/samples/cycles-export-star/_config.js
test/function/samples/cycles-export-star/a.js
test/function/samples/cycles-export-star/b.js
test/function/samples/cycles-export-star/main.js

closes #2815
Circular `export * from X` used to lead to a stack overflow. This Fix avoids that by keeping track of already walked modules. Not sure if this is the right place for such a fix?

Make sure circular `export * from X` does not stack overflow

---

src/ast/variables/NamespaceVariable.ts
src/utils/reservedNames.ts
test/form/samples/namespace-object-import/_config.js
test/form/samples/namespace-object-import/_expected/amd.js
test/form/samples/namespace-object-import/_expected/cjs.js
test/form/samples/namespace-object-import/_expected/es.js
test/form/samples/namespace-object-import/_expected/iife.js
test/form/samples/namespace-object-import/_expected/system.js
test/form/samples/namespace-object-import/_expected/umd.js
test/form/samples/namespace-object-import/dep.js
test/form/samples/namespace-object-import/main.js

#2591
Add ES3 support for namespace import. All other es3 compatibility issues I'm aware of could be fixed with polyfills and babel.

Add es3 support for namespace object import

---

src/utils/transform.ts
test/function/samples/transform-empty-string/_config.js
test/function/samples/transform-empty-string/main.js
test/function/samples/transform-empty-string/transformed.js

Resolves #2859 
As a regression of the latest release, transformers returning an empty string were treated as if they returned `null` and were therefore ignored. This broke Sapper.

Allow transformers to return an empty string

---

src/Chunk.ts
src/Module.ts
test/chunking-form/samples/preserve-modules-nested-export/_config.js
test/chunking-form/samples/preserve-modules-nested-export/_expected/amd/dep.js
test/chunking-form/samples/preserve-modules-nested-export/_expected/amd/main1.js
test/chunking-form/samples/preserve-modules-nested-export/_expected/amd/main2.js
test/chunking-form/samples/preserve-modules-nested-export/_expected/cjs/dep.js
test/chunking-form/samples/preserve-modules-nested-export/_expected/cjs/main1.js
test/chunking-form/samples/preserve-modules-nested-export/_expected/cjs/main2.js
test/chunking-form/samples/preserve-modules-nested-export/_expected/es/dep.js
test/chunking-form/samples/preserve-modules-nested-export/_expected/es/main1.js
test/chunking-form/samples/preserve-modules-nested-export/_expected/es/main2.js
test/chunking-form/samples/preserve-modules-nested-export/_expected/system/dep.js
test/chunking-form/samples/preserve-modules-nested-export/_expected/system/main1.js
test/chunking-form/samples/preserve-modules-nested-export/_expected/system/main2.js
test/chunking-form/samples/preserve-modules-nested-export/dep.js
test/chunking-form/samples/preserve-modules-nested-export/main1.js
test/chunking-form/samples/preserve-modules-nested-export/main2.js

#2854
This hopefully fixes the issue described in #2854 essentially ensuring that entry file exports are preserved when using `preserveModules`. 
This fix seemed a little too basic and I'm new to the codebase so theres a near certainty I've missed something important here or done something in an incorrect way.

Keep nested exports with preserveModules (#2854)

---

src/ModuleLoader.ts

Help to find where the error occurred from the plugin.

Reserve error stack information

---

docs/999-big-list-of-options.md

#2870 
This mentions in the documentation of the input option that you can use a "/" to create entry chunks in different sub-folders (see also #2870)

Mention subfolders in docs

---

src/Chunk.ts
test/form/samples/protect-cjs-globals/_config.js
test/form/samples/protect-cjs-globals/_expected/amd.js
test/form/samples/protect-cjs-globals/_expected/cjs.js
test/form/samples/protect-cjs-globals/_expected/es.js
test/form/samples/protect-cjs-globals/_expected/iife.js
test/form/samples/protect-cjs-globals/_expected/system.js
test/form/samples/protect-cjs-globals/_expected/umd.js
test/form/samples/protect-cjs-globals/main.js
test/form/samples/sequence-expression/_expected/cjs.js
test/function/samples/protect-cjs-globals/_config.js
test/function/samples/protect-cjs-globals/main.js

Resolves #2886 
This PR makes sure that Rollup does not produce invalid CJS modules when `module`, `require`, `__filename` or `__dirname` are defined as top-level variables in modules.

Protect all module globals for CJS output from being redefined

---

src/ast/nodes/TryStatement.ts
test/form/samples/try-statement-deoptimization/include-via-outside-variable/_config.js
test/form/samples/try-statement-deoptimization/include-via-outside-variable/_expected.js
test/form/samples/try-statement-deoptimization/include-via-outside-variable/main.js

Resolves #2894 
There was an overzealous performance optimization that prevented try statements from being included if they have already been included in a different way, e.g. because they contain a variable delaration that was included.

Properly include try-catch-statements even if they have already been included in some way

---

src/ast/nodes/MemberExpression.ts
test/form/samples/early-bind-member-expressions/_config.js
test/form/samples/early-bind-member-expressions/_expected.js
test/form/samples/early-bind-member-expressions/main.js

Resolves #2895 
When binding namespace members, it could happen that the base variable was bound to a variable before the member expression which could lead to the namespace being needlessly included later.

Correctly handle early bind for member expressions

---

browser/path.ts
src/Chunk.ts
test/function/index.js
test/function/samples/relative-outside-external/_config.js
test/function/samples/relative-outside-external/main.js

Resolves #2901 
This will fix an issue where a relative external dependency of a chunk was outside `dir` in a way that was no longer covered by the current working directory. We do this by using and adjusting our browser polyfill for path.relative for chunks.

Use browser relative path algorithm for chunks

---

src/Module.ts
src/ModuleLoader.ts
src/ast/variables/Variable.ts
test/function/samples/module-side-effects/external-false/_config.js
test/function/samples/module-side-effects/external-false/main.js
test/function/samples/module-side-effects/reexport-from-external/_config.js
test/function/samples/module-side-effects/reexport-from-external/main.js

Resolves #2904 
This fixes two things:
- If an external variable is re-exported, the external variable is always properly included
- If a module is only implicitly external (i.e. not found), it should still be marked as side-effect free if this configuration holds for external modules.

Make sure external re-exports are included for moduleSideEffects: false

---

src/ast/nodes/CallExpression.ts
test/form/samples/treeshake-excess-arguments/arrow-function-arguments/_expected.js
test/form/samples/treeshake-excess-arguments/arrow-function-arguments/main.js

Fix treeshaken parameters around parentheses

---

docs/05-plugins.md
docs/999-big-list-of-options.md
src/ModuleLoader.ts
src/utils/pluginDriver.ts
test/form/samples/relative-external-ids/_expected.js

Resolves #2867
This change will improve the behaviour of the resolveId hook so that the user has the option to specify external ids that will appear in the generated bundle unmodified even in the case of relative imports. This also contains a documentation update that explains this.
The logic is now:
- if a relative import is marked as external via user option or by returning "false" from the "resolveId" hook, Rollup will internally resolve the import to an absolute file system location to be able to merge different relative imports of the same external file. When the bundle is written, the absolute location will be converted to a relative import again as if the "output.file" or "output.dir" option …

Do not resolve relative external ids when using the object form

---

src/ModuleLoader.ts
test/incremental/index.js

Resolves #2903 
As it turns out, id resolution is REALLY expensive and while the ids of static imports were cached between builds, the ids of dynamic imports were not cached. This is fixed now for statically resolvable dynamic imports. This should also speed up watch mode.

Cache dynamic ids

---

src/ast/nodes/TryStatement.ts
test/form/samples/try-statement-deoptimization/deactivate-via-option/_expected.js
test/form/samples/try-statement-deoptimization/deactivate-via-option/main.js

Resolves #2913 
When tryCatchDeoptimization is deactivated, we need to run `include` on all children of the try statement for each tree-shaking pass, not only for the first (this is how it works for all other nodes). This caused e.g. call parameters to vanish but other effects could have been caused by this as well.

Properly include try statements for each pass when deoptimization is deactivated

---

src/ast/nodes/Literal.ts
test/form/samples/deopt-regexp-type/_config.js
test/form/samples/deopt-regexp-type/_expected.js
test/form/samples/deopt-regexp-type/main.js

As stated in the title, es6-shim scans if regular expressions have type `function`. This will deoptimize this check as I do not think this is a huge loss in treeshakeability.

Deoptimize typeof for regular expression literals to better support es6-shim

---

src/ast/nodes/BinaryExpression.ts
test/form/samples/deopt-string-concatenation/_config.js
test/form/samples/deopt-string-concatenation/_expected.js
test/form/samples/deopt-string-concatenation/main.js

This will deoptimize `'' + something` type conversion when used as an expression statement to better support es5-shim

Support implicit type coercion errors in es5-shim

---

src/ast/scopes/ParameterScope.ts
test/form/samples/treeshake-excess-arguments/argument-side-effects/_config.js
test/form/samples/treeshake-excess-arguments/argument-side-effects/_expected.js
test/form/samples/treeshake-excess-arguments/argument-side-effects/main.js

Resolves #2922
A simple case that was not covered by a test. Arguments should not be dropped if they have side-effects, independent of if there is a corresponding parameter or not.

Do not tree-shake arguments with side-effects

---

src/Chunk.ts
test/function/samples/chunking-duplicate-reexport/_config.js
test/function/samples/chunking-duplicate-reexport/chunk1.js
test/function/samples/chunking-duplicate-reexport/chunk2.js
test/function/samples/chunking-duplicate-reexport/lib.js
test/function/samples/chunking-duplicate-reexport/main.js

Handle reexports from dynamic entries across chunks

---

src/Module.ts
src/ModuleLoader.ts
src/rollup/types.d.ts
src/utils/pluginDriver.ts
src/utils/transform.ts
test/hooks/index.js

Resolves #2929
This applies the same logic to emitted chunks that we have for emitted assets.

Reemit chunks emitted from transform hooks

---

src/Module.ts
src/ModuleLoader.ts
src/rollup/types.d.ts
test/hooks/index.js

Resolves #2929 
Even though there was logic to re-emit assets emitted from a transform hook un incremental builds, this logic would only work once as the information about emitted assets was not passed on correctly. This PR fixes this + the same issue for chunks.

Fix repeated re-emission of files emitted from a transform hook

---

src/utils/defaultPlugin.ts
test/chunking-form/samples/asset-emission/_expected/cjs/main.js
test/chunking-form/samples/asset-emission/_expected/cjs/nested/chunk2.js
test/chunking-form/samples/configure-asset-url/_expected/cjs/main.js
test/chunking-form/samples/configure-file-url/_expected/cjs/main.js
test/chunking-form/samples/emit-chunk-worker/_expected/cjs/chunks/nested.js
test/chunking-form/samples/emit-chunk-worker/_expected/cjs/chunks/worker-proxy.js
test/chunking-form/samples/emit-chunk-worker/_expected/cjs/main.js
test/chunking-form/samples/emit-chunk-worklet/_expected/cjs/main.js
test/form/samples/asset-emission/_expected/cjs.js
test/form/samples/asset-emission/_expected/iife.js
test/form/samples/asset-emission/_expected/umd.js
test/form/samples/asset-emission/index-umd-iife-queryparam.html
test/form/samples/configure-asset-url/_expected/cjs.js
test/form/samples/configure-asset-url/_expected/iife.js
test/form/samples/configure-asset-url/_expected/umd.js
test/form/samples/configure-file-url/_expected/cjs.js
test/form/samples/configure-file-url/_expected/iife.js
test/form/samples/configure-file-url/_expected/umd.js
test/hooks/index.js

Resolves #2603 
Fixes URL resolution by not just concatenating strings but using the URL constructor to its full potential, i.e. `new URL('test/file.png', 'http://server.js/index.js?test=1').href === 'http://server.js/test/file.png')`

Fix URL resolution to work when the current script contains query parameters

---

src/Module.ts
src/ModuleLoader.ts
src/rollup/types.d.ts

Resolves #2939 
Apparently, `void` is not the same as `null | undefined`. This PR changes the types to explicitly list `null | undefined` in various plugin hooks where it makes sense.

Explicitly allow null as return value for various hooks

---

src/Chunk.ts
test/form/samples/remove-treeshaken-banners/_config.js
test/form/samples/remove-treeshaken-banners/_expected.js
test/form/samples/remove-treeshaken-banners/dep-included.js
test/form/samples/remove-treeshaken-banners/dep-removed.js
test/form/samples/remove-treeshaken-banners/main.js
test/form/samples/tree-shake-default-exports/_expected/amd.js
test/form/samples/tree-shake-default-exports/_expected/cjs.js
test/form/samples/tree-shake-default-exports/_expected/es.js
test/form/samples/tree-shake-default-exports/_expected/iife.js
test/form/samples/tree-shake-default-exports/_expected/system.js
test/form/samples/tree-shake-default-exports/_expected/umd.js
test/misc/bundle-information.js

Resolves #2927 
Previously even files where all statements were tree-shaken had their banner and footer comments included. This PR changes this so that files without included statements
- are not rendered internally for better performance
- are completely omitted from the generated code including all comments
- can be safely detected by checking for `renderedLength === 0` in the modules property of chunks in the generated bundle

Completely omit files that do not have any included statements

---

src/ast/scopes/ChildScope.ts
src/ast/scopes/ParameterScope.ts
src/ast/variables/Variable.ts
test/function/samples/argument-treeshaking-parameter-conflict/_config.js
test/function/samples/argument-treeshaking-parameter-conflict/dep.js
test/function/samples/argument-treeshaking-parameter-conflict/main.js

Resolves #2970 
As treeshaken parameters were still rendered, this could cause conflicts with other variables. This PR fixes this.

Deconflict unused parameters

---

docs/05-plugin-development.md
src/rollup/types.d.ts
src/utils/error.ts
src/utils/transform.ts

Resolves #2974 
This makes sure that both ways of supplying a position/location are supported and work.

Align TS types, docs and implementation for this.warn and this.error

---

.circleci/config.yml
package.json
src/watch/index.ts
test/function/samples/catch-dynamic-import-failure/_config.js
test/function/samples/dynamic-import-expression/_config.js
test/function/samples/dynamic-import-rewriting/_config.js
test/leak/index.js

This adds Node 12 to the test setup. It also improves cleanup of watchers as there was an issue that prevented the test run from finishing on Node 12.

Make tests run on Node 12, fix watcher cleanup issue

---

bin/src/run/batchWarnings.ts
bin/src/run/build.ts
docs/01-command-line-reference.md
docs/999-big-list-of-options.md
src/utils/mergeOptions.ts
test/cli/samples/silent-onwarn/_config.js
test/cli/samples/silent-onwarn/_expected.js
test/cli/samples/silent-onwarn/main.js
test/cli/samples/silent-onwarn/rollup.config.js

Resolves #2686 
This decouples the `onwarn` handler from the `--silent` option so that the handler is called even when the flag is used. The documentation is also updated to reflect this.
@filipesilva sorry this has taken so long considering it was a rather straightforward fix and had been on my mind for some time.

Do not skip onwarn handler when --silent is used

---

src/Module.ts
test/form/samples/dynamic-import-unresolvable/_config.js
test/form/samples/dynamic-import-unresolvable/_expected.js
test/form/samples/dynamic-import-unresolvable/main.js

Resolves #2980 
This makes sure that whenever a dynamic import does not contain a string or template string without inserted expressions, the raw AST nodes will be forwarded. Previously, the specifier would be null for template literals with expressions or literals that are not string.

Always forward AST nodes for unresolvable dynamic imports

---

package.json

The location of the binary had wrongly a file extension appended

Fix wrong file extension

---

cli/run/batchWarnings.ts
src/Module.ts
src/ast/nodes/MemberExpression.ts
test/function/samples/default-not-reexported/_config.js
test/function/samples/error-after-transform-should-throw-correct-location/_config.js
test/function/samples/import-of-unexported-fails/_config.js
test/function/samples/namespace-missing-export/_config.js
test/function/samples/reexport-missing-error/_config.js

Update existing tests.
Remove an unneeded trailing hyphen (`-`) from reference url in error messages.
Before: `https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module-`
After:    `https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module`

Fix reference url in error messages

---

CODE_OF_CONDUCT.md
README.md
docs/08-troubleshooting.md

Fix documents to use https, not http.

Fix documents to use https, not http

---

src/ast/nodes/ConditionalExpression.ts
src/ast/nodes/LogicalExpression.ts
src/ast/nodes/ReturnStatement.ts
src/ast/nodes/SequenceExpression.ts
src/ast/nodes/ThrowStatement.ts
src/utils/renderHelpers.ts
test/form/samples/keep-tree-shaking-comments-no-asi/_config.js
test/form/samples/keep-tree-shaking-comments-no-asi/_expected.js
test/form/samples/keep-tree-shaking-comments-no-asi/main.js
test/function/samples/prevent-tree-shaking-asi/_config.js
test/function/samples/prevent-tree-shaking-asi/main.js

Resolves #3019 
This will remove linebreaks before simplified statements if this would lead to an erroneous automatic semicolon insertion. The logic is in place for both return and break statements and checks for simplifications in conditional, logical and sequence expressions.
The logic only removes line-breaks but does not touch other non-code characters to retain (annotation?) comments in the best possible way.

Prevent ASI errors for conditional expressions

---

docs/01-command-line-reference.md

Small documentation update to include `ROLLUP_WATCH` envar.  fixes #2711.

docs: add ROLLUP_WATCH envar to docs

---

src/rollup/index.ts

I changed the code from this:
```typescript
function rollup(...): Promise<...> {
try {
...
} catch (err) {
return Promise.reject(err);
}
}
```
to this:
```typescript
async function rollup(...): Promise<...> {
...
}
```

Remove one try-catch

---

package-lock.json
package.json
rollup.config.js
src/Graph.ts
src/Module.ts
typings/declarations.d.ts

acorn built with bigint and dynamic import internal since 6.2.0 (while rollup depending on acorn ^6.2.1): https://github.com/acornjs/acorn/blob/master/acorn/CHANGELOG.md
(Note: don't update dependency acorn version to 7.0.0 for the moment, until most plugins compatible with that (at least waiting for acorn offcial stage3 plugins), and notice that `import()` has updated to `ImportExpression` in 7.0.0, which maybe need to update in rollup source.)

remove acorn-bigint and acorn-dynamic-import devDenpendencies

---

src/watch/index.ts

As seen on line 42, this function actually accepts either a `GenericConfigObject[]` or a `GenericConfigObject`.  The documentation uses the non-array form, which results in a user following the documentation in TypeScript getting a type checker error.

Fixes type definition on watch and Watcher constructor.

---

src/ast/nodes/ImportExpression.ts
test/form/samples/import-expression/_config.js
test/form/samples/import-expression/_expected/amd.js
test/form/samples/import-expression/_expected/cjs.js
test/form/samples/import-expression/_expected/es.js
test/form/samples/import-expression/_expected/iife.js
test/form/samples/import-expression/_expected/system.js
test/form/samples/import-expression/_expected/umd.js
test/form/samples/import-expression/main.js

Resolves #3072 
Import expressions did not properly render their source, which meant that variable name changes could be lost.

Fix wrong variable name in import expression

---

.eslintignore
cli/run/build.ts
docs/02-javascript-api.md
docs/05-plugin-development.md
src/rollup/index.ts
src/rollup/types.d.ts
src/utils/FileEmitter.ts
test/form/samples/deprecated/emit-asset/_config.js
test/form/samples/emit-asset-file/_config.js

#3079
I want to make it easier to develop plugins using typescript.
It is possible since Rollup is implemented in typescript. But there are few problems.
One of which is one fixed here, and reported in the issues mentioned above

feat: OutputBundle Tagged union with 'type = chunk|asset'

---

src/rollup/index.ts
test/form/samples/deprecated/emit-asset-hacky/_config.js
test/form/samples/deprecated/emit-asset-hacky/_expected/amd.js
test/form/samples/deprecated/emit-asset-hacky/_expected/cjs.js
test/form/samples/deprecated/emit-asset-hacky/_expected/es.js
test/form/samples/deprecated/emit-asset-hacky/_expected/iife.js
test/form/samples/deprecated/emit-asset-hacky/_expected/my-hacky-asset.txt
test/form/samples/deprecated/emit-asset-hacky/_expected/system.js
test/form/samples/deprecated/emit-asset-hacky/_expected/umd.js
test/form/samples/deprecated/emit-asset-hacky/main.js

Resolves #3104
Apparently some plugins heavily depend on the ability to directly add assets to the bundle object. This will permit this workflow again but add a deprecation message that will show when using `strictDeprecations`.

Permit plugins to add assets directly to the bundle in Rollup 1.x

---

src/utils/mergeOptions.ts
test/cli/samples/context/_config.js
test/cli/samples/context/_expected.js
test/cli/samples/context/main.js

Fixes #3121
#3121
It looks like --context was not wired up in mergeOptions. Using the `createGetOption` helper to check both the config and command line options.

Wire up --context CLI flag

---

src/ast/variables/NamespaceVariable.ts
test/form/samples/compact/_expected/amd.js
test/form/samples/compact/_expected/cjs.js
test/form/samples/compact/_expected/es.js
test/form/samples/compact/_expected/iife.js
test/form/samples/compact/_expected/system.js
test/form/samples/compact/_expected/umd.js
test/form/samples/namespace-tostringtag/_expected/amd.js
test/form/samples/namespace-tostringtag/_expected/cjs.js
test/form/samples/namespace-tostringtag/_expected/es.js
test/form/samples/namespace-tostringtag/_expected/iife.js
test/form/samples/namespace-tostringtag/_expected/system.js
test/form/samples/namespace-tostringtag/_expected/umd.js
test/function/samples/namespace-tostring/_config.js
test/function/samples/namespace-tostring/foo.js
test/function/samples/namespace-tostring/main.js

Fixes #3097.
This simplifies generated code for module namespaces by removing the `Symbol` polyfill. It is technically a breaking change but it was agreed in https://github.com/rollup/rollup/issues/3097#issuecomment-533856451.

Remove Symbol polyfill in module namespaces

---

src/ast/nodes/AwaitExpression.ts
src/ast/nodes/ForInStatement.ts
src/ast/nodes/ForOfStatement.ts
src/ast/nodes/ThrowStatement.ts
test/form/samples/side-effects-await/_config.js
test/form/samples/top-level-await/_expected/es.js
test/form/samples/top-level-await/_expected/system.js
test/form/samples/top-level-await/main.js
test/function/samples/missing-spaces-after-simplification/_config.js
test/function/samples/missing-spaces-after-simplification/main.js

Resolves #3158 
This resolves some cases where missing white-space could lead to invalid code when an expression is simplified so that after simplification, it starts with a word character while before, it started with some punctuation.
This affects for..in loops , for..of loops and throw statements. The fix is the same as is already in place for return statements and yield expressions in that a space is inserted at the right position if there is none in the original code.
Examples of the broken code: https://rollupjs.org/repl/?version=1.23.1&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiUyRiUyMCUyMyUyMGRpZmZlcmVudCUyMHNpbXBsaWZpZWQlMjBleHBy …

Add missing spaces in certain statements and expressions to avoid invalid code

---

cli/run/loadConfigFile.ts
docs/01-command-line-reference.md
test/cli/samples/config-mjs/_config.js
test/cli/samples/config-mjs/main.js
test/cli/samples/config-mjs/rollup.config.mjs

List any relevant issue numbers: #3189
support naming the config file *.mjs
```sh
rollup --config my.config.mjs
```

support all config file extensions (.js,.mjs,...)

---

src/ast/nodes/ExportAllDeclaration.ts
test/form/samples/no-treeshake/_expected/amd.js
test/form/samples/no-treeshake/_expected/cjs.js
test/form/samples/no-treeshake/_expected/es.js
test/form/samples/no-treeshake/_expected/iife.js
test/form/samples/no-treeshake/_expected/umd.js
test/form/samples/no-treeshake/main.js

Resolves #3196 
As exports are always re-rendering in the wrapper, export all declaration should always be removed completely. This basically emulates how it is done for import declarations to work also when tree-shaking is disabled.

Also remove export-all declarations when not tree-shaking

---

src/Module.ts
test/function/samples/handle-missing-export-source/_config.js
test/function/samples/handle-missing-export-source/foo.js
test/function/samples/handle-missing-export-source/main.js

Resolves #3210 
This is a quick fix by changing how Rollup checks for named re-exports, but it is recommended that rollup-plugin-dts improves the ESTree compliance of their generated ASTs.

Do no fail if the source attribute is `undefined` in an unused named export

---

src/Module.ts
src/rollup/index.ts
test/function/samples/deprecated/emit-asset/set-asset-source-transform/_config.js
test/function/samples/deprecated/emit-chunk/chunk-not-found/_config.js
test/function/samples/deprecations/transform-dependencies/_config.js
test/function/samples/dynamic-import-relative-not-found/_config.js
test/function/samples/emit-file/chunk-not-found/_config.js
test/function/samples/emit-file/set-asset-source-transform/_config.js
test/function/samples/external-conflict/_config.js
test/function/samples/load-returns-string-or-null/_config.js
test/function/samples/manual-chunks-conflict/_config.js
test/function/samples/no-relative-external/_config.js
test/function/samples/paths-are-case-sensitive/_config.js
test/function/samples/plugin-error-loc-instead-pos/_config.js
test/function/samples/plugin-error-only-first-transform/_config.js
test/function/samples/plugin-error/load/_config.js
test/function/samples/plugin-error/transform/_config.js
test/function/samples/throws-not-found-module/_config.js
test/watch/index.js

Resolves #3215
Resolves #2534 
This is a follow-up of the #3081. The approach is still the same, but instead of attaching the necessary watch information to parse errors, it will be attached to *any* error during the build phase. This includes any errors thrown by plugins, but also many other obscure errors that can be encountered during that phase. Hopefully, watch mode is now more enjoyable for everyone.

Also recover from plugin errors during the initial build in watch mode

---

src/rollup/index.ts
test/misc/misc.js

Resolves #3222
This fixes a regression where it is no longer possible to pass an object with an `output` key to bundle.generate.

Allow passing input options to output

---

src/ast/nodes/SwitchStatement.ts
test/function/samples/switch-statements-removed-default/_config.js
test/function/samples/switch-statements-removed-default/main.js

Resolves #3236 
When switch cases were removed, the logic to determine if ALL switch cases contained a return ignored the removed cases. This is fixed now.

Do not truncate after switch-statement with removed case

---

docs/00-introduction.md

Installation command was part of quick start and it was not easy to spot. So adding it separately.

Add installation step as a separate section in documentation

---

docs/05-plugin-development.md

List any relevant issue numbers: n/a
Small change to docs

Add note about generating source maps to load() and transform()

---

src/ast/nodes/ImportExpression.ts
src/ast/scopes/ChildScope.ts
src/utils/deconflictChunk.ts
test/form/samples/nested-inlined-dynamic-import/_config.js
test/form/samples/nested-inlined-dynamic-import/_expected/amd.js
test/form/samples/nested-inlined-dynamic-import/_expected/cjs.js
test/form/samples/nested-inlined-dynamic-import/_expected/es.js
test/form/samples/nested-inlined-dynamic-import/_expected/iife.js
test/form/samples/nested-inlined-dynamic-import/_expected/system.js
test/form/samples/nested-inlined-dynamic-import/_expected/umd.js
test/form/samples/nested-inlined-dynamic-import/foo.js
test/form/samples/nested-inlined-dynamic-import/main.js
test/function/samples/nested-inlined-dynamic-import-1/_config.js
test/function/samples/nested-inlined-dynamic-import-1/foo.js
test/function/samples/nested-inlined-dynamic-import-1/main.js
test/function/samples/nested-inlined-dynamic-import-2/_config.js
test/function/samples/nested-inlined-dynamic-import-2/lib1.js
test/function/samples/nested-inlined-dynamic-import-2/lib2.js
test/function/samples/nested-inlined-dynamic-import-2/main.js

resolves #3245 
This makes sure that when a dynamic import is used inside a function, variables inside this function are deconflicted with respect to the inlined namespace.

Avoid name conflicts when inlining dynamic imports nested in functions

---

src/ast/nodes/MemberExpression.ts
src/ast/nodes/ObjectExpression.ts
test/function/samples/deoptimize-cached-prop/_config.js
test/function/samples/deoptimize-cached-prop/main.js

Resolves #3264 
I am aware that #3266 already provides a fix for #3264 and I hope there is no ill thought from the author (the other fix in the PR is still welcome), but this PR will actually fix the root cause of the issue, which is that when the key of a computed property is later deoptimized, and the involved member expression had a deoptimized path, then ALL paths of the member expression need to be deoptimized (I know this may sound VERY confusing. I really hope to find some time soon to improve the names of the concepts around this).
So the result is that
```js
const obj1 = {};
let prop = 'x';
updateProp();
obj1[prop] = true;
assert.strictEqual(obj1.y ? 'WORKING' : 'BUG', 'WORKING');
function …
```

Fix incomplete computed property deoptimization

---

src/ast/nodes/MetaProperty.ts
test/form/samples/import-meta/_config.js
test/form/samples/import-meta/_expected/amd.js
test/form/samples/import-meta/_expected/cjs.js
test/form/samples/import-meta/_expected/es.js
test/form/samples/import-meta/_expected/iife.js
test/form/samples/import-meta/_expected/system.js
test/form/samples/import-meta/_expected/umd.js
test/form/samples/import-meta/main.js
test/form/samples/resolve-import-meta-url-export/resolved.js
test/form/samples/resolve-import-meta-url-export/unresolved.js

https://github.com/rollup/rollup/issues/3151#issuecomment-564697539
When `import.meta` is accessed directly, Rollup would render a polyfill object that accesses `module` for AMD and SystemJS formats without importing it. This is fixed here.

Always make "module" available for SystemJS and AMD formats if `import.meta` is accessed directly

---

cli/run/index.ts
test/cli/samples/config-env/_config.js
test/cli/samples/config-env/main.js
test/cli/samples/config-env/rollup.config.js

Environment variables may include colons. Currently if one does they are removed along with any text following.
**Before:**
```
URL:http://localhost:4200 =  ['URL', 'http']
```
**After:**
```
URL:http://localhost:4200 =  ['URL', 'http://localhost:4200']
```
**Example:**
https://jsbin.com/zizexetuqu/edit?js,console

Allow environment variables to contain colons

---

docs/07-tools.md

Update deprecated references to the node-resolve plugin in the docs

---

docs/04-tutorial.md
src/Module.ts
test/function/samples/error-parse-json/_config.js

In README, docs/*, and error messages in test/*
Update references to rollup-plugin-json throughout documentation and in test files messages. (Expands on #3296)

Update references to @rollup/plugin-json

---

README.md
docs/00-introduction.md
docs/01-command-line-reference.md
docs/04-tutorial.md
docs/06-faqs.md
docs/07-tools.md
docs/08-troubleshooting.md
docs/999-big-list-of-options.md
src/Module.ts
test/function/samples/error-parse-json/_config.js

Expanding on #3296 and #3297, this PR changes all references to official rollup plugins throughout the documentation.

Update references to official rollup plugins

---

docs/00-introduction.md

- https://github.com/rollup/rollup/pull/3226
This adds a note about setting the `types` field in the typescript config file, to prevent the `@types/node` types automatically being included.
Feel free to change it

add note about setting `types` in tsconfig file

---

src/ast/nodes/AssignmentExpression.ts
src/ast/nodes/IfStatement.ts
test/form/samples/lazy-assignment-deoptimization/_config.js
test/form/samples/lazy-assignment-deoptimization/_expected.js
test/form/samples/lazy-assignment-deoptimization/main.js
test/function/samples/assignment-deoptimization/assignee-is-deoptimized/_config.js
test/function/samples/assignment-deoptimization/assignee-is-deoptimized/main.js
test/function/samples/assignment-deoptimization/assignment-target-is-deoptimized/_config.js
test/function/samples/assignment-deoptimization/assignment-target-is-deoptimized/main.js
test/function/samples/assignment-deoptimization/nested-assignment/_config.js
test/function/samples/assignment-deoptimization/nested-assignment/main.js
test/function/samples/assignment-deoptimization/try-catch-inclusion/_config.js
test/function/samples/assignment-deoptimization/try-catch-inclusion/main.js

[WIP] handle assignments in dead code

---

src/utils/renderNamePattern.ts
test/chunking-form/samples/preserve-modules-id-case-sensitive/_config.js
test/chunking-form/samples/preserve-modules-id-case-sensitive/_expected/amd/_virtual/_One1.js
test/chunking-form/samples/preserve-modules-id-case-sensitive/_expected/amd/_virtual/_One2.js
test/chunking-form/samples/preserve-modules-id-case-sensitive/_expected/amd/_virtual/_one.js
test/chunking-form/samples/preserve-modules-id-case-sensitive/_expected/amd/main.js
test/chunking-form/samples/preserve-modules-id-case-sensitive/_expected/cjs/_virtual/_One1.js
test/chunking-form/samples/preserve-modules-id-case-sensitive/_expected/cjs/_virtual/_One2.js
test/chunking-form/samples/preserve-modules-id-case-sensitive/_expected/cjs/_virtual/_one.js
test/chunking-form/samples/preserve-modules-id-case-sensitive/_expected/cjs/main.js
test/chunking-form/samples/preserve-modules-id-case-sensitive/_expected/es/_virtual/_One1.js
test/chunking-form/samples/preserve-modules-id-case-sensitive/_expected/es/_virtual/_One2.js
test/chunking-form/samples/preserve-modules-id-case-sensitive/_expected/es/_virtual/_one.js
test/chunking-form/samples/preserve-modules-id-case-sensitive/_expected/es/main.js
test/chunking-form/samples/preserve-modules-id-case-sensitive/_expected/system/_virtual/_One1.js
test/chunking-form/samples/preserve-modules-id-case-sensitive/_expected/system/_virtual/_One2.js
test/chunking-form/samples/preserve-modules-id-case-sensitive/_expected/system/_virtual/_one.js
test/chunking-form/samples/preserve-modules-id-case-sensitive/_expected/system/main.js
test/chunking-form/samples/preserve-modules-id-case-sensitive/main.js

Suppose we have to files named `date.js` and `Date.js`, `makeUnique` treats these two files are different currently. But on a case insensitive OS, they are the same file. This commit try to fix the
problem.

Fix module id conflict on a case insensitive OS

---

LICENSE.md
src/ast/nodes/ConditionalExpression.ts
src/ast/nodes/LogicalExpression.ts
test/form/samples/conditional-expression-deopzimize-while-included/_config.js
test/form/samples/conditional-expression-deopzimize-while-included/_expected.js
test/form/samples/conditional-expression-deopzimize-while-included/main.js
test/form/samples/logical-expression/deopzimize-while-included/_config.js
test/form/samples/logical-expression/deopzimize-while-included/_expected.js
test/form/samples/logical-expression/deopzimize-while-included/main.js

Resolves #3324 
This fixes an issue with logical and conditional expressions that can arise when an expression that contains a variable reassignment is automatically included without a preceding `hasEffects` check.
The issue is quite complicated to trigger (see #3324) while the fix was in essence to switch the order of two lines.

Handle deoptimizations while a node is being included.

---

.mocharc.json
LICENSE.md
src/Chunk.ts
src/Module.ts
src/ModuleLoader.ts
src/ast/nodes/CallExpression.ts
src/ast/nodes/Identifier.ts
src/ast/nodes/MemberExpression.ts
src/ast/nodes/TaggedTemplateExpression.ts
src/ast/variables/NamespaceVariable.ts
src/finalisers/iife.ts
src/finalisers/umd.ts
src/rollup/index.ts
src/utils/FileEmitter.ts
src/utils/PluginContext.ts
src/utils/PluginDriver.ts
src/utils/addons.ts
src/utils/collapseSourcemaps.ts
src/utils/defaultPlugin.ts
src/utils/getExportMode.ts
src/utils/transform.ts
test/function/samples/circular-missed-reexports-2/_config.js
test/function/samples/circular-missed-reexports-2/dep1.js
test/function/samples/circular-missed-reexports-2/dep2.js
test/function/samples/circular-missed-reexports-2/main.js
test/function/samples/circular-missed-reexports/_config.js
test/function/samples/circular-missed-reexports/dep1.js
test/function/samples/circular-missed-reexports/dep2.js
test/function/samples/circular-missed-reexports/main.js
test/mocha.opts

Resolves #3348 
This adds a break-off condition when searching variables for export names. It prevents maximum callstack exceeded errors for both named and namespace circular reexports.

Properly handle circular reexports

---

src/rollup/types.d.ts
src/utils/chunkColouring.ts
test/chunking-form/samples/improved-dynamic-chunks/circular-dynamic-imports/_config.js
test/chunking-form/samples/improved-dynamic-chunks/circular-dynamic-imports/_expected/amd/generated-dynamic1.js
test/chunking-form/samples/improved-dynamic-chunks/circular-dynamic-imports/_expected/amd/generated-dynamic2.js
test/chunking-form/samples/improved-dynamic-chunks/circular-dynamic-imports/_expected/amd/main.js
test/chunking-form/samples/improved-dynamic-chunks/circular-dynamic-imports/_expected/cjs/generated-dynamic1.js
test/chunking-form/samples/improved-dynamic-chunks/circular-dynamic-imports/_expected/cjs/generated-dynamic2.js
test/chunking-form/samples/improved-dynamic-chunks/circular-dynamic-imports/_expected/cjs/main.js
test/chunking-form/samples/improved-dynamic-chunks/circular-dynamic-imports/_expected/es/generated-dynamic1.js
test/chunking-form/samples/improved-dynamic-chunks/circular-dynamic-imports/_expected/es/generated-dynamic2.js
test/chunking-form/samples/improved-dynamic-chunks/circular-dynamic-imports/_expected/es/main.js
test/chunking-form/samples/improved-dynamic-chunks/circular-dynamic-imports/_expected/system/generated-dynamic1.js
test/chunking-form/samples/improved-dynamic-chunks/circular-dynamic-imports/_expected/system/generated-dynamic2.js
test/chunking-form/samples/improved-dynamic-chunks/circular-dynamic-imports/_expected/system/main.js
test/chunking-form/samples/improved-dynamic-chunks/circular-dynamic-imports/dynamic1.js
test/chunking-form/samples/improved-dynamic-chunks/circular-dynamic-imports/dynamic2.js
test/chunking-form/samples/improved-dynamic-chunks/circular-dynamic-imports/main.js
test/test.js

This will resolve a situation where the chunk colouring algorithm could go into an infinite recursion. Also fixes a situation where static entry points were accidentally treated as dynamic ones.

Resolve issues with circular dynamic entries

---

src/ast/nodes/BlockStatement.ts
test/form/samples/preserve-asm-js/_config.js
test/form/samples/preserve-asm-js/_expected.js
test/form/samples/preserve-asm-js/main.js

Resolves #3360 
This will automatically include any code inside a "use asm" block unmodified, see #3360 for reasoning.

Preserve asm.js code

---

docs/999-big-list-of-options.md

Just correcting text since I was reading the page.

correct spelling minifaction to minification

---

src/rollup/rollup.ts
src/rollup/types.d.ts
test/hooks/index.js

Resolves #2717 
This is one of the few truly breaking changes in this release as there is no two-step deprecation; but to be honest, I could not think of another good name for this hook and well, writing a downward compatible plugin is not that difficult because you can do this:
```js
{
writeBundle(options, bundle = options) {
// now bundle is always the bundle, both in 1.x and 2.x
}
}
```
So you can detect the signature of the hook by checking if the second parameter is used; in that case, it is the bundle, otherwise the first is the bundle.

[v2.0.0] Change writeBundle signature to match generateBundle
